### ISSUE TITLE
Centrifugo release

### ISSUE THREAD

**Issue by yagobski** [centrifugal/centrifugo#1]
Hi, Iam waiting the release. It is released or still in beta test ?

**Comment by FZambia** [comment]
Hello:)

Just released all the things I've done, Centrifugo 0.1.0 is the first release, Note though, that at work we still use Centrifuge in production and will migrate to Centrifugo in several weeks - we are planning to see how it behaves - is it stable enough or not.

**Comment by thedeadofblackfire** [comment]
hi, 
Very good new stuff!
I'm not familiar with Go language but you mentioned better performance & multi cores ready.
Can you estimate what should be the best server to host only centrifugo as service (with memory engine) from 2 servers below:
- 8 CPUs (Intel Atom) with 8 GB RAM (Ubuntu 14.04)
- 4 CPUs (Intel Xeon) with 12 GB RAM (centOS 6.6)
So the battle between more memory vs more cores?
Do you have an idea of the max connections we can reach with one of this kind of server?
Did you use the benchmark tool from centrifuge repository ?
Thanks

**Comment by yagobski** [comment]
Thanks @thedeadofblackfire  for your question i want to ask the same. Iam also not familiar with Go language but if it make performance good why not. 
I want to join the project to develop an Angularjs frontend for Centrifugo with more features. 
Can you confirm us when centrifugo will be stable in production?

**Comment by FZambia** [comment]
@thedeadofblackfire, to be fair I don't know which of servers better. I used a benchmark tool with up to 10k connections, but I did not try to connect more than 10k clients. And I don't see much sense in this - depending on application there will be different amount of clients, channels, messages per second - all of these need additional CPU and memory – so the way to decide when resource limit of one server reached - CPU and memory usage monitoring.

**Comment by thedeadofblackfire** [comment]
Thanks for your reply. I think more memory is the best deal for now. Yep agree, 10 000 max connections simultaneous is already a solid base. I'm not yet at the beginning of the development phase about a medical chat platform. i like centrifuge & now centrifugo compared to pusher.com (price ^^). I try to make some projections of Use. The production phase will not be for the next months but i will try to use your benchmark on the servers to play with it (monitoring by newrelic).

**Comment by FZambia** [comment]
Ok, thanks, I am here and looking forward for your results. If you need any help – feel free to ask

**Comment by FZambia** [comment]
We finally replaced Centrifuge with Centrifugo in production 2 days ago. As we did this - we found problem with Redis engine resulting it message lost. That problem with Redis engine already fixed in version 0.2.3

Yesterday everything worked fine with updated code. Will see how it behaves.

**Comment by FZambia** [comment]
So I think Centrifugo is pretty stable at moment. In our project it works without any downtime since my last message. If you use Centrifugo please write me a message here or via email about your use case.

**Comment by yagobski** [comment]
I confirme that il is working on production without any downtime since 3
months.

Le jeudi 24 septembre 2015, Alexandr Emelin <notifications@github.com> a
écrit :

**Comment by FZambia** [comment]
Closing this as Centrifugo > 1.0 already out🍾
