### ISSUE TITLE
Modular design, separating components from libcentrifugo to its own packages

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifugo#100]
It's a hard issue, maybe even harder in terms of backwards compatibility concerns. But the idea looks correct - entities like Engine, Client, Application core should live in separate packages with well-defined API to communicate. So looks like one more massive refactoring:)

It's not a real problem right now for our users as things just work. But the more people start using Centrifugo the more questions appear about customizing some behaviour/commands etc.

At moment I have no idea is it even possible to do in a beautiful way or not - need some investigation, but I believe that it's worth it to try.

**Comment by vector090** [comment]
Wish commands, auth algorithm etc. allows extension.

**Comment by lmj0011** [comment]
yes, being able to write plugins would be nice.

**Comment by FZambia** [comment]
I almost finished splitting everything on packages - there is pull #112 . I can't say that I achieved all goals during this refactoring but at least Centrifugo got several important improvements I described in pr. Will continue to work on it - hopefully till the middle of November I am planning to make release that contains this work.

As this is Go - it's hard to create easy to use plugin system yet. But at least now Centrifugo will have possibility for extending in some way without needing to support separate code base in fork.

**Comment by vector090** [comment]
What a surprise! Thanks for the hard work! I'll look into it as soon as  I can.
------------------ Original ------------------

**Comment by FZambia** [comment]
@vector090 yeah, it would be nice! After release it will be not so simple to change something in backwards incompatible way so any advices much appreciated at this moment.

**Comment by vector090** [comment]
#112 looks good to me. If I understand correctly, in order to support my own customized client commands, I need to do it in my own client connection struct, is it?

**Comment by FZambia** [comment]
@vector090 - yes, but in its current state you also need to call create your custom client connection from server handler - i.e. modify [this](https://github.com/centrifugal/centrifugo/blob/master/libcentrifugo/server/httpserver/handlers.go#L266) line. Maybe it would be better to create client register or sth like this to modify default client in `main.go` file.

**Comment by FZambia** [comment]
v1.6.0 released. I want to emphasize though that Centrifugo internal Go packages don't have any API stability promise. We can change its API in any moment when we find something that must be fixed/improved. Centrifugo standalone server is our primary goal.
