### ISSUE TITLE
what format is stored to redis

### ISSUE THREAD

**Issue by lmj0011** [centrifugal/centrifugo#105]
When using the redis engine, what is the format when data is stored. the data looks serialized when outputted to the terminal via a Redis subscriber (ie. predis).

I don't know if it's being serialize by Centrifugo or Redis and how to unserialize it

ex. of what the data looks like
```
NqrFdfEfEya13lM7so73KW
1474227833channel1:577d8145c6c92"Z{"input":"hello\n"}*$ec6cbed6-5ea4-4e73-a5c5-42e9c40169b22�
1$ec6cbed6-5ea4-4e73-a5c5-42e9c40169b2�{"user_data":{"id":1,"username":"Tomjnd","rank":255,"zip":null,""last_login_at":"1474225829"}}
```

**Comment by FZambia** [comment]
Hello, it is serialized using google `protobuf` format. There is `message.proto` file in `libcentrifugo` folder with message schema.

**Comment by lmj0011** [comment]
I don't this really is necessary for JSON data, is there an option to disable proto buf encoding?

**Comment by FZambia** [comment]
I think yes - we can add such option. But we need to know what you are trying to achieve first - looks like you are hacking internals for some reason:)

**Comment by lmj0011** [comment]
I'm trying implementing this https://github.com/centrifugal/centrifugo/issues/102

By subscribing to the `message.history` channel using laravel.

What I plan on doing is storing each message to disk as it's published to Redis.

**Comment by FZambia** [comment]
But as soon as you already have Laravel backend why not to just save messages just before publish them to Centrifugo API? If you are using direct channel publish you still can call your custom server side endpoint from javascript. Both ways look simplier and you have more control.

**Comment by FZambia** [comment]
Also what is `message.history` channel? There is no such channel in Centrifugo. Is it your own? Centrifugo uses Redis pubsub for distributing messages in channels among nodes and Redis list structure to keep message history cache.

**Comment by lmj0011** [comment]
>But as soon as you already have Laravel backend why not to just save messages just before publish >them to Centrifugo API? 

I'm doing that with `Express` now

>Also what is message.history channel? 

This is the channel I was meaning to refer to `centrifugo.history.list.centrifugo.message`

**Comment by FZambia** [comment]
Express or Laravel - nevermind, options still the same.

`centrifugo.history.list.centrifugo.message` is a list data structure in Redis, it's not a PUB/SUB channel.

**Comment by FZambia** [comment]
@lmj0011 any updates?

**Comment by lmj0011** [comment]
no this issue is good to close.
