### ISSUE TITLE
Best way to integrate push notification 

### ISSUE THREAD

**Issue by narup** [centrifugal/centrifugo#110]
Centrifugo looks great and I am planning to try it out. I have one question. Real-time messaging on apps is not complete without push notifications, so what's the best way to handle that. So if user is not connected to the centrifugo server or app is not active, how the app backend can send push? I guess we can do a app backend to centrifugo to check if client is connected?

Thanks

**Comment by FZambia** [comment]
@narup hello, glad you like it!

There is last question in FAQ covering this - see https://fzambia.gitbooks.io/centrifugal/content/FAQ.html page. Its not reliable to just check if user online or not - because he can leave your app right after that moment. So implementing custom ack endpoint in your backend is necessary - so you can push notification after some interval.

**Comment by narup** [comment]
Thanks, even with this approach I can see out of sync issues happening. I see publish response has  error field, will it send any specific error response if it cannot deliver the message?

**Comment by FZambia** [comment]
Could you explain why out of sync issues happen?

Publish response only knows that message was successfully delivered to Centrifugo internal engine. For example it means that message was published into Redis channel (in case of Redis engine working). So it can not show was message delivered to someone or not.

**Comment by FZambia** [comment]
Just to formulate my ack suggestion into some pseudocode.

On client side you write sth like this:
```javascript
centrifuge.subscribe("channel", function(message) {
    renderMessage(message);
    // at this moment you know exactly that message was read by client.
    // use application specific message id to ack message.
    sendMessageAckToAppBackend(message.data["app_message_id"]);
});
```

On backend you have a message table in database with fields like this (on chat example):


Message table:
```
id ...
body ...
author ...
time_sent datetime
```

MessageToUser:
user_id ...
message_id ...
ack_received bool
push_sent bool
```

So when `sendMessageAckToAppBackend` called you send request to app server and set `ack_received` for message and that user to `true`.

Periodically you can look at `time_sent` field and send push notifications to all users with messages that have `ack_received == false` and `message.time_sent < now() - 10seconds`. Maybe you also need to check push notification delivery status via notification centers API.

As option you can also aggregate messages per user during this interval and send one push to them instead of separate for each message. 

If you think about reliable push notifications that I suppose you already have something like structure above in your database.

**Comment by narup** [comment]
Thanks, I got that part. But, I am thinking more in terms of group messaging. It seems bit too much of work to check message acknowledgement for each users within a group. I am not saying it's hard or not doable, but feels like should be handled by the centrifugo. It would be nice if centrifugo has some kinds of plugin handler or hook which can be used by developers to customize behaviors like these.

**Comment by FZambia** [comment]
Even with groups this looks like one query to database to get all messages without acknowlegement. I would be happy if Centrifugo can make this easier but I just dont see how. Do you have any ideas? What kind of hook you mean?

**Comment by narup** [comment]
I know what you mean, It's just that I am not very comfortable with maintaining status for each message on a group to each user of a group, at least for my use case. By hook, I mean some kind of callback URL that centrifugo can call on app's backend side for different events that could be interesting for app logic. User not in session is one event but there could be others. But, it means definitely more work for centrifugo :) But, for now I will try to go with your above solution you suggested. Thanks much for all the help.

**Comment by FZambia** [comment]
Yeah, I understand that Centrifugo does not solve everything application developers need but at the same time it does not limit final possible application functionality too much - i.e. most of missing features can be implemented on application level. About callback url - it will be almost the same as hook from client side I described above - we will save only few lines of code that initiates HTTP request that should be written now in browser. One of the advantages of making HTTP request manually from browser (and not from Centrifugo internals) is that you get authorized request in application (by native session mechanism used on your backend).

**Comment by narup** [comment]
Yeah sounds good.
