### ISSUE TITLE
Consider decouple log files by date or specified chunk size.

### ISSUE THREAD

**Issue by johndoejdg** [centrifugal/centrifugo#116]
Consider decouple log files by date or specified chunk size, to make work with logs files more easy. It works  for example in nginx by default.

**Comment by FZambia** [comment]
Hi! Don't understand what you mean, sorry - need examples:)

**Comment by banks** [comment]
I think you mean like logrotate does. 

IMO this is a solved problem outside of Centrifugo. Nginx might do it itself but almost every other daemon on Linux at least just writes to a log file and lets a daemon manager like runit or systemd or just logrotate itself manage rotating and compressing and/or shipping log files. 

I'd vote no change - use standard tools.

**Comment by FZambia** [comment]
Ah, actually if @johndoejdg mean log rotation then we already support it in our [package distributions](https://packagecloud.io/FZambia/centrifugo): using `logrotate`. [Here](https://github.com/centrifugal/centrifugo/blob/master/extras/packaging/logrotate) is an example logrotate config file.

**Comment by johndoejdg** [comment]
Yes, thanks for explanation. Logrotate will solves my problem.
