### ISSUE TITLE
Consider adding ability set up channel specific configuration

### ISSUE THREAD

**Issue by johndoejdg** [centrifugal/centrifugo#118]
In my application some channels must recover all items from history and for other channels just need recover only very last message. 
Could you consider add history_size option for channel. Channel history_size will override global option.

**Comment by banks** [comment]
This is already possible. 

Not specifically by channel but by prefix. You can architect you app around channel namespaces where shared namespace prefixed channels have same configuration. 

If you really want you could configure hundreds of namespaces which are actually contain only one channel if you really want per-channel semantics but the current namespace behaviour is sufficient I think. 

If it's not suitable for you, please let us know your use-case in more detail. 

See https://fzambia.gitbooks.io/centrifugal/content/server/configuration.html

**Comment by FZambia** [comment]
Specifically, here is an example of configuration with namespace (more in [docs](https://fzambia.gitbooks.io/centrifugal/content/server/settings.html))

```javascript
{
    "secret": "very-long-secret-key",
    "connection_lifetime": 0,
    "anonymous": true,
    "publish": true,
    "watch": true,
    "presence": true,
    "namespaces": [
        {
          "name": "public",
          "publish": true,
          "presence": true,
          "join_leave": true,
          "anonymous": true,
          "history_size": 10,
          "history_lifetime": 30,
          "recover": true
        },
        {
          "name": "gossips",
          "watch": true,
          "presence": true
        }
    ]
}
```

**Comment by johndoejdg** [comment]
Thank you for explanation. I want reduce join_leave events in channels. This is fit for me.
