### ISSUE TITLE
Create specific types for Project/Namespace/Channels/Users

### ISSUE THREAD

**Issue by klauspost** [centrifugal/centrifugo#12]
Currently are a lot of strings being thrown around to identify channels, users, etc.

If we change "string" in calls like `addPresence(projectKey, channel, uid string, info ClientInfo)` to typed version `addPresence(projectKey pID, channel cID, uid uID, info ClientInfo)` there is no risk of using the wrong value, sending them in wrong order or similar errors. Types could be:
```Go
type (
	nID string // Namespace ID
	pID  string // Project ID
	cID string // Channel ID
	uID  string // User ID
)
```

I wouldn't mind sending in a PR after #11 lands

**Comment by FZambia** [comment]
hmm..I personally don't think this is a good idea. It will make code harder to read for me. When I see `string` - I know what is it, but when I see `pID` – I had to think about what is it.

**Comment by klauspost** [comment]
The good thing it you *don't need to care* about what it is, but the compiler will make sure you never mess up and use the wrong one.

```Go
type (
    namespaceID string // Namespace ID
    projectID  string // Project ID
    channelID string // Channel ID
    userID  string // User ID
)
```

This is the big difference in a type-safe language. You use types to convey information, not variable names. That way the compiler will immediately tell you if you when you mix stuff up. The call would usually look like this `addPresence(pid projectID, cid channelID, uid userID, info ClientInfo)`.

The great things is that `map[projectID]map[channelID]*channel` without any work works the same as `map[string]map[string]*channel`, except there is no way for you to use the wrong key for a given level.

**Comment by FZambia** [comment]
You are right that `map[projectID]map[channelID]` is much more readable. This is much more persuading example. But I still don't like names for types. When I see `namespaceID` I think about something incremental or unique sequence of symbols (like uuid). The same for `channelID`. In Centrifugo both (and Project Key too) are just human readable strings - like `news`, `chat`, `public`, `gossips` etc

Maybe the way to go is naming those types in a more Centrifugo-specific manner:

type (
    ProjectKey string
    Channel string
    UserID  string
)

Namespace...maybe leave it as string? It appears in a couple of places only. Or `NamespaceKey`, or `NamespaceName`...

What do you think?

**Comment by klauspost** [comment]
I added a conversion of these 4 types as #13 - the actual name can be changed in 1 minute.
