### ISSUE TITLE
New method request: "cleanHistory" for both server and client API

### ISSUE THREAD

**Issue by roytan883** [centrifugal/centrifugo#127]
- for server API, it should be able to clean any channel's history
- for client API, it should be able to clean own channel history of #user-xxx

If client already get all history message in its own #user channel, it should be able to clean that channel's history to highly reduce the centrifugo or redis memory cost. 

Also should give the backend server a method to somehow control the channels history. For now, if remove specified message in channel history maybe hard, but clean all history of one channel should be easy.

Because most my designed channels would have `history_lifetime` by 1~30 days :)

**Comment by FZambia** [comment]
Hi! I am not sure that you use Centrifugo right. 30 days is not what it was designed for. I understand that for your use case it could be useful but I don't see much potential in this feature for most users. 

Btw there is no concept of own user channel - there could be several users in channel with `#` separated by comma.

**Comment by FZambia** [comment]
Maybe having this method in server API only would make sense for applications that need to clear history as part of their application logic (clear chat history for example).

**Comment by phouverneyuff** [comment]
I would like to see this feature. This's will help me on deploy em dev and stage when I need clean all data.

**Comment by FZambia** [comment]
@phouverneyuff maybe you better use different Centrifugo instances in your different setup stages. This feature won't help you at all as it's a per-channel call and Centrifugo has more data besides history - presence for example.

**Comment by phouverneyuff** [comment]
@FZambia , I use different Centrifugo instances. In dev I have centrifugo with Redis engine. I spend some time to delete the history in Dev. If I don't use with Redis is very easy to do it, but with Redis ...

**Comment by FZambia** [comment]
@phouverneyuff without diving deep into your setup have you considered `FLUSHDB` Redis command when you need to clean your Redis data?

**Comment by phouverneyuff** [comment]
@fzambia, yes. I don't know why, but if I shutdown Centrifugo, clean Redis with FLUSHDB and start again Centrifugo, all data are publish in Redis again. I don't know why. I kill all, flushDB in Redis and restart machine to clean all. I remove the Redis data file too.


`docker run  --name centrifugo -d --ulimit nofile=65536:65536 -v $HOME/centrifugo:/centrifugo -p 8000:8000  centrifugo/centrifugo centrifugo -c config.json  --admin --web --engine=redis --redis_host=172.17.0.1 --redis_port=6379`

**Comment by FZambia** [comment]
Implemented as server API call in Centrifugo v2:)
