### ISSUE TITLE
web_path can't work?

### ISSUE THREAD

**Issue by roytan883** [centrifugal/centrifugo#128]
If i start it with `./centrifugo --config=centrifugo_config.json --web`, then i can access the web by `http://192.168.1.xxx:8000/`

But if i start it with `./centrifugo --config=centrifugo_config.json --web --web_path=/abc/def`, then `http://192.168.1.xxx:8000/abc/def` can not be accessed , return `404 page not found`

**Centrifugo v1.5.1**

**Comment by FZambia** [comment]
`web_path` is a directory where custom web application lies in file system - it's not an URL path. 

Generally you need this option only when you want to use custom web interface (if you adapted it for your needs somehow) or during web interface development process (like I usually do).

**Comment by roytan883** [comment]
thanks, i got it.
