### ISSUE TITLE
Api method to detect if message has been consumed

### ISSUE THREAD

**Issue by MartinsThiago** [centrifugal/centrifugo#129]
Supposing I am developing a chat app, it's interesting to know If X message has arrived to the client... 

Is it possible to retrieve such information from api? If not... Coding my chat client to send a confirmation that X message arrived would be the best way to go?

**Comment by FZambia** [comment]
@MartinsThiago hello! Yes, the best reliable way to ensure your client received message is sending confirmation ack from your client to your application backend as soon as you processed message coming from channel.

**Comment by MartinsThiago** [comment]
@FZambia thks for clarifying 

Closing this one o/

**Comment by FZambia** [comment]
@MartinsThiago you are welcome, btw I currently prepare 1.6.0 release and there is a branch in docs that is not merged yet [with updated FAQ](https://github.com/centrifugal/documentation/blob/centrifugo1.6.0/FAQ.md) - maybe you find it useful.
