### ISSUE TITLE
RedisEngine issue when running with Supervisor

### ISSUE THREAD

**Issue by hemezh** [centrifugal/centrifugo#130]
I'm trying to run Centrifugo with Redis. It works fine when I copy and paste the command in the terminal but when I run it using Supervisor, it shows - 

>
[I]: 2016/12/14 10:30:10 Centrifugo version: 1.5.1
[I]: 2016/12/14 10:30:10 Process PID: 15693
[I]: 2016/12/14 10:30:10 Config file search path: /etc/centrifugo.json
[I]: 2016/12/14 10:30:10 GOMAXPROCS: 4
[I]: 2016/12/14 10:30:10 Redis engine: *****.\*\*\*\*\*.0001.apse1.cache.amazonaws.com:6379/29, pool: 256, using password: no, API enabled: no
[I]: 2016/12/14 10:30:10 Engine: redis
[I]: 2016/12/14 10:30:10 Use SSL: false
[I]: 2016/12/14 10:30:10 SockJS url: //cdn.jsdelivr.net/sockjs/1.1/sockjs.min.js
[I]: 2016/12/14 10:30:10 Start serving raw websocket, SockJS, API, admin endpoints on :8000
[C]: 2016/12/14 10:30:10 ERR invalid DB index
[E]: 2016/12/14 10:30:10 ERR invalid DB index
[C]: 2016/12/14 10:30:10 ERR invalid DB index
[E]: 2016/12/14 10:30:10 RedisEngine Receiver error: ERR invalid DB index
[I]: 2016/12/14 10:30:10 Starting RedisEngine Subscriber
[E]: 2016/12/14 10:30:10 RedisEngine Subscriber error: ERR invalid DB index
[I]: 2016/12/14 10:30:10 Stopping RedisEngine Subscriber
[C]: 2016/12/14 10:30:11 ERR invalid DB index
[E]: 2016/12/14 10:30:11 RedisEngine Receiver error: ERR invalid DB index
[I]: 2016/12/14 10:30:11 Starting RedisEngine Subscriber
[E]: 2016/12/14 10:30:11 RedisEngine Subscriber error: ERR invalid DB index
[C]: 2016/12/14 10:30:11 ERR invalid DB index
[I]: 2016/12/14 10:30:11 Stopping RedisEngine Subscriber
[E]: 2016/12/14 10:30:11 ERR invalid DB index
[C]: 2016/12/14 10:30:11 ERR invalid DB index
[E]: 2016/12/14 10:30:11 RedisEngine Receiver error: ERR invalid DB index
[I]: 2016/12/14 10:30:11 Starting RedisEngine Subscriber
[E]: 2016/12/14 10:30:11 RedisEngine Subscriber error: ERR invalid DB index
[I]: 2016/12/14 10:30:11 Stopping RedisEngine Subscriber
[C]: 2016/12/14 10:30:11 ERR invalid DB index
[E]: 2016/12/14 10:30:11 ERR invalid DB index
[C]: 2016/12/14 10:30:11 ERR invalid DB index

Anybody else facing similar issue?

**Comment by FZambia** [comment]
Hi, Centrifugo logs redis engine options on start - https://github.com/centrifugal/centrifugo/blob/v1.5.1/libcentrifugo/engineredis.go#L186 - could you show that line from logs? Also please provide supervisor config file you use.
