### ISSUE TITLE
1.6.0 require new format for ssl

### ISSUE THREAD

**Issue by johndoejdg** [centrifugal/centrifugo#132]
In 1.6.0 release I have problem with certificate format but in 1.5.1 it works good:

centrifugo --config="./scripts/centrifugo.json" --web --ssl=true --ssl_cert=/etc/nginx/ssl/crm.crt --ssl_key=/etc/nginx/ssl/crm.key

[I]: 2016/12/19 22:55:18 Config path: /var/www/crm/scripts/centrifugo.json
[I]: 2016/12/19 22:55:18 Centrifugo version: 1.6.0
[I]: 2016/12/19 22:55:18 Process PID: 17514
[I]: 2016/12/19 22:55:18 Engine: In memory – single node only
[I]: 2016/12/19 22:55:18 GOMAXPROCS: 8
[I]: 2016/12/19 22:55:18 Starting http server
[I]: 2016/12/19 22:55:18 SockJS url: //cdn.jsdelivr.net/sockjs/1.1/sockjs.min.js
[I]: 2016/12/19 22:55:18 Start serving raw websocket, SockJS, API, admin endpoints on :8000
[F]: 2016/12/19 22:55:18 ListenAndServe: tls: found a certificate rather than a key in the PEM for the private key

Could you please explain how I should it in 1.6.0?

**Comment by FZambia** [comment]
Hello! Sorry, this is my fault - just fixed this in 913eef992dae771b37d200480d1101748edbef69, will be released in 1.6.1

**Comment by FZambia** [comment]
v1.6.1 [released](https://github.com/centrifugal/centrifugo/releases/tag/v1.6.1)
