### ISSUE TITLE
One-Click Heroku Button Broken

### ISSUE THREAD

**Issue by jancel** [centrifugal/centrifugo#14]
I click the button on the main Readme of this repo and I just get an error on the Heroku side.

**Comment by FZambia** [comment]
Hello! Thanks for a report. This is very strange as I deployed demo instance several times via this button. It seems that something wrong with Heroku itself as it requires app-LONG-STRANGE-PROJECT-UID.json in project repo at moment.

**Comment by FZambia** [comment]
Also their official button tutorial repo also throws an error (https://github.com/heroku/node-js-sample). So I think this problem must go away soon.

**Comment by jancel** [comment]
That's too funny. I will report this to their support. It was working last
week!

On Friday, May 29, 2015, Alexandr Emelin <notifications@github.com> wrote:

> Also their official button tutorial repo also throws an error (
> https://github.com/heroku/node-js-sample). So I think this problem must
> go away soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/centrifugal/centrifugo/issues/14#issuecomment-106706887>
> .
>


-- 
Jeff Ancel

(314) 703-8829 - Main

www.jeffancel.com

**Comment by FZambia** [comment]
Thank you, let's keep this open until resolving

**Comment by FZambia** [comment]
@jancel it works now!

**Comment by jancel** [comment]
Did you do anything above and beyond to fix it or ah ha moment? I'm going
to be hitting it tonight. Thanks.

On Friday, May 29, 2015, Alexandr Emelin <notifications@github.com> wrote:

> @jancel <https://github.com/jancel> it works now!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/centrifugal/centrifugo/issues/14#issuecomment-106925380>
> .
>


-- 
Jeff Ancel

(314) 703-8829 - Main

www.jeffancel.com

**Comment by FZambia** [comment]
No, just patience:D
