### ISSUE TITLE
HTTP and HTTPS with the same process

### ISSUE THREAD

**Issue by ramon-ga** [centrifugal/centrifugo#140]
It's correct that's at the moment not possible to run http and https with the same process?
As seen here:
https://github.com/centrifugal/centrifugo/blob/1ea11c98b107b4d6e605930142913c27119290b3/libcentrifugo/server/httpserver/handlers.go#L197

If it's possible it will be perfect to use it with the packages for ex. ubuntu.

**Comment by FZambia** [comment]
Hello, yes, this is correct.

> If it's possible it will be perfect to use it with the packages for ex. ubuntu.

Could you explain what you mean here?

**Comment by FZambia** [comment]
Why not to use SSL server only? I mean that most services in the world now forcely redirect http traffic to https, the same relates to ws  --> wss I think.

**Comment by ramon-ga** [comment]
You're right, thank you for this hint! I don't think on that, issue solved ;)
