### ISSUE TITLE
tls: no cipher suite supported by both client and server

### ISSUE THREAD

**Issue by ramon-ga** [centrifugal/centrifugo#144]
I've got thousands or error messages in the log, like this:
```
Jan 23 06:25:48 ws centrifugo[1923]: 2017/01/23 06:25:48 http: TLS handshake error from xxx.xxx.xxx.x:48794: tls: no cipher suite supported by both client and server
```
This produces about 4GB of entries written to the log file per day..

This comes from browsers/os like this:
```
Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.42 (KHTML, like Gecko) Chromium/25.0.1349.2 Chrome/25.0.1349.2 Safari/537.42
ChromeChrome 25.0.1349.2, Linux X11

Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
ChromeChrome 49.0.2623.112, Windows XP

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2
SafariSafari 6.1.6, OS X 10.7.5
```
As i see this is only happening on old browsers and os...

Do you know if there's a solution for this?
Maybe a fallback connection to http?

**Comment by FZambia** [comment]
@ramon-ga this is where SockJS can help maybe? We can't just fallback connection to HTTP as it's a stateless protocol and requires more care to keep connection session and require sticky connections - what SockJS already solves.

And btw - looks like you use Centrifugo < 1.6.3 right? In Centrifugo 1.6.3 error from connection handshake goes to DEBUG level log so you won't get so many entries by default. I also suggest updating to Centrifugo 1.6.3 - see its changelog to see why.

**Comment by ramon-ga** [comment]
Ok, thank you. So there isn't a solution for older systems out of the box.
I'm going to investigate this a little bit to find a solution..

I was using 1.6.1 and now updated to 1.6.3, but the syslog (/var/log/syslog) is still flooded by the entries.
This error is maybe a direct output of the tls library?
Because centrifugo log entries are not the same format:
```
centrifugo log entry (--log_file=/var/log/centrifugo/centrifugo.log):
[I]: 2017/01/23 13:56:31 Starting http server
[E]: 2017/01/23 13:56:40 connect error: client already authenticated

Error in the syslog (/var/log/syslog):
Jan 23 14:19:01 ws centrifugo[5790]: 2017/01/23 14:19:01 http: TLS handshake error from xx.xx.xx.xx:4900: tls: no cipher suite supported by both client and server
```

**Comment by FZambia** [comment]
@ramon-ga yes, this comes from Go standard lib - looks like we can't catch it - will try to investigate from where it come from and is there a way to avoid flooding.

> So there isn't a solution for older systems out of the box.

Centrifugo supports SockJS out of the box to deal with old browser clients.

**Comment by FZambia** [comment]
@ramon-ga btw, you are using Go for TLS termination work right? Maybe putting this job on Nginx will allow to deal with such cases?

**Comment by FZambia** [comment]
Also I have a suggestion that disabling HTTP/2 could help. You can try to run Centrifugo with HTTP/2 disabled:

```
GODEBUG="http2server=0" ./centrifugo ....
```

**Comment by ramon-ga** [comment]
Hi, thanks for your tips.
i've done some tests, but no test has worked for the problem.

Test i've done:
**Disabled HTTP/2**
with `GODEBUG="http2server=0"` and directly in the code:
```
server := &http.Server{
     TLSNextProto: make(map[string]func(*http.Server, *tls.Conn, http.Handler), 0), // disable HTTP/2
}
```

**Set the cipher suites manually**
Interesting is on this part, the cipher list on ssllabs did not change after i change this..
```
server := &http.Server{
    TLSConfig: &tls.Config{
          PreferServerCipherSuites: true,
          CipherSuites: []uint16{
		tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
                ...
    }
}
```

**Test with direct certificate**
Run centrifugo without lets's encrypt (`--ssl --ssl_cert test.crt --ssl_key test.key`)



I run ssl test with ssllabs (https://www.ssllabs.com), and with no configuration i get it working.
Maybe interesting, with centrifugo 1.4.1 there is a better compability with older browser.

Cipher Suites centrifugo 1.4.1:
![image](https://cloud.githubusercontent.com/assets/402796/22248249/fcf81754-e23d-11e6-9ffe-070da0b65eb3.png)
Cipher Suites centrifugo 1.6.3:
![image](https://cloud.githubusercontent.com/assets/402796/22248281/1effa9f2-e23e-11e6-8b15-5ef7750416e8.png)

At the moment i'm going to live with that, but later i dive in this again.
The same problem exists on our other golang https server, so i try to find a solution on this.

Putting a proxy like nginx in front would be solve the problem, but at the moment i'm using a single server. With this i can reach about 250k Clients (or more), with a proxy in front the maximum client amount will be the half.. 
My target is to run golang standalone servers without a proxy.

On my other golang http server, this error will be catched by the logging package (https://gist.github.com/Tantas/1fc00c5eb7c291e2a34b)
```
2017-01-24T13:00:03.094Z [DEBUG] http: TLS handshake error from xx.xx.xx.xx:9323: tls: no cipher suite supported by both client and server
```

**Comment by FZambia** [comment]
@ramon-ga thanks for such a detailed investigation. During last day I also found mentioning this in  Caddy repo and [this](https://forum.golangbridge.org/t/caddy-0-7-6-released/) discussion - sure you also saw this. But it did not helped me a lot in understanding how to fix this especially now after you tried `PreferServerCipherSuites` and setting cipher suites manually.

> Maybe a fallback connection to http?

Sorry, I misinterpreted your words in issue description yesterday - so my words about SockJS were not helpful in any way. I suppose you meant fallback to plain `ws` instead of `wss`. But this anyway looks like a hack (and I don't really see how this could be implemented on client side) that eventually can lead to more issues.

It's hard for me to help with this a lot as I can not reproduce this, if you will find a simple way - please tell me.

> centrifugo 1.4.1 there is a better compability with older browser

It was built using older version of Go - so yeah, something could change. It's still possible to build Centrifugo using Go 1.5 : `GO15VENDOREXPERIMENT=1 go1.5 build`. But it's just to try maybe, that go version anyway already deprecated.

> On my other golang http server, this error will be catched by the logging package

Yeah, I think we can redirect those messages in our log, but what do you think is the appropriate level for them - debug, info, level? Semantically those messages are always errors so we can redirect into ERROR log. But will this save you from log spaming?

**Comment by FZambia** [comment]
What could be helpful in this situation is understanding what cipher suites client sends when such error happens. But without adding more logging into go std lib or using wireshark I don't see how to see this information.

**Comment by FZambia** [comment]
> With this i can reach about 250k Clients (or more), with a proxy in front the maximum client amount will be the half..

Just out of curiosity. This looks like a very huge number for a single server. Have you already tried this with Centrifugo? And have you already experimented with proxy in front?

**Comment by ramon-ga** [comment]
Thanks for your answers, old browser compatibility is always important for servers. But in this case i think most of the client browsers are ok with this. The problem ist just with old browsers/systems like `ChromeChrome 49.0.2623.112, Windows XP`, and these are just a few. I will make a workaround in our code, to disable the connection or reconnect without ssl. 
If i need that i will do it with a proxy/lb in front.

**Comment by ramon-ga** [comment]
> Just out of curiosity. This looks like a very huge number for a single server. Have you already tried this with Centrifugo? 

Yes this amount of clients i reached with centrifugo 1.6.1, i need to boot multiple client test servers to reach that. Because per client server the maximum connection count is around 64'500 tcp connections. 
![image](https://cloud.githubusercontent.com/assets/402796/22285272/2dcac4dc-e2eb-11e6-9bfc-cb0895891a71.png)
(Server: 8 Dedicated x86 64bit Cores, 32GB memory)

On the client servers i run your connections script: https://github.com/centrifugal/centrifugo/blob/master/extras/scripts/connections/connections.go
(With a workaround to not close all connections if one has an error: 
`sed -i -e "s/log.Fatal(err)/log.Print(err)/" $connectionsScript`)

To test a "real live" scenario, i send multiple messages to all ~258k clients, with this i'm getting a load around of 8 on the server. 
At the moment the maximum of real clients we reached is about 40k and normally about ~10k (On old server with 4 core processor, 8GB memory), but we want to be prepared for about 80k - 120k clients, we need this probably in future projects.

> And have you already experimented with proxy in front?

With the old centrifuge (Python) we had an autoscaling setup with a load balancer in front.
But we had some problems with that, so the decision was to deploy it as single server.
As Load Balancer we used tengine (fork of nginx, http://tengine.taobao.org/), because with a module it's possible to update the upstream-list without reloading Nginx.
(Details you will find here: https://github.com/centrifugal/centrifuge/issues/47 ;)

**Comment by FZambia** [comment]
Ah! I now remembered that issue, interesting - that was so long ago, happy that you are still using Centrifuge/Centrifugo. Thanks for sharing details - this looks incredible.

Still question about log level you prefer I redirect errors coming from Go std lib? We can make them `info` so `error` Centrifugo log level will suppress them.

**Comment by ramon-ga** [comment]
I've have to say thank you for this super simple stable websocket server! :1st_place_medal: 

For me it would be nice if all output is written to the specified log file, so i have the option to save it to another device. So it's not possible that the system fs is out of space because the log is huge...

**Comment by FZambia** [comment]
@ramon-ga made std lib logs go to INFO in this commit https://github.com/centrifugal/centrifugo/commit/ee82b1ae884cc8de2cf4e4cde0f4f7cb8468e380

**Comment by FZambia** [comment]
> Interesting is on this part, the cipher list on ssllabs did not change after i change this

This is really interesting, maybe ssllabs caches results for a while?

**Comment by ramon-ga** [comment]
> This is really interesting, maybe ssllabs caches results for a while?

I'm sorry this was wrong, i've corrected the text (https://github.com/centrifugal/centrifugo/issues/144#issuecomment-274803378). 
And no, the have a link `Clear cache` so nothing should be cached.

**Comment by FZambia** [comment]
@ramon-ga just found this [topic](https://productforums.google.com/forum/#!msg/chrome/g-9tUjLBp1E/xZDUg_kbAwAJ) - looks like Chrome 49 on XP uses RC4 suites which considered insecure. See [this line](https://github.com/golang/go/blob/master/src/crypto/tls/cipher_suites.go#L101) of Go source code: RC4 suites disabled by default. As far as I can see you tried with `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 ` but not with `TLS_ECDHE_ECDSA_WITH_RC4_128_SHA`, `TLS_ECDHE_RSA_WITH_RC4_128_SHA`, `TLS_RSA_WITH_RC4_128_SHA`.

**Comment by ramon-ga** [comment]
I tried alreasy to enable all ciphers i found in the go source code, i tested it with:
```
			TLSConfig: &tls.Config{
				GetCertificate:           certManager.GetCertificate,
				//MinVersion:               tls.VersionTLS12,
				//CurvePreferences:         []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256},
				PreferServerCipherSuites: true,
				CipherSuites: []uint16{
					tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
					tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
					tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
					tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
					tls.TLS_ECDHE_RSA_WITH_RC4_128_SHA,
					tls.TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,
					tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
					tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
					tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
					tls.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
					tls.TLS_RSA_WITH_AES_128_GCM_SHA256,
					tls.TLS_RSA_WITH_AES_256_GCM_SHA384,
					tls.TLS_RSA_WITH_RC4_128_SHA,
					tls.TLS_RSA_WITH_AES_128_CBC_SHA,
					tls.TLS_RSA_WITH_AES_256_CBC_SHA,
					tls.TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,
					tls.TLS_RSA_WITH_3DES_EDE_CBC_SHA,
				},
			},
			TLSNextProto: make(map[string]func(*http.Server, *tls.Conn, http.Handler), 0), // disable HTTP/2
```

**Comment by FZambia** [comment]
@ramon-ga investigated a bit with SSLLabs and real domain, here is results of simulated handshake from Chrome 49 on win XP SP3:
```
Supported: []uint16{0xc02f, 0xcca8, 0xcc13, 0xc014, 0xc013, 0x9c, 0x35, 0x2f, 0xa}
Preference: []uint16{0x5600, 0xc02f, 0xc02b, 0xc030, 0xc02c, 0xc011, 0xc007, 0xc013, 0xc009, 0xc014, 0xc00a, 0x9c, 0x9d, 0x5, 0x2f, 0x35, 0xc012, 0xa}

Start setting: 0xc02f for version 0x303 
!rsaSignOk

Start setting: 0xc013 for version 0x303 
!rsaSignOk

Start setting: 0xc014 for version 0x303 
!rsaSignOk

Start setting: 0x9c for version 0x303   
!rsaDecryptOk

Start setting: 0x2f for version 0x303   
!rsaDecryptOk

Start setting: 0x35 for version 0x303   
!rsaDecryptOk

Start setting: 0xa for version 0x303
!rsaDecryptOk
```

As you can see there are actually lots of matching cipher suites but none of them set by [setCipherSuite](https://github.com/golang/go/blob/81038d2e2b588f9df45d20a2ca0be446b0e421b2/src/crypto/tls/handshake_server.go#L770) function.  You can see reasons of why `continue` in that function was called in log above - i.e. all of the rejected by logic described [here](https://github.com/golang/go/blob/81038d2e2b588f9df45d20a2ca0be446b0e421b2/src/crypto/tls/handshake_server.go#L784).

**Comment by ramon-ga** [comment]
Thank you for investigating this so deeply!
As i understand this, It confirms that with old browsers there's no simple way to get it working.
The only way is a proxy like nginx in frontend to solve this right? So we can close this issue...

**Comment by FZambia** [comment]
@ramon-ga I don't see any solution at moment. Using Nginx can help - but maybe not if there is a real problems with client TLS. Maybe the error is deeply inside Go - but I am no qualified enough in this area at moment to say exactly. Actually we can try to use SSLLabs to test TLS with Nginx in front - I have not tried this when experimenting with `Chrome 49 XP SP3` handshake.

**Comment by FZambia** [comment]
@ramon-ga just run ssllabs over our demo https://centrifugo.herokuapp.com - it uses Heroku proxy for TLS - there is no problem with `Chrome 49 XP SP3`. Only IE6 on XP failed during handshake.

**Comment by FZambia** [comment]
@ramon-ga I posted question to [golang-nuts](https://groups.google.com/forum/#!topic/golang-nuts/neu_jKq9pYk) - hopefully someone strong in TLS can explain this behaviour.

**Comment by FZambia** [comment]
@ramon-ga I‘ve just tried running Go TLS server with trial certificate issued by Comodo - and it works on Chrome 49 XP SP3. So seems that the reason here is in certificates issued by Lets Encrypt. Dont think we can do much in this situation - consider dropping support for old clients like this or using another certificate authority.

**Comment by ramon-ga** [comment]
Thank you for your hint that this just occur with lets encrypt certs, now i had again some time to dive into it.
On a other host we have lets encrypt certs too, and there isn't a problem, so i compared it.
The main difference is the key `EC 256 bits` (golang autocert) and `RSA 2048 bits (e 65537)` (Other lets encrypt host).

So i searched and found a new flag for autocert `ForceRSA`, with this the server key will be `RSA 2048` and the ssllabs client `Chrome 49 XP SP3` is able to connect.
https://godoc.org/golang.org/x/crypto/acme/autocert#Manager
https://github.com/golang/crypto/blob/master/acme/autocert/autocert.go#L148

It's possible to add this line to the http handler (or make it configurable)?
```
ForceRSA:   true,
```
https://github.com/centrifugal/centrifugo/blob/master/libcentrifugo/server/httpserver/handlers.go#L196


Then the next thing is, that browsers without sni support didn't get a certificate (ex. `IE 8 / XP: Server sent fatal alert: internal_error`).
With a small change (call own function) to the `GetCertificate` function, we will able to set the default hostname to get the certificate.
Is it possible to implement this too?
```
		GetCertificate := func(hello *tls.ClientHelloInfo) (*tls.Certificate, error) {
			name := hello.ServerName
			if name == "" {
				hello.ServerName = "xx.myhostname.ch"
			}
			return certManager.GetCertificate(hello)
		}
```
https://github.com/centrifugal/centrifugo/blob/master/libcentrifugo/server/httpserver/handlers.go#L210

**Comment by FZambia** [comment]
@ramon-ga wow, you did brilliant research! 👍  Of course we can add both changes.

I think `ForceRSA` (`autocert_force_rsa`) must be configurable and off by default to mimic std lib behaviour and to prevent our backwards compatibility. And sth like `tls_server_name` for sni problem as looks like we also have to add it to our non Let's Encrypt https server [here](https://github.com/centrifugal/centrifugo/blob/master/libcentrifugo/server/httpserver/handlers.go#L227)

**Comment by ramon-ga** [comment]
Perfect, thank you. With this centrifugo should be fully backwards compatible with older browsers.

**Comment by FZambia** [comment]
@ramon-ga thanks for your work here! see release notes for v1.6.5
