### ISSUE TITLE
Remove "timestamp" field from message

### ISSUE THREAD

**Issue by joshdvir** [centrifugal/centrifugo#147]
Hi @FZambia 

Wanted to know why does the server needs to send a timestamp if it's in insecure mode?

Timestamp is needed in normal mode only from my understanding.

If removed it can save traffic 😄 

Thanks

**Comment by FZambia** [comment]
@joshdvir hello, do you mean timestamp in `connect` client to server message? It's not needed in insecure mode. Or you mean timestamp in every broadcasted message - if yes it's not related to security.

**Comment by joshdvir** [comment]
@FZambia yes I meant the timestamp send in every broadcasted message, does Centrifugo server use it?

From going over the code I didn't see the client using it, if removed it can save traffic.

Don't you think that any application has it's own logic about when messages are created and they use that? why does the server needs to send when messages where created ?

Thanks

**Comment by FZambia** [comment]
Actually this was added in Centrifuge that was written in Python after feature request in issue, so it was migrated into Go server version to preserve backwards compatibility. I've never used it myself so I'd be happy to remove it. If someone needs timestamp - it can be added into message payload.

But this is a breaking change for those who rely on it somehow. So at least we should wait with this for a while to collect opinions against removing it, then deprecate it in release notes and then remove. I'll change title of this issue to be more precise and let's wait.

**Comment by joshdvir** [comment]
👍 great, thanks a lot.

**Comment by williambao** [comment]
Hi @FZambia ,
Could you update the Android SDK for this?
Android SDK crashed when receive message from server, because the message json no `timestamp` property...
![image](https://cloud.githubusercontent.com/assets/779521/26034463/893dac26-38ef-11e7-9149-179fb9533180.png)
