### ISSUE TITLE
Resource consumption

### ISSUE THREAD

**Issue by arleincho** [centrifugal/centrifugo#149]
I have one server installed in our own vps, this server  is serving more or less 300 clients between 20 channels.

but the resource consumption is very heavy, like i show in the pictuare.

![captura de pantalla 2017-02-06 a las 9 10 40 a m](https://cloud.githubusercontent.com/assets/1291006/22650408/28b1d6aa-ec4d-11e6-901a-b770ec71cc3e.png)

Is  normal this behavior.

the configuration for the channel is:
"namespaces": [{
        "name": "players",
        "watch": true,
        "publish": true,
        "presence": true,
        "insecure": false,
        "join_leave": true,
        "history_size": 0,
        "history_lifetime": 0,
        "recover": false,
        "history_drop_inactive": true
    }] 

thanks for you advice.

**Comment by FZambia** [comment]
Hi @arleincho 

CPU usage is a one time snapshot - it can be less during the minute. Look at `top` command to see how it behaves.

I suggest you to disable `join_leave` option and see the difference first.

Next step is showing output of `stats` command from `actions` tab. 

And finally you can start Centrifugo in debug mode:
```
centrifugo -c config.json --debug
```
And then get cpu and memory profiles to get an exact understanding what is the reason of high CPU usage (it will take 30 sec):
```
curl http://your_centrifugo_address:8080/debug/pprof/profile > /tmp/cpu_profile
```

And memory:
```
curl http://your_centrifugo_address:8080/debug/pprof/heap > /tmp/heap_profile
```

Then send resulting files to me (as file attachments) and I'll look at them.

**Comment by arleincho** [comment]
i attach the two files

[Archivo comprimido.zip](https://github.com/centrifugal/centrifugo/files/755786/Archivo.comprimido.zip)

**Comment by FZambia** [comment]
Let's continue our discussion on Gitter - at moment this looks like abnormal Centrifugo usage with storm of heavy presence requests. Will reopen if we find that the problem is in Centrifugo itself.
