### ISSUE TITLE
Users how to join or leave channel? this same to Subscribe?

### ISSUE THREAD

**Issue by arden** [centrifugal/centrifugo#151]
Users how to join or leave channel? this same to Subscribe? i'm can't found it in centrifuge-ios example.

**Comment by FZambia** [comment]
@arden hello! 

`join` and `leave` events (messages) generated automatically when someone subscribes (`join` message emitted) to channel or unsubscribes (`leave` message emitted) from channel.  You don't need to do this manually. You need to turn `join_leave` configuration option for channel namespace where you want it to be sent.

I can't help with iOS client a lot as I am not Swift programmer, but I [opened an issue](https://github.com/centrifugal/centrifuge-ios/issues/9) and asked client author about how to set join and leave handlers.

**Comment by mogol** [comment]
@arden hey
`CentrifugeChannelDelegate` has methods
```swift
    func client(_ client: CentrifugeClient, didReceiveJoinInChannel channel: String, message: CentrifugeServerMessage)
    func client(_ client: CentrifugeClient, didReceiveLeaveInChannel channel: String, message: CentrifugeServerMessage) 
```
They should work after subscribing to channels.
