### ISSUE TITLE
centrifugo can support point to point chat?

### ISSUE THREAD

**Issue by arden** [centrifugal/centrifugo#154]
centrifugo can support point to point chat? or there have any way to do it ?

**Comment by FZambia** [comment]
Yes, it's possible to create channel that can only be used by 2 users (points). There are several ways to achieve this:

- use private channel (starting with $) - every time user will try to subscribe on it your backend should provide sign to confirm that subscription request. More in [docs](https://fzambia.gitbooks.io/centrifugal/content/mixed/private_channels.html)
- next is [user limited channels](https://fzambia.gitbooks.io/centrifugal/content/server/channels.html#user-channel-boundary) (with `#`) - you can create channel with name like `dialog#42,567` to limit subscribers only to user with id `42` and user with ID `567`
- finally you can create hard to guess channel name (based on some secret key and user IDs or just generate and save this long unique name into your main app database) so other users won't know this channel to subscribe on it.

**Comment by FZambia** [comment]
Also added this to our [FAQ](https://fzambia.gitbooks.io/centrifugal/content/FAQ.html#how-to-create-secure-channel-for-two-users-only-private-chat-case)
