### ISSUE TITLE
use of closed network connection

### ISSUE THREAD

**Issue by visrs** [centrifugal/centrifugo#157]
[I]: 2017/02/17 14:56:09 error sending to 44dbafec-f951-4558-affb-7ec02c9fb4c0 write tcp 192.168.62.135:8000->192.168.50.103:56740: use of closed network connection
[I]: 2017/02/17 14:57:20 error sending to ddfecec4-a14d-4529-9199-fd384090d7c9 websocket: close sent
[I]: 2017/02/17 14:57:23 error sending to 42913027-ae62-441b-8eb7-a4bee0104757 websocket: close sent
[I]: 2017/02/17 14:57:23 error sending to 5519fc4a-0272-4de8-827f-e8a9445b0bdc websocket: close sent
[I]: 2017/02/17 14:57:24 error sending to 824f9c32-6012-44a1-a9a3-b194506f2cd2 websocket: close sent
[I]: 2017/02/17 14:57:24 error sending to 5d0c0d84-d893-4e38-b362-76b414cc97e8 websocket: close sent
[I]: 2017/02/17 14:57:24 error sending to c87705c4-7cd0-491e-919c-0a3d309e8b85 websocket: close sent
[I]: 2017/02/17 14:57:25 error sending to 73df8dd0-5dc9-40aa-99f5-0bbe7563afd8 write tcp 192.168.62.135:8000->192.168.50.103:56455: write: broken pipe

**Comment by FZambia** [comment]
@visrs hello, as far as I can tell this happens when we are trying to send messages to already closed connection. So these messages are not actually errors. Maybe we should make them `debug` level in next release. Use log level `error` to avoid such messages in logs.

**Comment by visrs** [comment]
when one channel online user above 1200，this message will show，but i want support more users

**Comment by FZambia** [comment]
Have you increased open file descriptors limit?

**Comment by visrs** [comment]
ulimit -a|grep open
open files                      (-n) 51200

**Comment by FZambia** [comment]
Looks ok. As I said above these lines are not errors and do not indicate that sth wrong - in new releases we moved them to `debug` level so you won't see them by default. What makes you think that your instance can't support more than 1200 connections?

**Comment by visrs** [comment]
when connections above 1200 ，log will show and then all connections will lost connec

**Comment by FZambia** [comment]
Looks like network problem, maybe with proxy before Centrifugo - could you describe your setup in detail in our [gitter chat](https://gitter.im/centrifugal/centrifugo) ?

**Comment by visrs** [comment]
how many  connections  one centrifugo process   max  support，i want to know

**Comment by visrs** [comment]
proxy before Centrifugo is nginx

**Comment by FZambia** [comment]
> how many connections one centrifugo process max support，i want to know

See [FAQ](https://fzambia.gitbooks.io/centrifugal/content/FAQ.html#how-many-connections-can-centrifugo-handle)

**Comment by FZambia** [comment]
@visrs any update on this? I can't help without knowing details.

**Comment by visrs** [comment]
I just think how to do 50-100k clients?
Now, i use jmeter for test

**Comment by FZambia** [comment]
Personally I've never used jMeter. To emulate many connections in development environment you can use [our connections script](https://github.com/centrifugal/centrifugo/tree/master/extras/scripts/connections), it's written in Go so you need Go and some dependencies installed.

**Comment by visrs** [comment]
good tools.
I found online  client num will be affected with config "join_leave": true

**Comment by FZambia** [comment]
@visrs - closing this as this is not a real issue anymore - this looks like chat between two of us, so please ask questions in our [gitter chat](https://gitter.im/centrifugal/centrifugo), it's hard for me to understand what you mean sometimes - please try to write with more explanation to overcome the language barrier:)
