### ISSUE TITLE
session not in open state

### ISSUE THREAD

**Issue by visrs** [centrifugal/centrifugo#158]
[I]: 2017/02/16 08:22:26 New SockJS session established with uid 20bda3bf-fec0-4439-9708-1737cf0704db
[I]: 2017/02/16 08:56:05 error sending to 20bda3bf-fec0-4439-9708-1737cf0704db sockjs: session not in open state

**Comment by FZambia** [comment]
The same as #157

**Comment by FZambia** [comment]
Hmm, looks like you are using old Centrifugo right?

**Comment by visrs** [comment]
Yes，1.5.1

**Comment by FZambia** [comment]
Closing as duplicate of #157 . I also suggest you to upgrade to latest Centrifugo version.
