### ISSUE TITLE
How to monitor a optional channel?

### ISSUE THREAD

**Issue by liughost** [centrifugal/centrifugo#162]
We build a talk room,but I want to monitor a room, this room can selected on admin web page.
thanks!

**Comment by FZambia** [comment]
hello @liughost ! What do you mean exactly - what is room monitoring?

**Comment by DylanVolz** [comment]
I think he is building a chat room service using centrifugo that people can join and chat in, and is asking how to implement a way to passively watch the chat.

@liughost if that is the case, you could either monitor the channel via the admin app after setting the watch option to true (https://fzambia.gitbooks.io/centrifugal/content/web/index.html) or implement a subscriber to the channel that had no write capability.

**Comment by liughost** [comment]
thanks! I study admin interface.

**Comment by FZambia** [comment]
@liughost admin interface in pretty primitive, it allows only basic things. For example it's possible to monitor messages in channels with `watch` option set to `true`. But if you need to monitor specific channel then admin interface can be not a very suitable thing as it does not support any sort of filtering - you will see messages from all "watched" channels. Solution depends on actual task you want to solve - maybe admin capabilities are enough for your case, maybe you should build sth custom on top of Centrifugo.

**Comment by FZambia** [comment]
@liughost hope answers help you a bit, feel free to reopen issue and ask if you need more explanation - also knowing more context always helps to give a proper answer.
