### ISSUE TITLE
Way to know if history_lifetime was exceeded or that we can't get all missed messages from history

### ISSUE THREAD

**Issue by sergunich** [centrifugal/centrifugo#165]
**Use case 1:**
- history feature turned on, history_size - 5 messages (for example)
- user disconnects (poor network)
- on channel published 7 messages
- user reconnects
- user get 5 messages from history

Question: How to know that we missed 2 messages?

**Use case 2:**
- history feature turned on
- user disconnects (poor network)
- on channel published 7 messages
- user reconnects after some time (more then history_lifetime)
- user get 0 messages, because history empty

Question: How to know that we missed some messages because we exceeded history_lifetime?

**Comment by FZambia** [comment]
@sergunich hello, a very nice question. The answer is not simple. First thing I can say is Centrifugo approach for message recovery is just a best effort, there are no strong guarantees so you can't use this mechanism for critical data. As option you can configure your `history_size` and `history_lifetime` out of your message rates - maybe there are acceptable values for these options.

For critical messages you can only rely on your application backend as the only authority. I.e. think about mechanism to ask for missing messages from backend every time subscription successfully resubscribed.

Centrifugo has a field in it's internal protocol which indicates whether Centrifugo think that all messages were recovered after reconnect or not. So theoretically if we make it public it can be a signal that you need to ask your app server for missed messages. You can find how that flag is set looking at [this function](https://github.com/centrifugal/centrifugo/blob/master/libcentrifugo/conns/clientconn/conn.go#L680) - second returned value is `recovered` flag in subscription response I speak about.

It can sometimes return `true` when subscription request contained `last message id` and we found that id while iterating over history. In cases you described it will return `false`. Actually relying on this flag can slightly reduce amount of requests that you should do to your backend to get missed messages after each successful resubscribe. But it's impossible to say how strong this reduction will be as it heavily depends on application nature.

**Comment by sergunich** [comment]
@FZambia thanks for fast answer!

> Centrifugo has a field in it's internal protocol which indicates whether Centrifugo think that all messages were recovered after reconnect or not. So theoretically if we make it public it can be a signal that you need to ask your app server for missed messages.

That would be awesome. Seems like valuable feature.

>  Actually relying on this flag can slightly reduce amount of requests that you should do to your backend to get missed messages after each successful resubscribe.

Yes, that was exactly my plan :)

For now I will stick with "re-request all data after disconnect" approach

**Comment by FZambia** [comment]
@sergunich let's clarify API before I'll add it to Javascript client. With exported `recovered` flag it will be possible to rely on it in this way:

```javascript
function handleSubscribe(ctx) {
    // Called every time subscription succeeds - including resubscribe after reconnect.
    if (ctx.isResubscribe && !ctx.recovered) {
        drawText("you need to restore messages from app backend");
    } else {
        drawText("no need to restore state");
    }
}

var sub = centrifuge.subscribe(channel, handleMessage).on("subscribe", handleSubscribe)
```

Is this what you expect?

**Comment by banks** [comment]
Do we need to make it clear if exposing this that, while it might be useful, it doesn't hangs Centrifugo's "best effort" guarantee and that solutions relying on perfectly reliable or in-order message delivery still need to do more work to verify state with app rather than rely on Centrifugo transport?

**Comment by FZambia** [comment]
@sergunich yep as @banks noticed, relying on this still does not guarantee that all messages were perfectly recovered - this can only be a trade-off you can accept assuming that in normal workflow most messages have not been lost somewhere and no race conditions happened. So asking backend is still the most reliable way.

**Comment by sergunich** [comment]
> Is this what you expect?

Yes

> relying on this still does not guarantee that all messages were perfectly recovered

That's fine. I am aware of this.

**Comment by foobargeez** [comment]
+1 for this.  In need of this for Android and iOS clients too -- it helps to know `when` to request the backend app for more data.

**Comment by FZambia** [comment]
@sergunich I am a bit busy at moment, will try to add this into client before next week. @foobargeez  it's a bit difficult to add protocol features into mobile clients as I can't do this myself - but I'll open issues in both as soon as js client will support this. Actually our iOS and Android clients lack some features. They were contributed and now supported by community members. I work on https://github.com/centrifugal/centrifuge-mobile to at least provide generated from Go code Java and Swift full-featured client bindings - this is a work in progress and very experimental but at least I can control code myself.

**Comment by foobargeez** [comment]
Thanks @FZambia.  centrifuge-mobile is exciting.

**Comment by FZambia** [comment]
@sergunich just released `centrifuge-js` [1.4.6](https://github.com/centrifugal/centrifuge-js/blob/master/CHANGELOG.md#146) - please check it out.

**Comment by sergunich** [comment]
@FZambia I don't know why but recovery doesn't work.

Centrifugo server config:
![screenshot-area-2017-03-13-175244](https://cloud.githubusercontent.com/assets/2822102/23859798/f3333796-0815-11e7-9875-082cc751981f.png)

Centrifguge client config:
![screenshot-area-2017-03-13-175434](https://cloud.githubusercontent.com/assets/2822102/23860183/3772f2b0-0817-11e7-8cb2-1c8e2e0f552e.png)

Messages that I sent:
![screenshot-area-2017-03-13-180305](https://cloud.githubusercontent.com/assets/2822102/23860242/6ed7e4a4-0817-11e7-8e86-ed3afd4a2c60.png)

To emulate disconnection I use [redir](https://linux.die.net/man/1/redir).
Client -> redir -> centrifugo.
To disconnect client: just kill redir process.
To reconnect client: start redir again.

Steps:
- send several messages (through centrifugo admin)
- disconnect(kill redir)
- send several messages (through centrifugo admin)
- reconnect(start redir)

Result:
![screenshot-area-2017-03-13-174940](https://cloud.githubusercontent.com/assets/2822102/23859725/ad4a5462-0815-11e7-99c1-ff00d053655b.png)

**Comment by FZambia** [comment]
@sergunich looks like you are not using namespace `user` for which `recover` option is enabled: your channel is `user#2` right? To use namespace it must be sth like: `user:user#2`

**Comment by sergunich** [comment]
Wow! I somehow missed it...
Now with correct namespace it works.
Thanks @FZambia !

**Comment by FZambia** [comment]
Welcome:) Can we close this then?
