### ISSUE TITLE
How to start centrifugo?

### ISSUE THREAD

**Issue by chelkaz** [centrifugal/centrifugo#167]
CENTOS 7
# centrifugo -w --config="/etc/centrifugo/config.json" --log_level="debug" --log_file="/var/log/cintrifugo.log"

`ListenAndServe: listen tcp :8000: bind: address already in use`

# lsof -i -P -n

`COMMAND    PID          USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
...
centrifug  158    centrifugo    4u  IPv6 3128123121      0t0  TCP *:8000 (LISTEN)
...`
 site.ru:8000 page no open - ERR_CONNECTION_REFUSED

**Comment by FZambia** [comment]
@chelkaz hello! From what you've posted I suppose you actually successfully started Centrifugo but port 8000 not available from outside - maybe it's closed by firewall. Try asking 8000 port from inside the Centos 7 machine:

```
curl http://localhost:8000/connection/info
```

Output should be like:

```
{"websocket":true,"cookie_needed":false,"origins":["*:*"],"entropy":943439154}
```

**Comment by chelkaz** [comment]
Он!!! Thank you! You're right! From CURL console OK!
{"websocket":true,"cookie_needed":false,"origins":["*:*"],"entropy":565761875}

**Comment by FZambia** [comment]
Cool! So depending on your preferences - try to open port 8000, or proxy requests from already open port (maybe port 80 already open) to Centrifugo using reverse proxy like Nginx (we have Nginx configuration example in documentation), or you can just start Centrifugo on port that is already open changing `--port` flag.

**Comment by chelkaz** [comment]
You opened my eyes! Thanks, I read a lot of documentation and searched for examples, but my little experience makes it difficult for me to understand.

**Comment by chelkaz** [comment]
I open port 8000 and connect http://site.ru:8000/ - 404 page not found, if http://site.ru:8000/connection/info - {"websocket":true,"cookie_needed":false,"origins":["*:*"],"entropy":945434531}
**Why I do not see Admin?**

**Comment by chelkaz** [comment]
How i can restart centrifugo with add Flags? Default centrifugo start 8000 port without --web and --admin. If i restart systemctl restart centrifugo.service --web --admin Not work.

**Comment by FZambia** [comment]
@chelkaz just add port and web related options to Centrifugo JSON config file (`/etc/centrifugo/config.json`) instead of using command line flags:

```json
{
    "secret": "XXX",
    "admin": true,
    "admin_password": "XXX",
    "admin_secret": "XXX",
    "web": true,
    "port": "8000"
}
```

**Comment by systimanx-itsol** [comment]
I]: 2018/04/05 17:54:11 Start serving raw websocket, SockJS, API, admin, web endpoints on :8000
[F]: 2018/04/05 17:54:11 ListenAndServe: listen tcp :8000: bind: address already in use

curl http://localhost:8000/connection/info
{"websocket":true,"cookie_needed":false,"origins":["*:*"],"entropy":170012351}

and my config
{
  "secret": "admin",
    "connection_lifetime": 0,
    "anonymous": true,
    "publish": true,
    "watch": true,
    "presence": true,
    "join_leave": true,
    "history_size": 10,
    "history_lifetime": 30,
    "recover": true,
    "admin_password": "admin",
    "admin_secret": "admin",
    "port":"8000"
}

how to solve this issue?

**Comment by systimanx-itsol** [comment]
systimanx_itsol@centrifugal-instance:~$ lsof -i:8000
systimanx_itsol@centrifugal-instance:~$ curl http://localhost:8000/connection/info
{"websocket":true,"cookie_needed":false,"origins":["*:*"],"entropy":1387084916}
systimanx_itsol@centrifugal-instance:~$ sudo centrifugo --config=config.json --admin --web
[W]: 2018/04/06 02:26:33 No config file found
[I]: 2018/04/06 02:26:33 Config path: /home/systimanx_itsol/config.json
[I]: 2018/04/06 02:26:33 Version: 1.7.8
[I]: 2018/04/06 02:26:33 PID: 5633
[I]: 2018/04/06 02:26:33 Engine: In memory – single node only
[I]: 2018/04/06 02:26:33 GOMAXPROCS: 1
[I]: 2018/04/06 02:26:33 SockJS url: //cdn.jsdelivr.net/sockjs/1.1/sockjs.min.js
[I]: 2018/04/06 02:26:33 Start serving raw websocket, SockJS, API, admin, web endpoints on :8000
[F]: 2018/04/06 02:26:33 ListenAndServe: listen tcp :8000: bind: address already in use

**Comment by systimanx-itsol** [comment]
systimanx_itsol@centrifugal-instance:~$ sudo lsof -i:8000
COMMAND    PID       USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
centrifug 5697 centrifugo    3u  IPv6  49023      0t0  TCP *:8000 (LISTEN)

**Comment by systimanx-itsol** [comment]
After kill -15 <PID> i am able to stop all process and able to run it

**Comment by chelkaz** [comment]
HI! I use Nginx configuration for my domain and SSL https://centrifugal.github.io/centrifugo/deploy/nginx/
Admin page work http://mydomain.site:8000/#/ OK
default NGINX 8000
bot console command - curl http://localhost:8000/connection/info
404 page not found 
HELP Please(
