### ISSUE TITLE
Terminal client

### ISSUE THREAD

**Issue by synw** [centrifugal/centrifugo#168]
Hi. I made a little [terminal client for Centrifugo](https://github.com/synw/centcli): it can print stats, publish messages and listen to channels.

Note: this code is still experimental, furthermore that it uses a [custom wrapper around the Centrifugo drivers](https://github.com/synw/centcom).

**Comment by FZambia** [comment]
@synw thanks for contributing, good job! I'll look at this tool and create an issue with feedback. And then I think we can add a page in docs with a list of community-driven Centrifugo-related tools and libraries.

**Comment by FZambia** [comment]
@synw just created a [new section in documentation](https://fzambia.gitbooks.io/centrifugal/content/index.html#communitydriven-centrifugo-related-projects) - please feel free to add there other projects you built on top of Centrifugo.
