### ISSUE TITLE
can Server API have "subscribe" command?

### ISSUE THREAD

**Issue by roytan883** [centrifugal/centrifugo#169]
I just read the document again, find there only has "unsubscribe"  Server API command for backend server control user subscription. 

why no "subscribe" command in centrifugo Server API? 

the client can be fully passive.  make the three roles: backend server, centrifugo, client keeping sync subscription is inefficient. 

I think the simplest client would be only need connect to centrifugo, then wait new message coming.

**Comment by roytan883** [comment]
by the way, does the client need re-subscription when shortly disconnect? because the mobile network can lose connection and reconnect frequently.

**Comment by FZambia** [comment]
There is no subscribe in server API clients - server API clients were created to work on prefork-model framework side, there is no way to handle async subscriptions. And actually in normal flow all messages flow through backend so it have all messages anyway.

>  does the client need re-subscription when shortly disconnect? because the mobile network can lose connection and reconnect frequently.

Yep, it does - after disconnect Centrifugo node cleans client connection info, and actually client can then reconnect to another node. Do you know a better way?

**Comment by roytan883** [comment]
@FZambia 
**About "subscribe " command :**
For example:
If userA want join groupA on backend server. 
currently, userA need subscribe channel "public:groupA" by itself. it works like this:
1, client userA -> backend(join groupA)
2, backend -> userA (join groupA OK, now you should subscribe groupA)
3, client userA -> centrifugo (subscribe groupA)

The point is step 3, can be:
**3, backend -> centrifugo (userA subscribe groupA)**

That means the client should be **fully passive**. client no need subscribe any channel by itself . All subscription can be done by backend call centrifugo's Server API, backend server tell centrifugo which channels user want to subscribe.

It can simplify client logic, client no need concern which channel it should be subscription.  

current sync subscription status need 
```
1，client<-----> backend 
2，client<-----> centrifugo 
```

it can be simplify to :
```
1，client <-----> backend 
2，client <----- centrifugo 
```

**Comment by roytan883** [comment]
@FZambia 
**"there is no way to handle async subscriptions"**, it confuse me. 
why "unsubscribe" can be call by backend, but "subscribe" can not ?
You mean the client can only do subscription once at beginning , then it can not subscribe any new channels at runtime?

**Comment by roytan883** [comment]
The whole point is:

* Make the client simplify, just **call connect**, then **handle OnMessage**, that's all. 
* The subscription logic can be done by server side between backend and centrifugo.

**Comment by FZambia** [comment]
> "there is no way to handle async subscriptions", it confuse me.

I supposed you wanted to subscribe on channel and handle new messages on server side - so I answered on that, now I see that you are speaking about different thing - controlling client subscriptions on server side.

> 1, client userA -> backend(join groupA)
2, backend -> userA (join groupA OK, now you should subscribe groupA)
3, client userA -> centrifugo (subscribe groupA)

Do you mean only private channel subscriptions (because subscribe on normal channel does not require 3 steps now)? Or all subscriptions including non-private channels? I suppose you mean all subs because you said that client can be fully passive.

Some thoughts about caveats of approach you suggest:

1) Centrifugo should keep a state of user-channel subs in this case. And this state must be persistent as connection can live forever. So Centrifugo could restore client subscriptions on reconnect - this is what Centrifugo allows to avoid currently - subscriptions are self-managing.
2) How about recovering missed messages - who will send a last message ID - now it is sent in subscription request
3) It's not very flexible for big applications where client-side components can now subscribe from various parts of application, with your approach all client subscription logic must be concentrated in one place on backend. You need to maintain subscriptions on server side while now for most use cases this can be done in one line on client `centrifuge.subscribe('channel', callback)`.

**Comment by roytan883** [comment]
1，I want backend manage all subscriptions, backend server like a babysitter for all clients. clients no need worry about sync subscriptions status.
> For example, user join a temporary chat group , currently the client need subscribe a new channel, then when user leave , client need unsubscribe. If use my suggestion , client no need do any thing with centrifugo, it all handled by backend server. If the backend is intelligent, backend can delay the subscription when there have real new message in that temporary chat group, so if one user just fast join and leave temporary chat group in 3 seconds, then no thing happened.

2，recovering missed messages can be handled by backend, backend can provide a API "getMissedMessages" for client. And it will be much faster then client call each channel history by WAN network, because in most case, backend and centrifugo are running in the same LAN network. clients just post all channels last message ID to "getMissedMessages". Especially when the client has a lots subscription channels , faster and efficient by one API call for all channels.

3，I think in most case there is no real client subscription, that client subscribe a new channel but backend don't know that, it is horrible. Especially on business layer , i provide service , but i don't know who use it. I think the common logic should be :
> 1. clientX -> backend (hi, i want subscribe channel "news-A");  
> 2. backend -> client (OK, your subscription was made, just wait new message from "news-A") 
> 3. backend -> centrifugo (make clientX subscribe channel "news-A")

**Comment by roytan883** [comment]
centrifugo Server API command already has "unsubscribe", which give the ability to backend controlling user unsubscribe channels . Corresponding, there should have "subscribe" command for backend controlling user subscribe channels. 
If no "subscribe" coupled "unsubscribe", on Server API layer , it doesn't make sense.

**Comment by manson** [comment]
> the client can be fully passive.

> clients no need worry about sync subscriptions status.

> I think in most case there is no real client subscription, that client subscribe a new channel but backend don't know that, it is horrible

It all sounds stupid. If you dont want client to initiate subscription you should'n use any kind of pub/sub server except its a very simple app - i.e. any client will receive all messages. If client want to get a data from a channel it just subscribes it. In one code string. Almost all apps workflows is where the client desides what data to receive/consume and what not. Be it a web page or a desktop app. And backend only rules the permitions, filtering data and maybe some data processing. And of cause the delivery data user subscribed.  If its not - it looks like the app architecture is built wrong.

The other thing is that it lacks of server-side funcs to subscribe to channels as a client - in some situations it is very usefull, but its not hard to make it different way and is out of centrifugo conception as author wrote before...

As for your situation (backend desides should user subscribe or not) you may just use private channels and randomly generated channel names on backend:
As an example:
1) On app startup backend randomly generates channel names for topics
2) client->backend (hi, I want to subscribe to 'topic-A)
3) backend (check clientX authority, user role, channel "topic-A" settings ..... if all OK) - returns the real channel name for this topic
4) client subscribes to channel

**Comment by roytan883** [comment]
@manson 
if topic-A administrator want kick clientX, how to do that ? 
backend -> clientX: you should unsubscribe "topic-A-xxxx" ?  what if client has something wrong or not unsubscribe or even not received this message, what happened ? 

In this case, the only thing backend server can do is calling Centrifugo's Server API "unsubscribe" which force clientX to unsubscribe "topic-A-xxxx". But if you do that , here comes question : why backend can server side call "unsubscribe" but can not server side call "subscribe"???

**Comment by roytan883** [comment]
@manson in your opinion , I think Centrifugo should remove the Server API "unsubscribe". **Otherwise it doesn't make sense that only has "unsubscribe" but NO "subscribe".**
> unsubscribe allows to unsubscribe user from channel. params is an objects with two keys: channel and user (user ID you want to unsubscribe)
```
{
    "method": "unsubscribe",
    "params": {
        "channel": "CHANNEL NAME",
        "user": "USER ID"
    }
}
```

**Comment by manson** [comment]
@roytan883 
>if topic-A administrator want kick clientX, how to do that ?
If you're about security, make private channels to users or random for every user. And then just dont send data into this channel client listening to stop him receiving data. Anyway in a public or commonly used channels (for groups) you cannot rule security strictly. And as of this did user unsubscribed or not is not important

**Comment by manson** [comment]
@roytan883 
>I think Centrifugo should remove the Server API "unsubscribe". 

Why? This is right your situation.  User subscribed to a channel (you can hook the channel entered user on server side and make some authentication or other checks) and server may kick him out at any time...or leave...

**Comment by roytan883** [comment]
@manson 
> If you're about security, make private channels to users or random for every user. And then just dont send data into this channel client listening to stop him receiving data. Anyway in a public or commonly used channels (for groups) you cannot rule security strictly. And as of this did user unsubscribed or not is not important

To implement a chat room and its administrator, is that hard? need create lots of private channels for every user, just to implement one simple feature request "kick user" ?

**Comment by manson** [comment]
@roytan883 
>To implement a chat room and its administrator, is that hard? need create lots of private channels for every user, just to implement one simple feature request "kick user" ?

Oh? its all about chat? Ok lets see.
First of all we have the serverside function to unsubscribe user from any channel (join_leave). Right? So we already can kick user form channel. So the only thing left to do - auth user to a channel. Right? I think you're afraid that someone who is out of you app can connect to channel, right? Ok. From an app level we can simply auth user and manage his connection or disconnection from channel in a usual app workflow (client might unsubscribe itself if server said that). As for a foreign user - first he must connect with the same credentians than centrifugo server expose. He cannot just connect to any channel not being aware where to get connection parameters from. But ok, he did it and connected. And tries to connect to a channel. In this situation we can track the user connection from serverside (join_leave parameter in config). I didnt try it to know how it works in reality but it should give at least user id. You can check its availability in some serverside internal auth dictionaries and kick off the user if its not in.

**Comment by roytan883** [comment]
@manson I think the big difference opinion between you and me is : 

> in pub/sub system, who make the subscription ? I think your are insist on that subscription can be only made by client. But my opinion is both the client and backend server can make subscription. 

we just want use pub/sub system to implement a push service , like Apple's APNS. I don't think APNS all subscription are maintained by client. If you have  experience on iOS development , the only things need is "DeviceToken" from client to APP backend, then no matter how many channels or groups inside that APP, client no need call APNS subscribe on any channels .

**Comment by roytan883** [comment]
@manson 
> Oh? its all about chat? Ok lets see. First of all ......

I get you point , and your suggestion  is good. 

The things is, all your saying is based on one rule: `Client is the only one can make subscription.` **But why?** Does there have any specification about pub/sub system that rule ? what the bad effect if backend can server side full control user subscription ?

**Comment by roytan883** [comment]
@manson 
take a look at the Centrifugo Document :

>Centrifugo server easily integrates with your existing application – no need to change your project architecture and philosophy to get real-time events.

based on this, I don't think client handle subscription is a good idea. client should not concern which and when to subscribe or unsubscribe channels. The seamless integrate Centrifugo is only doing "connect" and "onMessage" on client side, thats all. 

All complex stuff should be handled by backend server. For example, you know that modify own server is much much faster than Apple's App store review and wait user to upgrade their client version.

**Make the client simple and clean , let the backend do the complex and heavy stuff** , that is my current prefered APP architecture.

**Comment by FZambia** [comment]
@roytan883 I think APNS analogy is not very correct because in APNS channel is just an app installed on device (device token is like channel) - so every message sent to APNS with device token will be delivered to app. You can do the same with Centrifugo subscribing on just one private channel.

I still have a question about how you imagine clients will reconnect. Consider this situation:

1) You have 10k clients online - all of them subscribed a month ago
2) They all need to reconnect (reason: network glitch, Centrifugo restart etc)
3) They reconnect to Centrifugo - but they won't receive messages because backend did not say Centrifugo which channels correspond to clients. Centrifugo does not have this information - because client channels are app specific. So every time clients will reconnect they should anyway send message to your app backend so backend can subscribe them to correct channels sending subscribe request to Centrifugo? If yes - this destroys your arguments about battery usage and traffic - you will have almost the same as we have now. Maybe I miss something?

**Comment by manson** [comment]
@roytan883 
>he only things need is "DeviceToken" from client to APP backend, then no matter how many channels or groups inside that APP
>Client is the only one can make subscription. But why?

Loosely speaking ios app is always subscribed to a one channel (in terms of our pub/sub). And by that device token it is the private channel created for a device. And all the info goes to a user in this channel. And if you remember in your mobile app when you "subscribe" to a notification along with this device token you supply the application name wich is a message filter for your app. If you wish to have something similar, nobody prevents you to subscribe user to a single private channel to which server will send all the user related data. You just filter it by a topics. And this is will be the same as IOS app you consider as a pattern.

**Comment by roytan883** [comment]
@FZambia @manson 
OK, maybe on big picture APNS is not a good example. My point is like this:

for client side code, it should be clean and simple. like use APNS, client side code only need 3 step:
`1，register which APNS get DeviceToke; 2 send tokens to backend ; 3, wait new message` , you see, at least, at source code level, there  is no code about `get channels`, `subscribe`, `unsubscribe` ......

what i want my client to integrate with centrifugo is the same . I want my client side code is like this:
`1，get centrifugo host address from backend api ; 2， connect to centrifugo ; 3， wait new messages`, **that's all**. what the bad effect if i implement my client code like this ?

**Comment by manson** [comment]
@roytan883 
>client should not concern which and when to subscribe or unsubscribe channels.
I think this is totally wrong. In chat application there might be hundreds channels client usually read info but currently he just wish to get the info from a single channel user swiched onto. Usually user just subscribes to a channel and unsubscribes from previous. In your model you will have to send all the data from all channels and let user filter data iteself (huge data amount) or if somehow server will know that you changed to a different channel (your client must say it to server) - in this case there is no difference how you gonna do it - remote methos call or resubscribe. Anyway you'll have to make server do something for client...

**Comment by manson** [comment]
@roytan883 
>what the bad effect if i implement my client code like this 

Its not for chat app if you want to see posts not only to a user but all from a chat room. As I sayed user may have hundreds of channells he subscribed and if you will send him all the data from them - you will have traffic overload and user disturbtion. But you can do it with clientside filtering and single subscription - its up to you how to get your users...

**Comment by roytan883** [comment]
@FZambia 
>Centrifugo does not have this information - because client channels are app specific. So every time clients will reconnect they should anyway send message to your app backend so backend can subscribe them to correct channels sending subscribe request to Centrifugo? If yes - this destroys your arguments about battery usage and traffic - you will have almost the same as we have now. Maybe I miss something?

It comes to the question again, **Why subscription only handled by client side?** In my plan, backend know all client's subscriptions. So this is simple, when client reconnect to Centrifugo, backend hooked it from Centrifugo, then backend call "subscribe" for that client user (server side recover client's subscriptions). During the reconnection, the client is fully passive. 

The problem is how to recover missed history , as my suggestion , backend can provide one API "getMissedMessages". when reconnect,  client need at least call one API to receive missed messages, I think this is common case for APP development.

for example , one client have 50 channel subscriptions. currently , when reconnect , client need send 50 subscribe command to Centrifugo, because subscription must handled by client. In my suggestion , client don't need send any thing except call "getMissedMessages".

**Comment by roytan883** [comment]
@manson 

In modern chat app, I don't think it still use join and leave rule, only one channel active rule. It is more like join group and stay, like **Skype**. If i join 10 groups, and my Skype is at background, when new messages comes from any group, should a notify shown. 

For you example , user may subscribe lots for topic or channels , like 1000 channels. Does that mean the client should maintain the 1000 subscription ? `join,leave, kick, subscribe ,unsubscribe ` at least those source code need to be implement in client side, and additional code to sync those subscription with backend server when user may operate it at PC or web. So what benifit we get from **"only client handled subscription"** ?

**Comment by manson** [comment]
@roytan883 
> Why subscription only handled by client side?

Because this is the common client-server use case. With a large amount of users the more effective balanced server is a stateless server. Users gets the minimum info from server and server dosen't care how user ask him and where from. The data sent to user is small enaugh as from server processing logic and from client simplisity. Client is simple not when it process all the info came from server as you think, but when it has only currently needfull information. In your situation you'll have to filter and manage info in client side all the time and its obvious for me not your "simple client". As for me your app arcitecture is totally wrong in this point of view.

**Comment by manson** [comment]
@roytan883 
>For you example , user may subscribe lots for topic or channels , like 1000 channels. Does that mean the client should maintain the 1000 subscription ? 

Of course not. When user selects one chat room - it subscribes to this chat room. When selects different - unsubscribes from previous and subscribes to current. There could be additional always subscribed to service channel where user can get common info - how many messages is on other channels, new and so, but not that currently unnessesary messages from other channels...

There no difficults to manage subscriptions this way. 

>at least those source code need to be implement in client side, and additional code to sync those subscription with backend server when user may operate it at PC or web

I dont get what the problems is here for you. Just get the latest messages when entering the channel and subscribe to new. That it. 2 simple steps.

**Comment by roytan883** [comment]
@manson if use your suggestion to implement a cross-platform APP: ios, Android , PC, web. At least, the synchronization of subscription information on each platform  is complex, because **"only client handled subscription"**

for example : 
```
1，user-A use Android client subscribe "topic-A"
2，backend notify user-A's: ios client, PC client , web webscoket page client;
3，those client subscribe "topic-A"
```
why can't we let backend handle step 2 and 3 ? 

I think to make one backend server code right is much easier, compare to make 4 different platform and 4 different develop languages synchronize subscriptions code right .

**Comment by manson** [comment]
@roytan883 
>why can't we let backend handle step 2 and 3 ?

 I dont get you. You make all the same client subscriptions from all platforms. Server doesn care from where you made subscription. Dont make server complex. All client will make the same steps on connect: make some queries (get latest messages) and subscribe to new one. From the serverside you of course may store linsk clientId->userId (clientId - unique client connection, userId - user id from db) to send info to all platforms in case of private channel. But if this is public channel you dont have to do anything at all on server side. Just push message to channel and forget

**Comment by roytan883** [comment]
@manson 
>I dont get you. You make all the same client subscriptions from all platforms. Server doesn care from where you made subscription. Dont make server complex. All client will make the same steps on connect: make some queries (get latest messages) and subscribe to new one. From the serverside you of course may store linsk clientId->userId (clientId - unique client connection, userId - user id from db) to send info to all platforms in case of private channel. But if this is public channel you dont have to do anything at all on server side. Just push message to channel and forget

OK, The simple use case:

> 1, user-A login on iPhone client , Android client , PC client , web client, simultaneously
> 2, user-A use iPhone client joined a new private channel "topic-123": this "topic-123" already has few user: user-B, user-C ...., and they may send new messages.
> 3, what next ? I want the user-A's other client(Android client , PC client , web client) also can get new message from "topic-123"

I don't how you implement step 3. 
**But in my solution, client side code on step 3 is none , because all stuff are handled by backend server**

**Comment by FZambia** [comment]
@roytan883 let's summarize, in current scheme you only need a server side call to subscribe client on channels. Because actually Centrifugo should not hook your backend - you can hook your backend from client on connect, reconnect events yourself via `backend.getMissedMessages()` call.

Every client has it's client ID, so call must be `backend.getMissedMessages(CLIENT-ID)`, because `subscribe` request from server to Centrifugo should look like this:

```
{
  "method": "subscribe",
  "params": {
    "client": "CLIENT-ID",
    "channels": ["channel_1", "channel_2"]
  }
}
```
So Centrifugo could subscribe this particular client to channels.

Is this what you expect?

**Comment by roytan883** [comment]
@FZambia 
That's right. corresponding current "unsubscribe", it may like this:
```
{
    "method": "subscribe",
    "params": {
        "channel": "CHANNEL NAME",
        "user": "USER ID"
    }
}
```
for performance , also provide "mSubscribe" will be nice:
```
{
    "method": "mSubscribe",
    "params": {
        "channels": ["channel_1", "channel_2"],
        "user": "USER ID"
    }
}
```

**Comment by FZambia** [comment]
See my updated post above - we can't operate with User IDs here - we must subscribe per client (per tab in browser in other words) - because the same user can see another page in other tab of  browser and not interested in events for another page.

**Comment by manson** [comment]
@roytan883 
>3, what next ? I want the user-A's other client(Android client , PC client , web client) also can get new message from "topic-123"
I don't how you implement step 3.
But in my solution, client side code on step 3 is none , because all stuff are handled by backend server

In common solution you dont have to to something special on step 3. This is all the same - you enters from another platform, does the same as if you enters from android. If this is common channel thats it. Centrifugo will send info to all connected clients of this channel. It doesnt care of your user id, every connected client is unique for centrifugo. Every client has its clientId. You can have multiple clientId's with one userId - its up to you how to link userId->clientId's. But this is nesessary only if you have to sent messages to specific userId clients. In this case as I said previously you have to store clientId->userId links on you backend. Maybe in redis, maybe in memory. In other situations its not nesessary.

**Comment by roytan883** [comment]
@FZambia 
> See my updated post above - we can't operate with User IDs here - we must subscribe per client (per tab in browser in other words) - because the same user can see another page in other tab of browser and not interested in events for another page.

I don't get it. you said **the same user**, so when user subscription changed, it should sync with user's all client. 

like currently the github page's right upper corner, the notification, when new message comes, all github browser tab show that blue point notification. 

for example, i opened an old github browser tab, then open a new github browser tab, subscribe new repository , when the new repository has notification , my old github tab also get new blue point notification.

**Comment by manson** [comment]
@roytan883 
>I don't get it. you said the same user, so when user subscription changed, it should sync with user's all client.

The "same" logic user, but not the same instance. In your example in github you see common notifications fot this user (you) but you dont see info (dont subscribe) on other your pages. I.e. dont have all the info opened in all pages in every page. Right? You see only those info you asked for current page, not more. The same in subscriptions. Some of them you subscribe according to your page, some globaly. And in this case (github) you should remember on server side how many clients (their ids) you have up for your userId

**Comment by FZambia** [comment]
> I don't get it. you said the same user, so when user subscription changed, it should sync with user's all client.

In general it should not. Imagine a web site where several absolutely different pages exist. On one page (PAGE_1) we show some sort of user schedule (calendar), on another page (PAGE_2) we show comments to some post. On PAGE_1 user must be subscribed only on CHANNEL_SCHEDULE, the same user on PAGE_2 must be subscribed only on CHANNEL_COMMENTS_FOR_SOME_POST. If you subscribe user on all possible events on your site it will receive tons of unnecessary messages that he/she currently does not actually need to handle.

**Comment by roytan883** [comment]
@manson 
> In common solution you dont have to to something special on step 3. This is all the same - you enters from another platform, does the same as if you enters from android. 

you mean user need manually open Android client , subscribe "topic-123" or re-login, by hand ??? **manually** ??? 

I don't get it , how you implement step 3, how to make Android client automatically receive new messages from "topic-123".

**Comment by manson** [comment]
@roytan883 
>I don't get it , how you implement step 3, how to make Android client automatically receive new messages from "topic-123".

Ok. Make this simple steps:
1) subscribe to topic-1 from android
2) subscribe to topic-1 fom web
3) push message to topic-1 from backend
You'll get that message as on android and on web because both subscribed to a same topic

**Comment by roytan883** [comment]
@FZambia @manson 

I think you are talking about traditional web page. But currently , web are more turn to SPA(single page web application), like angular or react, redux. web is more like a web client , not web page, especially APP area. 

You are worry about tons of message and network traffic, I think that's problem about what kind of message should be publish to channels. If only realtime message like chat message, i don't think it a problem. That depend on how APP's message architecture, can have some channel for user like  @xxx @forceALL @forceTopicA. Also APP can limit user's join channels (100?), no limit subscription is not support.  By the way, in real world, simultaneously real time messages in one user's different  channel is very very few.

**Comment by roytan883** [comment]
@manson 
> Ok. Make this simple steps:
.
> subscribe to topic-1 from android 
> subscribe to topic-1 fom web

**how to implement it?** how  Android know that should subscribe topic-1 ? 

need user manually awake his Android phone and open client APP, then manually click subscribe "topic-1" ? 

or need somehow server send notification to Android client, then android client automatically subscribe to topic-1? show me the code.

**Comment by roytan883** [comment]
@FZambia 
like i use Skype , if i joined "group-family-1" ,"group-company-1", "group-friends-1" . If currently i'm at group-family-1's chat page sending or read messages.  Meanwhile "group-company-1" and "group-friends-1" has new messages published, should i receive those new messages? 

I think the answer is YES. we are develop service for user, we are not technology decide which message should or not send to user. Its upto user. If the user is a salesman, he join lots of group , he want receive all messages , that is value for him. For normal user, if he joined too many group , those group messages already bother him, then it should be his responsibility to choose which group message need filter or leave that group, when he do it , our backend server just simplify unsubscribe that group's channel for him. Normally , we develop a chat APP, we provide user a setting options on every group, which are: "receive all notification", "receive All notification but not notify(ring)", "do not receive manually read".

**Comment by FZambia** [comment]
@roytan883 you asked @manson how client can subscribe on topic-1. You can implement it this way:

1) Have a channel named `topics`
2) As soon as client have to subscribe on channel `topic-1` you should send special type of message to channel `topics` (client already subscribed on it). This message can look:

```
{
    "event": "new_topic",
    "data": {
        "channel": "topic-1"
    }
}
```

And then you can programatically subscribe on channel "topic-1" - this is how client can discover new channels to subscribe.

> like i use Skype , if i joined "group-family-1" ,"group-company-1", "group-friends-1" . If currently i'm at group-family-1's chat page sending or read messages. Meanwhile "group-company-1" and "group-friends-1" has new messages published, should i receive those new messages?

I have not said that you always need to subscribe on one channel only - subscribe on many! If new chat created you previously not know about - send it to `topics` channel I described above and subscribe on client side.

**Comment by manson** [comment]
@roytan883 
>I think you are talking about traditional web page. But currently , web are more turn to SPA(single page web application), like angular or react, redux. web is more like a web client , not web page, especially APP area.

It doesnt matter. Actually I'm more in SPA. And I tryes to subscribe to channels that need at this moment. All this data store in browsers memory and in a intensive data exchange it might bring to browser's allocated for you app memory. Besides its like in database area normalization method - split data to tables and query only needing parts of info. You dont load all the data from database to your client but if yes - you have a very bad architecture.

>By the way, in real world, simultaneously real time messages in one user's different channel is very very few.

But you suggest exactly this. You want to realtime load all the new messages from all channels and filter it on client side. Even those messages you might even wont need (you wont go to all those channels).

>Also APP can limit user's join channels (100?), no limit subscription is not support

Aha! you allready limiting you users. Just because of architecture! But in our case you dont.

>how Android know that should subscribe topic-1 ?

How do I know you have to go home or to sleep? How do you know you want to read a book? You just know. The same is here. If I want to read a Topic-1 - I subscribe to this topic.

>need user manually awake his Android phone and open client APP, then manually click subscribe "topic-1" 

manually, automatically - whats the difference? Its up to you as a developer how your user will subscribe to topic - automaticcaly or manually. I really don't get you. If you wish make a subscrition on app start or when user enters the chat room or else...

>or need somehow server send notification to Android client, then android client automatically subscribe to topic-1? show me the code.

I dont get you. If you want to send to clients some common statistic, you can subscribe to a separate channel where you will send common info to a specific user. I dont understand why you should automattically subscribe to some channel according to a server event. You just do **subscribe("channel")** when you need according to you app workflow and thats it.

**Comment by manson** [comment]
@roytan883 

>I think the answer is YES. we are develop service for user, we are not technology decide which message should or not send to user.

Oh, I think I got you. It looks like your solution should be like this:
1) For every user you have a separate channel. Just for this user. Just one channel.
2) When user logins he subscribe to this channel. From all devices. This channel might me named by userId.
3) Its up to  you (your backend) to find out that specific user has a new message and server just publish it to a channel userId. All user devices will get this messages as they subscribed to a same user channel.
4) Every message has a property "room" by this you deside what to do in client side. I.e. you filters it. Say if you in a chat room "topic-1" - and this message has the same - you add it to a messages list. If this is a different chat room message - you popup it.
5) Message may have some special properties (service, system) for other purposes
6) thats it.

The same with sending messages. From any room you call the same server method, you just have to set the current room id property in message to which it belongs. 

This is very simple as I see and right what you want... I guess...

**Comment by roytan883** [comment]
@manson 
> But you suggest exactly this. You want to realtime load all the new messages from all channels and filter it on client side. Even those messages you might even wont need (you wont go to all those channels).

you are not reading my comments, filter not runned on client side.
> it should be his responsibility to choose which group message need filter or leave that group, when he do it , our backend server just simplify unsubscribe that group's channel for him. 

> Normally , we develop a chat APP, we provide user a setting options on every group, which are: "receive all notification", "receive All notification but not notify(ring)", "do not receive manually read".

------------------------------------------------------------------------------------------------------------

@manson @FZambia 
Ok, the manual channels subscription synchronization way is not our choice , no one like that in today cloud everywhere. 

The solution is like `server -> client (message: you should subscribe topic-1), client -> centrifugo (i want subscribe topic-1)`, no matter it is implement by private channel or other push system or sync plan. like i said need somehow server notify android client, then android do subscription .

The question is Why client need handled those kind of notification to know that it should subscribe topic-x ?  Why my client developer need write those source code to react channels subscription synchronization ?  

**Centrifugo claim that it can seamless integrate with existing system. What i provide is a simple and clean integrate plan, Why you insist on invade client code to handle all sub-unsub. This is big question i'm confused. If i can provide client developer with 10 line code to use Centrifugo , Why you insist on write more code on client side?**

**Comment by roytan883** [comment]
@manson 
> Oh, I think I got you. It looks like your solution should be like this: ..............

No, its not like that. If user-A joined group 1~100， then it subscribe "group-1" ~ "group-100", they are 100 subscriptions. 

your misunderstanding me is : 
who do the subscription **command** ? 

* **The result is the same** : user-A's client subscribed 100 channels on Centrifugo. 
* **The method is different**: you use client do the subscription , i use backend do the subscription.
* **another difference is** : At client side, my solution only need 10 lines code, yours i don't know. I already answered, the channels filter is handled by server side, so the network traffic is the same , or my solution is less, because my solution do not send any sub-unsub command to Centrifugo.

**Comment by manson** [comment]
@roytan883 
>No, its not like that. If user-A joined group 1~100， then it subscribe "group-1" ~ "group-100", they are 100 subscriptions.

In my suggestion doesnt matter how many subscriptions user has. When he "vurtually" joined and subscribes to "group-1-100" backend just knows that user will accept messages from all this subscriptions. Anyway your backend is a main ruler so let him do this job. New message arrived - it looks all the users who can accept this message (subscribed to a group message belongs) and send them. Here client is totally passive except the initial subscription to his channel.

**Comment by roytan883** [comment]
@manson 
> manually, automatically - whats the difference?

* **manually**, it botherthe USER. 
* **automatically**, my solution is only bother backend server developer. Your solution is bother both the client developer and backend server developer.

**Comment by manson** [comment]
@roytan883 
>Your solution is bother both the client developer and backend server developer.

There is no miracles. In development bothers both sides. In a good product

**Comment by roytan883** [comment]
@manson 
> There is no miracles. In development bothers both sides. In a good product

No, in a good product, is let server handle those dynamic frequently changed logic, let client be dumb just do basic logic and show. Currently , most successful APP on iPhone and Android , is hybrid APP, half native haft web page. If a application logic can be handled by server then no need chagne the client. 

like our argument, if the subscription can be handled by server , why bother client ?

**Comment by roytan883** [comment]
@FZambia although i don't get why can't "**subscribe**" by User_ID, but i think if you provide 
```
{
  "method": "subscribe",
  "params": {
    "client": "CLIENT-ID",
    "channels": ["channel_1", "channel_2"]
  }
}
```
then my backend can call it multiple time to implement server side controlling user subscription for all that user's client.

**Comment by manson** [comment]
@roytan883 
>If a application logic can be handled by server then no need chagne the client.

According to my experience I would give some reasonable logic to client to make by server breath. Let users processors work instead of my server. Thats why SPA has a growing interest - because its client-rendered. But of course it should be balanced. My main tool is Meteor.js and it has the similar websocket subscriptions engine. But because of node.js (serverside of meteor) not very good with sockets - a couple hundred of users make it die and even several users over ssh make it use 100% of processor I had to rewrite subscribtion engine using centrifugo. On my users count centrifugo almost always sleeps - I event cannot detect when it use some resources. And works fine. 
So SPA is not dumb clients.

**Comment by FZambia** [comment]
@roytan883 thinking more, imagine Centrifugo many Centrifugo nodes with 100k clients on each. If they all need to reconnect (Centrifugo restart) they will reconnect almost immediately.

In current approach:

1) If channels are public no requests will be made to server backend at all (and I consider this is a main Centrifugo feature, most use cases are ok with public channels)
2) If channels are private - 100k requests will be sent to backend requesting channel sign, and then 100k requests will be sent from client to one Centrifugo to actually subscribe on channel.

In your approach:

1) After reconnect every client will issue a request to your backend - i.e. 100k requests in any way
2) Then 100k requests from backend to Centrifugo
3) Then every subscribe command should be broadcasted to other Centrifugo node because user can be connected to any node - i.e. 100k publish operation in Redis. And then all those messages must be received and processed on **every node** I think this is not scalable.

**Comment by roytan883** [comment]
@FZambia 
Yes, this is a good example. 

In current approach:
> If channels are public no requests will be made to server backend at all (and I consider this is a main Centrifugo feature, most use cases are ok with public channels)

but the client still need send subscribe to public channels to Centrifugo after reconnect ? right? as your answer `Yep, it does - after disconnect Centrifugo node cleans client connection info`. Because  the client don't know the reconnection is caused by network problem or server problem. so every client will subscribe its channels again , then lots of subscription command are made to Centrifugo , must be more than 100K.

So in current approach, its not cheap when Centrifugo restart .

------------------------------------------------------------------------------------------------------------------------

In my approach:
> 1. After reconnect every client will issue a request to your backend - i.e. 100k requests in any way
> 2. Then 100k requests from backend to Centrifugo

backend can have request limitation when very large requests post simultaneously for this performance concerned API.  for example , limit to 100/s, so it is 6k/min, for 100K, only need 16 minutes. We are talking about Centrifugo restart, this shouldn't happen frequently. If it really happen , then need 16 minutes, I think its a reasonable time cost. For those deny request , backend  API will return a specified error to client , let it retry in a random 30~60 seconds. 

In real world, when server restart, client reconnect , those thing happened in background, most our client is in sleeping background mode, only user are currently using our APP at front, then user will notice that connection lose.  And in real world, server performance is much better than 100/s, it will be recovered quickly, even the user have not noticed connection lose.

I think its a common issue about requests limitation , like nginx or other server , can config a reasonable limitation.

for centrifugo, can do the same thing to limit connection rate. If centrifugo do those limitation , then backend no need limitation :) because step 2 is triggered by step 1's succeed reconnect. Anyway , backend API server should have basic requests limitation for all APIs. No matter how powerful Centrifugo, or nginx , or our backend server , there always need requests limitation setting. 

In your example , 100K clients, if each client need subscribe 10 channels . Lets do the math, how many network traffic need: 100K connect command , 1000K subscribe command . You see , in my solution , the 1000K subscribe command were saved, it running in server side LAN network.

**Comment by manson** [comment]
@roytan883 
>You see , in my solution , the 1000K subscribe command were saved, it running in server side LAN network.

If you dont use your app you'll save 2000K commands, he-he :-)

**Comment by FZambia** [comment]
@roytan883 I have a strong feeling that in PUB/SUB system client must control what he want to receive. This is how all PUB/SUB systems work. Decoupling publisher and subscriber is what PUB/SUB was invented for. 

I see your points about some savings (traffic and client simplicity benefits) but if we think deeper we will see that every server-side subscribe command must be reliable - we can miss messages, but I think we can't afford a system in non-deterministic subscribe state. This non-deterministic state will appear as soon as we will share subscribe commands across Centrifugo nodes cluster. As this is done via non-reliable Redis PUB/SUB mechanism we can't guarantee clients will be subscribed on channels they must be subscribed to. Subscribe command can be lost somewhere on its way. So in any given moment we can't say exactly what's happening with client subscriptions. This can be an acceptable trade-off for you but once I add this into Centrifugo other people will start using this too and I have to deal with this and with all problems this can introduce - I feel that this can be a wrong step for Centrifugo.
