### ISSUE TITLE
Close status codes?

### ISSUE THREAD

**Issue by klauspost** [centrifugal/centrifugo#17]
What is the purpose of the "status" error code ion the session interface?

Typical usage:
```Go
	if err != nil {
		c.sess.Close(3000, "error sending message")
	}
```

Of course the number "3000" seems very arbitrary, and for instance in the wsConn it is just ignored:
```Go
func (conn wsConn) Close(status uint32, reason string) error {
	return conn.ws.Close()
}
```

**Comment by FZambia** [comment]
This is a SockJS protocol specific error code. Please, see [this](https://github.com/sockjs/sockjs-protocol/blob/master/sockjs-protocol-0.3.3.py#L479) and also [this](https://github.com/igm/sockjs-go/blob/v2/sockjs/sockjs.go#L12). I don't really know why 3000 so just followed conventions I saw. In case of raw websocket I just implemented `Close(status uint32, reason string) error` to fit SockJS session interface

**Comment by klauspost** [comment]
ok. fair enough. Maybe is should just be added as a constant?

**Comment by FZambia** [comment]
yes, why not

**Comment by FZambia** [comment]
Added a constant in a21ee1ff00fe14c7c1c8b9a133ca7c5e64ae7840
