### ISSUE TITLE
[feature request] new Server API "mPresence" and "mHistory"

### ISSUE THREAD

**Issue by roytan883** [centrifugal/centrifugo#172]
On server side backend and centrifugo, it will be much efficient that one API call operate multiple channels. Maybe also need "mDisconnect", "mSubscribe", "mUnsubscribe"
```
{
    "method": "mPresence",
    "params": {
        "channels": ["CHANNEL_1", "CHANNEL_2"]
    }
}
```

```
{
    "method": "mHistory",
    "params": {
        "channels": ["CHANNEL_1", "CHANNEL_2"]
    }
}
```

**Comment by FZambia** [comment]
It's already possible to do  in one request using array of commands:

```json
[
  {
    "method": "presence",
    "params": {
        "channel": "CHANNEL_1"
    }
  },
  {
    "method": "presence",
    "params": {
        "channel": "CHANNEL_2"
    }
  }
]
```

This is a bit more verbose than what you suggested of course - but I don't think we need to optimize this until someone will have real problems with it.

**Comment by roytan883** [comment]
@FZambia Thanks
`array of commands` works for me
