### ISSUE TITLE
Need Developer documentation

### ISSUE THREAD

**Issue by msaranas** [centrifugal/centrifugo#178]
Create Developer documentation about setup workspace , dependency packages installation for beginner , customise the code , build and run debug.

**Comment by FZambia** [comment]
@msaranas hello, just started wiki and added [page for developers](https://github.com/centrifugal/centrifugo/wiki/For-developers-and-contributors) there - should I add some more info?

**Comment by msaranas** [comment]
i tried go build , got errors, I am using Gogland EAP IDE , go 1.8 version Please refer screenshot attached <img width="1276" alt="screen shot 2017-05-16 at 1 05 35 pm" src="https://cloud.githubusercontent.com/assets/3191440/26094662/6fa6de00-3a38-11e7-9e74-5ce024ac83b1.png">

**Comment by banks** [comment]
Thanks for the ticket. 

I can see having some basics on this would make the project more friendly for potential contributors. 

Can I ask if you found any specific areas confusing here?

It's been a while since I worked on Centrifugo but I recall it follows all the go practices and almost all of the points you mentioned would be more or less identical to any other Golang project. 

If you ran into specific issues that would help guide the task. If it was just general Golang project familiarity we could maybe link to more general resources?

**Comment by banks** [comment]
Sorry wrote that earlier before your reply. 

That is useful context thanks!

**Comment by msaranas** [comment]
Log FYI,

/usr/local/Cellar/go/1.8.1/libexec/bin/go run /Users/admin/GoglandProjects/centrifugo/main.go
# github.com/centrifugal/centrifugo/libcentrifugo/centrifugo
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/centrifugo/main.go:208: cannot use nod (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node in argument to engineFactory
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/centrifugo/main.go:221: cannot use nod (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node in argument to fn
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/centrifugo/main.go:248: cannot use servers (type map[string]"vendor/github.com/centrifugal/centrifugo/libcentrifugo/server".Server) as type map[string]"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/server".Server in field value
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/centrifugo/main.go:269: cannot use "github.com/centrifugal/centrifugo/vendor/github.com/FZambia/viper-lite".GetViper() (type *"github.com/centrifugal/centrifugo/vendor/github.com/FZambia/viper-lite".Viper) as type *"vendor/github.com/centrifugal/centrifugo/vendor/github.com/FZambia/viper-lite".Viper in argument to "vendor/github.com/centrifugal/centrifugo/libcentrifugo/config".NewViperConfigSetter
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/centrifugo/main.go:269: cannot use rootCmd.Flags() (type *"github.com/centrifugal/centrifugo/vendor/github.com/spf13/pflag".FlagSet) as type *"vendor/github.com/centrifugal/centrifugo/vendor/github.com/spf13/pflag".FlagSet in argument to "vendor/github.com/centrifugal/centrifugo/libcentrifugo/config".NewViperConfigSetter
# github.com/centrifugal/centrifugo/libcentrifugo/engine/enginememory
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/enginememory/engine.go:19: cannot use Plugin (type func(*"vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node, "vendor/github.com/centrifugal/centrifugo/libcentrifugo/config".Getter) ("vendor/github.com/centrifugal/centrifugo/libcentrifugo/engine".Engine, error)) as type plugin.EngineFactory in argument to plugin.RegisterEngine
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/enginememory/engine.go:24: cannot use *MemoryEngine as type "vendor/github.com/centrifugal/centrifugo/libcentrifugo/engine".Engine in return argument:
	*MemoryEngine does not implement "vendor/github.com/centrifugal/centrifugo/libcentrifugo/engine".Engine (wrong type for AddPresence method)
		have AddPresence(string, string, "vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".ClientInfo, int) error
		want AddPresence(string, string, "vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".ClientInfo, int) error
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/enginememory/engine.go:83: cannot use message (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".Message) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".Message in argument to e.node.ClientMsg
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/enginememory/engine.go:90: cannot use message (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".JoinMessage) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".JoinMessage in argument to e.node.JoinMsg
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/enginememory/engine.go:97: cannot use message (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".LeaveMessage) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".LeaveMessage in argument to e.node.LeaveMsg
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/enginememory/engine.go:104: cannot use message (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".ControlMessage) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".ControlMessage in argument to e.node.ControlMsg
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/enginememory/engine.go:111: cannot use message (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".AdminMessage) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".AdminMessage in argument to e.node.AdminMsg
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/enginememory/engine.go:124: cannot use &chOpts (type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".ChannelOptions) as type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".ChannelOptions in argument to e.historyHub.touch
# github.com/centrifugal/centrifugo/libcentrifugo/engine/engineredis
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/engineredis/engine.go:26: cannot use Plugin (type func(*"vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node, "vendor/github.com/centrifugal/centrifugo/libcentrifugo/config".Getter) ("vendor/github.com/centrifugal/centrifugo/libcentrifugo/engine".Engine, error)) as type plugin.EngineFactory in argument to plugin.RegisterEngine
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/engineredis/engine.go:27: cannot use Configure (type func("vendor/github.com/centrifugal/centrifugo/libcentrifugo/config".Setter) error) as type plugin.Configurator in argument to plugin.RegisterConfigurator
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/engineredis/engine.go:513: cannot use *RedisEngine as type "vendor/github.com/centrifugal/centrifugo/libcentrifugo/engine".Engine in return argument:
	*RedisEngine does not implement "vendor/github.com/centrifugal/centrifugo/libcentrifugo/engine".Engine (wrong type for AddPresence method)
		have AddPresence(string, string, "vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".ClientInfo, int) error
		want AddPresence(string, string, "vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".ClientInfo, int) error
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/engineredis/engine.go:1009: cannot use &message (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".ControlMessage) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".ControlMessage in argument to e.node.ControlMsg
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/engineredis/engine.go:1017: cannot use &message (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".AdminMessage) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".AdminMessage in argument to e.node.AdminMsg
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/engineredis/engine.go:1093: cannot use &message (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".Message) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".Message in argument to e.node.ClientMsg
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/engineredis/engine.go:1100: cannot use &message (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".JoinMessage) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".JoinMessage in argument to e.node.JoinMsg
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/engineredis/engine.go:1107: cannot use &message (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".LeaveMessage) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".LeaveMessage in argument to e.node.LeaveMsg
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/engineredis/engine.go:1697: cannot use cmd (type "vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".APICommand) as type "vendor/github.com/centrifugal/centrifugo/libcentrifugo/proto".APICommand in argument to apiCmd
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/engineredis/engine.go:1714: cannot use n (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node in argument to apiv1.PublishCmdAsync
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/engine/engineredis/engine.go:1714: too many errors
# github.com/centrifugal/centrifugo/libcentrifugo/server/httpserver
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/server/httpserver/handlers.go:309: cannot use s.node (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node in argument to clientconn.New
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/server/httpserver/handlers.go:309: cannot use newSockjsSession(sess) (type *sockjsSession) as type "vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/conns".Session in argument to clientconn.New:
	*sockjsSession does not implement "vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/conns".Session (wrong type for Close method)
		have Close(*"vendor/github.com/centrifugal/centrifugo/libcentrifugo/conns".DisconnectAdvice) error
		want Close(*"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/conns".DisconnectAdvice) error
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/server/httpserver/handlers.go:380: cannot use s.node (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node in argument to clientconn.New
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/server/httpserver/handlers.go:380: cannot use newWSSession(ws, pingInterval, writeTimeout, wsCompressionMinSize) (type *wsSession) as type "vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/conns".Session in argument to clientconn.New:
	*wsSession does not implement "vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/conns".Session (wrong type for Close method)
		have Close(*"vendor/github.com/centrifugal/centrifugo/libcentrifugo/conns".DisconnectAdvice) error
		want Close(*"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/conns".DisconnectAdvice) error
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/server/httpserver/handlers.go:470: cannot use s.node (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node in argument to apiv1.ProcessAPIData
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/server/httpserver/handlers.go:592: cannot use s.node (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node in argument to adminconn.New
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/server/httpserver/handlers.go:592: cannot use sess (type *wsSession) as type "vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/conns".Session in argument to adminconn.New:
	*wsSession does not implement "vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/conns".Session (wrong type for Close method)
		have Close(*"vendor/github.com/centrifugal/centrifugo/libcentrifugo/conns".DisconnectAdvice) error
		want Close(*"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/conns".DisconnectAdvice) error
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/server/httpserver/handlers.go:612: cannot use "vendor/github.com/centrifugal/centrifugo/libcentrifugo/conns".DisconnectAdvice literal (type *"vendor/github.com/centrifugal/centrifugo/libcentrifugo/conns".DisconnectAdvice) as type *"vendor/vendor/github.com/centrifugal/centrifugo/libcentrifugo/conns".DisconnectAdvice in argument to c.Close
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/server/httpserver/server.go:14: cannot use HTTPServerPlugin (type func(*"vendor/github.com/centrifugal/centrifugo/libcentrifugo/node".Node, "vendor/github.com/centrifugal/centrifugo/libcentrifugo/config".Getter) ("vendor/github.com/centrifugal/centrifugo/libcentrifugo/server".Server, error)) as type plugin.ServerFactory in argument to plugin.RegisterServer
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/server/httpserver/server.go:15: cannot use HTTPServerConfigure (type func("vendor/github.com/centrifugal/centrifugo/libcentrifugo/config".Setter) error) as type plugin.Configurator in argument to plugin.RegisterConfigurator
../../go/src/github.com/centrifugal/centrifugo/libcentrifugo/server/httpserver/server.go:15: too many errors

Process finished with exit code 2

**Comment by FZambia** [comment]
@msaranas looks like you have a mess in directories at moment. This can be related to Gogland somehow - I never used it yet, so hard to say. You can start from scratch without using Gogland - just in your terminal. Also note that code should be located inside your $GOPATH dir: `$GOPATH/src/github.com/centrifugal/centrifugo`

**Comment by msaranas** [comment]
@FZambia @banks Thank you for your support, yes issue related to directory and  vendor directory.
Now bale to build ,run and debug using Gogland.
<img width="1274" alt="screen shot 2017-05-16 at 3 03 05 pm" src="https://cloud.githubusercontent.com/assets/3191440/26099693/2996e2d2-3a49-11e7-9e92-ca4e16c794eb.png">

**Comment by FZambia** [comment]
@msaranas great, happy coding! 👍
