### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by klauspost** [centrifugal/centrifugo#18]
Right now shutting down the server, will just kill whatever it currently is doing. 

I would propose that we put in a way to flush pending messages while rejecting incoming requests.

I will send a PR.

**Comment by FZambia** [comment]
It's too late in Moscow, will see at all you propose here tomorrow!

**Comment by klauspost** [comment]
Same here. Sleep well!

**Comment by klauspost** [comment]
Continued in #26
