### ISSUE TITLE
Centrifugo PID file

### ISSUE THREAD

**Issue by nanom1t** [centrifugal/centrifugo#181]
Hi.

I've installed Centrifugo on my Ubuntu 16.04 LTS server using https://packagecloud.io/FZambia/centrifugo. Here https://github.com/centrifugal/centrifugo/blob/master/extras/packaging/initd.sh I've found that Centrifugo stores PID in /var/run/centrifugo/centrifugo.pid file. However there is not this file in my system.

Where can I find this file or how can I configure pidfile path for Centrifugo?

Thanks

**Comment by FZambia** [comment]
Hello, if I remember right on Ubuntu 16.04 we use `systemd` to daemonize Centrifugo - [here](https://github.com/centrifugal/centrifugo/blob/master/extras/packaging/centrifugo.service) is its config. There is no pidfile used. The script in your link is for previous Ubuntu releases which had no `systemd` installed.

**Comment by nanom1t** [comment]
Thanks for your response. Yes, you are right. You can also create pid file in systemd using next example:
'PIDFile=/var/run/centrifugo.pid'. it is useful for process monitoring (for example with Monit).

**Comment by FZambia** [comment]
systemd does not create PID file itself - it's a task for a process it daemonizes (i.e. Centrifugo in this case), this `PIDFile` option only helps systemd to get a value of main daemon process (see [this](https://www.freedesktop.org/software/systemd/man/systemd.service.html#PIDFile=)). So just adding `PIDFile=/var/run/centrifugo.pid` won't work. With Monit it's possible to monitor process by name I suppose?

**Comment by nanom1t** [comment]
Yes, it is possible to monitor process by name. Now I'm using next configuration for Monit and it is working. 
`
check process centrifugo
    matching "centrifugo"
    start program = "/usr/sbin/service centrifugo start"
    stop program = "/usr/sbin/service centrifugo stop"
    if failed host 127.0.0.1 port {{ centrifugo_port }} then restart
    if cpu > 60% for 2 cycles then alert
    if cpu > 85% for 5 cycles then restart
    if children > 255 for 5 cycles then stop
    if 5 restarts within 5 cycles then timeout
`
However the traditional way for Monit is to use something like this:
`
check process redis with pidfile "/var/run/redis/redis-server.pid"
`
I'm not sure how it will beheive if there will be runnning few processes of Centrifugo with same name.

Thanks

**Comment by nanom1t** [comment]
I have a little question. In my Nginx configuration file I have next lines for static resource caching:
```
    location ~ \.(ico|jpg|jpeg|gif|png|wav|ogg|m4a|mp3|swf|flv|zip|rar|xml|txt)$ {
        root /var/www/public_html/{{ host_domain }}/www/;
        access_log off;

        # cache static
        add_header Cache-Control public;
        expires 30d;
    }
```
Also I've enabled Centrifugo web panel. It works, but I have issues with loading static resources from centrifugo admin panel:
`GET http://domain.net/centrifugo/public/images/bg.png 404 (Not Found)`
Where is `public/` directory is located/cached in the filesystem? I need to create root directive for it in Nginx.

Thank you.

**Comment by FZambia** [comment]
> Where is public/ directory located/cached in the filesystem? I need to create root directive for it in Nginx.

Static assets embedded into Centrifugo server - you need to proxy directly on Centrifugo, there is an [example config in docs](https://fzambia.gitbooks.io/centrifugal/content/deploy/nginx.html#embed-to-a-location-of-web-site) - it should work. Have you tried that?
