### ISSUE TITLE
Channels question

### ISSUE THREAD

**Issue by nanom1t** [centrifugal/centrifugo#183]
Hi,

I'm using Centrifugo in my Node.js application and it looks pretty good. I want to implement something like personal messages between users in my application. I have a few questions about channels.

Lets imagine that I have 2 users (user1 and user2) and they want to chat. The first user send a message to my server using AJAX, then I will subscribe user1 to Centrifugo channel chat#<user1_id>,<user2_id>, save the message to database and publish message into Centrufugo channel chat#<user1_id>,<user2_id>. 

1) Is there a way to notify user2 about message in channel chat#<user1_id>,<user2_id> if he does not subscribed for this channel on client side yet? The channel chat#<user1_id>,<user2_id> limited by <user2_id> will be already created. Can I subscribe/unsubscribe user to/from channel on server-side?

2) Will channel be automatically droppped in Centrifugo if history is disabled and both users disconnected?

Thanks

**Comment by FZambia** [comment]
> Is there a way to notify user2 about message in channel chat#<user1_id>,<user2_id> if he does not subscribed for this channel on client side yet?

You can have extra private channel for each user - chat#<user1_id> - and send personal notifications to it. For example you can send notification about new chat created with user2_id - and then subscribe on channel chat#<user1_id>,<user2_id> on client side. All subscriptions on channels must be initiated by client. New chats created relatively rare - so this workflow should not affect performance a lot. After user refreshes page you send all active dialog channels to him from server.

> Will channel be automatically droppped in Centrifugo if history is disabled and both users disconnected?

Yes. Even if you enable history channel will be dropped - but history for channel will be kept for `history_lifetime`so when it will be created again (user came back) history will still be there.
