### ISSUE TITLE
Livereload SSL certificate after renew

### ISSUE THREAD

**Issue by johndoejdg** [centrifugal/centrifugo#185]
I faced with problem that SSL certificate used by centrifugo did not reload when I renew it by letsencrypt certbot. Could you please add auto reload SSL certificate option?

How I start centrifugo from systemd:
`ExecStart=/usr/bin/centrifugo --log_file="/var/log/centrifugo/centrifugo.log" --log_level="debug" --web --config=/etc/centrifugo/config.json --ssl=true --ssl_cert=/etc/letsencrypt/live/my_domain/fullchain.pem --ssl_key=/etc/letsencrypt/live/my_domain/privkey.pem`

**Comment by FZambia** [comment]
Hi, Centrifugo has [built-in support](https://fzambia.gitbooks.io/centrifugal/content/deploy/certificates.html#automatic-certificates) for Let's Encrypt certs and can update Let's Encrypt certificates automatically - maybe you can use it instead?

**Comment by johndoejdg** [comment]
Hi. I already have certificate generated by certbot for nginx. Will it option generate new certificate for centrifugo or it could found already generated for specified domain?

**Comment by FZambia** [comment]
It will generate new I suppose. If you already have certificate for Nginx then maybe you can just put Centrifugo behind Nginx and let Nginx deal with TLS stuff?

**Comment by FZambia** [comment]
@johndoejdg any feedback? Actually [looks like there is a way](https://stackoverflow.com/questions/37473201/is-there-a-way-to-update-the-tls-certificates-in-a-net-http-server-without-any-d) to handle what you ask here but it seems pretty hacky to me and I'd prefer to not adding this - especially because we already have builtin Let's Encrypt integration.

**Comment by johndoejdg** [comment]
Will builtin integration with lets encrypt upgrade SSL certificate without loose connection to prevent miss sensitive information during upgrade?

**Comment by johndoejdg** [comment]
Something wrong with builtin integration. I tried start second centrifugo process on 9000 port for testing lets encrypt but it does not work. 

Second config centrifugo
```
{
  "ssl_autocert": true,
  "ssl_autocert_host_whitelist": "MY_DOMAIN",
  "ssl_autocert_cache_dir": "/tmp/certs",
  "ssl_autocert_email": "my_email@gmail.com",
  "secret": "my_secret",
  "admin_password": "my_pass,
  "admin_secret": "my_admin_secret",
  "port": "9000",
  "join_leave": false,
  "anonymous": false,
  "publish": true,
  "watch": true,
  "presence": true,
  "history_size": 100,
  "history_lifetime": 1800,
  "recover": true,
  "history_drop_inactive": true,
  "namespaces": [
    {
      "name": "system",
      "publish": true,
      "anonymous": true,
      "watch": true,
      "presence": true,
      "join_leave": true,
      "history_size": 0,
      "history_lifetime": 0,
      "history_drop_inactive": false
    }
  ]
}
```

Logs centrifugo process:
```
[I]: 2017/06/22 12:58:01 Config path: /root/test_centrifugo/config.json
[I]: 2017/06/22 12:58:01 Centrifugo version: 1.7.3
[I]: 2017/06/22 12:58:01 Process PID: 10960
[I]: 2017/06/22 12:58:01 Engine: In memory – single node only
[I]: 2017/06/22 12:58:01 GOMAXPROCS: 2
[I]: 2017/06/22 12:58:01 Starting http server
[I]: 2017/06/22 12:58:01 SockJS url: //cdn.jsdelivr.net/sockjs/1.1/sockjs.min.js
[I]: 2017/06/22 12:58:01 Start serving raw websocket, SockJS, API endpoints on :9000
[I]: 2017/06/22 12:58:14 http: TLS handshake error from MY_IP:41876: acme: identifier authorization failed
```


When I open https://MY_DOMAIN:9000 in browser I see:
`[I]: 2017/06/22 12:58:14 http: TLS handshake error from MY_IP:41876: acme: identifier authorization failed`

**Comment by FZambia** [comment]
I think the reason here is port - see [this](https://community.letsencrypt.org/t/support-for-ports-other-than-80-and-443/3419)

**Comment by johndoejdg** [comment]
Thank you for feedback, we decide create hack for ourself. We will compare actual certificate with loaded by each service like nginx, centrofigo and so on and inform about mismatching.

**Comment by Inpassor** [comment]
> centrofigo

*ROFL*
