### ISSUE TITLE
Documentation request: Benchmarks with django-channels

### ISSUE THREAD

**Issue by johnsonc** [centrifugal/centrifugo#187]
Centrifugo has got a lot gunpowder in it! 
But it's bang for the buck seems to not be visible.
However, given the language shift and the added advantage of moving to Go. 
It would be great if we could evaluate performance and other metrics like: Ease-of-integration(centrifugo seems easier), maintainability, etc. 
It would be great if you had a benchmark run as part of the build activities, I believe it would foster further adoption.

**Comment by synw** [comment]
Do you have some ready to use django-channels code? We could start comparing it to [django-instant](https://github.com/synw/django-instant) which uses Centrifugo. About the ease of use and stuff I made a little +/- vs channels [here](https://github.com/synw/django-presence/issues/1#issuecomment-257793975)

**Comment by FZambia** [comment]
@johnsonc hello, this a bunch of non-trivial work behind this documentation request:) While I'd be very curious to see results  - I have no plans to do this myself and include into docs. This will be a biased work anyway. And it's pretty hard to do right and maintain.

I'd be happy to have benchmark suite for Centrifugo but only to let users estimate what to expect from Centrifugo itself using load they expect in application.

Channels and Centrifugo are not identical - different languages, different approaches (though both allow to solve similar problems). Centrifugo's model is language agnostic - with its pros and cons (pretty well described by @synw above - I can just add that with channels you are required to use Django/Python while Centrifugo can work with backend written in any language). I am sure you already understand differences well - choose whatever more suitable for your case.

**Comment by johnsonc** [comment]
@synw Hey! Sorry about the delay. I do have django-channels implementations lying around :) 
There are a couple over the web. Let me know what we can measure against and we can try it out?

@FZambia Thanks for the reply! Yes! Am absolutely aware that it will take some non-trivial work and here's why I believe it will be beneficial: 
1. Benchmarks and documentation drive adoption. 
2. Your knowledge of the application is what is paramount to 
  a) Squeeze the juice out of it, that other devs cannot. 
  b) If you slap in into a build process (which as the author of this beautiful piece of work), you don't need to touch it too many times :) 
   => run_benchmarks.go or something and you're sorted! 

3.) Django-channels has a lot of concepts, very little production usage or metrics. But code for code, there are thousands of more repos just testing out channels which is a pure python implementation as opposed to centrifugo, which I believe owing to the stack, will be much more performant.

**Comment by synw** [comment]
@johnsonc sorry for the delay as well. As this request is about Django I opened [an issue](https://github.com/synw/django-instant/issues/7) in the django-instant repository so that we can discuss this in the details and start something.

**Comment by FZambia** [comment]
Closing, as this is out of scope of Centrifugo - though as I said I'd be happy to have a proper benchmark suite for Centrifugo itself without intent to compare it to something else - we now have benchmarks inside Go code but those are not very meaningful for users . @synw and @johnsonc - if you are interested in comparing Centrifugo with Channels take a look at [Channels test project](https://github.com/django/channels/tree/master/testproject) which has benchmark code for Channels - maybe it's a good place to start.
