### ISSUE TITLE
[question] It would be great to have an example for a client...

### ISSUE THREAD

**Issue by mkevac** [centrifugal/centrifugo#189]
It would be great to have an example for a client...

**Comment by FZambia** [comment]
@mkevac hello! What example do you mean? We have clients for several languages, some of them with examples in repo. But I suppose you mean sth different.

**Comment by mkevac** [comment]
I mean something like example index.html that uses centrifugo.js, connects to centrifugo and just prints all messages received for a selected channel in text area.
One can use such an example as an example :-) and for debugging.

**Comment by FZambia** [comment]
Ok, personally I am using [Tornado example](https://github.com/centrifugal/examples/tree/master/tornado_application) for debugging and testing but having just `index.html` is much more simple. There is [an example](https://github.com/centrifugal/examples/blob/master/insecure_mode/README.md) close to that one but not exactly what you want - it uses insecure mode, no channel selection etc. Will try to make it soon.

**Comment by FZambia** [comment]
Started prototype in https://github.com/centrifugal/examples/tree/developer_index/developer branch - @mkevac if you are still interested please look - is this what you asked for? Do you need sth else? It's really only a prototype at moment - sth like `python3 -m http.server 3000` will help to serve.

**Comment by iamsee** [comment]
thank u,that help me

**Comment by FZambia** [comment]
Improved that page a bit and merged into master - though a lot of improvements can be done there looks like it already can be useful.

**Comment by MagnaibayarMN** [comment]
Is this still available?

**Comment by FZambia** [comment]
Closing, see https://github.com/centrifugal/examples/tree/developer_index/developer and feel free to contribute to it.

Also Quick Start chapter: https://centrifugal.github.io/centrifugo/quick_start/
A good example of centrifuge-js API possibilities: https://github.com/centrifugal/centrifuge/blob/master/_examples/chat_json/index.html
