### ISSUE TITLE
Client has an buffer limit of 256 messages before failing

### ISSUE THREAD

**Issue by klauspost** [centrifugal/centrifugo#19]
A client can currently only buffer 256 messages. When that is reached the connection is simply closed:
```Go
func (c *client) send(message string) error {
	select {
	case c.messageChan <- message:
		return nil
	default:
		c.sess.Close(3000, "error sending message")
		return ErrInternalServerError
	}
}
```

It makes sense that we never want send() to block, the limit seems a bit arbitrary.

I the usage scenario you describe it does make sense, but if we imagine a scenario where a huge bunch of messages is being sent to a single client. For instance a "message received" notification from 1000 other clients, suddenly the client gets disconnected.

Solutions could be:
* Make the number configurable. I don't like this so much, since it simply pushes the problem to the server user, but it is way the easiest.
* Add a timeout to client.send() - not good because it will block the whole server.
* Use a slice buffer to send messages to "client.sendMessages()". Very annoying to synchronize.
* Have 'client.sendMessages()' receive messages as it does now, but put messages on a slice with yet another go-routine to send them. That way it should be safe to make "messageChan" sized '1' and blocking send().

Last option could look something like this:

```Go
// sendMessages waits for messages from messageChan and sends them to client
func (c *client) sendMessages() {
	var mu sync.Mutex
	m := make([]string, 0, 10)
	go func() {
		for {
			mu.Lock()
			if len(m) == 0 {
				mu.Unlock()
				// TODO: Replace sleep with a notification
				time.Sleep(time.Second)
				continue
			}
			msg := m[0]
			m = m[1:]
			mu.Unlock()
			err := c.sess.Send(msg)
			if err != nil {
				c.sess.Close(3000, "error sending message")
			}
		}
	}()
	for {
		select {
		case message := <-c.messageChan:
			mu.Lock()
			m = append(m, string)
			mu.Unlock()
		case <-c.closeChan:
			return
		}
	}
}
```

**Comment by FZambia** [comment]
When I wrote this I thought that this can prevent blocking when slow client does not read from socket fast enough. Your last solution will help with arbitrary throughput - but what if `send` blocks and `m` will grow more and more? I don't have strong understanding if this blocking possible or not.

**Comment by klauspost** [comment]
`client.send()` blocking shouldn't be an issue, since `sendMessages` will always pull messages from `c.messageChan`.

But if `c.sess.Send(msg)` doesn't return, `m` will keep growing. What do you think would be the optimal solution?  A 10 second (configurable) timeout on `c.sess.Send(msg)`?

**Comment by FZambia** [comment]
For raw websocket connection there is `SetWriteDeadline` method available, but SockJS session has no such possibility.

**Comment by klauspost** [comment]
We could wrap message sending in a function:

```Go
func (c *client) sendTimeout(msg string) error {
  to := time.After(time.Second)
  sent := make(chan error)
  go func() {
      sent <- c.sess.Send(msg)
  }
  select {
     case err := <- sent
        return err
     case <- to:
        return ErrSendTimeout
  }
  panic("unreachable")
  return nil
}
```
The timeout length could be added to the client.

The thing that I don't really like about this solution is that we are spawning 2 goroutines to send a single message. Not a huge deal - goroutines are cheap, and it does seem like it is required.

I will make a PR proposal. It is a bit easier to discuss.

**Comment by FZambia** [comment]
Maybe the best way right now - make buffer larger and make it configurable and see how it goes? And then after writing some benchmark tests it will be more clear what's the best way?

**Comment by klauspost** [comment]
I made a proposal in #23. After a few rewrites I think it is fairly unobtrusive, light on resources and rather easy to follow (except perhaps the ring queue implementation).

**Comment by FZambia** [comment]
Looks very interesting! Not sure [this](https://github.com/klauspost/centrifugo/blob/0b4535e3e5d8fe65d99b9ed0f81f997585448ae4/libcentrifugo/client.go#L180) line necessary as `clean` method must be called anyway. There is [old benchmark for Centrifuge](https://github.com/centrifugal/centrifuge/tree/master/development/benchmarks) - will try to run it after work to see memory and performance impact of these changes.
