### ISSUE TITLE
1.7.4 Publishing to private channels via HTTP API requires publish=true?

### ISSUE THREAD

**Issue by a1martin** [centrifugal/centrifugo#190]
Hi,

I'm able to publish via HTTP API to private channels **only** when namespace is used and publish=true. If I remove the namespaces (channel name just "$test")  then the message is not published to browser. Although the HTTP response gives no errors. Is that intended or am I doing something wrong?
* Insecure API is turned on
* browser snippet is like that:
`centrifuge.subscribe("test:$test", function(message) {
        console.log(message);		
    });`
* HTTP POST body:
`{
    "method": "publish",
    "params": {
        "channel": "test:$test",
        "data": {
            "input": "hello"
        }
    }
}`
* config.json: 
`{
    "secret": "key",
    "admin_password": "admin_psw",
    "admin_secret": "key",
    "insecure_api":true,
    "api_port":7777,
    "namespaces": [
        {
          "name": "test",
          "publish": true         
        }        
    ]
}
`

Any ideas?

**Comment by FZambia** [comment]
@a1martin hello! On client side you should subscribe on `$test` - namespaces allows to use custom channel options but they are part of channel name.

**Comment by FZambia** [comment]
I mean if you subscribed on `$test` on client side - you should publish to `$test`, if you are using `test` namespace then you should subscribe on client side on `$test:channel_name` and publish into `$test:channel_name`. Also note that `$` sign must be in the beginning of channel name to make it private (not in the middle like in `test:$test`)

**Comment by a1martin** [comment]
Are the namespaces required then? 
If I have the conf like that:
`{ "secret": "key", 
"admin_password": "admin_psw", 
"admin_secret": "key", 
"insecure_api":true, 
"api_port":7777 }`

and subscribe to channel $test: `centrifuge.subscribe("$test", function(message) { console.log(message); });`

and send to HTTP API: 
`
{
    "method": "publish",
    "params": {
        "channel": "$test",
        "data": {
            "input": "hello"
        }
    }
}`

then the centrifugo console shows ` POST /api/ from [::1]:50295 completed in 0s` but nothing shows up in browser.

**Comment by FZambia** [comment]
This should work if client correctly subscribed on channel. Could you show websocket frames from browser developer tools? Maybe you have not implemented private channel auth endpoint in your backend and client not actually subscribed on that channel?

**Comment by a1martin** [comment]
Case solved! The problem was malformed response. Signature was on JSON field "token" but had to be "sign". Thanks for help!

**Comment by FZambia** [comment]
Cool, welcome!
