### ISSUE TITLE
How to expire a client token

### ISSUE THREAD

**Issue by CharAct3** [centrifugal/centrifugo#191]
Hi, I generated a token for user(id:100) : `c585c9fcbfad84f177aac654eb46a8fbde8900b8383d3e7fd6ad95b4527bb763`,
 and it seems this token will never expire.

Is there any way to expire existed tokens for user  ;)

**Comment by FZambia** [comment]
Hi, here is a chapter about [connection check mechanism](https://fzambia.gitbooks.io/centrifugal/content/server/connection_check.html) available in Centrifugo. You can also protect channel access using private channels.
