### ISSUE TITLE
Create new releases entirely in Travis CI

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifugo#197]
Currently when releasing Centrifugo I create binary releases manually at my computer and then upload them on Github release page.

To create binary releases at moment:

```
make release
```

– is used.

It would be great if in Travis CI we not only upload deb/rpm packages to packagecloud.io but also create binary Github releases. https://docs.travis-ci.com/user/deployment/releases/

**Comment by FZambia** [comment]
Looks like this can be drastically simplified using https://github.com/goreleaser/goreleaser tool.

**Comment by furdarius** [comment]
I'll take it.

**Comment by FZambia** [comment]
Closing as this is done for Centrifugo v2 in c2 branch. Thanks @furdarius
