### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by amaleev** [centrifugal/centrifugo#199]
Hello,
I have a problem in memory leak in centrifugo on high load system https://www.dropbox.com/s/f1jb7hfavf9bx29/1.jpg?dl=0 .
Our system serve obove 30k. online websocket and has generate outbound traffic obove 3 Gbps https://www.dropbox.com/s/4rqsq5teucmq8tk/2.png?dl=0 .
I use centrifugo in docker conteiner. As you can see in screenshot https://www.dropbox.com/s/q45kcx6jrff96l6/3.png?dl=0 centrifugo constantly fill up memory and does not release it. As a result Docker container falls and restarts due to memory lack.

My centrifugo config:
root@centrifugo:/# cat /etc/centrifugo.json
{
  "secret": "XXXXXX",
  "admin_password": "XXXXXX",
  "admin_secret": "XXXXXX",
  "watch": true,
  "publish": true,
  "client_channel_limit": 1024
}

I run the centrifugo looks like this:
docker run -d -p 443:443 -p 80:80 -p 8000:8000 --name centrifugo -h centrifugo centrifugo

**Comment by FZambia** [comment]
Hello!

There is an article in [wiki](https://github.com/centrifugal/centrifugo/wiki/Investigating-performance-issues) that describes how to investigate problems like this. Please create 2 heap profiles on Centrifugo start and when memory usage is high.

**Comment by FZambia** [comment]
One more note - I see `watch: true` in your configuration, this is a bit strange to see on top level in high load system. I don't want to say this is a bad practice - just mentioning that maybe you better to turn this option off as it's pretty useless in production when traffic is high.

**Comment by FZambia** [comment]
@amaleev any news?

**Comment by FZambia** [comment]
Please reopen with more info if still actual.
