### ISSUE TITLE
Use sync.RWMutex in hubs.go

### ISSUE THREAD

**Issue by klauspost** [centrifugal/centrifugo#2]
Just looking through the code I wondered why you don't use sync.RWMutex in your `clientConnectionHub`? Right now you serialize all incoming data without any reason I can see.

It would appear that these are read-only operations on `clientConnectionHub`: 
* `getClientsCount` 
* `getUniqueClientsCount`, 
* `getUserConnections` (this should return a copy either way, it is unsafe/racy as it is now AFAICT)

In `clientSubscriptionHub`, read only are:
* `getChannelsCount`
* `getChannels`
* `broadcast`

In `adminConnectionHub`:
* `broadcast`

If these were using a RWMutex, and using RLock/RUnlock, they would be able to work concurrently. Right now only one broadcast can run at the time, without any real reason.

**Comment by FZambia** [comment]
Thanks for such a great advice. Moved read-only things to `RWMutex ` in `application.go` but missed `hubs.go`... I'll go through all methods you pointed and make changes.

**Comment by FZambia** [comment]
Fixed in 3e4ecaa78f6f3e29f356c4ab429047014b0d209d and in d9638c25dc9899fb8341fe4381ef2b7924eb4e78
