### ISSUE TITLE
is it possible to get history from array of channels?

### ISSUE THREAD

**Issue by vadimkozak** [centrifugal/centrifugo#200]
i am working with the geo based service, users have a mobile app and sends their location via centrifugo, and i need to get position of each user on request, i can use channels then history but its will be too long

**Comment by FZambia** [comment]
Hello! Sorry - I don't understand your question. Could you explain it in more obvious way?

**Comment by vadimkozak** [comment]
Geo based system, so I have 100 users with mobile app which send their locations every 2 seconds to centrifugo. Each user have an their own channel called user_{id}. In Admin panel I need to get all users in some X radius on api call, on my opinion would be best way to get all latest messages of each channel (for example from user_1 to user_100), and then calculate which users in radius (on my side).

**Comment by FZambia** [comment]
Got it! You are misusing Centrifugo a bit - you should go with Geo specific database, which allow to make queries like this and optimized for this sort of task. Use Centrifugo as server->client transport. When client sends new positions send them not via Centrifugo but via HTTP call for example, save coordinates to Geo specific database and then publish to Centrifugo API to show positions in real-time. The client side `publish` feature of Centrifugo is mostly for demos, presentations, or maybe projects that do not require business logic - this is stated in documentation. Consider Centrifugo only as transport for real-time messages going from server to client.

**Comment by vadimkozak** [comment]
thanks for response, centrifugo Is a great service, I want to try it as a transport from client to server bcz http will slow down my server)
