### ISSUE TITLE
Getting timed out message from socket on subscribe or presence

### ISSUE THREAD

**Issue by foobargeez** [centrifugal/centrifugo#202]
I am intermittently noticing `timed out` message when I do subscribe or presence and when in this state, the client never reconnects.  I noticed this in go-mobile client and the only way to get out of this state is to terminate the app and relaunch it, so the socket connection gets established successfully.

The issue, unfortunately, doesn't happen consistently, so I don't have a reproducible case.  I will describe the steps once I have a way to reproduce.

Thanks in advance!

**Comment by FZambia** [comment]
@foobargeez please reopen in centrifuge-mobile repo.
