### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by vladshut** [centrifugal/centrifugo#207]
When centrifugo is running for 12 or more hours, memory leak appears.
There are a lot of (millions) gouroutines started at libcentrifugo/conns/clientconn/conn.go:252
The reason of hangs of goroutines is waiting for resource at: libcentrifugo/conns/clientconn/conn.go:261
With debugging we found that resource was locked at the last time at: libcentrifugo/conns/clientconn/conn.go:173

How to fix this issue?

**Comment by FZambia** [comment]
@vladshut hello, thanks for report! Could you provide goroutine profile?

**Comment by FZambia** [comment]
@vladshut actually goroutine profile not needed - the fix is very simple. But could you describe the way you found deadlock? Have you used blocking profile? Or maybe some other tools/instruments?

**Comment by vladshut** [comment]
Sory, here it is: [goroutine.txt](https://github.com/centrifugal/centrifugo/files/1805728/goroutine.txt)
Unfortunately, that fix does not help.

**Comment by FZambia** [comment]
@vladshut hmm, unfortunate.. could you write me on [Gitter](https://gitter.im/centrifugal/centrifugo) to personal messages?

**Comment by vladshut** [comment]
@FZambia I wrote you message on Gitter.
