### ISSUE TITLE
How to Distributed deployment

### ISSUE THREAD

**Issue by tianxia007** [centrifugal/centrifugo#212]

**Comment by FZambia** [comment]
It's possible to scale with Redis engine. You can run many Centrifugo nodes each connecting to Redis. Also you can run many Redis instances and configure Redis sharding - Centrifugo will shard everything by channel. Sentinel can be used to add HA to each Redis instance. All of this written in docs - do you have any specific question?

**Comment by tianxia007** [comment]
thanks
