### ISSUE TITLE
Recover missed messages after network disconnect

### ISSUE THREAD

**Issue by tianxia007** [centrifugal/centrifugo#213]
Where to store missed messages

**Comment by FZambia** [comment]
Hello @tianxia007! Sorry - I don't understand your question. Could you ask with more details?

**Comment by tianxia007** [comment]
after network disconnect,the messages stored to where..

**Comment by FZambia** [comment]
Messages are being kept in Centrifugo node memory in case of using Memory engine and in Redis (in Redis process memory, there is no much sense to enable disk persistence in Redis for Centrifugo data) in case of using Redis engine.

**Comment by tianxia007** [comment]
thanks
