### ISSUE TITLE
hi,how to configure the file config.json to use redis

### ISSUE THREAD

**Issue by tianxia007** [centrifugal/centrifugo#215]
i found this just:
And you will see the following options among the others:

    --redis_api=false: enable Redis API listener (Redis engine)
    --redis_api_num_shards=0: Number of shards for redis API queue (Redis engine)
    --redis_db="0": redis database (Redis engine)
    --redis_host="127.0.0.1": redis host (Redis engine)
    --redis_password="": redis auth password (Redis engine)
    --redis_pool=256: Redis pool size (Redis engine)
    --redis_port="6379": redis port (Redis engine)
    --redis_url="": redis connection URL (Redis engine)

can show me some info how to write config.json thanks

**Comment by tianxia007** [comment]
wrong:2018/04/13 18:06:30 Error parsing configuration: While parsing config: invalid character '"' after object key:value pair
 
 "watch": true,
  "publish": true,
  "secret": "",
  "web": true,
  "admin_password": "password",
  "admin_secret": "secret"
  "namespaces": [
    {
      "name": "public",
      "anonymous": true,
      "publish": true,
      "watch": true,
      "presence": true,
      "join_leave": true,
      "history_size": 10,
      "history_lifetime": 30,
      "recover": true,
		"engine": "redis",
		"redis_host"= "ip1",
		"redis_port"= "7000",
		"redis_db"= "3",
		"redis_password"= "pass1"
    }

**Comment by FZambia** [comment]
Try this:

```json
{
  "secret": "secret",
  "web": true,
  "admin_password": "password",
  "admin_secret": "secret",
  "engine": "redis",
  "redis_host"= "ip.top",
  "redis_port"= "7000",
  "redis_db"= "3",
  "redis_password"= "pass1",
  "namespaces": [
    {
      "name": "public",
      "anonymous": true,
      "publish": true,
      "watch": true,
      "presence": true,
      "join_leave": true,
      "history_size": 10,
      "history_lifetime": 30,
      "recover": true
    }  
  ]
}
```

So you put options in the wrong level and also forgot one comma

**Comment by tianxia007** [comment]
thanks!
