### ISSUE TITLE
Documentation translation to Chinese language

### ISSUE THREAD

**Issue by tianxia007** [centrifugal/centrifugo#217]

**Comment by FZambia** [comment]
Unfortunately I can not do this myself, the best I can do is leave this issue open and mark it with `help_wanted` label.

**Comment by xurwxj** [comment]
@FZambia i can do this
https://github.com/xurwxj/centrifugal_cn_doc

**Comment by xurwxj** [comment]
finish start and configuration translation, change gitbook to v3
now u can run gitbook serve directly in your local env after pull the doc repo of mine

**Comment by xurwxj** [comment]
@FZambia u can merge into your docs repo when i finish translation.

**Comment by FZambia** [comment]
@xurwxj added link to your translation in commit https://github.com/centrifugal/documentation/commit/64b3d5ef8ddf1055a8feeb273beb326a4cfed280

I did not understand what you mean under `integrate Centrifugo's session into redis in v2` – could you provide more details about your idea?

Closing this issue as link to translation is now in docs
