### ISSUE TITLE
SSL with centrifuge-android

### ISSUE THREAD

**Issue by kaizer666** [centrifugal/centrifugo#218]
Hello!
We use centrifugo as webSocket-server with SSL and centrifuge-android in our android-app.
On disconnect we have an error
`java.lang.NullPointerException: ssl == null`

Centrifugo config is here https://pastebin.com/3RF2r6BJ
Nginx config is here https://pastebin.com/ZQffYxfd

Android-app was connected to address `wss://ws. mycompany.com` and `wss://websocket.mycompany.com:8000`, but error is always here.

What are we doing wrong?

========

Здравствуйте!
Мы используем centrifugo как webSocket-сервер с SSL и centrifuge-android в нашем андроид-приложении.
При отключении (onDisconnect) мы получаем ошибку
`java.lang.NullPointerException: ssl == null`

Конфигурация Centrifugo находится здесь https://pastebin.com/3RF2r6BJ
Конфигурация Nginx находится здесь https://pastebin.com/ZQffYxfd

Android-приложение подключается к адресу `wss://ws.mycompany.com` или `wss://websocket.mycompany.com:8000`, но ошибка всё равно есть.

Что мы делаем не так?

**Comment by kaizer666** [comment]
We have asked in https://github.com/centrifugal/centrifuge-android/issues/14, but we have no answer

**Comment by kaizer666** [comment]
Трейс при коннекте к домену (через Nginx) - https://pastebin.com/HyuGkTPu
Трейс при коннекте к Ceentrifugo (напрямую) - https://pastebin.com/yC3Cd0Xx

**Comment by FZambia** [comment]
As stated in centrifuge-android repo description we are looking for maintainer for it, this issue relates to Android client and looks like a bug in it. I can't say when maintainer will be found but as soon as it happen hopefully issues will be fixed.

**Comment by kaizer666** [comment]
@FZambia And many people need to fix https://github.com/centrifugal/centrifugo/issues/147

A timestamp is not sent from centrifugo.
