### ISSUE TITLE
No package for Ubuntu 18.04

### ISSUE THREAD

**Issue by bubooon** [centrifugal/centrifugo#226]
Can't find package for Ubuntu 18.04 LTS in [https://packagecloud.io/FZambia/centrifugo](https://packagecloud.io/FZambia/centrifugo)

**Comment by FZambia** [comment]
Hello! Here is [a list of packages](https://fzambia.gitbooks.io/centrifugal/content/deploy/packages.html) we build at moment. If there are no differences in how package should be built then we only need to add a new line [here](https://github.com/centrifugal/centrifugo/blob/master/Makefile#L37)

**Comment by FZambia** [comment]
@bubooon see https://github.com/centrifugal/centrifugo/commit/c2d78ec045793b2bb5b3355fe081ce47dabc2408 - it will be built with next release, unfortunately I have no possibility at moment to test this on Ubuntu 18.04.

**Comment by bubooon** [comment]
@FZambia thx, so much!

**Comment by FZambia** [comment]
Released in [v1.8.0](https://github.com/centrifugal/centrifugo/releases/tag/v1.8.0)
