### ISSUE TITLE
Redis history size is incorrect

### ISSUE THREAD

**Issue by masterada** [centrifugal/centrifugo#227]
With redis engine history is actually longer by 1 than history setting. The reason for this is the following line in redis engine:
```
redis.call("ltrim", KEYS[1], 0, ARGV[3])
```

Redis ltrim 2nd parameter is inclusive:

> For example: LTRIM foobar 0 2 will modify the list stored at foobar so that only the first three elements of the list will remain.

Correct would be:
```
redis.call("ltrim", KEYS[1], 0, ARGV[3] - 1)
```

It's in v2, but probably wrong in v1 as well. Fix tested in v2.

**Comment by FZambia** [comment]
Thanks! Did you experienced wrong result with any API call? Because looks like we [already do this right](https://github.com/centrifugal/centrifugo/blob/master/libcentrifugo/engine/engineredis/engine.go#L1637) at least in v1

**Comment by masterada** [comment]
Only checked it in v2. Set history size to 1, published 3 events on the channel from admin interfance, then checked the history and there were two items in it.

**Comment by FZambia** [comment]
You are right, thanks a lot!
