### ISSUE TITLE
Save the last message id apart from history

### ISSUE THREAD

**Issue by nmorel** [centrifugal/centrifugo#230]
With the current system, the `recovered` flag isn't accurate.  
If the user subscribe while there are no messages in history, the last message id received is empty.  
When resubscribing, the `recovered` flag is false even if no messages were sent or they were all inside history.  
Same if the user has a last message id and the associated message expires. Even if no messages were sent, the `recovered` flag will be false.  

In my app, a user can't miss messages. They are all importants and currently, I'm reloading the app when the user resubscribes to the channel.  
I wanted to use the recover system to avoid the reload for short disconnection but the innaccuracy of recovered flag makes it almost useless.

**Comment by FZambia** [comment]
Recovery algorithm described [here](https://centrifugal.github.io/centrifugo/server/recover/).

**Comment by nmorel** [comment]
Thanks for your work!  
I will try v2 asap

**Comment by devig** [comment]
> Recovery algorithm described [here](https://centrifugal.github.io/centrifugo/server/recover/).

404 - Not found
