### ISSUE TITLE
Any plan to support dart-lang and used in Flutter app?

### ISSUE THREAD

**Issue by jonahfang** [centrifugal/centrifugo#231]

**Comment by FZambia** [comment]
Hello! There are no technical barriers – only skill and time. Unfortunately I personally don't know Dart and Flutter ecosystem. But I know that @mogol which is an author of centrifuge-ios currently develops a lot of things in Flutter and likes it.

It's hard to give a forecast on when such client will be implemented. Writing a client is quite a big work. Actually writing a client with basic PUB/SUB functionality is very simple. The complex part is making it compatible with all protocol features.

From my side I can help to everyone who wants to implement client - answering questions and extending protocol documentation, adding missing parts to it.

**Comment by jonahfang** [comment]
I will try to read source code of Centrifugo andriod library and convert it to dart. But I am new to the dart-lang, and may fail in this process.

**Comment by mogol** [comment]
I have already started implantation. Let me build skeleton, then it will be worth to push.

**Comment by mogol** [comment]
I have added very basic api.  It's definitely not ready for production. 
But you could try and provide feedback if any. 
https://github.com/centrifugal/centrifuge-dart

**Comment by jonahfang** [comment]
@mogol Thanks, I will test it soon.
