### ISSUE TITLE
make possible to use domain names as namespace (add .(dot)  as allowed symbol) 

### ISSUE THREAD

**Issue by khvalov** [centrifugal/centrifugo#235]
https://github.com/centrifugal/centrifugo/blob/master/vendor/github.com/centrifugal/centrifuge/config.go line 94. 
Just add . (dot) as allowed in regexp 

Thanks

**Comment by FZambia** [comment]
Yep, currently in business trip, will do very soon

**Comment by FZambia** [comment]
Fix in master, will be in next release
