### ISSUE TITLE
client cannot connect to centrifugo server

### ISSUE THREAD

**Issue by rampredd** [centrifugal/centrifugo#236]
Am doing like this.

server config: in /etc/centrifugo/
{
  "name": "centrifuge",
  "secret": "secret",
  "insecure": true,
  "anonymous": false,
  "namespaces": [
    {
      "name": "chat",
      "publish": false,
      "subscribe_to_publish":false,
      "anonymous": false,
      "join_leave": false,
      "presence": false,
      "history_size": 0,
      "history_lifetime": 0,
      "history_recover": false,
      "history_drop_inactive": false
    }
  ]
}

And the client is written in golang
	url := "ws://localhost:8000/connection/websocket?format=protobuf"
	handler := &eventHandler{}

	events := centrifuge.NewEventHub()
	events.OnConnect(handler)
	events.OnError(handler)
	events.OnDisconnect(handler)

	c := centrifuge.New(url, events, centrifuge.DefaultConfig())

	subEvents := centrifuge.NewSubscriptionEventHub()
	subEvents.OnPublish(handler)
	subEvents.OnJoin(handler)
	subEvents.OnLeave(handler)
	subEvents.OnSubscribeSuccess(handler)
	subEvents.OnSubscribeError(handler)
	subEvents.OnUnsubscribe(handler)

	sub, err := c.Subscribe("chat:index", subEvents)
	if err != nil {
		log.Println("error on subscribe: ", err)
		return
	} else {
		log.Println("subscrie SUCCESS")
	}

	//	timeStamp := strconv.FormatInt(time.Now().Unix(), 10)
	//		token := gocent.GenerateClientToken("secret", "", "", "")
	//	c.SetToken("secret")
	//		c.SetConnectData()

	err = c.Connect()
	if err != nil {
		log.Fatalln(err)
		log.Println("error on connect: ", err)
		return
	} else {
		log.Println("Connected to server")
	}

Then I run the server with the command:
centrifugo -c /etc/centrifugo/config.json --debug
Then I run the client

The result is on the server side is:
[I]: 2018/09/28 17:31:12 Config path: /etc/centrifugo/config.json
[I]: 2018/09/28 17:31:12 Version: 1.8.0
[I]: 2018/09/28 17:31:12 PID: 18702
[I]: 2018/09/28 17:31:12 Engine: In memory – single node only
[I]: 2018/09/28 17:31:12 GOMAXPROCS: 2
[W]: 2018/09/28 17:31:12 Running in INSECURE client mode
[W]: 2018/09/28 17:31:12 Running in DEBUG mode
[I]: 2018/09/28 17:31:12 SockJS url: //cdn.jsdelivr.net/sockjs/1.1/sockjs.min.js
[I]: 2018/09/28 17:31:12 Start serving raw websocket, SockJS, API, debug endpoints on :8000

[E]: 2018/09/28 17:31:22 got request from client without commands

Please help me

**Comment by FZambia** [comment]
@rampredd hi, which client version are you using - latest version from master branch? Latest code supposed to work with Centrifugo 2.0.0 while you are connecting to 1.8.0

**Comment by rampredd** [comment]
Thanks for quick response.
Now I got it working with latest centrifugo linux tar.gz got from downloads page.


Now I can run jwt example from centeifuge_go examples.

This example has connect and subscribe to channel. That is private.go file.

I tried add publish to that subscription in private.go file.

But server is not permitted.

Please explain.

**Comment by FZambia** [comment]
See https://centrifugal.github.io/centrifugo/server/configuration/#channel-options about channel options - you need Publish set to true when publishing from client side

**Comment by rampredd** [comment]
Am using centrifugo v2.0.0 and centrifuge,centrifuge-go and gocent libraries are checkedout from git.
I did (go get centrifug****) to get these libraries.

With this version if I connect to server http client api like this
cFugoApiCli = gocent.NewClient("http://localhost:8000", "secret", 5*time.Second)
But it gives error:
CFUGO PUBLISH ERROR:  :  wrong status code: 404 Not Found

centrifugo is run with following config
{
  "secret": "secret",
  "namespaces": [
    {
      "name": "chat"
    }
  ],
  "pubish": true,
  "anonymous": true,
  "insecure":true
}

**Comment by FZambia** [comment]
Gocent library have not been updated to work with Centrifugo v2 - see https://centrifugal.github.io/centrifugo/libraries/api/ about state of API clients. At moment you can manually integrate with HTTP API using this doc: https://centrifugal.github.io/centrifugo/server/api/. This is pretty simple - just send POST request with Authorization header and JSON command in body.

**Comment by rampredd** [comment]
Thank you.
Please tell me any other version that can work gocent and also client side connection.
I wanted to bring server API and client connect to same centrifugo server.

Please let me know the version that works from both sides.

**Comment by FZambia** [comment]
If you want to use Centrifugo v1 then here you can find a list of compatible libraries: https://centrifugal.github.io/centrifugo/misc/migrate/#centrifugo-v1-repos

If you want to use Centrifugo v2 then you should communicate with Centrifugo HTTP API manually implementing request to server. Gocent will be updated to work with Centrifugo v2 eventually. Maybe in a couple of weeks.
