### ISSUE TITLE
Any update on gocent?

### ISSUE THREAD

**Issue by aannuujj** [centrifugal/centrifugo#237]
Hello @FZambia 

Any update on the gocent upgrade to Centrifugo V2?
In #236 you mentioned that it was planned for within the next couple of weeks. 

Just wanted to know before deciding which way to go in terms of versions or writing my own
Thanks

**Comment by FZambia** [comment]
Hello, yes - it's still in my roadmap, I was tired and vacationing so failed those deadlines. Let's create new one - will try to come up with updated library until the end of this week. Will appreciate if you help me with reviewing updated code.

**Comment by aannuujj** [comment]
@FZambia Wow, end of this week will be perfect. I would be more than happy to report any issues and review the updated code as I work through using the client.

If by any chance you can make the changes by Friday or Saturday morning, I can set aside this weekend on to work on them and report back with any review

**Comment by FZambia** [comment]
@aannuujj just opened pull request with working code: https://github.com/centrifugal/gocent/pull/6 - please look and comment inside pr.

**Comment by aannuujj** [comment]
@FZambia Top effort. Thanks for the quick response on this. Will set aside time work on this, this weekend and get back to you.

**Comment by FZambia** [comment]
`gocent` lib for Centrifugo v2 released (gocent v2.0.0)
