### ISSUE TITLE
Sometimes adjacent's Client can't send messages to Centrifugo

### ISSUE THREAD

**Issue by applecat** [centrifugal/centrifugo#244]
We use Centrifugo 1.8.0, running it within a docker container:
```sudo docker run --name centrifugo_ru -d --restart always --ulimit nofile=65536:65536 -v /web/site.com:/centrifugo -p 8020:8020 centrifugo/centrifugo centrifugo -c centrifugo_config.yaml --log_level=info -p 8020 --web --admin```

And access to Centrifugo through Django + adjacent:
```
from adjacent import Client
from cent import RequestException

client = Client()

def centrifugo_publish(channel, data):
    client.publish(channel, data)

def centrifugo_send():
    try:
        client.send()
    except RequestException as e:
        mail_admins('Centrifugo RequestException!', f'Error: {str(e)}')
```

And from time to time this two errors are received:
```Error: wrong status code: 503```

```Error: HTTPSConnectionPool(host='site.com', port=443): Max retries exceeded with url: /centrifugo/api/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:833)'),))```

I can't understand why this is happening. Centrifugo's debug mode also doesn't help to understand what causes an error.

Here is current centrufugo status:

<img width="878" alt="2018-10-29 18 47 04" src="https://user-images.githubusercontent.com/390483/47661972-1f8c9e80-dbab-11e8-8ec0-a6a60571e461.png">

**Comment by FZambia** [comment]
The only place where Centrifugo v1.8.0 returns 503 is [this one](https://github.com/centrifugal/centrifugo/blob/v1.8.0/libcentrifugo/server/handlers.go#L387) - when node shutdown initiated it stops accepting API requests. This allows load balancers to proxy requests to another Centrifugo node if any. Not sure how this relates to your case though as there is some sort of SSL error involved.

I am not sure this can be fixed from Centrifugo side as this looks like client issue. Have you tried solutions described [here](https://stackoverflow.com/questions/14102416/python-requests-requests-exceptions-sslerror-errno-8-ssl-c504-eof-occurred)?

**Comment by applecat** [comment]
@FZambia, thank you for help! But for now the problem is solved itself in some way. I'll back to this if it appears again.

**Comment by FZambia** [comment]
OK, I suppose it somehow relates to client machine environment, closing for now, if happens again - please try advices from Stackoverflow post
