### ISSUE TITLE
Can I use namespace for private channel?

### ISSUE THREAD

**Issue by thanhps42** [centrifugal/centrifugo#250]
Can I use namespace for private channel?

Thanks.

**Comment by FZambia** [comment]
Hello, yes, you can. For example you have `public` namespace then you can use channel name `$public:news` to use namespace options for that channel. [Example](https://github.com/centrifugal/examples/blob/master/tornado_application/code.html#L10) which works [with config like this](https://github.com/centrifugal/centrifugo/blob/master/config.json#L7)

**Comment by thanhps42** [comment]
Thanks
