### ISSUE TITLE
health probe

### ISSUE THREAD

**Issue by cpanato** [centrifugal/centrifugo#252]
Hello
this is a nice product, i like it thanks for that

One question does the api have any health endpoint to check? I would like to setup k8s Liveness and Readiness Probes but did not found in the documentation

thanks!

**Comment by FZambia** [comment]
Hello, thanks.

At moment Centrifugo has no health probe endpoint, there is also similar request in Centrifuge library which is the core of Centrifugo - https://github.com/centrifugal/centrifuge/issues/27 - with a bit more details.

**Comment by sj26** [comment]
Imho, a fixed "200 OK" response would be sufficient. It should exercise that the application is available to service requests. Generally health checks should not check upstream services (i.e. redis).

**Comment by FZambia** [comment]
ok, will include health endpoint into next release then if it already has benefits in this state. At work we have services that check external storages in liveness probe so I suppose it has some reasoning in certain scenarios - broken reconnect, possible deadlock in drivers, connectivity lost forever for the whole underlying machine.

**Comment by cpanato** [comment]
thanks, sounds great. please let me know if need help or where can i help :)

**Comment by sj26** [comment]
That's true, Kubernetes has two different probes which differentiate "this service is alive" versus "this service is healthy and all upstreams are okay"

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

**Comment by FZambia** [comment]
Released with [v2.1.0](https://github.com/centrifugal/centrifugo/releases/tag/v2.1.0), docs [here](https://centrifugal.github.io/centrifugo/server/configuration/#healthcheck-endpoint)

**Comment by sj26** [comment]
Thanks!

**Comment by cpanato** [comment]
thanks, I've updated the helm charts to use that
