### ISSUE TITLE
Ephemeral tls key/cert

### ISSUE THREAD

**Issue by sj26** [centrifugal/centrifugo#255]
I'd like to run centrifugo with tls turned on, but I'm only interested in transport encryption, not verification, so I don't want to supply a key and cert, I'd like it to use a generated self-signed certificate.

(I'd be happy to contribute a PR if you'd be interested in this feature.)

**Comment by FZambia** [comment]
Hello!

Many questions here:)

Do you mean generating certificate in runtime on process start? I.e. the only reason is not to provide `key` and `cert` files on disk? Is using separate files is impossible in your environment?

Also you will need to turn off verification on client side in this case right? So I suppose you won't use this in browser?

**Comment by sj26** [comment]
> Do you mean generating certificate in runtime on process start? I.e. the only reason is not to provide key and cert files on disk?

Yes!

> Is using separate files is impossible in your environment?

No, but I would have to generate some in an entrypoint, or create a layer that does so, or something. For the moment I'm creating my own centrifugo docker image based on ubuntu and installing ssl-cert which generates a "snakeoil" self-signed cert at /etc/ssl/private/ssl-cert-snakeoil.key and /etc/ssl/certs/ssl-cert-snakeoil.pem. But these are created at docker build time and shared amongst all instances.

Instead, I'd ideally like `--tls` without `--tls_key`/`--tls_cert` to generate a self-signed keypair to use for HTTPS.

> Also you will need to turn off verification on client side in this case right? So I suppose you won't use this in browser?

Absolutely. But in our case the browsers are connected to a load balancer with verified certs, then the load balancer connects to centrifugo running in containers. I'd like that backhaul connection to be https, not plain text. But verification isn't important, it's just about securing the transport layer.

**Comment by FZambia** [comment]
@sj26 do you know any Go lang software that already does this? To be fair I am not 100% sure we have to support things like this as certificate generation has lot's of options and is a better task for separate specialized tool.

**Comment by sj26** [comment]
No, looking around I can't find a good example of this. Perhaps everybody uses sidecar containers to translate https, or fancy service meshes, or finds ways to inject certificate files into pre-built containers. 🤷‍♂️

**Comment by FZambia** [comment]
@sj26 hello, I suppose we should close this for now. I can't decide on adding this feature at moment as it involves new responsibility for Centrifugo which is already fat enough. Just want to keep its code base as simple as possible while sth can be done outside. Maybe if several more people will need this we can reconsider this.
