### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by fre5h** [centrifugal/centrifugo#256]
Hello. Found some typo in the documentation.

Find this part of the text `unique namespace name (name must must consist of letters ...` in the file `/docs/content/server/configuration.md`
There are two `must` one after one. One is redundant :)

**Comment by FZambia** [comment]
Hello, thank you, fixed with https://github.com/centrifugal/centrifugo/commit/73667014da0aeb1f32a0ba632cfc10355a347963
