### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by Gadgetroch** [centrifugal/centrifugo#260]
Good morning,

When i launch centrifugo and go to 8000 port, i get "400 not found". You know why ?

Thank's

**Comment by FZambia** [comment]
Hello, you need to enable admin web interface in config. See how to do this in [this documentation chapter](https://centrifugal.github.io/centrifugo/server/admin/).

**Comment by Gadgetroch** [comment]
Add this permit to have web interface for write in chat ?

**Comment by FZambia** [comment]
Sorry, I don't understand you question, could you ask with more details?

**Comment by Gadgetroch** [comment]
Add this allows me to access the web interface to write in the chat ?
