### ISSUE TITLE
Add 400 status code for bad requests

### ISSUE THREAD

**Issue by atygaev** [centrifugal/centrifugo#266]
Dear @FZambia!
Thank you for your project! Good job!

I've faced with one weird moment when I was trying to create own server http API client.

Centrifugo returns HTTP 200 on bad request.

I am not a Go developer and my [PR](https://github.com/centrifugal/centrifugo/pull/265) is just an idea how to fix it quickly.

Consider my PR please. I am ready to talk about the change or its consequences.
Please feel free to let me know what do you think about my PR.

I've copied the PR description to here.

---

Server sends HTTP 200 status code on bad requests instead of HTTP 400.
The change sets HTTP 400 status code for bad requests.

### Request
```
curl -v \
  --header 'Authorization: apikey apikey' \
  --header 'Content-Type: application/json' \
  -d '{
        "method": "publish",
        "params": {
          "channel": "unknown:channel",
          "data": {"1": "2"}
        } 
    }' http://localhost:8000/api
```
### :heavy_check_mark: Response (after the change)
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /api HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.61.0
> Accept: */*
> Authorization: apikey apikey
> Content-Type: application/json
> Content-Length: 155
> 
* upload completely sent off: 155 out of 155 bytes
< HTTP/1.1 400 Bad Request
< Date: Wed, 30 Jan 2019 05:42:43 GMT
< Content-Length: 55
< Content-Type: text/plain; charset=utf-8
< 
{"error":{"code":102,"message":"namespace not found"}}
* Connection #0 to host localhost left intact
```

### :exclamation: Response (before the change)
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /api HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.61.0
> Accept: */*
> Authorization: apikey apikey
> Content-Type: application/json
> Content-Length: 155
> 
* upload completely sent off: 155 out of 155 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Wed, 30 Jan 2019 05:45:15 GMT
< Content-Length: 55
< 
{"error":{"code":102,"message":"namespace not found"}}
* Connection #0 to host localhost left intact
```

**Comment by FZambia** [comment]
@atygaev hello, thanks for positive feedback and pull request!

The reason I doubt we should change this is the fact that one request can contain several API commands and thus several replies in one response ([example in Go HTTP client](https://github.com/centrifugal/gocent/blob/master/examples/client.go#L67)).  So there is a chance that one of those commands will contain protocol error, another will be successful. In this perspective having 400 Bad Request code is not semantically great.

Another concern is that this can theoretically break existing API clients as HTTP libraries in different languages react on non-20x status codes differently.

**Comment by FZambia** [comment]
Closing as I don't see how to change this without breaking semantics and client libraries.
