### ISSUE TITLE
404 curl http://localhost:8000 CentOS

### ISSUE THREAD

**Issue by chelkaz** [centrifugal/centrifugo#267]
HI! I use Nginx configuration for my domain and SSL https://centrifugal.github.io/centrifugo/deploy/nginx/
Admin page work http://mydomain.site:8000/#/ OK
default NGINX 8000
bot console command - curl http://localhost:8000/connection/info
404 page not found
HELP Please(

**Comment by FZambia** [comment]
Hi, are you migrating from Centrifugo v1 to Centrifugo v2? In v2 SockJS info endpoint path is `/connection/sockjs/info`

**Comment by chelkaz** [comment]
> Hi, are you migrating from Centrifugo v1 to Centrifugo v2? In v2 SockJS info endpoint path is `/connection/sockjs/info`
No, i quick install new https://packagecloud.io/FZambia/centrifugo/install#bash-rpm
I did not have other versions

/connection/sockjs/info failed: Error during WebSocket handshake: Unexpected response code: 404

**Comment by FZambia** [comment]
You asked for `info` endpoint so I answered on that question:)

Now your task is clear - you need to use new SockJS endpoint in you JS:

```javascript
var centrifuge = new Centrifuge('https://my.site/connection/sockjs', {
    sockjs: SockJS
});
```

This is [described in migration docs](https://centrifugal.github.io/centrifugo/misc/migrate/) BTW. Also I suggest you to read new documentation from scratch as Centrifugo v2 has some important and some backwards incompatible changes.
