### ISSUE TITLE
Centrifugo V2 rpm + PHP + JS How to listen to events?

### ISSUE THREAD

**Issue by chelkaz** [centrifugal/centrifugo#268]
For example, a new client has connected
How can I listen?
If i have a new client, shout it out to everyone - Hi, we have a new friend)
(The latest Centrifugo is installed on CentOS) A new user has entered the WEB page.
Contact Centrifugo is established. How do I get this from PHP? There are ways?

(На CentOS установлена latest Centrifugo) На WEB страницу зашел новый пользователь.
Связь с Centrifugo установлена. Как например из PHP мне услышать это? Есть способы?

**Comment by FZambia** [comment]
@chelkaz you have two ways:

1) Manually send AJAX request to you app as soon as client connected, process that event and then publish event to all listeners over Centrifugo API if needed. I suppose this option is more suitable for your case.

2) Enable JOIN/LEAVE events - but you have to properly estimate cost of this operation, for channels with lots subscribers you have a risk of overwhelming your clients with join/leave events. Those are mostly suitable for channels with reasonable amount of subscribers and cases where you really need to instantly react on client presence.  See `join_leave` option of channel namespace - https://centrifugal.github.io/centrifugo/server/configuration/. I suppose this way is not what you need as you only have to notify other users on first join to channel.

Consider not posting questions like this to Github issue tracker, it's mostly for bug reports and well-planned feature proposals. We have chat groups on Gitter and Telegram - see links in README.
