### ISSUE TITLE
Configuration via env vars conflicts with Kubernetes

### ISSUE THREAD

**Issue by zigmund** [centrifugal/centrifugo#269]
Not a critical issue, but got a case when configuration via env vars conflicts with Kubernetes pod's env vars.

Example:
1. Create service named centrifugo.
2. Deploy pods with matching labels with the service.
3. Pods will have CENTRIFUGO_PORT env var pointing to service enpoint (e.g. tcp://10.251.15.166:8080)
4. Centrifugo will fail to start with message:
```
[F]: 2019/02/12 05:23:09 ListenAndServe: listen tcp: address :tcp://10.251.15.166:8080: too many colons in address
```

Centrifugo version 1.8.0

**Comment by zigmund** [comment]
As workaround if you need to set exact same service name - overwrite env var in deployment:
```yaml
      - env:
        - name: CENTRIFUGO_PORT
          value: ""
```

**Comment by FZambia** [comment]
Hi, thanks for pointing - a bit unfortunate. So I suppose you can just rename your service? Another possible solution is explicitly set port over command line flag option `--port` - according to Viper docs Centrifugo will resolve configuration in this order:

```
Viper uses the following precedence order. Each item takes precedence over the item below it:

explicit call to Set
flag
env
config
key/value store
default
```

Also a bit odd that env var contains not only port but ip address and protocol parts.

**Comment by zigmund** [comment]
@FZambia sure we can rename service or set flag. So it's not critical issue or not an issue at all, just a rare case. :)

Just for history if someone else will catch this. Thanks.

**Comment by FZambia** [comment]
Yep, this is good to know, thanks!

**Comment by weijer** [comment]
Thank you. It's real
