### ISSUE TITLE
Real-time messaging app architecture

### ISSUE THREAD

**Issue by KakarN** [centrifugal/centrifugo#270]
Hello,

I am not sure if this is an issue worthy post, and if you think this not an issue worthy post please feel free to close it. I need to know how to build the architecture for a messaging app, i.e., a user can chat a single user, or can chat on a group thread. In this scenario all the threads including the group threads are private.

Okay so here it goes.

I am building a WhatsApp like messaging app. The idea is simple:
- User
- Thread: A thread can have a name if it's a group, or no name if it's between two users only. One thread can have many users (thread members). And a user can be on many threads. Each thread will have a unique private channel name.
- Message: A message will have a foreign key field to the thread, and will have a timestamp and the sender info. And obviously the message body.

**Use case:**

1. The user installs the app (built using react-native).
2. If the user already has an account, then log in. Else create a new account and log in.
3. When the user logs in, the user can view the threads that the user is already a member of.
4. The user can join a thread or create a new thread to chat a single user, or by creating a new group.

**Real-time (Django and centifugo) architecture:**

1. When the user login successfully on the Django server, Django backend responds back with four important data :
    - jwt token (let's call it _django_token_) to authenticate requests for the Django server
    - centrifugo auth token to authenticate the centrifugo server, let's call it _centrifugo auth token_.
    - Recent/Latest 20 threads (thread id, name, etc.) in a lazy loading fashion.
    - User's private channel id for the centrifugo server, let's call it _user notification channel_. This is to send notification of other events.

2. The client connects to the centrifugo server with the _centrifugo auth token_.
3. Centrifugo server responds back with the client id.
4. Client asks for permission for the subscription on the user's private channel from the Django server using the jwt token (i.e., the _django token_) and the client id.
5. Django server authenticates the user, sends back the token to connect to user's private channel on the centrifugo server.
6. The client connects to the centrifugo server using the private token to the user's _notification channel_ on the centrifugo server.

So my question is that:

1. Should I subscribe the user to all the thread's that he/she is a member of? Suppose he has 500 threads (can be private ie one on one channel between two users or different groups), will this still be a good architecture to call subscribe for 200+ channels on the server?
2. Or subscribe the user to the specific channel, only when the user taps that thread, or when selecting a user to start the chat? But doing this way, suppose the user (UserA) is not yet subscribed to the thread, and another user (UserB) sends a message on this thread, this means the UserA wont receive the message sent by the UserB.
3. Use the _user notification channel_ to send thread messages as well. Suppose a group thread has three users, i.e.,  UserA, UserB and UserC. UserA sends a message on the thread, and the backend would loop through each user's notification channel to publish the message for each user. But, suppose a group thread can have 1000 users, won't this effect the message latency for different users?
4. Or use option 3 with option 2. That is, initially UserA will be subscribed to the private _user notification channel_. If the user selects a specific thread, subscribe to that thread. Also, later, if the UserB sends a message on a thread (threadX), notifiy UserA that UserB has sent a message on threadX, and subscribe UserA to threadX.
 
Any help or insight is greatly appreciated! Thank you.

**Comment by FZambia** [comment]
Asking question like this you should be ready than no one can give exact answer on how to architect channel configuration without knowing all corner cases and specifics.

What I can say:

* Option 1 simply does not scale, you should avoid arbitrary amount of channels for many reasons.
* In messaging app you definitely need per user personal channel, actually with Centrifugo you can use user-limited channel (with `#`) and not necessary use private channels. Though private channels have a characteristic to be confirmed with private subscription token on every subscribe attempt - even on every reconnect. So maybe this is valuable for you.
* Of course broadcasting message to 1000 users will affect latency, but in general new messages not created in a very high rate so there is a chance that you will be fine. Centrifugo can process 1000 messages pretty quickly (look at `broadcast` API method). But you should measure and estimate how it works for your case.

I'd start with one channel per user.

I will close this issue as this is not bug report or feature request, but feel free to continue discussion.

**Comment by KakarN** [comment]
Hi @FZambia ! Thank you for your insight. 

I have not quite grasped the concept of `#` of Centrifugo's channel design. But I will certainly look into it more.

It would be great if you could help me clear some of my doubts:

1. When sending (publishing) messages from the server API, is it in a non block fashion? 
    - Because if not, suppose a group has 5000 members
    - Publishing a single msg to 5000  private channel user channels.
    - Wont the process of the sender's request will block until the message is published to all of the individual use's channel. Or should I be using something like to Celery.
    - A very simple example using python (Cent and Django): 

```
data = request.data
members = thread.members.all()
for member in members:
	channel = member.private_channel
	client.publish(channel, data) # without celery
	celery_function_to_publish.delay(channel, data) # with celery
```
2. And yes, you are absolutely right, that _messages are not created in a very high rate_. As you mentioned that 

> Centrifugo can process 1000 messages pretty quickly (look at `broadcast` API method).

I was not familiar with the broadcast command, but now looking at the broadcast command, it seems the right choice for the job! I can pass all the user's private single channel to the channels list in the broadcast command. However, could you please tell me whether the performance will be improved by using the broadcast command as opposed to looping (for loop) through all the channels as described in the above example?

3. Can you please tell how to go about load testing the Centrifugo server's connection?

**Comment by FZambia** [comment]
You can very quickly estimate time locally:

```python
from timeit import default_timer as timer
from cent.core import Client

client = Client("http://localhost:8000", "<API KEY>")

numChannels = 5000

def publish_in_loop():
    start = timer()
    for i in range(numChannels):
        client.publish("test" + str(i), {"input": "hello"})
    end = timer()
    print(f"publish in a loop to {numChannels} channels: {end - start} sec")

def broadcast():
    start = timer()
    channels = []
    for i in range(numChannels):
        channels.append("test" + str(i))

    client.broadcast(channels, {"input": "hello"})
    end = timer()
    print(f"broadcast to {numChannels} channels: {end - start} sec")

if __name__ == "__main__":
    publish_in_loop()
    broadcast()
```

This gives me the following output on my machine:

```
publish in a loop to 5000 channels: 16.99 sec
broadcast to 5000 channels: 0.017 sec
```

As you publish in a synchronous loop it's a very long operation - Centrifugo can handle thousands of requests per second so here you are limited in speed of Python and sequential sending. If you have a possibility to send requests in async way (actually you can start asyncio event loop inside your Django worker and send many requests and then close loop, but it's a bit esoteric). So just using broadcast gives you a great speed up here (17 sec vs 17ms).

I'd avoid Celery until you really understand it's required.

Also note that this test was done with Centrifugo memory engine, history turned of and no connections to channels. So numbers could be a bit different in real case but still the difference will be the same. 

One more property you better to implement is making your messages idempotent - if client received message that it already loaded with state from backend this should not result in extra information on user screen. Though I suppose React gives this for you for free as it has `key` concept.

About load testing - this is hard topic but in general you can artificially create many connections using our client libraries (for Javascript, Go, Swift, Dart at moment) and experiment in a way you want. Don't forget to make file descriptor limit higher on your machine to handle many connections. If you end up with any results - please share here, this is very interesting.

We also have benchmarking script [here](https://github.com/centrifugal/centrifuge-go/tree/master/examples/benchmark) - but not sure how it suits for you.

**Comment by KakarN** [comment]
@FZambia Thank you so much! Your insights were really very helpful! And I will be sure to share my results with you.

**Comment by KakarN** [comment]
@FZambia So, I have set up the required architecture, on the client and backend server. However, I have stumbled across some issues:

1. Is there any way to know in the backend server (Django) when the client is connected?
    - I need this so that I can send the remaining messages (message sent by other users on the thread when the user was offline) to the client when the client is online, and also to set the user active status to true in the database.
    - To solve this I can make a request on the backend server, to get the remaining messages on the client, and set the active status to true.
    - In Django-channels, it was possible to send data back after the connection is established, without any request from the client. It would be great to know that we can do this with Centrifugo too.

2. Similar to connection event, after the user disconnects, is there any way to know in the backend server (Django) that the user has unsubscribed or disconnected?
    - I need this to update the user active status to false. So that other users may know that the user is offline.
    - I cannot think of any better way to solve this problem. The only solution I can think is making a ping request by the backend server on the client. But I am not familiar with how to start with this.
    - It would be great to know that this is possible using Centrifugo out of the box.

Your insights on this matter would be great!

**Comment by FZambia** [comment]
1) You should send request to your app
2) This should be solved periodically pinging your backend

Some insights why this limitation exists can be found in #195 

Both cases supported by [Centrifuge](https://github.com/centrifugal/centrifuge) library Centrifugo built on top of. But I don't know scalable solution to make it work properly in Centrifugo case - consider  node restart with many active connections - some events can be lost. I suppose this is the same for Django channels. In normal workflow everything works fine but under heavy reconnect time you can not rely on Django channels at all. Correct me if I wrong.

**Comment by FZambia** [comment]
Or if you just kill Daphne server.. I suppose all events will be missed too in Django channels case

**Comment by KakarN** [comment]
Yes, you have a point. 

I think for the _last seen feature_, there's no best option than to solve this issue on the client side, by making a ping request every 5 or maybe 30 seconds in the backend server. 

For the user's _active status_, could you tell me if the `presence` method will suffice to know if the user is online? Since, every user will have its own private channel (e.g.: `$user-8`), and the user will subscribed to that channel on the client side. So using cent library, if `len(client.presence("$user-8"))` is greater than 0, means the user is online, else the user is offline. 

Although even if the `presence` method will work on first request, suppose userA and userB is chatting, and after some time userB is offline, I think there is no way to inform userA, that userB is offline. The only solution again would be if userA ask the server every x seconds whether userB is online or not.

**Comment by FZambia** [comment]
I suppose you can use presence for this. 

For two users case I think you can use presence and join/leave messages. Have you considered join/leave messages? Maybe I just do not understand problem right.

**Comment by KakarN** [comment]
Please consider this scenario:

1. userA opens the app, and is connected (authenticated and subscribed to its private channel) to the Centrifugo server.
2. userA selects a user (userB). 
3. And it is navigated to the next screen, which is the thread (messages) between userA and userB.
4. Since, userB is offline, so the last seen will be displayed on the user-detail on the top header of userA.
5. Later, userB opens the app. (Here, userB does not select userA, but may open a different thread or is doing nothing.)
6. Back on the userA's app, which is still on the thread between userA and userB screen, the server notifies, that the userB is online.
7. After a while, userB closes the app. 
8. Bac, on userA's app, which is still on the thread between userA and userB screen, the server notifies, that userB is offline, and the last seen is displayed again.

As you have told me, I also think `join/leave` events are the best approach for this case. But I am not sure how to emit the join/leave events to both the clients (userA and userB), since each user is only subscribed to its own private channel (eq. userA is subscribed to channel $user-A, and userB is subscribed to $user-B)? Could you please elaborate if possible how can I utilize the join/leave events to both the user?

**Comment by FZambia** [comment]
Got it now.

Theoretically you can have one more common channel each user will be subscribed to. For this channel you can enable presence and rely on it. But this does not scale well when there are many users... This works fine for isolated groups - gam lobbies maybe... But for messenger app I suppose every user could have many contacts. So presence info will be pretty heavy. 

At work we develop messenger with pretty big amount of users. We use part of Centrifugo (slightly modified Redis engine) and we solve this problem using separate service which is responsible for online status. It works pretty fine, though it gives small delay when user goes online/offline. But it's robust and very simple - there are no edge cases at all.

**Comment by KakarN** [comment]
Okay! I will try to solve the issue. Thank you for your helpful insights!
