### ISSUE TITLE
Excluding event recipients

### ISSUE THREAD

**Issue by Raerten** [centrifugal/centrifugo#274]
Pusher have option to exclude recipients from receiving events on subscribed channel.
Possible reasons described here https://pusher.com/docs/server_api_guide/server_excluding_recipients
and it's used by [laravel pusher driver](https://laravel.com/docs/5.8/broadcasting#broadcasting-events) (section "Only To Others").
It can partly be implemented with proxying to all subscribers "sender id" and filtering it on client side but it discloses sender id and make solution insecure.

Can something similar be implemented in centrifugo?

**Comment by FZambia** [comment]
I was thinking about this before, but looks like this feature does not fit well Centrifugo design. It's definitely possible to do the same way Pusher does. But semantically this ruins the main idea of Centrifugo history - which is an immutable stream of events where each message can be safely sent to each subscriber.

Also, even with Pusher, there is possible race condition - imagine that you sent message and immediately reconnected. In this case your Pusher connection has new socket_id and there is a chance that you will receive that message. I suppose that a more robust way is handle this on application side level and assign some sort of per-page identificator to message that is not related to currently established connection. Also a good practice is just making this sort of messages idempotent.

**Comment by Raerten** [comment]
We don't use history and I completely forgot about it.
Indeed It doesn't fit "history" design and implementation may cause misbehavior.
Perhaps it is worth mentioning in the documentation.

Thanks for your project!

**Comment by FZambia** [comment]
@Raerten welcome! One of the biggest difficulties is that I know a little about Centrifugo use cases actually. While I know that Centrifugo is used in many projects only a few people share their stories. So if you have a time to share details about your use case - please write me a couple of lines about its details, this will help me to understand project better.

**Comment by ernsheong** [comment]
Sorry to hijack the thread, but I have a related question: Is it possible to exclude the sender client from list of recipients? 

For example, web client A deletes a resource... deletion message bounces back via WebSockets, only to find there is nothing to delete because of course the web client knows about the deletion already and has executed it.

**Comment by FZambia** [comment]
@ernsheong hi, isn't it the same question already discussed above? Do you suggest sth different? You pointed to solution which is recommended way to deal with this. Adding sender does not fit well Centrifugo design and guarantees

**Comment by ernsheong** [comment]
@FZambia thanks for the clarification
