### ISSUE TITLE
Problem with .deb packages on Ubuntu 18.04

### ISSUE THREAD

**Issue by devops787** [centrifugal/centrifugo#275]
Hi. I can't install centrifugo on Ubuntu 18.04 from https://packagecloud.io/FZambia/centrifugo
```
E: Corrupted archive
E: Prior errors apply to /var/cache/apt/archives/centrifugo_2.2.0-0_amd64.deb
debconf: apt-extracttemplates failed: No such file or directory
tar: Archive is compressed. Use -j option
tar: Error is not recoverable: exiting now
dpkg-deb: error: tar subprocess returned error exit status 2
dpkg: error processing archive /var/cache/apt/archives/centrifugo_2.2.0-0_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/centrifugo_2.2.0-0_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I've tried to clear apt cache, but it does not help

**Comment by devops787** [comment]
Looks like it is a bug in fpm which is used to build deb package in Travis - https://github.com/jordansissel/fpm/issues/1612

**Comment by FZambia** [comment]
@devops787 thanks for report!

Just pushed new 2.2.0 package revision (2.2.0-1) to Packagecloud - see  https://packagecloud.io/FZambia/centrifugo/packages/ubuntu/bionic/centrifugo_2.2.0-1_amd64.deb for Ubuntu 18.04 package
