### ISSUE TITLE
WebSub

### ISSUE THREAD

**Issue by gedw99** [centrifugal/centrifugo#278]
Btw i was just reading Banks review of the long long list of technologies for doing push from the server to client here:
https://banksco.de/

He left one out that is really designed for constant messaging:
https://www.w3.org/TR/websub/

There is a golang lib for it floating around.
https://github.com/adamsanghera/go-websub
Its maybe worth looking at another day.
https://nordicapis.com/websub-common-cases-and-implementations/

Its starting to get attention.

**Comment by FZambia** [comment]
Yeah, that's a really great article by @banks ! I've heard about PubSubHubBub before but have never heard about WebSub - thanks for sharing. On the first look that seems like backend stuff as publications sent to subscribers over webhooks, do you mean that this can be somehow useful in terms of extending Centrifugo?

**Comment by banks** [comment]
Nice. WebSub is new to me! I wrote that article in January 2016 and looks like WebSub published was last year. I’ll read it!

**Comment by FZambia** [comment]
Closing, interesting spec but I have not found sth we could extrapolate to Centrifugo.
