### ISSUE TITLE
GRPC failure to connect: pickfirstBalancer: failed to NewSubConn

### ISSUE THREAD

**Issue by ernsheong** [centrifugal/centrifugo#282]
After launching Centrifugo server, I try to connect to it from my app server via GRPC, and am promptly greeted by the following error:

```
pickfirstBalancer: failed to NewSubConn: rpc error: code = Canceled desc = grpc: the client connection is closing
```

![image](https://user-images.githubusercontent.com/1343284/57466568-87871480-72b3-11e9-85c8-f881b27b6797.png)

GRPC client creation:
![image](https://user-images.githubusercontent.com/1343284/57470214-e308d080-72ba-11e9-9e7f-50fa556b5361.png)

Any idea what am I doing wrong? I am on macOS

**Comment by ernsheong** [comment]
When I turn on `log_level=debug`, I see debugs from the websocket connection, but none from the GRPC service:

![image](https://user-images.githubusercontent.com/1343284/57469295-e8651b80-72b8-11e9-902b-18e7bbb29f26.png)

**Comment by FZambia** [comment]
@ernsheong hello, does this error happen on every request and results into non working RPCs? Or it happens once when HTTP/2 connection established?

**Comment by ernsheong** [comment]
Hi Alexander, thanks for the reply. It happens on every request. It may or
may not happen when connecting.

The request was a Publish, and resulted in nothing being published because
of the error.

**Comment by FZambia** [comment]
Got it, thanks, will try to reproduce

**Comment by ernsheong** [comment]
Thanks. Apologies in advance if I missed out something obvious

**Comment by FZambia** [comment]
@ernsheong I suppose your problem arise from the fact that you are using `func init` instead of `func main`. You are closing connection as soon as your init finish its work (at the beginning of program).

Here is a simple example on how I managed to run Centrifugo with GRPC Go client locally on MacOS:

```bash
cd ~
mkdir centrifugo_grpc_example
cd centrifugo_grpc_example/
wget https://raw.githubusercontent.com/centrifugal/centrifugo/master/misc/proto/api.proto -O api.proto
protoc api.proto --go_out=plugins=grpc,import_path=main:./
touch main.go
```

Put the following code to `main.go` file (created on last step above) :

```go
package main

import (
	"context"
	"log"
	"time"

	"google.golang.org/grpc"
)

func main() {
	conn, err := grpc.Dial("localhost:10000", grpc.WithInsecure())
	if err != nil {
		log.Fatalln(err)
	}
	defer conn.Close()
	client := NewCentrifugoClient(conn)
	for {
		_, err := client.Publish(context.Background(), &PublishRequest{
			Channel: "chat:index",
			Data:    []byte(`{"input": "hello from GRPC"}`),
		})
		if err != nil {
			log.Println(err.Error())
		} else {
			log.Println("successfully published")
		}
		time.Sleep(time.Second)
	}
}
```

Then run:

```bash
GO111MODULE=on go run *.go
```

Hope this will help to solve a problem.

**Comment by ernsheong** [comment]
I found the issue thanks to your code; the issue became clear:

![image](https://user-images.githubusercontent.com/1343284/57500828-7cfe6680-7317-11e9-819e-b6a2a2ec9334.png)

I had renamed the package to `centrifugo` from `api` as I already have an `api` package... 

In any case you're right doing networking setup in `func init()` is a bad idea.

**Comment by ernsheong** [comment]
Also `defer conn.Close()` only makes sense in a main loop, not elsewhere. That was my other mystery. Thanks for taking the time.

**Comment by FZambia** [comment]
Just published an example into docs: https://centrifugal.github.io/centrifugo/server/grpc_api/#example-for-go

**Comment by ernsheong** [comment]
Btw `data.data` seems a bit redundant... unless I missed something the additional `data` is not from my payload.

![image](https://user-images.githubusercontent.com/1343284/57508487-2e12fa00-7334-11e9-8f6b-04a808b166c1.png)

**Comment by FZambia** [comment]
Yeah, this is how client-server protocol structured. You can investigate how everything encapsulated in proto file https://github.com/centrifugal/centrifuge/blob/master/misc/proto/client.proto
