### ISSUE TITLE
ACME Autocert tls-sni-01 deprecated

### ISSUE THREAD

**Issue by Signorini** [centrifugal/centrifugo#283]
Hello I trie to use tls auto cert configs, but received the error.

```
TLS handshake error from XXX: acme/autocert: unable to authorize "XXX"; tried ["tls-sni-02" "tls-sni-01"]
```

Little reserach lets encrypt stop to accept the tls-sni-01
https://www.digitalocean.com/community/questions/let-s-encrypt-acme-tls-sni-01-end-of-life

How I can force to stop using tls-sni-01?

My config is:
```
{
  "secret": "",
  "api_key": "",
  "admin_password": "",
  "admin_secret": "",
  "tls_autocert": true,
  "tls_autocert_cache_dir": "/tmp/certs",
}
``` 

thanks

**Comment by FZambia** [comment]
Hello, Centrifugo supports http-01 at moment - see docs on how to enable it (you will need 80 port open in this case). Though looks like there is new tls-alpn-01 challenge we should enable instead of tls-sni-01.

**Comment by FZambia** [comment]
@Signorini just merged related pr to support tls-alpn-01, unfortunately I have no chance to check it out on live domain.

**Comment by Signorini** [comment]
Thanks @FZambia - For now I use http-01 and works, after I will update centrifugo and use alpn method. [my concerns regarding http-01 its need to open a new port on firewall only to validate things, its not the best scenario but works].

thanks again
