### ISSUE TITLE
Do you have benchmarks?

### ISSUE THREAD

**Issue by nicola-spb** [centrifugal/centrifugo#286]
Hello,

Do you have benchmarks for centrifugo?

**Comment by FZambia** [comment]
Hi, as ready to use suite - no. There are many microbenchmarks throughout Centrifuge library code. Also there are results of benchmark I did while developing version 2 of Centrifugo - https://github.com/centrifugal/centrifuge-go/tree/master/examples/benchmark - can be interesting.

Which kind of benchmark you expected to see btw?

**Comment by nicola-spb** [comment]
I wanted to see count messages per second and count of connections.
https://github.com/centrifugal/centrifuge-go/tree/master/examples/benchmark

I think it`s useful information for readme file.
Thanks.
