### ISSUE TITLE
cant install centrifuge  2.2.1 on windows WSL

### ISSUE THREAD

**Issue by mcroni** [centrifugal/centrifugo#287]
i keep getting `-bash: ./centrifugo: cannot execute binary file: Exec format error` when i run `./centrifugo genconfig`

**Comment by FZambia** [comment]
Hello @mcroni, we have an issue template you skipped for some reason. Personally I don't have WSL installed and Centrifugo have never been tested on WSL so please provide steps to reproduce:

* Which binary you are using
* Windows version
* Linux distro
* Any other installation details
* Is the problem reproduces with 2.2.1 only and works fine with previous versions?

**Comment by FZambia** [comment]
Closing as no answer from op for more than a week. @mcroni feel free to reopen if this is still actual but please provide all required information.
