### ISSUE TITLE
is there has api/webui show clients list?

### ISSUE THREAD

**Issue by excxapp** [centrifugal/centrifugo#292]
## Prerequisites

_Put an `x` in the boxes that apply:_

* [x] This is a bug report
* [x ] This is a feature request
* [ ] This is a question (did you check the [FAQ](https://centrifugal.github.io/centrifugo/faq/) btw?)

## Description
can has any api/webui show all clients
show clients list

**Comment by FZambia** [comment]
Hello, what problem you want to solve with this?

**Comment by excxapp** [comment]
can have  api show clients and user list.


![image](https://user-images.githubusercontent.com/4355581/62419913-7a64a080-b6bd-11e9-8b0c-4fa824337098.png)

**Comment by excxapp** [comment]
another feature
also can  query who subscribe channel
like 
`
{
    "method": "channel_subscriber",
    "params": {
        "channel": "CHANNEL NAME",
    }
}

response
{
    "result": {
        "users": [
            "uid1",
            "uid2",
            ....
        ],
       "client":["client1", "client2", ...]
    }
}
`

**Comment by FZambia** [comment]
When I asking about problem I mean information on how you are planning to use this statistics. Centrifugo designed to work with thousands of client connections throughout many nodes. At moment I can't imagine a way to efficiently do what you suggest, if you describe your use case for this with details it can help to find reasoning for such feature or alternative way to solve. Until that it seems unjustified and not efficient to have.

**Comment by FZambia** [comment]
Closing as no response from op for more than a week. Theoretically this can be implemented as some tracing info sent into external system from application client side (after connect or subscribe events, with expiration).
