### ISSUE TITLE
How about performance？

### ISSUE THREAD

**Issue by ab92015359** [centrifugal/centrifugo#293]
Because my website has 500K daily active users. I want to use centrifugo in my website. So I want to know a lot of performance information about centrifugo. 

For example: Connection number in a certain hardware environment

**Comment by FZambia** [comment]
Hello.

We use approach similar to Centrifugo (not Centrifugo itself but the same algorithms and code from Centrifugo Redis Engine) on a site/app with 2.2 million daily users. We have about 500k online connections served by single Redis instance. Look at [FAQ](https://centrifugal.github.io/centrifugo/faq/#how-many-connections-can-one-centrifugo-instance-handle). I can't say how many Centrifugo nodes you will need for your case as it heavily depends on load profile.

Some numbers I can share:

* Each 10k connections will cost you about 350 MB of RAM
* You can expect that Centrifugo will restore 100k subscriptions in several seconds with Redis, faster with Memory engine. 
* You should properly configure your machine to handle lots of connections - some information can be found in our docs

Some artificial numbers can be found [in this benchmark](https://github.com/centrifugal/centrifuge-go/tree/master/examples/benchmark).

In general you need to measure performance for your own hardware and with your own load profile.

You can ask the following questions regarding this in our Gitter or Telegram chats (links in README).

**Comment by ab92015359** [comment]
Thanks for the reply.

**Comment by iheb719** [comment]
@FZambia the benchmark link is dead. Was it similar to [the one in the documentation](https://centrifugal.dev/docs/tutorial/scale)?
