### ISSUE TITLE
[feature] Endpoint customization

### ISSUE THREAD

**Issue by ZL0D3Y** [centrifugal/centrifugo#294]
It there any way to customize endpoints with PORTS instead of URL's?

**Comment by FZambia** [comment]
@ZL0D3Y hello, could you post an example of what you mean?

**Comment by ZL0D3Y** [comment]
@FZambia  
Yes, now I'm connecting to centrifugo WS thru **ws://localhost:8000/connection/websocket** but in my case I can't use URL, I'm operating only with host and port. So is there some kind of configuration where I can change ws://localhost:8000/connection/websocket  endpoint to localhost:8333 for example?

**Comment by FZambia** [comment]
You can change port with `--port` option. For changing URL path – possibly you can use Nginx and `rewrite` directive?

**Comment by ZL0D3Y** [comment]
But isn't it a little overhead to use Nginx with Centrifugo instead of accepting connection to defined port without url in connection and allow to configure this settings in Centrifugo configurations?

**Comment by FZambia** [comment]
Yeah, it adds some overhead of course, but usually you need some load balancer before Centrifugo anyway - to load balance connections between different Centrifugo nodes, so if you already have one you can rewrite path on that level.

If it's not possible we can consider adding options to override paths in configuration. But URLs are also used for some other things like saying to server which protocol format client uses in query params (ex. `?protocol=protobuf`) - looks like if you can't change query params you won't be able to use Protobuf at moment. Is it a problem for you? Could you describe why you can only operate with domain and port btw?

Some other things I see is that if you change `/connection/websocket` to `/` in Centrifugo config then you also have to change path on which admin static assets served (`/` if admin enabled). So this adds some mess.

**Comment by FZambia** [comment]
> Btw, you can't connect to ws://localhost:8000/connection/websocket as long as I know, but you can do it via host:port.

Not sure I understand this - we connect to exactly this endpoint in all our examples. Of course in production you don't have localhost:)

**Comment by FZambia** [comment]
Just made a quick experiment - unfortunately moving admin web interface to another endpoint requires some work - does not work when I simply changing its path prefix.
