### ISSUE TITLE
How do I catch a customer subscription event?

### ISSUE THREAD

**Issue by chelkaz** [centrifugal/centrifugo#296]
**How do I catch a customer subscription event?**
My PHP product
My idea for implementation:
When a client subscribes, I must check his permission, whether he has the permission to access the channel, if so, let him in, if not, deny entrance to the channel

**Comment by FZambia** [comment]
Hello, https://centrifugal.github.io/centrifugo/server/private_channels/

You can ask questions like this in our Telegram chat btw.
