### ISSUE TITLE
[question] Limit who can publish in a public channel

### ISSUE THREAD

**Issue by maurodelazeri** [centrifugal/centrifugo#298]
Does centrifugo supports only a set of clients to publish into a public channel?

let me expand... I have one to many subscribers on one channel and I only want to have a few users who can produce messages on that channel, reading the documentation I found nothing that covers it since it is not a private channel... is there any way to work around this?

**Comment by FZambia** [comment]
@maurodelazeri hello. In current paradigm this should be done over server-side API - i.e. your client sends request to your backend (AJAX, REST or whatever you want), then application backend checks permissions, saves message into main database if needed and publishes message to Centrifugo over HTTP or GRPC API.

**Comment by maurodelazeri** [comment]
yeaa, I figured out... thanks
