### ISSUE TITLE
HELP - How to start centrifugo with Redis engine when starting through systemd

### ISSUE THREAD

**Issue by zappan** [centrifugal/centrifugo#299]
Hi,

When Centrifugo gets started via SystemD it just reads config.json. I'm trying to find the `config.json` option on how to configure it there to use Redis, but unable to find it - that is documented as an option listed for command line, but nowhere for config.json

It might be really useful to have a page with a full list of parameters for `config.json` like it has for command line flags (https://centrifugal.github.io/centrifugo/server/configuration/)

Thanks.

**Comment by FZambia** [comment]
@zappan hello, all command line options can be set in configuration file too with the same names. This means that sth like this will work for you:
```
{
  ...
  "engine": "redis",
  "redis_host": "..."
}
```

Looks like we have to update docs about this.

**Comment by FZambia** [comment]
Improved docs a bit in d7c3c3c48758dd095ca7078c71ec8b2bc85f2abf

**Comment by zappan** [comment]
I'd just maybe say instead

> Keep in mind that all command-line options of Centrifugo can be set via configuration file with the same name

this:

> Keep in mind that all command-line options of Centrifugo can be set in the `config.json` file as well, having with the same parameter names

But, even this is good, see if you wish to do another change. 

Thanks very much for clearing it up for me!
