### ISSUE TITLE
memoryPresenceHub.get(..) is racy.

### ISSUE THREAD

**Issue by klauspost** [centrifugal/centrifugo#3]
You return a reference to the `map[string]interface{}`, but you unlock when the function returns. There is no way for the caller so ensure that the map isn't modified by another goroutine while it operates on the data.

Unfortunately copying a map[string]interface{} isn't trivial, but maybe "https://godoc.org/code.google.com/p/rog-go/exp/deepcopy" can help, but the best solution would probably be to not use `interface{}`, but some more "controlled" type.

**Comment by FZambia** [comment]
Thanks again!

In this case presence information can contain any decoded JSON object provided by web application on connect. What do you mean under `more "controlled" type`? keep that data as JSON `string` without decoding first and decode from string when actually requested?

**Comment by klauspost** [comment]
Sorry, that was a bit unclear. I meant a struct or something similar.

I tracked back the "presence", which is (as you know)

```Go
	info := map[string]interface{}{
		"user":         c.user,
		"client":       c.uid,
		"default_info": c.info,
		"channel_info": channelInfo,
	}
```
Where `channel_info` is  set by
```Go
			err := json.Unmarshal([]byte(cmd.Info), &info)
			if err == nil {
				c.channelInfo[channel] = info
			}
```

To me it would make sense to do that as

```Go
type ChannelInfo struct{
		User string `json:"user"`
		Client string `json:"client"`
		DefaultInfo *json.RawMessage  `json:"default_info"` // Marshalled JSON - do we ever need the content of this? 
		ChannelInfo *json.RawMessage `json:"channel_info"` // Marshalled JSON? 
}
```

**Comment by FZambia** [comment]
Yes, this feels like a much more cleaner way. One question - will this result in double encoded JSON in the response output or json.RawMessage will be unmarshalled automatically later?

**Comment by FZambia** [comment]
Maybe it's a good idea to skip unmarshalling this custom JSON at all and just let client side to deal with JSON string in `default_info` and `channel_info` when it's needed?

**Comment by klauspost** [comment]
Yes, it doesn't seem like there is any real reason to do so. json.RawMessage will just store the JSON as bytes, and when it is Marhalled it is re-inserted. 

It will still be syntax validated when it is parsed, so you will not begin passing around invalid JSON. This will probably be a good speedup for the server.

**Comment by klauspost** [comment]
In general, every time you use a `interface{}"`, and even some `map[string]interface{}` ask yourself if it really is arbitrary data.

To a long time gopher it hurts to see:
```Go
		resp.Body = map[string]interface{}{
			"project": p.Name,
			"message": message,
		}
```
If you have fields you don't want returned, use the "omitempty" json tag.

**Comment by klauspost** [comment]
Sorry - forgot your question ;)

>One question - will this result in double encoded JSON in the response output for default_info and channel_info or json.RawMessage must be unmarshalled manually later when building a final response?

json.RawMessage is special. When you insert it, the content of the tag will be stored as raw json; a []byte slice containing the encoded JSON. When the struct is marshalled, it simply re-inserts the content of the slice as the value of the tag.

That also means that you can decode it later, as shown in #5 - because you can simply cast it to a byte array, which will contain the content of the tag.

**Comment by FZambia** [comment]
> To a long time gopher it hurts to see

Got it, will try to get rid of such map[string]interface{} usages in near perspective

**Comment by FZambia** [comment]
Started refactoring in [strong_types](https://github.com/centrifugal/centrifugo/tree/strong_types) branch. Added `ClientInfo` struct:
```go
// ClientInfo contains information about client to use in message
// meta information, presence information, join/leave events etc.
type ClientInfo struct {
	User        string           `json:"user"`
	Client      string           `json:"client"`
	DefaultInfo *json.RawMessage `json:"default_info"`
	ChannelInfo *json.RawMessage `json:"channel_info"`
}
```
And Message struct:
```go
type Message struct {
	Uid       string      `json:"uid"`
	Timestamp string      `json:"timestamp"`
	Info      *ClientInfo `json:"info"`
	Channel   string      `json:"channel"`
	Data      interface{} `json:"data"`
}
```
I think we need to use `json.RawMessage` for `Data` too (as `Data` travels unmodified through Centrifugo)?

**Comment by FZambia** [comment]
Replaced
```
Data      interface{} `json:"data"`
```
with 
```
Data     *json.RawMessage `json:"data"`
```
in a0bd971927273c5f44dba117c2e2332f75daff51

**Comment by klauspost** [comment]
Awesome!

**Comment by FZambia** [comment]
Merged all of these changes into master. There are still lots of places left though where `map[string]interface{}` used to create response bodies – created another issue #10 to refactor this

**Comment by FZambia** [comment]
@klauspost could you check this? is the problem gone away?

**Comment by FZambia** [comment]
@klauspost hope you will find a time to review changes made, I am closing this as I think race in memoryPresenceHub was fixed.
