### ISSUE TITLE
[feature] add nats event bus for client states

### ISSUE THREAD

**Issue by puryagh** [centrifugal/centrifugo#305]
In real messaging app we need to know if user is online or not like telegram, watsapp , ...
So when app user connects to server the backend can handle some info for client state such as who is online ,  Like (mqtt will topic) to get client state
…
today i was download source code and make some change to notifi backend for client state changes and on backend.
First add nats (nats.io) client to Centrifuge package
Add configuration for nats connection info like url and topic subject for publish message
i create nats client to listen connection , pub / sub events on backend side and every time a client subscribed to private channel (chat#uid) , centrifuge package publish sub or unsub to nats topic and a worker that listen to this nats topic parse chan and send it state to client status topic (status:uid) using centrifuge api

**Comment by FZambia** [comment]
Hi, is this somewhat different from current presence and join/leave features? Also there were some thoughts in [this issue](https://github.com/centrifugal/centrifugo/issues/270) on online status detection over separate service if Centrifugo does not solve your case.

At moment I don't think that your approach is robust enough for this task, what would we do with errors when publishing to Nats for example and therefore missed client state notifications?

**Comment by FZambia** [comment]
Closing as no response from op for a week, @puryagh consider my questions above and come with more concrete proposal if it's still actual.
