### ISSUE TITLE
[feature] Support all available options in command-line flags and env vars

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifugo#308]
Currently only frequently used options in Centrifugo go to command-line and not all options can be set over env var. Maybe it's time to reconsider current politics and simply support all options everywhere. As bonus we will have description for all available options using `centrifugo -h`

**Comment by zappan** [comment]
This would be highly appreciated to support running in ECS/Fargate - the only way of passing in the options is through the environment variables, or by building a custom image.

@FZambia do you have any time-frame in mind when this could be supported - I'd like to deploy Centrifugo in Fargate, shall I wait or just go with building my custom image? Thx for the feedback.

**Comment by FZambia** [comment]
@zappan hello, I suppose I can look into this during next weekend - the only difficult thing is `namespaces` configuration which is now an array of objects and I need to investigate how to properly configure them using envs or flags. BTW Centrifugo already supports [some of options](https://github.com/centrifugal/centrifugo/blob/master/main.go#L63) to be set over env vars as `CENTRIFUGO_<option name>` but I suppose this is not properly documented. Maybe those are enough for you (but lack of namespaces configuration can be crucial though as I recommend using custom namespace name for every real-time feature in app).

**Comment by zappan** [comment]
I use some Redis options not supported, plus this namespace thingy which I
reckon could be somewhat tricky for you to support.

Thanks for the answer. I hope you'll get some smart idea on how to support
namespaces.

**Comment by FZambia** [comment]
I think the most straighforward way to deal with namespaces is let it be passed as valid JSON string

**Comment by FZambia** [comment]
@zappan pull request #313 allows to set everything over env vars, looks like I only add this change to next release. Regarding to adding everything to flags - I still have some thoughts that we should not add absolutely all options to flags as it will be a very huge list where many flags never used because default values fit most user needs in all cases (smth like `client_presence_ping_interval` for example). So I will try to think a bit more on this.

**Comment by zappan** [comment]
Awesome, thank you very much!
I'll check it out and report if I find any issues, but I believe it will be all fine.

**Comment by FZambia** [comment]
Closing - I suppose all the necessary work has been done here. Since this moment Centrifugo will support configuration of all available options over environment variables. I think in today cloud world this is more important and flexible than command-line flags. Regarding to cmd flags the politics will stay the same as before - some options will be added, some won't. It's pretty OK to move some existing options to cmd flags but not all of them. I think most users are not using cmd flags in production at all when deploying Centrifugo. If someone have objections please feel free to discuss this further.
