### ISSUE TITLE
[feature] show more information with debug level logging

### ISSUE THREAD

**Issue by danqing** [centrifugal/centrifugo#309]
With `log_level=debug` Centrifugo shows useful information like receiving HTTP calls and client connections. It doesn't however show things like the status code or error message (when present) of these calls.

I think having more information for the calls is super helpful with debug level logging. Now when something goes wrong, I still need to catch things on the caller side to see what's going on, which kind of defeats the point of debug logging.

Maybe we can at least log the status/error here?

Thank you!

**Comment by FZambia** [comment]
Hello! You mean HTTP status codes right? Regarding to errors: in general Centrifugo writes errors to log, do you mean any specific case where error is swallowed?

**Comment by danqing** [comment]
Yes.

For example, when I'm hitting the /api endpoint, log_level=debug only shows a record of that (/api being hit), with no error or status code.

**Comment by FZambia** [comment]
I agree with status codes - those are not written to logs at moment, but all errors which happen during API  call execution must be written as separate `ERROR` level log entry - see [API handler](https://github.com/centrifugal/centrifugo/blob/master/internal/api/handler.go#L32). So my question is what was the concrete situation you came across which was hard to investigate?

**Comment by danqing** [comment]
Hmm I didn't see an ERROR level logging.

To answer your question, I can and should log errors on my end for sure. However, I think having error logs on Centrifugo end will make its logging a lot more useful.

**Comment by FZambia** [comment]
> To answer your question, I can and should log errors on my end for sure. However, I think having error logs on Centrifugo end will make its logging a lot more useful.

I mean that Centrifugo already writes `ERROR` logs - my link above was to Centrifugo server code.

**Comment by danqing** [comment]
Yeah I understand what you meant - I was saying somehow I didn't see those logs when I ran centrifugo with `log_level=debug` and logging to stdout.

**Comment by FZambia** [comment]
```
$ go run main.go --log_level=debug
2019-11-15T11:09:27+03:00 |INFO| starting Centrifugo dev (go1.13)
2019-11-15T11:09:27+03:00 |INFO| config path: /Users/ayuemelin/go/src/github.com/centrifugal/centrifugo/config.json
2019-11-15T11:09:27+03:00 |INFO| pid: 97703
2019-11-15T11:09:27+03:00 |INFO| engine: Memory
2019-11-15T11:09:27+03:00 |INFO| gomaxprocs: 8
2019-11-15T11:09:27+03:00 |INFO| serving websocket, SockJS, API endpoints on :8000
2019-11-15T11:09:29+03:00 |ERROR| API key is empty
2019-11-15T11:09:29+03:00 |DEBUG| http request addr=[::1]:55169 duration=0.141457 method=GET path=/api
```
So error logs are written as separate at moment

**Comment by danqing** [comment]
Hmm weird. I don't see the ERROR entry in my log. (I have no problem at all with it being a separate record)

**Comment by FZambia** [comment]
Please post steps to reproduce and I'll check it out
