### ISSUE TITLE
[question] Grpc security issues

### ISSUE THREAD

**Issue by sclzzhanghaijun** [centrifugal/centrifugo#315]
**Ask your question**
> Please provide as many details as possible – you will get the answer much faster then!

Grpc can be authenticated by TLS, but we deploy centrifugo in cluster mode, and the front end uses load balancing agent. If we have configured TLS certificate for load balancing, then centrifugo can't connect when TLS is enabled.

**"Show us an example of what you mean!"**
> An example can be useful, otherwise we're left guessing!

centrifugo：server_1(port：8000,10000，tls：true),server_2(port：8000,10000，tls：true),server_3(port：8000,10000，tls：true)
Load Balance：lbs_1(open TLS)--->server_1:8000,server_2:8000.server_3:8000
question：
1、If TLS is enabled for load balancing and TLS is enabled for centrifugo, then websocket will not be connected？
2、Can grpc use load balancing agent？

**Comment by FZambia** [comment]
Hello, do I understand right that you need to enable TLS in Centrifugo only for GRPC while running rest of Centrifugo endpoints over plain HTTP to let LBS terminate TLS?

**Comment by sclzzhanghaijun** [comment]
Yes！

**Comment by sclzzhanghaijun** [comment]
At present, can centrifugo's grpc only use TLS for security authentication? There is no token way.

**Comment by FZambia** [comment]
At moment Centrifugo uses TLS for server authentication and traffic encryption. HRPC client authentication (via TLS or token-based) not supported at all. I think adding possibility to set  custom TLS for GRPC is pretty possible, while adding client authentication requires investigation as I never used it myself.

**Comment by sclzzhanghaijun** [comment]
OK！ thank you.

**Comment by FZambia** [comment]
@sclzzhanghaijun so if I add custom TLS config for GRPC API which will be enabled only for GRPC API - will this help you or not? And one more question - do you need Let's Encrypt integration for GRPC API certificates?

**Comment by sclzzhanghaijun** [comment]
Thank you! I solved the problem of the last time in other ways. I think it is necessary to add TLS certificate configuration to grpc separately. But I also hope you can ask other users if they need it. If most people need it, you can merge this function into the master branch.

**Comment by FZambia** [comment]
Thanks, I agree that this change is useful anyway. Merged it to master, will be available in next release.
