### ISSUE TITLE
[feature] support apikey as field in post body

### ISSUE THREAD

**Issue by ballad89** [centrifugal/centrifugo#317]
**Is your feature request related to a problem? Please describe.**
I am trying to use centrifugo in kubernetes and I can not make successful api calls
This is because of this feature in kubernetes https://github.com/kubernetes/kubernetes/pull/34076 where it strips the `Authorization` header before forwarding to the pod.
Which means I rightly get `401` because centrifugo does not see the header

…

**Describe the solution you'd like**
I propose centrifugo checks for the apikey in 2 places, as a header or in the post body.
something like this 
```
{
    "method": "publish",
     "apikey": "<APIKEY>",
    "params": {
        "channel": "chat", 
        "data": {
            "text": "hello"
        }
    } 
}
```
This ways it checks first in the header, if not found, it checks in the post body.
That way you can choose to either authenticate via header or body field
This is how most APIs check for creds, including Oauth https://tools.ietf.org/html/rfc6749#section-2.3.1

Looking forward to hearing your thoughts

**Comment by FZambia** [comment]
@ballad89 hello! This is unfortunate:) Adding this to command JSON object will require changing all our API libraries to support alternative place to look for API key. What do you think about adding it to URL query param? Looks like this will work with most of our libs out of the box.

**Comment by ballad89** [comment]
@FZambia  thanks for your response.
I was a little concerned about the api_key as part of the URL, but after reading the link you sent and other specs and taking into account the scenario in which the api is used. I agree with you the query param is good enough and would work in my case.
I would appreciate it if this feature could be added

**Comment by ballad89** [comment]
Hello ... thanks for adding this feature ... would you be pushing a new docker container soon ?

**Comment by FZambia** [comment]
@ballad89 https://github.com/centrifugal/centrifugo/releases/tag/v2.2.7
