### ISSUE TITLE
[question] What is the performance of grpc?

### ISSUE THREAD

**Issue by sclzzhanghaijun** [centrifugal/centrifugo#325]
Recently, I tested the performance of GPRC. At present, I open a client, but the concurrency can only reach 1600 / s. If I open more clients, QPS will not increase, sometimes it will decrease. Would you like to ask if the grpc of centrifuge has been tested for performance?

**Comment by FZambia** [comment]
Hello, your question is too broad. Benchmarking is hard and involves many factors - load profile, hardware, network latency etc. You have not even provided a method you called via GRPC API.

I just made a quick experiment on my laptop. With a simple program like this:

```go
var conn *grpc.ClientConn
conn, err := grpc.Dial(":10000", grpc.WithInsecure())
if err != nil {
	log.Fatalf("did not connect: %s", err)
}
defer conn.Close()
c := api.NewCentrifugoClient(conn)

var count int64

go func() {
	var previous int64
	for {
		time.Sleep(time.Second)
		current := atomic.LoadInt64(&count)
		delta := current - previous
		previous = current
		log.Printf("%d req/sec", delta)
	}
}()

for i := 0; i < 16; i++ {
	go func() {
		for {
			response, err := c.Publish(context.Background(), &api.PublishRequest{Channel: "test", Data: []byte("{}")})
			if err != nil {
				log.Fatalf("Error when calling SayHello: %s", err)
			}
			if response.Error != nil {
				log.Printf("Response from server: %v", response.Error.Message)
			} else {
				atomic.AddInt64(&count, 1)
			}
		}
	}()
}

select {}
```

I achieved 32000 requests per second. It must be much more on decent Linux server machine. So if you called PUBLISH - then I suppose you are limited by your client code or client machine resources/limits.

**Comment by sclzzhanghaijun** [comment]
Thank you very much! Yes, at the beginning, my own test method was wrong and it was really efficient.
