### ISSUE TITLE
[bug] config file not detected in docker 

### ISSUE THREAD

**Issue by cdamose** [centrifugal/centrifugo#327]
whenever run docker image using below command 

docker run --ulimit nofile=65536:65536 -e CENTRIFUGO_SECRET=mysecret -e CENTRIFUGO_ADMIN=1 -e CENTRIFUGO_ADMIN_PASSWORD=admin -e CENTRIFUGO_ADMIN_SECRET=admin   -p 8009:8000 centrifugo/centrifugo centrifugo -c config.json

logs :
{"level":"warn","time":"2019-12-21T07:10:58Z","message":"No config file found"}
{"level":"info","time":"2019-12-21T07:10:58Z","message":"starting Centrifugo 2.2.7 (go1.13.4)"}
{"level":"info","time":"2019-12-21T07:10:58Z","message":"config path: /centrifugo/config.json"}
{"level":"info","time":"2019-12-21T07:10:58Z","message":"pid: 1"}
{"level":"info","time":"2019-12-21T07:10:58Z","message":"engine: Memory"}
{"level":"info","time":"2019-12-21T07:10:58Z","message":"gomaxprocs: 2"}
{"level":"info","time":"2019-12-21T07:10:58Z","message":"serving websocket, SockJS, API, admin endpoints on :8000"}

i configured config files , but it throwing error "No config file found"

**Comment by FZambia** [comment]
Hello,  you need to mount directory with configuration file to Docker image:

```
docker run --ulimit nofile=65536:65536 -v /host/dir/with/config/file:/centrifugo -p 8000:8000 centrifugo/centrifugo centrifugo -c config.json
```

**Comment by cdamose** [comment]
still it's throwing same error ,

C:\Users\acd\Desktop\New folder\docker\centrifugo-docker>docker run --ulimit nofile=65536:65536 -v /host/dir/with/config/file:/centrifugo -p 8000:8000 centrifugo/centrifugo centrifugo -c config.json
{"level":"warn","time":"2019-12-21T08:51:15Z","message":"No config file found"}
{"level":"info","time":"2019-12-21T08:51:15Z","message":"starting Centrifugo 2.2.7 (go1.13.4)"}
{"level":"info","time":"2019-12-21T08:51:15Z","message":"config path: /centrifugo/config.json"}
{"level":"info","time":"2019-12-21T08:51:15Z","message":"pid: 1"}
{"level":"info","time":"2019-12-21T08:51:15Z","message":"engine: Memory"}
{"level":"info","time":"2019-12-21T08:51:15Z","message":"gomaxprocs: 2"}
{"level":"info","time":"2019-12-21T08:51:15Z","message":"serving websocket, SockJS, API endpoints on :8000"}

 config file location : C:\Users\acd\Desktop\New folder\docker\centrifugo-docker
i'm running docker command in same directory only.
Config.json:
{
  "secret": "secret",
  "admin_password": "password",
  "admin_secret": "secret",
  "namespaces": [
    {
      "name": "chat",
      "anonymous": false,
      "publish": true,
      "join_leave": true,
      "presence": true,
      "presence_stats": true,
      "history_size": 10,
      "history_lifetime": 60,
      "history_recover": true
    },
    {
      "name": "public",
      "anonymous": true,
      "publish": true,
      "join_leave": true,
      "presence": true,
      "presence_stats": true,
      "history_size": 10,
      "history_lifetime": 60,
      "history_recover": true
    }
  ]
}

**Comment by FZambia** [comment]
Replace `/host/dir/with/config/file` with your real path on your system - that was just an example

**Comment by cdamose** [comment]
Thanks for your quick response and clear explanation
