### ISSUE TITLE
[question] How to get last history seq for channel using http api?

### ISSUE THREAD

**Issue by stbit** [centrifugal/centrifugo#328]
How to get last history seq for channel using http api? I want to check whether new messages have arrived when you open the site between bootstrap data and connecting to the centrifugo.

**Comment by FZambia** [comment]
Hello, at moment `seq`, `gen` and `epoch` fields are only used for client-server protocol and not exposed to server API. In general it can be added to subscribe success context which is now looks like this:

```json
{
    "channel": "$public:chat",
    "isResubscribe": true,
    "recovered": false
}
```

But I am not sure whether this will solve your case or not - you provided almost no info.

**Comment by stbit** [comment]
We have a service with a very thick client. When you first open the site, we get bootstrap data (directories) and connect to websockets (centrifugo). All changes made by the user are done through the http api and sent out via centrifugo (pubsub). It is critically important for us that the messages sent are delivered and the user data is synchronized with the server (history mode is turned on in the centrifuge, 5 minutes). We track the correct sequence using req, if newMessage.req! == lastReq + 1 then we update the user data using the backend. We still have 1 problem or question. If the user goes into sleep mode for 30 minutes, after a centrifuge tries to reconnect but has no new messages (they have timed out), then until new messages appear, we will not determine that the user data is already incorrect. The principle of adding req to the context of the "subscribe" event would allow us to do the lastReq check immediately upon reconnection. Is this event triggered after the restoration of missed messages?

**Comment by FZambia** [comment]
Looks like you are doing the same what Centrifugo already does on server side - it does +1 logic to deal with at most once Redis PUB/SUB delivery nature and periodically synchronizes with Redis to deal with the case when no new messages sent to channel for a long time. In case of any mismatch it disconnects client. On client side you can rely on `recovered` flag provided in subscription success callback - it will be `false` if some messages lost. I suppose it should also cover a situation of long timeout. Am I missing sth or this is a lack of proper documentation?

**Comment by stbit** [comment]
I added the logic of checking for the recovered flag and tried different options with a disconnected connection, in general, everything works well. Thanks so much for the clarification.
