### ISSUE TITLE
[feature] Additional user/info object passed on connect event.

### ISSUE THREAD

**Issue by telemmaite** [centrifugal/centrifugo#332]
**Is your feature request related to a problem? Please describe.**
I am using **centrifugo 2.3** and `proxy_connect_endpoint` with `proxy_connect_timeout`.
In this case centrifugo asks my backend about user auth and it works nicely as now I don\`t have to force and pass my token around in the frontend.

I want my user to subscribe to `user#99` channel on connect.
Before I was using the `info` part of the auth token to get my user id(99) so I can join a user private channel ie. `user#99`
Current backend `/centrifugo/connect` proxy endpoint provides 
```json
{
    "result": {
        "user": "99",
        "info": {
            "firstName": "xxx",
            "lastName": "xxx",
            "companyId": 1
        }
    }
}
```
**but there is no way to access this `info` data on connect.**

---
**Describe the solution you'd like**
Two options I see:
1 add a js-api call like `centrifuge.info()` or `centrifuge.userInfo()`
2 add more context to the context returned with the `on('connect', ctx)` event.

---
**Describe alternatives you've considered**
Workaround is sending the user id in another request, before or just after connect event, then using the user id to create a user private channel with `#`.

**Comment by FZambia** [comment]
@telemmaite hello, thanks for detailed issue.

Looks like there is one more things I forgot to add to initial proxy implementation: possibility to proxy custom data to client. It already exists in protocol and possible with Centrifuge library, with #333 it will be possible to proxy whatever you need to client in connect response.

It's already supported by `centrifuge-js` and will look like this:

```javascript
centrifuge.on('connect', function(ctx){
    console.log(ctx.data);
});
```

So you can put user ID field to this `data` object.

It's a bit more flexible than simply proxying `info` to client side as `info` will be appended to other messages and shown in presence response which is not what you may want.

Will this solve your case?

**Comment by telemmaite** [comment]
Thanks @FZambia. Looks great!
