### ISSUE TITLE
[feature] Proxy headers more options or proxy all

### ISSUE THREAD

**Issue by telemmaite** [centrifugal/centrifugo#334]
**Is your feature request related to a problem? Please describe.**
We are using `distributed tracing` for example https://opentracing.io/, https://zipkin.io/ (https://zipkin.io/pages/architecture.html, https://github.com/openzipkin/b3-propagation)

We have the option to trace request from from frontend > through backend > back to frontend.
This means a few `trace` headers are added, as quoted:

> For example, when an operation is being traced and it needs to make an outgoing http request, a few headers are added to propagate IDs. Headers are not used to send details such as the operation name.
---

**Describe the solution you'd like**
1. Would it be possible to allow proxying  all headers, not just this limited list.
https://github.com/centrifugal/centrifugo/blob/02d489a1ae4280396e4cab97e82cabf091da0215/internal/proxy/http.go#L74
2. Alternatively allow configuration of list of extra headers, like X-B3-TraceId, X-B3-SpanId, X-B3-Sampled etc...

---

**Describe alternatives you've considered**
Missing part of our tracing log for all proxied requests from **centrifugo**, if the headers are not passed our backend will assume it is the first entry point and we will add the headers on the trip back.

**Comment by FZambia** [comment]
@telemmaite yeah, this is reasonable to have. We should not proxy all headers as those can contain a lot of headers that do not have much sense like `Connection: Upgrade`, `Pragma: no-cache` etc, but having a white list of extra headers is helpful.

Please look at #335 - is it ok?

**Comment by telemmaite** [comment]
@FZambia looks great and thank you very much for your effort on this project!

**Comment by FZambia** [comment]
@telemmaite hi, released new version with new proxy features - [v2.3.1](https://github.com/centrifugal/centrifugo/releases/tag/v2.3.1)

**Comment by telemmaite** [comment]
@FZambia thank you! Already using the `data` object with the proxy authentication.
