### ISSUE TITLE
[bug] too many colons in address

### ISSUE THREAD

**Issue by holooloo** [centrifugal/centrifugo#336]
**Describe the bug**
I tried to run Centrifugo (versions 1.8.0 and 2.3.0) in Kubernetes via Deployment.
In both versions i had CrashLoopBackOff with such error:

`[I]: 2020/01/08 18:48:50 Config path: /centrifugo/config.json
[I]: 2020/01/08 18:48:50 Version: 1.8.0
[I]: 2020/01/08 18:48:50 PID: 1
[I]: 2020/01/08 18:48:50 Engine: In memory – single node only
[I]: 2020/01/08 18:48:50 GOMAXPROCS: 4
[W]: 2020/01/08 18:48:50 Running in INSECURE client mode
[W]: 2020/01/08 18:48:50 Running in INSECURE API mode
[W]: 2020/01/08 18:48:50 Running in INSECURE admin mode
[W]: 2020/01/08 18:48:50 Running in DEBUG mode
[I]: 2020/01/08 18:48:50 SockJS url: //cdn.jsdelivr.net/sockjs/1.1/sockjs.min.js
[I]: 2020/01/08 18:48:50 Start serving raw websocket, SockJS, API, admin, web, debug endpoints on :tcp://10.233.24.181:8000
[F]: 2020/01/08 18:48:50 ListenAndServe: listen tcp: address :tcp://10.233.24.181:8000: too many colons in address`

and new versiob 2.3.0

`{"level":"warn","time":"2020-01-08T19:05:04Z","message":"secret is deprecated, use token_hmac_secret_key instead"}
{"level":"info","version":"2.3.0","runtime":"go1.13.5","pid":1,"engine":"Memory","gomaxprocs":4,"time":"2020-01-08T19:05:04Z","message":"starting Centrifugo"}
{"level":"info","path":"/centrifugo/config.json","time":"2020-01-08T19:05:04Z","message":"using config file"}
{"level":"warn","time":"2020-01-08T19:05:04Z","message":"DEBUG mode enabled, see /debug/pprof"}
{"level":"info","time":"2020-01-08T19:05:04Z","message":"serving websocket, SockJS, API, admin, debug endpoints on :tcp://10.233.24.181:8000"}
{"level":"fatal","time":"2020-01-08T19:05:04Z","message":"ListenAndServe: listen tcp: address :tcp://10.233.24.181:8000: too many colons in address"}`

…

**Versions**
> Centrifugo version is <1.8.0 & 2.3.0>
> Client library used is centrifuge-<???> of version <???>
> Operating system is <Centos 7 latest >

...

**Steps to Reproduce**
> How can the bug be triggered?
Centos 7 > Kubernetes Latest > error
…

**Expected behavior**
> What output or behaviour were you expecting instead?
Running pod with Centrifugo
…

**Code Snippets**
> A minimum viable code snippet can be useful! (use backticks to format it).

…

**Comment by FZambia** [comment]
Hello, at first glance this looks like misconfiguration and not a bug in server. Could you show your configuration?

**Comment by holooloo** [comment]
Just found a great solution - customize a port to default 8000

`---
apiVersion: v1
kind: Service
metadata:
  name: centrifugo
  namespace: test
  labels:
    app: centrifugo
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: centrifugo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: centrifugo
  namespace: test
  labels:
    app: centrifugo
spec:
  selector:
    matchLabels:
      app: centrifugo
  replicas: 1
  template:
    metadata:
      labels:
        app: centrifugo
    spec:
      containers:
      - name: centrifugo
        image: centrifugo/centrifugo:1.8.0
        command: ["centrifugo"]
        args: ["-p","8000","-c","config.json"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: centrifugo
          mountPath: /centrifugo/config.json
          subPath: config.json
      volumes:
      - name: centrifugo
        configMap:
          name: centrifugo`

**Comment by FZambia** [comment]
Glad it works. You don't need to set protocol in address btw - you need to set interface ip only. For example:
```
./centrifugo --address 0.0.0.0
```

**Comment by holooloo** [comment]
Kubernetes assigned an IP for me
Thanx for help)
