### ISSUE TITLE
[question] code for benchmark test

### ISSUE THREAD

**Issue by bsr203** [centrifugal/centrifugo#340]
I am so excited to find this library, and meet my needs exactly. To learn how it behaves in a cluster deployment scenario, I would love to see the test setup you used in this benchmark. Can you please let me know if it available freely, or any good opensource example of deployment to Kubernetes.

https://github.com/centrifugal/centrifugo/blob/master/docs/content/misc/benchmark.md

thank you for all the hard work and making this library available
bsr

**Comment by FZambia** [comment]
@bsr203 hello, that benchmark have been run in Kubernetes cluster of company where I currently work. It has some infrastructure and wrappers on top of Kubernetes so I can't give exact instructions on how to run it in other Kubernetes cluster. Though I can share code. As said in docs benchmark used Centrifuge library (not Centrifugo itself). But performance of Centrifugo should be comparable as it's simply based on that library. If you really interested to repeat experiment - sure you will be able to reproduce it in your environment. It will take some time for me to open source it.

Regarding to Kubernetes deployment example: I don't think this is very different to deploying any other software. We have Docker image, you need to describe Kubernetes Deployment and most probably service and that's it. 

There is [helm chart with Centrifugo](https://github.com/helm/charts/tree/master/stable/centrifugo) - but it's not official and I personally never used it - but maybe it will be helpful for you.

**Comment by FZambia** [comment]
Updated previous comment - just realized that I am not sure I can open source full code of that benchmark as it contains some proprietary libraries. But I will try to post relevant client and server parts related to Centrifuge.

**Comment by bsr203** [comment]
Thanks @FZambia I am amazed by the level of effort you are putting into support this. 

I am a programmer, and currently in a need to test distributed pubsub for a go application mainly to deliver notification to clients (web + mobile). I use gRPC for transport and will be deploying to [GKE](https://cloud.google.com/kubernetes-engine/). 

My understanding of cluster deployment and redis is very limited, and thought seeing how you would deploy few centrifugo nodes, and redis server and how they all communicate together. My intention is not to repeat the benchmark experiment, but lean how to deploy as above. Rather than open sourcing the benchmark test setup which may add irrelevant code , I think it may more beneficial if you can do a quick writeup or point me to any resource, where I can try
1. Deploy  few centrifugo nodes
2. Deploy 2 redis server (distributed)
3. extend the chat app, so server push the message to centrifugo 
4. chat client connect to the centrifugo 

thanks again for your time and effort.

**Comment by FZambia** [comment]
These doc sections can hep:
 
https://centrifugal.github.io/centrifugo/server/engines/#scaling-with-redis-tutorial
https://centrifugal.github.io/centrifugo/server/engines/#redis-sharding

**Comment by bsr203** [comment]
Thanks. Closing now, as need to learn and try out a lot.  If you think a need of an advanced / distributed example, please reopen. Thank you.

**Comment by bsr203** [comment]
I am halfway through the docs, and wish a walk though for cloud deployment. Couple of references.

https://github.com/dapr/samples/tree/master/2.hello-kubernetes
https://socketcluster.io/docs/deploying-to-kubernetes/

thanks
