### ISSUE TITLE
[feature] pagination for channels api request

### ISSUE THREAD

**Issue by skyeagle** [centrifugal/centrifugo#341]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is - e.g. "I'm always frustrated when [...]"

We have multiple channels that users are able to subscribe to, ie: 
```
per-user-[digest]
per-location-[digest]
per-company-[digest]
```

The total number of channels is around 5k/node. It leads to a situation when `/channels` API request from the admin panel returns to many results and the page just hangs.

**Describe the solution you'd like**
> What would the feature look like? How would it work? How would it change the API?

It would be nice to have some sort of pagination for that. 

**Describe alternatives you've considered**
> Are there alternatives you've tried, and/or workarounds in-place?

I could not think of any alternative.

---
Thank you for the exciting project! Looking forward to using it!

**Comment by FZambia** [comment]
Hello!

Is this a problem only with web interface or running `channels` API via console for example also results in long response time?

In general `channels` API simply returns all channels that active in broker at moment. I don't think that paginating such a dynamic information will give us proper solution for massive deployments anyway. While we can imagine some sort of pagination with Memory Engine, Redis does not provide this functionality (can only filter list of channels by glob pattern). If you look at `Channels` [method description](https://github.com/centrifugal/centrifuge/blob/v0.4.0/engine.go#L81) in broker interface you will find that it's considered optional.

Could you describe which problem you are trying to solve calling `channels` API in production? Maybe we can think about alternative way to solve it.

**Comment by skyeagle** [comment]
The main concern is that in a case of a much bigger number of channels, somebody could accidentally shutdown a node or multiple nodes while making `/channels` requests through the server's admin panel or by external API client.

Is there any limitation/recommendation on the maximum possible number of channels that could be handled by centrifugo?

**Comment by FZambia** [comment]
> Is there any limitation/recommendation on the maximum possible number of channels that could be handled by centrifugo?

There is no limitation in general - channel as entity is very cheap. I can't say what is the maximum amount possible to achieve. It's ok to have millions of them sharded over different Redis instances. See [benchmark](https://centrifugal.github.io/centrifugo/misc/benchmark/) with more than million of active channels. But I can't say how far someone can go with Centrifugo.

> The main concern is that in a case of a much bigger number of channels, somebody could accidentally shutdown a node or multiple nodes while making /channels requests through the server's admin panel or by external API client.

The simplest solution could be updating docs and option to disable it.

**Comment by FZambia** [comment]
Added a note in 2f95de74b14c376a0fab65dc312b2513f9bd3245

**Comment by skyeagle** [comment]
Thanks for the explanation and fast feedback! Closing this.
