### ISSUE TITLE
[feature] Support Redis cluster?

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifugo#342]
**Is your feature request related to a problem? Please describe.**

At this moment to achieve high availability Centrifugo works with master-slave Redis setups sharding data by channel using client-side sharding. As far as I know many companies already adopted Redis cluster setups. And setting up HA for Redis using Sentinel is not very convenient for them these days.

**Describe the solution you'd like**

My suggestion is to add cluster support. But as soon as PUB/SUB does not scale linearly in Redis Cluster we will still shard data on client side but between several different Redis clusters.

Just an idea at moment - need to validate this concept in terms of possibility to reuse current Lua scripts and PUB/SUB logic. If someone has thoughts and feedback - please share.

**Comment by kevinanew** [comment]
Great idea. This will make centrifugo more easy to use in K8s.

**Comment by FZambia** [comment]
@kevinanew hello, thanks for feedback, I started making prototype in related pull request. Still need time to figure out various nuances and edge cases since I had no practical experience with Redis Cluster before. But it seems to work in general.

**Comment by FZambia** [comment]
Available since v2.5.0 - https://centrifugal.github.io/centrifugo/server/engines/#redis-cluster

**Comment by kevinanew** [comment]
Awesome, I will upgrade to 2.5.0
Appreciate your work.
