### ISSUE TITLE
Return 405 on /api request

### ISSUE THREAD

**Issue by pahuss** [centrifugal/centrifugo#344]
**API eturn 405**
Good time of day. When I try to access the api with php cent, I get the message "cURL error: Failed to connect to localhost port 8000: Connection refused", if I access via the browser, the error is 405. I tried to sort through the settings in different ways, but the result is the same.

> {
  "token_hmac_secret_key": "f751d42f-c663-4322-be4d-a42ec91bf2ff",
  "admin_password": "37b3d1e2-641d-42dd-b544-82664c83b014",
  "admin_secret": "0af61365-ef59-446d-b78e-45e4057ae5e0",
  "api_key": "31497a7c-28ba-40ee-a469-9a2a745f7c76"
}

**Comment by FZambia** [comment]
@pahuss this looks like some sort of your host misconfiguration. Make sure that Centrifugo really started on that port. Check out server logs. Make sure you are using correct server address in phpcent case. Try to reproduce this locally. You can try to ask for help in Centrifugo chat groups (links in readme)
