### ISSUE TITLE
[question] disable point SockJS

### ISSUE THREAD

**Issue by bronte2k7** [centrifugal/centrifugo#345]
Hi
Is it possible to disable an unused point?

thanks

**Comment by FZambia** [comment]
Hello, no - it's not possible at moment. Please describe a problem you came across if you need this to be implemented.

**Comment by bronte2k7** [comment]
Thanks for the answer. This is not a problem. This desire to disable what is not used

P.S. It's my habit

**Comment by FZambia** [comment]
Got it, we can add such option I suppose, though we need to add not only `sockjs_disable` in this case but also `websocket_disable` for SockJS fans and `api_disable` for those who use insecure client-side publishes or publishes over proxy (if we add one some day). As far as I remember these are the only endpoints that we start by default, all other available routes must be explicitly turned on.

For now I suppose you can close access to endpoint on load balancer level.

**Comment by bronte2k7** [comment]
I like it, thanks

P.S. Nginx now hides all unnecessary

**Comment by FZambia** [comment]
@bronte2k7 available in v2.4.0 https://github.com/centrifugal/centrifugo/releases/tag/v2.4.0

**Comment by bronte2k7** [comment]
Hello! thanks a lot
