### ISSUE TITLE
Can i limit the history size per channel ?[question] 

### ISSUE THREAD

**Issue by Iampato** [centrifugal/centrifugo#346]
**Ask your question**
I have over 10 channel i would like to limit the history size per channel

…

**"Show us an example of what you mean!"**
Or is way of clean the history except the last publication from the server code (i am using golang ->gocent)

…

**Comment by FZambia** [comment]
Hello, you can create separate namespaces for different history settings. There is no other way. Regarding to your next question - its not supported, all available methods described in API doc https://github.com/centrifugal/centrifugo/server/http_api/

**Comment by Iampato** [comment]
https://github.com/centrifugal/centrifugo/server/http_api/
page not found

**Comment by FZambia** [comment]
Sorry - https://centrifugal.github.io/centrifugo/server/http_api/

**Comment by Iampato** [comment]
Not cool that the remove history method is not available and its either in the centrifugo admin and the js client
