### ISSUE TITLE
[question] How to publish message via redis

### ISSUE THREAD

**Issue by BatuhanK** [centrifugal/centrifugo#347]
**Ask your question**
When we are using rest api for publishing message to a channel, it produces this redis publish command.

channel: events#test_user_id
data:
```
{"hello": "world"}
```

redis command
```
1582419988.456343 [0 172.17.0.1:39816] "PUBLISH" "centrifugo.client.events#test_user_id" "\x12\x13events#test_user_id\x1a\x13\"\x11{\"hello\":\"world\"}"
```

What I want is, publish messages directly from redis publish command without touching rest or grpc api.
How this json encoded? Seems like it has some prefix?
…

**Comment by FZambia** [comment]
Hello. Publications encoded in Protobuf format, see [this part](https://github.com/centrifugal/centrifugo/blob/v2.3.1/vendor/github.com/centrifugal/centrifuge/engine_redis.go#L1165).

As this is an internal part of server I can't promise anything about backwards compatibility on this level. Also as soon as you enable history option you need a bit more than just PUBLISH to Redis channel. Could you describe why do you want to avoid publishing over API? I understand that using Redis directly will reduce latency a bit and can improve overall publish stability but it should not be real bottleneck on practice and you will still need to retry PUBLISH ops for some messages anyway.

**Comment by BatuhanK** [comment]
Thanks, we don't need history. And you're right it's all about latency and better performance while pushing concurrent events

**Comment by FZambia** [comment]
So you are free to do this on your own risk. Can we close this issue or you need additional information/details?

**Comment by BatuhanK** [comment]
`cent.proto`
```
syntax = "proto3";
enum MethodType {
    PUBLISH = 0;
    BROADCAST = 1;
    UNSUBSCRIBE = 2;
    DISCONNECT = 3;
    PRESENCE = 4;
    PRESENCE_STATS = 5;
    HISTORY = 6;
    HISTORY_REMOVE = 7;
    CHANNELS = 8;
    INFO = 9;
}
message PublishRequest {
    MethodType type = 1;
    string channel = 2;
    bytes data = 3;
}
```

`publish.js`
```js

const protobuf = require('protocol-buffers');
const cent = protobuf(fs.readFileSync(__dirname + '/cent.proto'));

const channel = `user#${data.room}`;
    const centData = messages.PublishRequest.encode({
      type: messages.MethodType.PUBLISH,
      channel,
      data: Buffer.from(JSON.stringify(data.message), 'utf8')
    });
    await redisClient.publish(`centrifugo.client.${channel}`, centData);
```

centrifugo server console error:
```
2020-02-23T18:57:12+03:00 |ERROR| error handling client message error="unexpected EOF"
```

Am I doing something wrong while encoding data?

**Comment by FZambia** [comment]
`data` inside `PublishRequest` must be [Publication type](https://github.com/centrifugal/protocol/blob/master/definitions/client.proto#L62) marshalled to Protobuf as well.

I.e. smth like this:

```
const data = new Publication{data: Buffer.from(JSON.stringify(data.message), 'utf8')}
const channel = `user#${data.room}`;
const centData = messages.PublishRequest.encode({
      type: messages.PushType.PUBLICATION,
      channel,
      data: data
    });
await redisClient.publish(`centrifugo.client.${channel}`, centData);
```
