### ISSUE TITLE
[feature] Migrate to go.mod

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifugo#349]
As it's now a standard production ready way to manage dependencies in Go. This should also simplify building Centrifugo from source code a bit.

The main thing here is to not break release workflow.

**Comment by PatrickKvartsaniy** [comment]
Hello @FZambia ! Here is a PR https://github.com/centrifugal/centrifugo/pull/352
Can you review it?

**Comment by FZambia** [comment]
@PatrickKvartsaniy thanks for a help, just released v2.5.0 based on go mod - had to fix some things in `.travis.yml` because using some other tools modified `go.mod` in CI so git repo was in dirty state (see https://github.com/centrifugal/centrifugo/commit/3c12de644bcd387c47adce04ab0b4d083f4259cd) - but otherwise all good.
