### ISSUE TITLE
Docker image wont start

### ISSUE THREAD

**Issue by averrin** [centrifugal/centrifugo#35]
[F]: 2015/10/13 14:56:50 main.go:179: Unable to locate config file, use "centrifugo genconfig -c config.json" command to generate one

**Comment by FZambia** [comment]
Hi! Which command have you used to run it?

Here is one from docs:
```
docker run -v /your/host/dir/containing/config/file:/centrifugo -p 8000:8000 fzambia/centrifugo centrifugo -c config.json
```

At first glance it seems that you have not provided configuration file to use.

**Comment by averrin** [comment]
Thanks, but you can add this command to readme ;)

**Comment by FZambia** [comment]
Did it helped?

**Comment by averrin** [comment]
Yeah. It wasnt critical for me, but i prefered to notify you.

**Comment by FZambia** [comment]
Yep, thanks
