### ISSUE TITLE
[feature] RPM for Centos 8

### ISSUE THREAD

**Issue by tasselchof** [centrifugal/centrifugo#354]
Installation of RPM through yum on Centos 8 is not working (package not found).

[root@f01 log]# yum -y install FZambia_centrifugo-source
Failed to set locale, defaulting to C.UTF-8
CentOS-8 - AppStream                                                                                                                                                    7.7 kB/s | 4.3 kB     00:00    
CentOS-8 - Base                                                                                                                                                          10 kB/s | 3.8 kB     00:00    
CentOS-8 - Extras                                                                                                                                                       7.6 kB/s | 3.0 kB     00:00    
FZambia_centrifugo                                                                                                                                                      327  B/s | 819  B     00:02    
FZambia_centrifugo-source                                                                                                                                               288  B/s | 819  B     00:02    
Extra Packages for Enterprise Linux Modular 8 - x86_64                                                                                                                   37 kB/s |  33 kB     00:00    
Extra Packages for Enterprise Linux 8 - x86_64                                                                                                                           44 kB/s |  33 kB     00:00    
nginx repo                                                                                                                                                               43 kB/s | 2.9 kB     00:00    
Remi's Modular repository for Enterprise Linux 8 - x86_64                                                                                                                20 kB/s | 3.5 kB     00:00    
Safe Remi's RPM repository for Enterprise Linux 8 - x86_64                                                                                                               17 kB/s | 3.0 kB     00:00    
No match for argument: FZambia_centrifugo-source
Error: Unable to find a match: FZambia_centrifugo-source

**Comment by FZambia** [comment]
Fixed with 76a2502e665a5f742e6eb13462cb76f9a667be3b, package will be available with next release

**Comment by FZambia** [comment]
Done, available since v2.5.0
