### ISSUE TITLE
[feature] Linter

### ISSUE THREAD

**Issue by PatrickKvartsaniy** [centrifugal/centrifugo#355]
It would be nice to have a linter for development and CI. I can add a config and update make file

**Comment by FZambia** [comment]
@PatrickKvartsaniy I think it's a good thing to have. Do you have suggestions on which linter to use and what kind of checks to enable in it? Since I use `golint` during development the code can have some warnings with other linters.

**Comment by PatrickKvartsaniy** [comment]
@FZambia we are using `golint` in our company for development and CI. I think this is a good option to have for everyone. With a good config, it might be very useful

**Comment by FZambia** [comment]
Then I think it should be fine, feel free to send pr - would be nice!

**Comment by FZambia** [comment]
Fixed by #414
