### ISSUE TITLE
[question] Deployment

### ISSUE THREAD

**Issue by TIGRAN02** [centrifugal/centrifugo#356]
I am trying to deploy my own Centrifugo instance to Heroku via the link in your README.md. However, I am getting the following error:
`internal/proxy/connect_handler.go:55:7: undefined: errors.Is
internal/proxy/refresh_handler.go:47:7: undefined: errors.Is
internal/proxy/rpc_handler.go:48:7: undefined: errors.Is
note: module requires Go 1.13
github.com/FZambia/statik/fs
github.com/centrifugal/centrifugo/internal/webui
google.golang.org/grpc/internal/transport
github.com/mattn/go-isatty
github.com/prometheus/client_golang/prometheus/promhttp
github.com/satori/go.uuid
github.com/spf13/cobra
google.golang.org/grpc
golang.org/x/crypto/acme
golang.org/x/crypto/acme/autocert
github.com/ajstarks/svgo
github.com/centrifugal/centrifugo/internal/api
github.com/centrifugal/centrifugo/misc/scripts/logo
github.com/centrifugal/centrifugo/internal/admin
 !     Push rejected, failed to compile Go app.
 !     Push failed`

Could you please suggest what I might be doing wrong?

**Comment by FZambia** [comment]
@TIGRAN02 hi, looks like our recent migration to Go modules broke Heroku build, should be fixed now with 065ccbf4c09671b3241cd2405b9fd999acb39289 - please try again.

**Comment by TIGRAN02** [comment]
@FZambia it is indeed fixed. Thanks a lot!

**Comment by FZambia** [comment]
Can be closed I suppose
