### ISSUE TITLE
Server side private subscription

### ISSUE THREAD

**Issue by adamcollier1** [centrifugal/centrifugo#357]
Hi! Centrifugo really is great.. thanks

The new server side subscription is a good idea, however I am not able to subscribe the user automatically to a private channel? is this correct? or is there something I am missing..

This is the token I am creating.. it works if I change it to **private**, just not $private
`
let obj = {
	channels: ["$private"],
	exp: 0
}
`

Thanks

**Comment by FZambia** [comment]
Hello, what is a use case when you need to use private channels with server-side subscriptions? Do you have different types of subscribers?

Looks like private subscriptions ignored at moment while subscribing on server side.

**Comment by FZambia** [comment]
Fixed in https://github.com/centrifugal/centrifuge/commit/dc52a2c88e1f8ffad143ce1e00d06d2cdf24ac10 - will work in next release

**Comment by adamcollier1** [comment]
Awesome thanks for your work.
