### ISSUE TITLE
[feature] Documentation improvements

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifugo#361]
Based on feedback we collected [Centrifugo docs](https://centrifugal.github.io/centrifugo/) are not complete and hard to understand for developers.

I think it's obvious that we need to improve things here. Since I wrote it myself my vision is a bit blurred and I want to understand what are the main weak points of current docs. Will appreciate help with this.

**Comment by connoryates** [comment]
Adding on to this, I think including a swagger file would be useful

**Comment by FZambia** [comment]
@connoryates thanks!

Looks like it's possible to extract some definitions from our `api.proto` using `protoc-gen-swagger` command from https://github.com/grpc-ecosystem/grpc-gateway. 

```
cd internal/api/
mkdir swagger
protoc --proto_path=$GOPATH/src/github.com/centrifugal/centrifugo/vendor:. --swagger_out=logtostderr=true:./swagger api.proto
```

[Here](https://gist.github.com/FZambia/756f4ab97d166b9e33753e293e634e81) is how the output `api.swagger.json` looks like. I think it can be used to create a proper Swagger spec.

**Comment by FZambia** [comment]
New documentation site for Centrifugo v3 – https://centrifugal.dev
