### ISSUE TITLE
Client to centrifugo publications

### ISSUE THREAD

**Issue by chansdad** [centrifugal/centrifugo#363]
**Ask your question**
> Please provide as many details as possible – you will get the answer much faster then!
Iam planning on using centrifugo where there would be a lot of trusted clients which will publish to centrifugo. Think of mqtt server ..where in iot devices are sending messages - one channel per device.

In your faq you had "Can I publish new messages over websocket connection from client?¶
Centrifugo designed to stream messages from server to client. Even though it’s possible to publish messages into channels directly from client (when publish channel option enabled) - we strongly discourage this in production usage as those messages will go through Centrifugo without any control."
Does this mean iam out of luck ? Iam looking at zeromq and other message servers and came across centrifugo. And really would like to use it for its simplicity and multiple language support as well as good documentation.
…

**"Show us an example of what you mean!"**
> An example can be useful, otherwise we're left guessing!

…

**Comment by FZambia** [comment]
@chansdad - but what is your question?

**Comment by chansdad** [comment]
So my question is basically can I use centrifugo in a use case where lot of clients(25k ) are publishing to their own channels.. ?

**Comment by FZambia** [comment]
Yes, you can if you don't care about any validation, permissions and saving messages to database since published messages will simply go through Centrifugo and your backend never receive them. See `publish` option in docs: https://centrifugal.github.io/centrifugo/server/configuration/#channel-options and most of our clients have `.Publish` method implemented.

**Comment by FZambia** [comment]
Closing, hope I answered your question, btw we have Telegram group (see in docs https://centrifugal.github.io/centrifugo/) if you will need more information
