### ISSUE TITLE
[bug] Proxy calls haven't content-type header

### ISSUE THREAD

**Issue by pafik13** [centrifugal/centrifugo#368]
**Describe the bug**
> A clear and concise description of what the bug is.

I try to use proxy calls, but I am faced with the fact that 'content-type' header does not reach the backend.

**Versions**
> Centrifugo version is <2.4.0>
> Client library used is centrifuge-<js> of version <2.6.0>
> Operating system is <Ubuntu 18.04.4 LTS>

**Steps to Reproduce**
> How can the bug be triggered?

Follow documentation

**Expected behavior**
> What output or behaviour were you expecting instead?

Now, headers on connect event:
```
{
  host: 'localhost:4004',
  'user-agent': 'Go-http-client/1.1',
  'content-length': '157',
  'accept-encoding': 'gzip'
}
```
I expect next:
```
{
  host: 'localhost:4004',
  'user-agent': 'Go-http-client/1.1',
  'content-type': 'application/json',
  'content-length': '157',
  'accept-encoding': 'gzip'
}
```

**Comment by FZambia** [comment]
Hi, this works in a way it was planned to work - I don't think initial WebSocket Upgrade request has this until explicitly set for some reason. Could you describe more why you expect `'content-type': 'application/json'` in headers?

Since we send JSON to your backend I suppose we can set it on Centrifugo level for all proxy requests - but it does not come from client.

**Comment by pafik13** [comment]
> Could you describe more why you expect 'content-type': 'application/json' in headers?

For backend, I tried `expressjs` and `fastifyjs`. Without `'content-type'` I got an empty body in `expressjs`  and I got error `FST_ERR_CTP_INVALID_MEDIA_TYPE` in `fastifyjs`.

I think it is strange when there is a header `'content-length'` without `'content-type'`.

I added `'content-type'` manually and got next:

```
{
  client: '18187286-2fde-4300-97ba-dd4e44925759',
  transport: 'websocket',
  protocol: 'json',
  encoding: 'json',
  data: { userId: 'my-super-user' }
}
```

> Since we send JSON to your backend I suppose we can set it on Centrifugo level for all proxy requests

It looks good.

> but it does not come from client.

I think websocket message doesn't contain headers, but in RPC calls I got same problems with next headers:

```
{
  host: 'localhost:4004',
  'user-agent': 'Go-http-client/1.1',
  'content-length': '157',
  'accept-encoding': 'gzip'
}
```

**Comment by FZambia** [comment]
Got it, then let's add Content-Type `application/json` to all HTTP requests from Centrifugo to app backend.
