### ISSUE TITLE
Secret required error

### ISSUE THREAD

**Issue by andremendonca** [centrifugal/centrifugo#37]
I'm aware that recent release (1.0.0) changed a bit how Centrifugo works. However, when I try to setup it from scratch generating a new config file using `genconfig` I get the following error:

```
$ ./centrifugo genconfig
[F]: 2015/10/26 10:25:47 main.go:368: config error: secret required
```

After getting that error, I manually created a `config.json` file and used `checkconfig`, but I still get the same error even though I defined a secret property in config file:

```
$ ./centrifugo checkconfig
[F]: 2015/10/26 10:48:03 main.go:353: config error: secret required
```

My `config.json` manually created:
```
{
  "secret": "very-long-secret-key"
}
```

When I start Centrifugo server, I don't get any error though.

**Comment by FZambia** [comment]
Hello! Thanks for a report - it's a bug.

I fixed it. And as soon as I did't announced v1.0.0 anywhere I will create v1.0.0 release with fixed binaries later today.

**Comment by FZambia** [comment]
It happened because now it's possible to set secret key via environment variable CENTRIFUGO_SECRET and start Centrifugo without config file for the simplest usage.

**Comment by FZambia** [comment]
@andremendonca just updated binaries in 1.0.0 release, thanks again for opening issue.

**Comment by andremendonca** [comment]
@FZambia no problem at all. I read about the environment variable, thanks for the explanation. I didn't send a fix myself because I've just started with Go Lang but I'm glad I could still help :)

I will update my project binary

**Comment by FZambia** [comment]
I can update release binaries again in the evening as I made several changes I want to be in 1.0.0.

**Comment by FZambia** [comment]
Done! Updated tag and binaries. I've made several changes to reduce memory consumption a bit and deal with stale connections, i.e. connections which join Websocket or SockJS endpoint and do not send `connect` client protocol command. Hopefully release is done now:)
