### ISSUE TITLE
[feature] Reading server requests from AMQP queue

### ISSUE THREAD

**Issue by RuSPanzer** [centrifugal/centrifugo#373]
Hi. 
I have chat backend on a PHP. 

I use backend PHP API for publishing new messages to chanels, and use centrifugo for deliver new messages to all clients on chanel. 

Simple mechanis publication like this:
1. Client send POST request to backend API
2. Backend API save new message to database
3. Backend create RabbitMQ message with a publisher to queue 
4. One of many counsumer listen this queue and making POST request to centrifugo 
5. Centrifugo send new message to target chanel for all clients with a websockets.

But consumer in a PHP is a realy pain. 
I propose that the centrifugo act as a consumer to some AMQP queue and remove 4 step from my scheme.

**Comment by FZambia** [comment]
Hello, sorry but this is out of Centrifugo scope. You can implement AMQP consumer in any language and make it POST messages to Centrifugo API.

Maybe this is a nice idea for external project - i.e. get messages from Rabbit/Kafka/Redis and send them effectively to Centrifugo API.

**Comment by FZambia** [comment]
Closing since no response from op and nothing actionable here.

**Comment by deefdragon** [comment]
@FZambia with the addition of the async consumers in 5.2.0, can this be re-opened? I'm not sure if there are plans to expand the supported async input methods, or if [Benthos](https://centrifugal.dev/blog/2023/08/19/asynchronous-message-streaming-to-centrifugo-with-benthos) is still the "expected" pattern.
