### ISSUE TITLE
[feature] Client authentication for GRPC server API

### ISSUE THREAD

**Issue by unikzforce** [centrifugal/centrifugo#378]
I wanted to connect from a server code to centrifugo and send server api request via grpc, is there any way to configure my server code with some kind of apikey so that i could initiate a secure grpc connection like what you do with http server api? 

An also for js clients.. can i use grpc with an added JWT token? 

How should i do everything with grpc and have a secure environment?

**Comment by FZambia** [comment]
> I wanted to connect from a server code to centrifugo and send server api request via grpc, is there any way to configure my server code with some kind of apikey so that i could initiate a secure grpc connection like what you do with http server api?

Centrifugo only supports server authentication over TLS at moment, nothing implemented in terms of API client authentication. Will having a token in configuration file (like we already have for HTTP API) will be sufficient for your case?

> An also for js clients.. can i use grpc with an added JWT token?

Client-server protocol only works over WebSocket or SockJS, it does not support GRPC.

**Comment by unikzforce** [comment]
Yes sure, I think, I'm not a security expert, but It seems very sufficient to me to just have token like that.

And thanks for Clarification. Could you please kindly mention this in the Documentation.
I was confused sometimes by the capabilities of the clients , specially when I go to the client library github (centrifuge-js for ex) there is a part talking about Protobuf but it doesn't tell that It's not for using inside browsers ( any way I should have guessed that my self because the grpc is not supported natively  by browsers, and grpc-web is not feature complete).
And also Thanks for the Good Software.

**Comment by FZambia** [comment]
> I was confused sometimes by the capabilities of the clients , specially when I go to the client library github (centrifuge-js for ex) there is a part talking about Protobuf but it doesn't tell that It's not for using inside browsers

Actually you can use Protobuf from browser, I mean our Javascript client centrifuge-js can work with Protobuf from browser. Take a look at https://github.com/centrifugal/centrifuge/tree/master/_examples/chat_protobuf - this is an example that communicates with server over binary WebSocket with Protobuf encoded protocol frames.

But Protobuf != GRPC.

**Comment by unikzforce** [comment]
Ooo, I thought You're relying on grpc for browser protobuf based connection. So I was wrong. 
Cool decision though.

**Comment by unikzforce** [comment]
Don't know if you want to close the issue. My Questions are resolved.

**Comment by FZambia** [comment]
@unikzforce welcome, actually all our other clients work over Protobuf (not only centrifuge-js). Though not all clients support all server features at moment (there is a feature matrix inside each client library README). Also keep in mind that SockJS polyfill can't work with Protobuf since it only works with JSON and this can not be changed.

I'll rename this issue a bit and will leave it to track progress on client authentication for GRPC server API. If you decide to use Centrifugo in your projects and absence of any GRPC auth in server API will block you let us know – will try to force this. GRPC API runs on separate port and thus not available to external internet clients, but client auth makes sense even in private network – I agree with this.

**Comment by unikzforce** [comment]
For now, I'll try to access the centrifugo through the DMZ, If we needed an extra layer of security, we would adopt TLS.
But It would be awesome to have an alternative way to secure this api too :)

**Comment by FZambia** [comment]
Opened #380 that adds `grpc_api_key` option.

**Comment by unikzforce** [comment]
Hey there:) thanks a lottt
