### ISSUE TITLE
How i can run it as daemon?

### ISSUE THREAD

**Issue by aleksraiden** [centrifugal/centrifugo#38]
Hi, 

I starting server by command: centrifugo -w --config="/opt/centrifugo/config.json" --log_level="debug" --log_file="/var/log/cintrifugo.log"  but can I run it as daemon? E.g. options -d , for examples? Any idea?

**Comment by FZambia** [comment]
Hello! Centrifugo can not daemonize itself. You can use other daemonize tools such as `supervisord`, `upstart` etc. Depending on operating system and linux distribution you are using.

We are using Centos and run Centrifugo using `supervisord` or just built-in `daemon` function ([init.d](https://github.com/centrifugal/centrifugo/blob/master/extras/rpm/centrifugo.initd#L38))

**Comment by FZambia** [comment]
Helpful [discussion on Reddit](https://www.reddit.com/r/golang/comments/35v5bm/best_way_to_run_go_server_as_a_daemon/)

**Comment by aleksraiden** [comment]
Yea, init.d scripts awesome! Thanks!

**Comment by FZambia** [comment]
You are welcome! There is also [discussion](https://groups.google.com/forum/#!topic/golang-nuts/othxUDO-EoE) in Go mailing list about program daemonization. And general opinion is let external program do this.

**Comment by sl4mmer** [comment]
@aleksraiden if you use Debian/Ubuntu here is init script

```
vagrant@ubuntu-14:/var/www/centrifugo$ cat /etc/init.d/centrifugo
CENTRIFUGO=centrifugo
CENTRIFUGO_ARGS="--config=/etc/centrifugo/config.json --log_file=/var/log/centrifugo.log"
PIDFILE=/var/run/centrifugo.pid
case "$1" in
  start)
    echo -n "Starting Centrifugo"
    start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $CENTRIFUGO -- $CENTRIFUGO_ARGS
    echo "."
    ;;
  stop)
    echo -n "Stopping Centrifugo"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    echo "."
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
        echo "Usage: /etc/init.d/centrifugo {start|stop|restart}"
        exit 1
esac

exit 0


```
