### ISSUE TITLE
[feature] Is it possible to alert my server code, when a client subscribes to any channel?

### ISSUE THREAD

**Issue by unikzforce** [centrifugal/centrifugo#381]
**Is your feature request related to a problem? Please describe.**
In my web server code I wanted to stay Alert and React when a client started to subscribe to a channel.

the thing is In my hypothetical case, The channel is just for that user ( for example `users#userId12`), and the name of that channel is not yet known to me, so I have to be notified that `users#userId12` is being contacted by some client. once I got that event, I could react accordingly.

So is it possible to come up with a mechanism so that when a channel is being subscribed upon, a code in my web server could react to that event?

and if it is possible, Can it have two functionalities? one for listening to subscription events of all channels, and one for listening to subscription events to an specific channel?

**Comment by unikzforce** [comment]
for example one possibility could be this: Centrifugo could be told that upon some event happening to some channels ( channels could be targeted via an array of regexes [ "users#*", "*chat$*" , ...]) tell the server via server api.

**Comment by FZambia** [comment]
I suppose [subscribe proxy](https://centrifugal.github.io/centrifugo/server/proxy/#subscribe-proxy) already does what you want?

**Comment by unikzforce** [comment]
Yes, Thanks I didn't know that.
but unfortunately It does not support `private` or `user-limited` channels yet.

Is there any plan for that?

**Comment by unikzforce** [comment]
Is there anything special about them? I mean if centrifugo and the server which is consuming events, were in the same Trust Zone, would there be any security problem?

**Comment by FZambia** [comment]
You are free to just not use those types of channels in your app. Subscribe proxy allows backend to decide whether client has permission to subscribe or not. Private channel already signed by backend since subscription contains token at the moment of subscription, user-limited channel just belongs to one user usually - so nothing to check actually.

**Comment by unikzforce** [comment]
In my case I have to use `user-limited` channels and in the server code I wanted to react to that.
I mean If user `A` subscribed to channel `users#A` then, I wanted the server to notice and do something with respect of that event.

**Comment by FZambia** [comment]
You can use any other channels and make whatever rules you need on proxy level since you have user ID. I.e. imitate the same what user-limited channels provide.

**Comment by FZambia** [comment]
Closing, since nothing actionable left here.
