### ISSUE TITLE
[feature] Official Grafana dashboard

### ISSUE THREAD

**Issue by jekakm** [centrifugal/centrifugo#383]
Would be nice, if centrifugo has official dashboard for visualize metrics from prometheus

**Comment by FZambia** [comment]
@jekakm hello, just want to mention that I took this into work. While making this dashboard I found some things to be improved so our official Grafana dashboard will fully work with Centrifugo >= 2.7.0 I suppose, but it will be quite simple to adapt for current earlier Centrifugo versions too after importing.

**Comment by FZambia** [comment]
Published first revision [in Grafana dashboards registry](https://grafana.com/grafana/dashboards/13039). As I already mentioned this dashboard should only be used with Centrifugo >= 2.7.0.  To adapt it to previous versions one can import it and change `centrifugo_` prefix to `centrifuge_` prefix for some metrics.

@jekakm maybe you can check it out and validate that dashboard works fine with Centrifugo v2.7.0 and not only my local Prometheus/Grafana setup?

**Comment by jekakm** [comment]
@FZambia Yeah, it's works on my k8s cluster with prometheus-operator (I just change singlestat panels to stat because I have grafana 6.4.3, but in 7 version it will work fine as I know). Thank you!

**Comment by FZambia** [comment]
Great! Then I suppose we can close this issue 🎉  Thanks for opening - it was always in my mind, but looking on thumb ups count – many devs have been waiting for it. Already added link to dashboard into [Centrifugo monitoring docs chapter](https://centrifugal.github.io/centrifugo/deploy/monitoring/#grafana-dashboard).

**Comment by FZambia** [comment]
Actually looks like Singlestats panel deprecated and it's recommended to use Stat panels as [said here](https://grafana.com/docs/grafana/latest/panels/visualizations/stat-panel/). Will try to figure out the best way to deal with it.

**Comment by FZambia** [comment]
The current dashboard already uses Stat panel instead of Singlestat, so I suppose you changed Stat to Singlestat actually, not vice versa :) Now good to close I hope

**Comment by sentabi** [comment]
We'll move to 2.7 in next few weeks from 2.5 and use the official version

![grafana](https://user-images.githubusercontent.com/203196/93856795-c1f42480-fce3-11ea-8209-52e1108d734a.png)

**Comment by dbeneker** [comment]
Just tested it with centrifuge lib 0.11.1, works perfectly 👍

**Comment by itismoej** [comment]
How can I contribute to the official dashboard?

@FZambia
