### ISSUE TITLE
Cannot get history or presence

### ISSUE THREAD

**Issue by curioustolearn** [centrifugal/centrifugo#384]
**Describe the bug**
> A clear and concise description of what the bug is.
I was trying out the example described in quickstart section of the documentation. Some things, such as sending the messages, worked well. However, 'history' did not work. I got the following response in the admin panel:

```Request:
{
    "method": "history",
    "params": {
        "channel": "channel"
    }
}
Response:
{
    "error": {
        "code": 108,
        "message": "not available"
    }
}
```

**Versions**
`centrifugo version` returns 
`Centrifugo v (Go version: go1.15)`

**Client library**

`https://cdn.jsdelivr.net/gh/centrifugal/centrifuge-js@2.6.2/dist/centrifuge.min.js`

**Operating system**

Mac OSX Mojave

**Comment by FZambia** [comment]
Hello, you should enable history and presence per channel namespace. See [channel options in docs](https://centrifugal.github.io/centrifugo/server/channels/#channel-options).

For top-level channels this means you should add:
```
{
    ...
    "presence": true,
    "history_size": 100,
    "history_lifetime": 300
}
```
– to configuration file. I recommend create separate `namespace` for channels where history and presence enabled – this is more flexible in the end.

**Comment by curioustolearn** [comment]
Thank you so much. I realized the need to enable presence later, but did not know I had to do that for history too. Thank you so much for creating centrifugo. I hope to use it.

**Comment by FZambia** [comment]
Welcome, join our community chats in Telegram or Discord
