### ISSUE TITLE
[question] Does centrifugo support the publishing and receiving of voice messages?

### ISSUE THREAD

**Issue by yoyomule** [centrifugal/centrifugo#389]
Does centrifugo support the publishing and receiving of voice messages?

**Comment by FZambia** [comment]
@yoyomule hello.

Centrifugo supports sending and receiving arbitrary binary data over WebSocket transport with Protobuf protocol. I suppose it's possible to send audio/video by chunks and use codes on a client side to play media on a device. Though if you look through the internet – almost nobody does audio sending/streaming over WebSocket. Most APIs upload audio/video files over a special endpoint on a server, then send a text notification with a file URL to a user so a user can click `play` button and listen for a voice data streamed from your server.

If you want to stream voice from one user to another in real-time without a server and additional file storage involved then maybe you need WebRTC technology for this. You can do this with Centrifugo but I can not provide any guidance on how to do it – this requires some research and coding, it won't be the most optimal way to deal with a task anyway so I don't have plans moving into this area with Centrifugo.

If you decide to experiment with sending audio data through Centrifugo channels and end up with some example – please share, this is curious, though I still recommend you to avoid doing this and go convenient way if possible.
