### ISSUE TITLE
[feature] Aerospike as a backend

### ISSUE THREAD

**Issue by evstratbg** [centrifugal/centrifugo#392]
Any thoughts about aerospike as a backend?

Airspike is ACID based, relatively fast and easier to cluster, than redis

**Comment by FZambia** [comment]
@evstratbg hello. I've heard a lot of good reviews about Aerospike 👍

Have you done at least basic analysis on how Aerospike fits internal Centrifugo design? Centrifugo uses Redis not as simple key/value storage but also relies on PUB/SUB and Stream data structure for messaging and Sorted Sets for presence. Does Aerospike provide these things? I quickly searched but have not found analogues in Aerospike (even basic PUB/SUB).

See also related discussion in #45

**Comment by evstratbg** [comment]
> @evstratbg hello. I've heard a lot of good reviews about Aerospike 👍
> 
> Have you done at least basic analysis on how Aerospike fits internal Centrifugo design? Centrifugo uses Redis not as simple key/value storage but also relies on PUB/SUB and Stream data structure for messaging and Sorted Sets for presence. Does Aerospike provide these things? I quickly searched but have not found analogues in Aerospike (even basic PUB/SUB).
> 
> See also related discussion in #45

Extremly fast dived headlong into Centrifugo, so completely forgot about pub/sub :( 

Thanks!
