### ISSUE TITLE
[question] How can we use the admin website with a url path prefix

### ISSUE THREAD

**Issue by othke** [centrifugal/centrifugo#397]
**How to make the admin website work on a root prefix url**
> I use centrifugo on a K8S cluster. we use an ingress controller and the centrifugo server (https, wss) is accessible on this path:
https://my-fqdn.com/centrifugo-bridge
I think (but not sure) that since this [commit](https://github.com/centrifugal/centrifugo/commit/14da33867aa1d25e577b198e1feb3dbefb263888#diff-73df3e51d9f3dad73034f8fc2c80de0a3c3de2b20864a511d79747e62a07c752) the assets of the webui are relative to the root path. 

…

**"This is what the browser try to load"**
> Web Admin cannot get styles.css and bundle.js. There is a HTTP 404 while loading the assets with https://my-fqdn.com/bundle.js instead of https://my-fqdn.com/centrifugo-bridge/bundle.js

…

**Comment by FZambia** [comment]
Hello, @othke .

Assets have always used relative paths in Centrifugo v2, there were no changes related to it.

I suppose you can try to use `rewrite` directive to make Centrifugo think it works on root prefix. [Here is an example rewrite annotation](https://github.com/centrifugal/helm-charts/blob/master/charts/centrifugo/values.yaml#L52) for Nginx ingress.
