### ISSUE TITLE
application.handlePublishCommand: inconsistent error

### ISSUE THREAD

**Issue by klauspost** [centrifugal/centrifugo#4]
In `handlePublishCommand` there is the following code:
```Go
	channelOptions := app.getChannelOptions(p.Name, channel)
	if channelOptions == nil {
		resp.Error = ErrNamespaceNotFound
		return resp, nil
	}

	// Client disconnects here...
	err := app.publishClientMessage(p, channel, data, nil)
	if err != nil {
		resp.Error = ErrInternalServerError
	}
```

1) app.getChannelOptions is actually called in `app.publishClientMessage`, so there is no real need for it here. 
2) If the client disconnects around the added comment `ErrInternalServerError` will be returned instead of `ErrNamespaceNotFound`.

**Comment by klauspost** [comment]
There are a lot of similar 'race', where the same operation will return different results based on random timing. The practice of just returning `ErrInternalServerError` could perhaps be improved.

**Comment by FZambia** [comment]
Thanks, do you mean a situation when channel options changed between those calls?

**Comment by klauspost** [comment]
Yes - maybe it isn't possible (I cannot really say 100%).

**Comment by FZambia** [comment]
This is possible theoretically - I just asked to make sure I understood a problem correctly.

**Comment by FZambia** [comment]
I refactored a bit.

But it seems that still can be race as `getChannelOptions` return a pointer to `ChannelOptions` 

```
// getChannelOptions returns channel options for channel using structure
func (app *application) getChannelOptions(projectKey, channel string) *ChannelOptions {
	app.RLock()
	defer app.RUnlock()
	namespaceName := app.extractNamespaceName(channel)
	return app.structure.getChannelOptions(projectKey, namespaceName)
}
```

Maybe this method should be rewritten as:

 ```
// getChannelOptions returns channel options for channel using structure
func (app *application) getChannelOptions(projectKey, channel string) ChannelOptions {
	app.RLock()
	defer app.RUnlock()
	namespaceName := app.extractNamespaceName(channel)
	return *app.structure.getChannelOptions(projectKey, namespaceName)
}
```

I  am a bit confused - will we get a copy of ChannelOptions in this case?

**Comment by klauspost** [comment]
Yes, I think that is the only safe way to do so, since it no longer holds the lock to the data once it returns. With the latter, you copy it before you return it, and you are safe.

**Comment by FZambia** [comment]
OK, thx, will make this change

**Comment by klauspost** [comment]
(you can of course still return a pointer, but since I assume it cannot be nil, there isn't much point)
```
// getChannelOptions returns channel options for channel using structure
func (app *application) getChannelOptions(projectKey, channel string) *ChannelOptions {
    app.RLock()
    defer app.RUnlock()
    namespaceName := app.extractNamespaceName(channel)
    b := *app.structure.getChannelOptions(projectKey, namespaceName)
    return &b
}
```

**Comment by FZambia** [comment]
Btw it can be `nil` in case when namespace not found...Maybe returning second return boolean value (`found`) will make sense

**Comment by FZambia** [comment]
@klauspost , please, look at current code - is problem solved?
