### ISSUE TITLE
Error: proto: wrong wireType = 2 for field Method

### ISSUE THREAD

**Issue by vadimkozak** [centrifugal/centrifugo#402]
Hi there, we like centrifugo and now using it in several projects, thanks. But now we're finally decided to migrate from the first to the second version (v2.8.0 to be precise [centrifugo_2.8.0_linux_amd64.tar.gz](https://github.com/centrifugal/centrifugo/releases/download/v2.8.0/centrifugo_2.8.0_linux_amd64.tar.gz))
Right after starting the application, we got that log: 
```
Nov 21 10:09:07 centrifugo centrifugo[9615]: {"level":"error","error":"proto: wrong wireType = 2 for field Method","time":"2020-11-21T10:09:07Z","message":"error handling control message"}
Nov 21 10:09:10 centrifugo centrifugo[9615]: {"level":"error","error":"proto: wrong wireType = 2 for field Method","time":"2020-11-21T10:09:10Z","message":"error decoding control command"}
Nov 21 10:09:10 centrifugo centrifugo[9615]: {"level":"error","error":"proto: wrong wireType = 2 for field Method","time":"2020-11-21T10:09:10Z","message":"error handling control message"}
Nov 21 10:09:13 centrifugo centrifugo[9615]: {"level":"error","error":"proto: wrong wireType = 2 for field Method","time":"2020-11-21T10:09:13Z","message":"error decoding control command"}
Nov 21 10:09:13 centrifugo centrifugo[9615]: {"level":"error","error":"proto: wrong wireType = 2 for field Method","time":"2020-11-21T10:09:13Z","message":"error handling control message"}
```

OS Version: 
`PRETTY_NAME="Ubuntu 20.04.1 LTS"`

Is there some additional OS packages we need to install?

**Comment by FZambia** [comment]
Hello!

No extra packages required.

Please provide steps to reproduce – I don't see these errors when I start Centrifugo. This can be specific to the fact that you still using Centrifugo v1 on the same Redis – but control protocol can be incompatible.

**Comment by vadimkozak** [comment]
We just downloaded binary file i mentioned and run it using

**Comment by FZambia** [comment]
@vadimkozak hello, have you tried a separate Redis instance?

**Comment by vadimkozak** [comment]
Hi @FZambia , we just tried it and it works great. Thank you for help!
