### ISSUE TITLE
[question] Publishing from the command line

### ISSUE THREAD

**Issue by ashokgelal** [centrifugal/centrifugo#403]
With `publish` set to `true` is it possible to send a message from the command line? I don't know if it is possible to use `curl`. I was looking at using [websocat](https://github.com/vi/websocat).

**Comment by FZambia** [comment]
Hello, Centrifugo [has HTTP API](https://centrifugal.github.io/centrifugo/server/http_api/), so you can use `curl` to publish. Like this:
```
curl --header "Content-Type: application/json" \
  --header "Authorization: apikey aaaf202f-b5f8-4b34-bf88-f6c03a1ecda6" \
  --request POST \
  --data '{"method": "publish", "params": {"channel": "mychannel", "data": {"value": 1}}}' \
  http://localhost:8000/api
```

Replace `aaaf202f-b5f8-4b34-bf88-f6c03a1ecda6` with your Centrifugo API key.

**Comment by ashokgelal** [comment]
I'm sorry, I should have been more clearer. Yes, I'm aware of the API but I'm looking more similar to a client publishing a message. The HTTP API would have worked but I can't distribute the API key. This client is trusted but can't trusted enough to have a API key. It could however have a JWT token. I wish there was an HTTP API to send a message without the API key.

**Comment by FZambia** [comment]
Got it, I suppose there are several options:
1) Use one of Centrifugo clients that work nice on backend side, for example https://github.com/centrifugal/centrifuge-go - it's possible to write client based on it and build binary that can be executed from console.
2) Write your own simple client in any language and works over client protocol: https://centrifugal.github.io/centrifugo/transports/protocol/
3) Provide the client you are talking about an endpoint on your service to which client can send messages (over HTTP for example) and on your backend you can then republish this to Centrifugo API if access is allowed. So you basically can have any type of auth in this case between a client and your backend.

I am not sure about `websocat` but maybe it's possible to implement client protocol with it (but you need to establish connection, then send Connect frame over websocket, then wait for response, then subscribe on channel, and then publish). With `curl` it's not possible at all I suppose.

**Comment by ashokgelal** [comment]
> Provide the client you are talking about an endpoint on your service to which client can send messages (over HTTP for example) and on your backend you can then republish this to Centrifugo API if access is allowed. So you basically can have any type of auth in this case between a client and your backend.

This is what I was trying to avoid and hence I mentioned "with publish set to true" :) For my use case I don't need to make a trip to the backend as there is nothing that needs to be saved or validated. A client will just say "Hey, I executed this command and here's a huge output payload" and the other client's will display the payload and that's it.

I guess the second option might work. I was sure that it couldn't just be me who has run into this use case so wanted to ask.

BTW, I really appreciate your quick replies. Thank you!

**Comment by FZambia** [comment]
Welcome:) If you will have any questions with implementation – you can ask them in Telegram or Discord Centrifugo groups (links in readme). Closing since I think nothing actionable left here.
