### ISSUE TITLE
[question] Publish to specific user

### ISSUE THREAD

**Issue by car1ot** [centrifugal/centrifugo#406]
**Ask your question**. Please provide as many details as possible – you will get the answer much faster then!

I need to publish personal info to each auntificated user. How to do this?

**"Show us an example of what you mean!"**. An example can be useful, otherwise we're left guessing!

...

**Comment by FZambia** [comment]
Hello, you can subscribe each user to a personal channel and publish data to that channel when needed. For example [user-limited channels](https://centrifugal.github.io/centrifugo/server/channels/#user-channel-boundary) should be good enough for this task.
