### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by car1ot** [centrifugal/centrifugo#408]
**Ask your question**. Please provide as many details as possible – you will get the answer much faster then!
...

**"Show us an example of what you mean!"**. An example can be useful, otherwise we're left guessing!

...

I have nginx server with upstream (multiple backend app instances).  How to make centrifugo proxy connection requests to upstream, but not for exact app instance (balance load between apps)?

**Comment by FZambia** [comment]
Hello, in almost the same way you do this for external HTTP requests – i.e. by setting proxy endpoint to load balancer endpoint - Nginx in your case. You may need to configure special upstream for Centrifugo if you need custom behaviour on load balancer level.
