### ISSUE TITLE
[question] will there be env var for namespaces as "CENTRIFUGO_namespaces"?

### ISSUE THREAD

**Issue by MuslimBeibytuly** [centrifugal/centrifugo#409]
**Ask your question**. Please provide as many details as possible – you will get the answer much faster then!

hi, will there be env var for namespaces as "CENTRIFUGO_namespaces"?

**"Show us an example of what you mean!"**. An example can be useful, otherwise we're left guessing!

It's needed for me to not build own image with config for ci services

**Comment by FZambia** [comment]
Hello, it's already possible to set namespaces over env:

```console
CENTRIFUGO_NAMESPACES='[{"name": "ns1"}, {"name": "ns2"}]' ./centrifugo
```

`CENTRIFUGO_NAMESPACES` should be a valid JSON string that represents namespaces array.

**Comment by MuslimBeibytuly** [comment]
@FZambia thank you, it works just fine!:) is it available somewhere in official docs?

**Comment by FZambia** [comment]
Welcome! No - but it is definitely worth adding, lets keep this issue open till we add this.

**Comment by FZambia** [comment]
Done in 59852ef9c55be762224d7b7fa97cb747c4ec9de0, @MuslimBeibytuly thanks for pointing - this is really important to be described.
