### ISSUE TITLE
[question] Load balancer

### ISSUE THREAD

**Issue by car1ot** [centrifugal/centrifugo#426]
**Ask your question**. Please provide as many details as possible – you will get the answer much faster then!

Centrifugo 2.8.0
Nginx proxy server
Ubuntu screen

**"Show us an example of what you mean!"**. An example can be useful, otherwise we're left guessing!

I am running 3 Centrifugo instances in screen with redis, option "engine": "redis".  But if there is many API requests to centrifugo with publish. But when there is many many publish requests, my app start working slowly... How to start load balancer in centrifugo?

**Comment by FZambia** [comment]
Hello, you can put your app behind any load balancer and point Centrifugo to it.

**Comment by car1ot** [comment]
> 
> 
> Hello, you can put your app behind any load balancer and point Centrifugo to it.

Do I need to run only one centrifugo instance, or I need to make 2-3 copies running to load balance between them?

**Comment by FZambia** [comment]
If you are asking about Centrifugo load balancing then you may have the following scheme:

```
application_user
    └── load_balancer
        ├── centrifugo01
        ├── centrifugo02
        └── centrifugo03
```

I am not sure I am answering correct question - try to be more precise if you want a better answer.

**Comment by car1ot** [comment]
> 
> 
> If you are asking about Centrifugo load balancing then you may have the following scheme:
> 
> ```
> application_user
>     └── load_balancer
>         ├── centrifugo01
>         ├── centrifugo02
>         └── centrifugo03
> ```
> 
> I am not sure I am answering correct question - try to be more precise if you want a better answer.

Yes, I have the exact model. Is this model correct?
Also, do I need to make this scheme for working with api:
```
application_server
    └── load_balancer
        ├── centrifugo01
        ├── centrifugo02
        └── centrifugo03
```

Or I can left this:
```
application_server
       └── centrifugo01
```

**Comment by FZambia** [comment]
It's up to you – in general I'd put Centrifugo API endpoint behind load balancer too, just make sure API endpoint not available from wild internet (it's not too critical if protected by API key but just a good thing to do).

Using load balancer here is nice for Centrifugo API availability - if you loose centrifugo01 then load balancer can proxy API requests to  centrifugo02, centrifugo03.

**Comment by car1ot** [comment]
> 
> 
> It's up to you – in general I'd put Centrifugo API endpoint behind load balancer too, just make sure API endpoint not available from wild internet (it's not too critical if protected by API key but just a good thing to do).
> 
> Using load balancer here is nice for Centrifugo API availability - if you loose centrifugo01 then load balancer can proxy API requests to centrifugo02, centrifugo03.

Okay, got it, thanks. But if I don't need avaliability if one centrifugo errored? If I, for example, have 20k concurrent users online, do I need to scale, or centrifugo scales between cpu cores?

**Comment by FZambia** [comment]
> If I, for example, have 20k concurrent users online, do I need to scale, or centrifugo scales automatically between cpu cores?

Centrifugo runs on all available CPU cores by default.

it's impossible to say how many Centrifugo instances you may need for your load profile - this is very specific, there are many factors (not only the number of concurrent connections).

Some known insights about resource usage described in [FAQ](https://centrifugal.github.io/centrifugo/faq/).
