### ISSUE TITLE
[bug]  http: Accept error: accept tcp accept4: too many open files; retrying in 640ms 

### ISSUE THREAD

**Issue by car1ot** [centrifugal/centrifugo#429]
Hello, I am using the last version of centrifugo with nginx proxyfiing.
I made `unlimit -n 200000`.
There is error, when there is a lot of new connections (>500). Got an error `[WRN] http: Accept error: accept tcp [::]:8000: accept4: too many open files; retrying in 640ms`.
What to do? How to fix this?

**Comment by FZambia** [comment]
Hello,

This does not seem like a bug – looks like you have not tuned an open file limit in the correct way.

You can check limits for a running process using on Linux:

```
cat /proc/$PID/limits
```

(replace $PID with Centrifugo process ID).

Depending on how and where you run Centrifugo a way to tune an open file limit can vary. Make sure you tuned it persistently,  and for the correct user that runs Centrifugo.
