### ISSUE TITLE
[question] Auth JWT user id

### ISSUE THREAD

**Issue by car1ot** [centrifugal/centrifugo#430]
I am providing JWT token to centrifugo with the following data: `{ clientUserId: number }`.
I have private channel in centrifugo config:
```
{
    "name": "private",
    "anonymous": false
}
```

I need to identify user connection with JWT token user id and connect clients this way: centrifugo.connect("private#" + clientUserId).

But there is "permission denied". How to compare JWT `clientUserId` with channel connection path exact user id?

**Comment by FZambia** [comment]
Hi, I am not sure what you are trying to achieve - in you example you are using user-limited channel (with #), but asking about private channels (starting with $).

I suppose you need user-limited channel. If yes - then Centrifugo will compare user ID automatically when subscription being created. The format of JWT is defined and described in docs - https://centrifugal.github.io/centrifugo/server/authentication/ - Centrifugo expects user ID to be passed in `sub` claim. So you can not just use `clientUserId` for this.

**Comment by FZambia** [comment]
If you still have questions try to ask in our communities in Discord or Telegram
