### ISSUE TITLE
[question] Asynch Server API

### ISSUE THREAD

**Issue by AlexeyChuhrov** [centrifugal/centrifugo#440]
Currently we have two options to publish message into Centrifugo - HTTP and gRPC:
https://centrifugal.github.io/centrifugo/server/http_api/
https://centrifugal.github.io/centrifugo/server/grpc_api/

Both options offer synchronous communications, hence it affects service avialability making the publish request. Any backend service making the request through Centrifugo Server API must wait for response to continue working

So, for now, if I want to make things asynchronous, I need something like Bridge Service in between. And the resulting flow will look something like this:
Backend Service puts the message in message brocker (amqp, kafka, etc.) -> Bridge Service gets the message from the queue and sends the request to Centrifugo. The downside is increased latency.

The question is:
Is it viable approach I suggest here if I don't want to make blocking API calls to Centrifugo? 
Or do you have any plans to provide the asynchronous API functionality in future?

**Comment by FZambia** [comment]
@AlexeyChuhrov hello.

There was a similar feature request before: https://github.com/centrifugal/centrifugo/issues/373. And Centrifugo v1 had sort of this over Redis queue.

In general I'd like to avoid this pattern in Centrifugo core. Couple of reasons:

* This increases maintenance scope, which I'd like to keep as small as possible. I believe what you suggest is possible to implement as an external tool
* I am not sure how to deal with error handling or not actual message delivery in this case. Imagine a situation when Kafka consumer stopped consuming for a while, number of messages in queue will grow - then as soon as things go normal will be sent to subscribers. In some cases this can be problematic and I don't have ready advice on how to properly deal with this (I think it's possible with some sort of idempotency on client side but it's not very obvious)
* You still need to wait response from queue system that message queued (which I believe also synchronous)
