### ISSUE TITLE
[feature] Centrifugo subscribe api

### ISSUE THREAD

**Issue by aryan340** [centrifugal/centrifugo#443]
I have been reading the server http documentation and got to know that the subscribe api is not supported.

However, I need to implement such a feature for dynamic subscriptions. Any alternatives to this at the moment?
Why isnt the feature supported yet?

Thanks a lot!

**Comment by FZambia** [comment]
Hello, could you describe what is this feature about? Because otherwise I think we can discuss different things.

**Comment by aryan340** [comment]
Hello @FZambia 
so here centrifugo has an unsubscribe api, which allows the server to unsubscribe clients.
```js
{
    "method": "unsubscribe",
    "params": {
        "channel": "CHANNEL NAME",
        "user": "USER ID"
    }
}
```
I was wondering if there was a subscribe api in the same way, so that we can add users to channels dynamically when needed.
Something like this.
```js
{
    "method": "subscribe",
    "params": {
        "channel": "CHANNEL NAME",
        "user": "USER ID"
    }
}
```

**Comment by aryan340** [comment]
Heres an use case.
Users can be part of objects called boxes.
Everytime a user joins a box, they have to be subscribed to the channel associated with the box. When they leave the box, they have to unsubscribe from the particular channel.

I would like the subscribe part to be handled by the server, because we only know when the user joins the box from the server.

How would I implement this?

**Comment by aryan340** [comment]
I think #367 is related.

**Comment by FZambia** [comment]
Yep - #367 is exactly about this, it's planned for Centrifugo v3 and I already have this API working in my early v3 builds. It's a bit hard to introduce this in terms of Centrifugo v2 since it involves some tedious backporting work I'd like to avoid.

> Everytime a user joins a box, they have to be subscribed to the channel associated with the box.

Just a tip - in general this is still possible with client-initiated subscriptions because you can notify client about everything over a personal channel.
