### ISSUE TITLE
Centrifugo v3: the work has been started

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifugo#447]
Hello! After a 2.5 years of Centrifugo v2 life cycle looks like we approach a time for Centrifugo v3 🎉 

There are several cool ideas in my head – some are definitely useful, some still need to be evaluated more. I'll try to share soon - here or in our community channels.

The work has already been started and the current release target is **end of summer**.

## Centrifugo v3 should be client protocol compatible (mostly)

Some deprecated things will be removed (seq/gen fields for example) and maybe minor cosmetic JSON changes - the important thing is to keep mobile applications working due to long and painful update cycle. I believe that the current client protocol is good enough to keep for v3.

I am planning to change the default behaviour of history call - it won't receive all publications by default, but going to provide an option to turn on old behaviour until clients migrate to new API.

## Centrifugo v3 should be feature compatible

Existing features should stay and it should be possible to migrate any existing application that works with Centrifugo v2 to v3. There will be some configuration option changes on backend, some craft will be removed.

## Centrifugo v3 can have different license and PRO version

Since project is big enough and requires more and more time to maintain I am trying to evaluate a way to make Centrifugo development sustainable. This means that I can proceed with an idea of having Centrifugo Pro version with additional features on top of base version. The alternative way over [Opencollective organization](https://opencollective.com/centrifugal) did not work well (I believe mostly because I have to put more effort into this initiative but don't really have enough time and energy for it). So going to try another direction.

Also, I am considering moving from MIT to AGPL v3 license for Centrifugo v3, **please contact me directly over email** if you have concerns about this. This is not a final decision yet but I don't see real downsides for a project in making this move at the moment.

## Do you have any proposals for v3?

If you have any ideas - please share here (or feel free to do it over mail, community rooms), this is the right time – even if the idea won't be implemented it can point Centrifugo to some direction I never thought about myself, or I'll be able to foresee the design for extending Centrifugo in the future.

Appreciate any feedback. Thanks, guys.

**Comment by matpuk** [comment]
Hello!

I have two ideas:

1. Multitenancy: different tenants can't subscribe or send messages to channels of other tenants on Centrifugo side without involving of any of proxies.
2. Nested namespaces support.

**Comment by FZambia** [comment]
> Multitenancy: different tenants can't subscribe or send messages to channels of other tenants on Centrifugo side without involving of any of proxies.

Not sure I'll be able to implement this. Multitenancy if not done right can lead to anti-patterns when one tenant affects another one. See some related discussion in #395. I still believe that multitenancy should be solved by infrastructure. There are several software examples (for example Redis) where builtin multitenancy resulted in many problems. So tenants must be isolated, not really possible to do for v3.

> Nested namespaces support.

Could you show an example of what you mean?

**Comment by matpuk** [comment]
> > Nested namespaces support.
> 
> Could you show an example of what you mean?

Currently, as far as I understand, I can't declare namespace inside a namespace to get something like "ns1:ns2:chat" and inherit some settings from ns1 by ns2. For example, I can declare proxies in ns1, inherit them in ns2 but add additional settings like 'only subscriber can send to a channels', etc.

**Comment by FZambia** [comment]
> Currently, as far as I understand, I can't declare namespace inside a namespace to get something like "ns1:ns2:chat" and inherit some settings from ns1 by ns2. For example, I can declare proxies in ns1, inherit them in ns2 but add additional settings like 'only subscriber can send to a channels', etc.

This makes sense, I am not sure we want `ns1:ns2:chat` though - I think we can still have `ns2:chat` name but inherit options from ns1 since we know its parent on Centrifugo side – I don't think allowing client to construct channel with different namespaces is a good idea.

**Comment by si3nloong** [comment]
@FZambia thank you for making this library, I would like to contribute + maintain this open source, but I think I need to study this library first before that, any material or docs can I go thru?

**Comment by FZambia** [comment]
@si3nloong hello, link to documentation is https://centrifugal.github.io/centrifugo/ - I think the best you can help when starting with Centrifugo is write a tutorial on how to integrate your favorite framework/stack with it to deliver real-time updates to client.

**Comment by FZambia** [comment]
A new documentation site is in progress:

https://user-images.githubusercontent.com/1196565/123224028-1417df80-d4da-11eb-88cb-d745d734d420.mp4

**Comment by longlonghands** [comment]
Hi Alexander,
Does license change affect the centrifuge library? I know the risk of SaaSification and AGPL prevention, but I wanted to know if there is any other concern. because with AGPLing centrifuge libraries you prevent using centrifuge as a library in a closed source service.
am I right?

**Comment by FZambia** [comment]
@longlonghands all libraries will be MIT, I am only thinking about AGPL for Centrifugo but I am still have no final decision to be honest.

**Comment by FZambia** [comment]
Beta 1 release just published: https://github.com/centrifugal/centrifugo/releases/tag/v3.0.0-beta.1

**Comment by FZambia** [comment]
For those who subscribed on this issue: tomorrow we schedule a community meeting where insights of Centrifugo v3 will be first shared. Join any of our community to find out a link to Zoom event.

**Comment by FZambia** [comment]
Docs work in progress, video contains just finished migration chapter - so you can look at what exactly will be changed in v3. This migration chapter does not include new features - those will be in separate blog post. Sorry for a quality - had to reduce video size to embed on Github.


https://user-images.githubusercontent.com/1196565/126752269-6df762c2-4069-425a-9bd3-ab2bef98c1ad.mp4

**Comment by FZambia** [comment]
Just deployed https://centrifugal.dev which is a site for Centrifugo v3 and ecosystem. Please note, that this is still a work in progress and subject to change.

**Comment by zorca** [comment]
What about user events? Like Pusher events:
`var channel = pusher.subscribe('my-channel');
channel.bind('my-event', function(data) {
  alert('Received my-event with message: ' + data.message);
});`
In our SAAS app we need subscribe on custom events, not only 'publish' or another built-in events. This feature will improve compatibility with Laravel and maybe we can use Laravel Echo as JS-client.

**Comment by zorca** [comment]
I'll explain. Now we have a server broadcaster for Laravel: https://github.com/denis660/laravel-centrifugo , which sent events throw data variable:
`{"result":{"channel":"tenant.public:2b28#$%#$%#$%#$%","data":{"data":{"socket":null,"event":"App\\Events\\UserVisitedTimetable"},"offset":25}}}` But we dont have Centrifugo driver for Laravel Echo  for bind to this events.

**Comment by zorca** [comment]
Maybe it is possible to embed such functionality into the default js-client: https://github.com/centrifugal/centrifuge-js ?

**Comment by FZambia** [comment]
> What about user events? Like Pusher events

There are a couple of reasons why I don't want to add this:
1. This is an extra complexity for client libraries which already are complex enough and hard to maintain
2. I don't see a clear path on how to integrate this with channel history (offset handling, history calls) - since this looks like an additional level of multiplexing

If we find answers on these two questions then `event` should become first-class protocol citizen and all publish APIs should have a way to set event.

I think the best way for now is use small wrapper over centrifuge-js and send `event` inside data payload where you can control things in a way you need for a specific solution.

**Comment by zorca** [comment]
> > What about user events? Like Pusher events
> 
> There are a couple of reasons why I don't want to add this:
> 
>     1. This is an extra complexity for client libraries which already are complex enough and hard to maintain
> 
>     2. I don't see a clear path on how to integrate this with channel history (offset handling, history calls) - since this looks like an additional level of multiplexing
> 
> 
> If we find answers on these two questions then `event` should become first-class protocol citizen and all publish APIs should have a way to set event.
> 
> I think the best way for now is use small wrapper over centrifuge-js and send `event` inside data payload where you can control things in a way you need for a specific solution.

Thank you for the clarification. We will try to develop such wrapper for centrifuge-js.

**Comment by FZambia** [comment]
Centrifugo [v3.0.0 beta 2](https://github.com/centrifugal/centrifugo/releases/tag/v3.0.0-beta.2) released recently. There is a link to the latest migration guide draft.

Still hope to release v3 in the end of summer.

**Comment by FZambia** [comment]
Centrifugo v3 released 🎉  [Introduction blog post](https://centrifugal.dev/blog/2021/08/31/hello-centrifugo-v3)
