### ISSUE TITLE
Share where and how you are using Centrifugo

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifugo#448]
If you are using Centrifugo in one of your projects in production environment and it's not a secret could you please share this information here?

Why this is important? Because this can help newcomers to find out some existing projects already using Centrifugo, also this is simply very interesting to me as a server author. Hope you understand how difficult it is to collect feedback and can help me with this. While I know several companies using Centrifugo (like ManyChat, several Mail.Ru projects etc), I'd like to have a place where users can share this sort of information publicly. My plan is to keep this issue open.

To make things more structured please follow the following template:

1. Project name, link (really optional), short description, project features Centrifugo is used for.
2. Centrifugo setup details - installation method, which client connectors are used, application backend language.
3. Some stats you can share - max number of connections, number of messages published in a minute etc.
4. Anything else you wish to add to points above.

Would anyone like to start?

**Comment by mcroni** [comment]
1. Payslar Payroll, http://payslar.com/ , A fully automated online payroll software for SMEs in Ghana , Used for notifications and chat.
2. Binary on VPS , I used the JS centrigo module
3.  200 max connections, 400 messages per minute

**Comment by mcroni** [comment]
1. Mybitstore , http://mybitstore.com/ ,An online marketplace that provides fast and secure ways to purchase bitcoin with both local and international payment methods, Used centrifugo for notifications and chat.
2. Binary on VPS , I used the JS centrigo module
3. more than 200 max connections, more than 3000 messages per minute

**Comment by russiansmack** [comment]
1. Patio Chat App, Chat app for college students
2. NLB w/ ECS Fargate, everything is in typescript
3. 400-600 active, with 2x-3x spikes in connections count. 800k pubs an hour at peak

**Comment by FZambia** [comment]
Thanks for everyone who wrote about use cases - really appreciate this ❤️  The lack of feedback is sth that should be addressed somehow in OSS community.

But looks like the idea of having an issue to track use cases does not work well in general – this is unfortunate but I understand why this happens. Closing and will try to search for better alternatives.
