### ISSUE TITLE
Publishing via RPC causes ECONNREFUSED

### ISSUE THREAD

**Issue by SimonHausdorf** [centrifugal/centrifugo#450]
I am trying to publish hundreds of messages per second via HTTP RCP.

My request is simple:
```javascript
  fetch('http://xx:8000/api', {
    method: 'post',
    body:    JSON.stringify(body),
    headers: { 'Content-Type': 'application/json', 'Authorization': 'apikey ' + api_key },
  }).catch(err => console.error(err));;
```

I increased the open file limit, however, I am not sure if this is causing my problem. The error I get it

```
FetchError: request to http://xx:8000/api failed, reason: connect ECONNREFUSED xx:8000
```

Debug log shows this
```
2021-05-22 07:03:27 [DBG] http request addr=xx:52465 duration=0.080919 method=POST path=/api status=200
2021-05-22 07:03:27 [DBG] http request addr=xx:52504 duration=0.135358 method=POST path=/api status=200
2021-05-22 07:03:27 [DBG] http request addr=xx:64952 duration=0.116246 method=POST path=/api status=200
2021-05-22 07:03:27 [DBG] http request addr=xx:52507 duration=0.200511 method=POST path=/api status=200
2021-05-22 07:03:27 [DBG] http request addr=xx:64962 duration=0.108599 method=POST path=/api status=200
```

I realized that addr is using different ports, could it be that my system is running out of available ports?
The open file count for the centrifugo process is 9.

It takes a few seconds until the error appears. Then a few messages make it through and a few are stuck with `ECONNREFUSED`. It kind of sound like an open file problem but as said, the count is 9.

**Comment by FZambia** [comment]
Hello, my first guess would be the ephemeral ports problem (on client side), but not really sure. Could you give me the entire script and instructions to reproduce - I'll try to run it on my machine?

**Comment by SimonHausdorf** [comment]
just a short dirty example.

```javascript
const http = require('http')
var api_key = 'api key';

function publish({channel, data}) {
  const body = JSON.stringify({
    "method": "publish",
    "params": {
        "channel": channel, 
        "data": data
    }
  });
  
  const options = {
    hostname: 'SERVER HOST',
    port: 8000,
    path: '/api',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Content-Length': body.length,
      'Authorization': 'apikey ' + api_key
    }
  }
  
  const req = http.request(options, res => {
  })
  
  req.write(body)
  req.end()
}

const body = {
  "foo": "bar",
}

setInterval(() => publish({channel: 'news', data: body}), 1);
```

**Comment by FZambia** [comment]
I suppose it's not unexpected with this script - every millisecond you are creating a new request thus client runs out of resources at some point (this may be CPU, file descriptors). I think you better use futures or `await` and create requests one after another in a loop. If you want to increase load on a server then create more workers which send requests in a loop. I.e. in pseudocode:
```
async func publishInLoop() {
   while true {
     await publish()
   }
}

CONCURRENCY_LEVEL = 10;

for i := 0; i < CONCURRENCY_LEVEL; i++ {
    publishInLoop(); // i.e. run many functions each publishing and waiting for result.
}
```

Also you can benchmark Centrifugo with load generator tools. For example with `wrk`:

Create file `publish.lua`:

```
wrk.method = "POST"
wrk.body   = '{"method": "publish", "params": {"channel": "index", "data": 1}}'
wrk.headers["Content-Type"] = "application/json"
```

Run Centrifugo without API key required:

```
./centrifugo --api_insecure
```

Run wrk:

```
wrk -s publish.lua http://localhost:8000/api -d 10s -t 10 -c 40
```

**Comment by SimonHausdorf** [comment]
I have to admit it was a stupid way to test. However, now we have it here for other people which do the same like me :)

Closing it!

**Comment by FZambia** [comment]
ha-ha, np - I did the same myself once.
