### ISSUE TITLE
Please help with tls

### ISSUE THREAD

**Issue by andrconstruction** [centrifugal/centrifugo#451]
After I include in a config tls, clients connecting properly, but a request to localhost:8000/api from localhost return the bad request 400, should I change endpoint with https protocol or how to allow a server send the publish command to centrifugo without tls.

centrifugo config :

{
  "v3_use_offset": true,
  "token_hmac_secret_key": "********-****-****-****-*********",
  "admin_password": "********-****-****-****-*********",
  "admin_secret": "********-****-****-****-*********",
  "api_key": "********-****-****-****-*********",
  "allowed_origins": ["*"],
  "tls": true,
  "tls_key": "/certs/cert.key",
  "tls_cert": "/certs/cert.crt"
}

when I remove tls all work as expected

**Comment by FZambia** [comment]
Resolved in Telegram group, the reason - request have been issued to http, while it should be https.
