### ISSUE TITLE
Packaging for fedora/centos

### ISSUE THREAD

**Issue by Sulverus** [centrifugal/centrifugo#46]
Idea.
It's possible to update centrifuge packaging policy:
1. Update RPM spec to use `git describe --long` to get version and release number
2. Build all packages in travis-ci using cloud [build](https://github.com/tarantool/build)
3. Create free repository in packagecloud.io ([example](https://packagecloud.io/tarantool/1_6))
4. Probably add tests runs directly in docker containers (to run test for each os)
now we support centos 6/7, fedora 20-23

How it works: https://travis-ci.org/tarantool/tarantool/builds/96720534
Results: https://packagecloud.io/tarantool/1_6

**Comment by rtsisyk** [comment]
You can take our RPM/DEB specs as an example:
https://github.com/tarantool/modulekit/

**Comment by Sulverus** [comment]
@rtsisyk, probably we need to add go language support in docker images

**Comment by FZambia** [comment]
Thanks for suggestion! I asked for custom free plan for open-source project on packagecloud.io - waiting for answer from them

**Comment by FZambia** [comment]
Just got an email with great news from packagecloud.io - 5GB of storage without package limits - more than enough I think. So we can keep going here:)

**Comment by FZambia** [comment]
@Sulverus @rtsisyk I almost done with this in #70 , I don't use cloud build, just building in travis using fpm and push to packagecloud.io - please look maybe you have comments, there could be lots of caveats. I also decided to support only linux distributions for this moment that Digital Ocean offers for droplets - assuming those are the most popular for server machines now.
