### ISSUE TITLE
[feature] replace encoding/json with jsoniter

### ISSUE THREAD

**Issue by kokizzu** [centrifugal/centrifugo#460]
**Is your feature request related to a problem? Please describe.**

no, just want to squeeze a bit of performance

**Describe the solution you'd like**.
> https://github.com/json-iterator/go

```
import jsoniter "github.com/json-iterator/go"

var json = jsoniter.ConfigCompatibleWithStandardLibrary
json.Unmarshal(input, &data)
```

**Comment by cristaloleg** [comment]
Just curious: any info about how much time is spent in json?

**Comment by FZambia** [comment]
> Just curious: any info about how much time is spent in json?

It's significant. Heavily depends on concrete operation executed, here is an example where optimized encoding/decoding results into 2x overall server speedup of calling history API - https://centrifugal.dev/docs/pro/performance#history-http-api

**Comment by FZambia** [comment]
Addressed by Centrifugo v3 – client JSON protocol is much faster.  Some additional details can be found in [introduction blog post](https://centrifugal.dev/blog/2021/08/31/hello-centrifugo-v3).

For API and proxy fast JSON encoding/decoding is a [Centrifugo PRO feature](https://centrifugal.dev/docs/pro/performance).
