### ISSUE TITLE
[question] Notify backend worker a new channel has been opened

### ISSUE THREAD

**Issue by clmno** [centrifugal/centrifugo#461]
I'm building a whatsapp like chat app (realtime & offline first) and would want the client to `GET` historic chat messages it missed when it was offline.

## Question
1. Can we notify when a new channel is created. I.e when a client subscribes to a channel and a new channel is created.

### An example

1. Assume 3 clients `Client A`, `Client B` and `Client C`
2. Redis, a worker, centrifugo
    ```
    (online) Client A -----
                           |
    (online) Client B ----- ----- centrifugo ----- worker ----- redis streams
                           |
    (offline) Client C -----
    
    
    * Centrifugo channels at the moment - clientA , clientB
    * There is not active channel for clientC as it is offline.
    ```
3. Clients A and B are online and Client C is offline. And so current active channels are `clientA`, `clientB`.
4. Worker is connected to channels `clientA`, `clientB`
4. Client A creates a message locally (with a UUID) and sends it to the backend
5. Worker - 2 types of workers `listener` and `sender`
    - `listener` worker receives the message as it is subscribed to all channels
    - `listener` worker adds message to redis stream
    - `sender` worker gets to know new messages are in redis stream
    - `sender` worker gets list of active clients and sends message to all active clients
6. Offline client connects
    ```
    (online) Client A -----
                           |
    (online) Client B ----- ----- centrifugo ----- worker ----- redis streams
                           |
    (online) Client C -----
    
    
    * Centrifugo channels at the moment - clientA , clientB, clientC
    ```
7. `sender` worker gets notified of a new channel creation and so checks if there are any pending messages to be send (using ID in redis stream).
8. `sender` worker sends missed messages to Client C

## Question
1. Can we notify when a new channel is created. I.e when a client subscribes to a channel and a new channel is created.

**Comment by FZambia** [comment]
Hello!

Without diving too deep into your application scheme – have you seen a [Subscribe Proxy](https://centrifugal.github.io/centrifugo/server/proxy/#subscribe-proxy) feature? It will call a configured endpoint as soon as client subscribes to a channel. It will be called for every subscription attempt though, not only the first one (I don't see a way to call some hook on the first subscribe only – that's racy and hard in distributed case).

**Comment by clmno** [comment]
> It will call a configured endpoint as soon as client subscribes to a channel.

This is perfect. When a client disconnects the channel is also closed (as I understand). And when it is back online it will subscribe to the channel again. So this feature seem to be perfect (as from what I understand) as it proxies new subscriptions to an endpoint which can trigger the a sync messages from redis stream event.

Thank you

**Comment by FZambia** [comment]
Welcome!
