### ISSUE TITLE
[question] Possible to ignore sending a message to a specific user within a channel?

### ISSUE THREAD

**Issue by garrensweet** [centrifugal/centrifugo#469]
Basically, title.

I'm trying to replicate functionality that Ably and Pusher provide where it's possible to send a message to a channel, but prevent a user (for instance, the current user) from receiving the message.

The use case for this is to publish updates made to an entity by the current user to all other users. 

Pusher/Ably do this by accepting a `socket` value which is the unique Socket ID assigned by the connection event. Centrifugo does provide that, so I'm wondering if there's a tie-in somewhere that can be made to replicate this functionality.

I've checked the centrifugo source but I'm not finding anything that would prevent a specific Socket ID from receiving a message.

Thanks!

**Comment by FZambia** [comment]
Added this information to [FAQ](https://centrifugal.dev/docs/faq/index#any-way-to-exclude-message-publisher-from-receiving-a-message-from-a-channel).

**Comment by FZambia** [comment]
Closing - given comments outlined here and information added to FAQ it seems that we won't add sth like this to Centrifugo. Current approach while being not very handy at first glance leads to a better app design at the end.
