### ISSUE TITLE
[feature] Proxy URL configuration per namespace

### ISSUE THREAD

**Issue by matpuk** [centrifugal/centrifugo#477]
Hello!

Currently, it is possible to configure proxy URL on a global config level only. This makes some Centrifugo usages hard to implement.

For example, I have ns1 for some telemetry events and ns2 for chat. I have two microservices and want to direct subscribe requests and published messages to them depending on a channel's namespace. There is no way to do this using Centrifugo only.
I need to implement some 'smart' proxy service which will proxy Centrifugo proxy calls depending on request payload (or setup nginx with lua scripting enabled and do 'smart' part there). This adds unnecessary complexity or implicit behavior to an app architecture.

How about to make Subscribe, Publish and RPC proxies configurable on namespace level?

**Comment by FZambia** [comment]
Hello! Yep, seems reasonable to have. Someone already asked about this in community chat.

One note is that RPC calls do not have namespace as they are not related to channels. RPC calls have `method` field - so we need to configure different RPC endpoints based on method prefix maybe. Do you already need RPC proxy to different endpoints or having publish and subscribe per namespace will be enough for now? Just trying to understand the priority as RPC endpoint configuration will require a bit different implementation.

**Comment by matpuk** [comment]
Hello!

Publish & subscribe proxies will be enough for now.

**Comment by FZambia** [comment]
@matpuk hi, check out #478 - still requires work but would be awesome to get a feedback on things.

**Comment by matpuk** [comment]
> @matpuk hi, check out #478 - still requires work but would be awesome to get a feedback on things.

Hello!

- The overall change looks very complicated. I thought that you just let us write 'proxy_subscribe_endpoint/proxy_publish_endpoint' options inside namespace definition. I understand, that it will force us to copy-paste those options with the same values to different namespaces in some cases, but I'm ok with this.
- What is the purpose of the new proxy configuration "type" property?

**Comment by FZambia** [comment]
> The overall change looks very complicated. I thought that you just let us write 'proxy_subscribe_endpoint/proxy_publish_endpoint' options inside namespace definition.

Unfortunately, it's not backwards compatible in terms of how namespacing currently works. Because we also have root (default) namespace and it already has an option with this name – and it's global endpoint at the moment. Thus we can't add this behavior without breaking existing logic (without additional flag at least).

Second – the next addition users will ask about would be possibility to configure different timeouts and different headers for proxies in different namespaces. This pr allows doing this.

> What is the purpose of the new proxy configuration "type" property?

This will allow more explicit proxy configuration in the future if we'll be able to make this configurable over the database.

**Comment by alex-tedeev** [comment]
too much complicated

**Comment by FZambia** [comment]
> too much complicated

@alex-tedeev I provided a reasoning why it was implemented in this way, your comment does not add any value to a discussion. If you have a better proposal which solves all things I mentioned in a more simple way keeping all properties of current pull request (i.e. backwards compatible, custom headers per namespace, avoid namespace option pollution) then write it here until pr is merged.

**Comment by FZambia** [comment]
Current pr also allows not only setting custom headers per namespace, but also avoid sending Cookie headers in all proxy requests except `connect`, for example. Since after connect the ID of user is known and sent by Centrifugo in proxy request payload.

**Comment by matpuk** [comment]
> > The overall change looks very complicated. I thought that you just let us write 'proxy_subscribe_endpoint/proxy_publish_endpoint' options inside namespace definition.
> 
> Unfortunately, it's not backwards compatible in terms of how namespacing currently works. Because we also have root (default) namespace and it already has an option with this name – and it's global endpoint at the moment. Thus we can't add this behavior without breaking existing logic (without additional flag at least).
> 
> Second – the next addition users will ask about would be possibility to configure different timeouts and different headers for proxies in different namespaces. This pr allows doing this (in normalized form and without polluting namespace with options).
> 
> > What is the purpose of the new proxy configuration "type" property?
> 
> This will allow more explicit proxy configuration in the future if we'll be able to make this configurable over the database.

@FZambia Thanks for the explanation. The proposed solution is more robust, agree. Waiting for it :)

**Comment by FZambia** [comment]
Remember about this, hopefully will be able to finish soon (mostly dev testing and docs left).

**Comment by FZambia** [comment]
I think all set up – will release today or tomorrow.

**Comment by FZambia** [comment]
[v3.1.0](https://github.com/centrifugal/centrifugo/releases/tag/v3.1.0) with granular proxy mode just released.

**Comment by hugohaggmark** [comment]
@FZambia do I understand this correctly that `connect` and `refresh` configuration is a top-level configuration? So there is no way to configure `connect` and `refresh` per namespace? 
Thanks

**Comment by FZambia** [comment]
@hugohaggmark hello, it's possible to describe granular connect and refresh proxies (to use different headers for example), but you can only set one connect proxy and one refresh proxy on configuration top-level. As they act without any channel context. So you understand right.

**Comment by hugohaggmark** [comment]
> @hugohaggmark hello, it's possible to describe granular connect and refresh proxies (to use different headers for example), but you can only set one connect proxy and one refresh proxy on configuration top-level. As they act without any channel context. So you understand right.

@FZambia thanks for quick reply, do I just use `connect_proxy_name` in my namespaces like the example below?
```json
{
  ...
  "granular_proxy_mode": true,
  "proxies": [...],
  "namespaces": [
    {
      "name":"dev",
      "connect_proxy_name": "http://localhost:9000"
    },
    {
      "name":"prod",
      "connect_proxy_name": "https://abc.com"    
    },
 ]
}
```

**Comment by FZambia** [comment]
No, again - connect and refresh proxy do not relate to channel namespaces, you can't configure them per namespace - it simply does not make sense in Centrifugo.

**Comment by hugohaggmark** [comment]
> No, again - connect and refresh proxies do not relate to channel namespaces, you can't configure them per namespace - it simply does not make sense in Centrifugo. When I say "granular" - I mean [Granular proxy mode](https://centrifugal.dev/docs/server/proxy#granular-proxy-mode)

Gotcha, thank you again for a swift answer 🙏
