### ISSUE TITLE
[bug] HTTP method HistoryRemove is not documented

### ISSUE THREAD

**Issue by matpuk** [centrifugal/centrifugo#480]
**Describe the bug**. A clear and concise description of what the bug is.

HTTP method HistoryRemove (api.go:552) is not documented in both v2 & v3.
It was introduced in https://github.com/centrifugal/centrifugo/issues/127 .

...

**Versions**

Centrifugo version is v2 & v3

**Steps to Reproduce** How can the bug be triggered?

Search the docs. No such method in HTTP API docs.

...

**Expected behavior** What output or behaviour were you expecting instead?

Document this method.

**Comment by FZambia** [comment]
Thanks!

Fixed by https://github.com/centrifugal/centrifugal.dev/commit/f978d3dae8c31e2d97c0b013d3448858037e1487

Regarding v2: only critical bug fixes will be backported to v2 branch.
