### ISSUE TITLE
[bug] TLS handshake error from XXX.XX: remote error: tls: unknown certificate

### ISSUE THREAD

**Issue by mukulgoyalbuilder** [centrifugal/centrifugo#482]
**Describe the bug**. Getting TLS handshake error, while calling Centrifuge.default_client.publish("channel_name", event)

...

**Versions**

Centrifugo version is 1.7.3
Client library used is centrifuge-<???> of version <???>
Operating system is <???>

**Steps to Reproduce** How can the bug be triggered?

...

**Expected behavior** What output or behaviour were you expecting instead?

...

**Code Snippets** A minimum viable code snippet can be useful.

```
Your code here.
```

**Comment by FZambia** [comment]
Hello, Centrifugo v1 is not supported for a long time.

You can try to ask for help in our community rooms. But you definitely need to provide a better description of problem as it's impossible to guess what you are doing looking at poor info like this.
