### ISSUE TITLE
[question] Is "Proxy to backend" feature suited for this use case ?

### ISSUE THREAD

**Issue by nmorel** [centrifugal/centrifugo#484]
Hello,

My team and I are currently looking to speed up our communications between clients.  
Some feature require to send lots of messages with no persistence and it's not an issue if we lose some messages.  
But other feature require persistence and it's crucial not to lose messages.  
In both usage, we want to authenticate the user and validate what he send to the others.  

The publish proxy seems appropriate at first. Our proxy can handle validation of the message, update it if needed and even persist data.  But after some test to validate the robustness of the solution, we stumbled on some issues.   

If the proxy is getting slow to answer and a client send messages faster than the proxy can answer, the messages are queued and after a while, the client is disconnected (the websocket is closed) and the remaining messages are never sent to the proxy and the other clients.  
We tried to put high timeout duration on proxy, on ping, remove ping and other configuration we could find.  
Is there some kind of internal timeout that closes the connection to the client if its messages are queued for too long ?

Also, when a client has messages published but in queue before going through the proxy, if he leaves, the messages in queue are lost.  

Writing this last issue, I may have my answer :)   
It seems the "Proxy to backend" is ok when the messages are expendable but not when you can't lose any message published.
But maybe you have some inputs ?

**Comment by FZambia** [comment]
Hello

This all is pretty abstract.

If you publish to a channel from a client then you can wait until publish response from a server received to prevent flooding a channel with tons of messages. You can also have parallel publishing, but avoid unlimited concurrency when publishing.

Centrifugo is a user-faced pub/sub server, so sending more than 60 messages per second towards one channel does not make sense as client device won't keep up with a rate and will be simply hot.

What you described is expected, there are lots of different timeouts and disconnect reasons. For example when client queue exceeds 1 mb client is disconnected as slow.

You can also try to publish over http/grpc API. Publishing performance can be different - expect thousands of publishes per second, but again, there is no sense to try sending lots of messages to one channel and one client. Again - Centrifugo designed in a way that messages go to frontend app which can mostly process up to 60 msg per sec.

If you need to process thousands of messages per channel - then this seems like a backend infrastructure task - use systems designed for parallel message processing. Like Kafka.

**Comment by nmorel** [comment]
Thanks for your time and answer !  
Instead of one solution for two different problems, we will use direct publish from client when we need to send lots of messages and a special backend infrastructure for the other cases.  

And yes, no need to send more than 60 msg per sec :+1:  
We were testing with a 30 msg/s rate but we will probably go a bit slower.
