### ISSUE TITLE
What is the best way to send initial message to new connected users?

### ISSUE THREAD

**Issue by mehrdd** [centrifugal/centrifugo#492]
Hi,

What is the best way to send initial message to new connected users?
I my case, i have a json file and want to send this data to new connecting users.
I now some ways but i was wondering is there any straightforward way to do this?

Thanks.

**Comment by FZambia** [comment]
Hello, from the minimum info I know I can suggest to look at connect proxy `data` result field: https://centrifugal.dev/docs/server/proxy#connect-proxy. Or the same `data` for subscriptions: https://centrifugal.dev/docs/server/proxy#subscribe-proxy.

You can also issue RPC request to the backend upon connection to Centrifugo (with [RPC proxy](https://centrifugal.dev/docs/server/proxy#rpc-proxy)) or just call your backend via HTTP to load initial data.

**Comment by mehrdd** [comment]
I guess the "proxy-to-backend" is a good way to do what i'm trying to accomplish..
Thanks.
