### ISSUE TITLE
[question] Getting history

### ISSUE THREAD

**Issue by v1lev** [centrifugal/centrifugo#493]
Hello! I'm trying to setup and get messages history. I read the docs, tried to tune the config, and still can't get the response like in the [docs](https://centrifugal.dev/docs/server/server_api#history)
I can't get if I'm blindly missing something really important so I came here with this question and will be grateful for help.
...
What am I doing:
1. Connect user to centrifugo via websocket
2. Subscribe user to a channel and send some messages
3. Confirm that the messages have been received
4. Making request to get history
5. Here I expect to see the messages sent but there are no publications in the response.

My config: 
```
{
<...>

"engine": "redis",
"log_level": "debug",
"presence": true,
"presence_stats": true,
"history_size": 50,
"history_ttl": "720h",
"recover": true,
"namespaces": [
{
 "name": "public",
 "same history settings as above"
}]}
```

 Sample response:
```
{"result":{
"publications": [],
"epoch": "1639402969",
"offset": 20
}}
```
I tried both memory and redis engine, played a bit with config, the response is the same: the offset changes but publications are always empty. What am I missing?
...

**Comment by v1lev** [comment]
Just wrote this and found actual issue: I set limit 0 in the request, so it was returning 0 messages. I'm closing the issue.

**Comment by v1lev** [comment]
I think this should be reopened just FYI.

There is a statement in the [docs](https://centrifugal.dev/docs/server/server_api#history) which says that the parameter limit is not required, but if we remove it from the request body the response won't contain any publications, it will be "empty" (I guess it's assuming limit 0 by default?), that is a bit confusing.

You might want to cover that case in some way or clarify that limit 0 has some other purpose.

If it's intended logic please close this question.

**Comment by FZambia** [comment]
The behaviour is expected right – without explicit limit Centrifugo only returns a stream position information. So limit is optional parameter. But I agree that doc can be confusing – will try to address this with a better description of `history` API.

**Comment by FZambia** [comment]
Improved doc in https://github.com/centrifugal/centrifugal.dev/commit/9ec9bfd8bc2a460d51d320d91f44b0abfc2e3e06 - if you feel that sth is still can be described better - feel free to send pr to docs. Thanks for raising this!
