### ISSUE TITLE
[question] How to configure own `ca.crt`?

### ISSUE THREAD

**Issue by powerman** [centrifugal/centrifugo#495]
We're using own CA to sign TLS certificates for all our internal services (this includes both our backend API and 3rd-party services like Redis).

How to configure our `ca.crt` needed to validating Redis certificate when using redis engine?

**Comment by FZambia** [comment]
Hello! Centrifugo currently does not have an option to control this.

Though, according to [Go docs](https://pkg.go.dev/crypto/x509#SystemCertPool):

> On Unix systems other than macOS the environment variables SSL_CERT_FILE and SSL_CERT_DIR can be used to override the system default locations for the SSL certificate file and SSL certificate files directory, respectively. The latter can be a colon-separated list.

I've never tried this myself – maybe you can experiment with those? Can be a workaround until options to set custom CA file appear in Centrifugo.

**Comment by powerman** [comment]
Thanks! SSL_CERT_FILE works (at least there are no more errors related to checking Redis cert on start).

**Comment by chakrapani123** [comment]
Hello,

i tried with ssl_cert_file but still get error like below 
error dialing to Redis error="x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SAN
does ur SSL_CERT_FILE have both IP address and DNS or just one of them ?

**Comment by FZambia** [comment]
> i tried with ssl_cert_file but still get error like below
error dialing to Redis error="x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SAN
does ur SSL_CERT_FILE have both IP address and DNS or just one of them ?

Seems we also need to support `TLSConfig.ServerName` to fix `x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SAN`

**Comment by chakrapani123** [comment]
so if we pass just IP Addresses will it work ? or this is a feature enhancement that will be added a  later point?

**Comment by FZambia** [comment]
Most probably v4.1.0 with these changes will be released tomorrow.

**Comment by FZambia** [comment]
Unfortunately, had to delay v4.1.0 for some time – found some issues with it to improve.

**Comment by chakrapani123** [comment]
thanks for the update . really appreciate it. does this release take care of helm chart upgrades as well?

**Comment by FZambia** [comment]
> does this release take care of helm chart upgrades as well?

Helm chart for Centrifugo v4.0.5 was also released - https://github.com/centrifugal/helm-charts/releases/tag/centrifugo-9.0.8, you can whether update app version in existing helm chart or update helm chart to 9.0.8. Maybe I did not understand the question.

**Comment by FZambia** [comment]
Now it's released and part of Centrifugo [v4.1.0](https://github.com/centrifugal/centrifugo/releases/tag/v4.1.0)
