### ISSUE TITLE
[feature] Better error reporting when checking config file

### ISSUE THREAD

**Issue by matpuk** [centrifugal/centrifugo#497]
Hello!

Currently, if any errors are present in config file, the 'checkconfig' command returns only error message:

`/centrifugo # /usr/local/bin/centrifugo checkconfig -c config_new.json`
`error: While parsing config: invalid character '}' looking for beginning of object key string`

It would be nice to have at least a line number where the error arose.

**Comment by FZambia** [comment]
Hello, sent pr which makes an error more friendly. Unfortunately it requires some dancing around errors and manually extract that data from file. But seems to work.
