### ISSUE TITLE
Why use "mapstructure" and not just json.Unmarshal?

### ISSUE THREAD

**Issue by klauspost** [centrifugal/centrifugo#5]
It seems strange to use a third party library for something the standard library does just as well:

```Go
	var cmd connectClientCommand
	err = mapstructure.Decode(params, &cmd)
```

Is the same as

```Go
	var cmd connectClientCommand
	err = json.Unmarshal(params, &cmd)
```
Furthermore, if you want to defer parsing of some parts, simply do:

```Go
type clientCommand struct {
	Method string
	Params json.RawMessage  // Params are stored here, but not decoded
}
 // ...
	var cmd connectClientCommand
	err = json.Unmarshal([]byte(params), &cmd)
```

Using `encoding/json` is likely faster, much better tested and easier to read for "outsiders". Unless I am missing something (I could likely be), you don't use any "magic" features from mapstructure.

**Comment by FZambia** [comment]
Thanks a lot for your advices - I am so grateful. This is valid point again - I did not know about `json.RawMessage` before and will try to refactor this.

**Comment by FZambia** [comment]
Did this also in [strong_types](https://github.com/centrifugal/centrifugo/tree/strong_types) branch in this commit a0bd971927273c5f44dba117c2e2332f75daff51 - seems to work

**Comment by FZambia** [comment]
Merged that branch, also refactored the last place left –  in `engineredis.go` – in handling API request.

**Comment by FZambia** [comment]
I think we can close this?

**Comment by klauspost** [comment]
sure :)
