### ISSUE TITLE
Redis Username? [question] 

### ISSUE THREAD

**Issue by BirdyUK** [centrifugal/centrifugo#501]
How does one provide the username to authenticate with redis?

Im using the following config but get the below errors:

```
{
  "allowed_origins": ["0.0.0.0", "127.0.0.1", "localhost", "*"],
  "debug": true,
  "admin": true,
  "api_key": "123456",
  "engine": "redis",
  "redis_address": "***********************",
  "redis_username": "redisuser",
  "redis_user": "redisuser,
  "redis_password": "**********",
  "redis_tls": true
}
```

```
2022-01-18 18:12:50 [ERR] error auth in Redis error="WRONGPASS invalid username-password pair or user is disabled."
```

I can authenticate with redis via other methods or via the redis-cli using the username and password allocated, however it appears centrifugo does not pass the username down to the connection?

Thanks, PS: Amazing work, love the project!

**Comment by FZambia** [comment]
@BirdyUK hello!

Right, it's not supported at the moment, will try to add in next release. 

BTW, looking at your config noticed you struggled with setting allowed_origins and finally allowed all origins with `*`? :) Note that if you want to allow origin then it should not be just ip address like `127.0.0.1` - it should be URL like `http://127.0.0.1:3000` - i.e. with schema and port.

**Comment by BirdyUK** [comment]
No problem thank you, its my first time playing with centrifugo so i wasn't sure of the exact schema and threw what i assumed would pass for testing purposes :-)

We currently use a managed redis cluster for production so unfortunately it is not possible to authenticate without the user | password but more than happy to wait for this to be merged as i can see you have already tagged it above 👍 

Again, great work and thank you for your time (We might end up merging to the PRO edition once we have done the required testing and ACL is supported).

*Closed*
