### ISSUE TITLE
[question] Where to put use_unlimited_history_by_default option in config file?

### ISSUE THREAD

**Issue by matpuk** [centrifugal/centrifugo#504]
Hello!

v2 -> v3 migration guide mentions use_unlimited_history_by_default option, but it's unclear where to put it exactly.

Could you please explain?

**Comment by FZambia** [comment]
Hello, on config top level, added this to migration guide in https://github.com/centrifugal/centrifugal.dev/commit/db4ab7c6cd229f859c2c514b99f65175c01360ce
