### ISSUE TITLE
[feature] Make a subscription JWT behavior similar to a connection JWT (remove client claim)

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifugo#507]
At the moment private channel subscriptions require new token for a subscribe after establishing new connection. The reason is because subscription JWT includes client connection ID. This is a unique ID generated by a server for each connection and sent to a client in a reply to connect protocol command.

### Problem

This can be problematic in case of mass reconnect scenario – since having many users subscribed to a private channel may result into lots of requests to the backend for a new token. The question is whether we really need this client ID to be part of subscription JWT? I think not always. 

### Proposal

The proposal here is to remove client id from subscription JWT and make it work similar to a connection JWT. Or at least make client id optional.

This will allow caching private subscription token inside subscription object and re-use it during reconnect process (during which resubscribe happens). This can remove a peak load on the backend since most subscription tokens will still be valid. This also means subscription JWTs can be set during subscription initialization time. Mostly the same way as a connection JWT can be set for a client.

Let's consider some corner cases:

1. Token will also be valid for a new connection. Currently it is always invalid. This means it won't be possible to disconnect a user and thus make sure user can not subscribe to a private channel again. The answer to this may be a reasonably small subscription token expiration time. And maybe an option to temporary block a user in a channel (similar way we have in Centrifugo PRO [user block feature](https://centrifugal.dev/docs/pro/user_block)) - on a time of token expiration.
2. One-time subscription JWTs are still possible with short `exp` and `expire_at: 0`. In this case we need to make sure that upon re-subscription client receives token expired error and tries to request a new token from the backend.

### Can we support both approaches? With `client` claim and without?

If token has a `client` claim we do the check on the server. If it does not have a `client` claim - then skip the check. If no token set for a private channel initially callback will be issued by connector, on re-subscribe client may get a `token expired` error if client ID present but does not match – in this case client will re-issue subscribe callback to get an actual token. The downsides in this case are:

* increased subscribe latency
* more load on Centrifugo

We can avoid both downsides if client connector knows the mode in which subscription JWT operates. Subscription can have an option set by a developer as a tip. Something like `tokenUniquePerConnection: true/false`. This way client will know that it must always ask backend for a new subscription token like it works now. In the case of `tokenUniquePerConnection: true` client won't cache the token internally at all and will always issue callback to get new token upon resubscribe. We can avoid an additional option by looking at token contents (decode from base64) – but don't really like this approach as we stick to JWT format.

Regarding security and optional client claim – there is no problem since token has a `client` claim set by the backend which can't be simply removed by a malicious user. So Centrifugo always understands how to validate a token.

Supporting both approaches will make things more complicated (including docs), but it's backwards compatible and solves a problem. Personally, I'd like to have only the way without `client` claim at all – per-connection subscriptions may be achieved with subscribe proxy if required.

**Comment by BuyOwnEx** [comment]
It will be perfect, if you support both approaches (with client claim and without) for backwards compatible

**Comment by FZambia** [comment]
In Centrifugo v4 we are going to remove concept of private channels starting with `$`. By default, all channels will be non-public. But channel token authorization is not removed.

Clients will be able to subscribe to **any** channel by providing a **valid** subscription token. `client` claim won't be used anymore. This changes semantics of subscription tokens a bit – but the thinking is that it matches well with connection JWT and it's a much more flexible and performant approach. This new behaviour described in v4 WIP docs - [Channel token authorization](https://centrifugal.dev/docs/next/server/channel_token_auth). 

To replace current functionality it will be possible to use one-time subscription tokens (with short `exp`). In this case client will ask for a new token upon expiration.

**Comment by FZambia** [comment]
Part of Centrifugo v4 which was just released
