### ISSUE TITLE
[question] response on subscribing to channel

### ISSUE THREAD

**Issue by sSimuSs** [centrifugal/centrifugo#508]
How can I send response some json data as a response when users have connected to any channel?

**Comment by FZambia** [comment]
@sSimuSs hello, I think the most straightforward way to achieve this (i.e. send individual initial data for channel subscription) is using [subscribe proxy](https://centrifugal.dev/docs/server/proxy#subscribe-proxy). If you are using `centrifuge-js` as client connector then data will be available in [SubscribeSuccessContext](https://github.com/centrifugal/centrifuge-js/blob/2.8.4/dist/centrifuge.d.ts#L138).

**Comment by sSimuSs** [comment]
> @sSimuSs hello, I think the most straightforward way to achieve this (i.e. send individual initial data for channel subscription) is using [subscribe proxy](https://centrifugal.dev/docs/server/proxy#subscribe-proxy). If you are using `centrifuge-js` as a client connector then data will be available in [SubscribeSuccessContext](https://github.com/centrifugal/centrifuge-js/blob/2.8.4/dist/centrifuge.d.ts#L138).

Thank you much, that is what I needed

**Comment by sSimuSs** [comment]
> Subscribe proxy does not proxy private and user-limited channels at the moment.

But I want to handle user-limited channels, how can I do that?
Ex.: `notifications#1331`

**Comment by FZambia** [comment]
With subscribe proxy you can do any logic on the backend side. You will have user in context – so check permissions in a way you want. Just do not use user-limited channels in this case - those are explicitly designed to avoid permission round trip to the backend.

**Comment by sSimuSs** [comment]
In this case I can't send privately data directly to the user
Ex.:
- user subscribed to `notifications`, and got result data from subscribe_proxy
- I want to send some data after than, to the user with id 1331 (sub=1331 as I know, in the JWT auth token) as `notifications#1331`
- he won't accept the data, because of subscribe to the just `notifications` not `notifications#1331` channel

My solution(that I don't want): user will subscribe to the `notifications` just to get result (initial data) and will subscribe to the  `notifications#1331` to get other data

Am I right?

**Comment by FZambia** [comment]
You can just mimic the behaviour of Centrifugo's user-limited channel on your backend side. Nothing stops you from using channel like `notifications_1331`, do the required subscribe permission checks, then use it to send personal updates.

**Comment by sSimuSs** [comment]
Oh, really...))) thank yo much for idea and for fast answers)) Have a good day))

**Comment by sSimuSs** [comment]
Your advice is to use HTTP request to get initial data, instead subscribe_proxy. Am I right?

**Comment by sSimuSs** [comment]
initial data was counters of unread notifications, I decided to get initial counters from HTTP GET, and after If got any new noty from ws it will be replaced, with counter in coming ws data)

**Comment by FZambia** [comment]
Yeah, I think this makes sense 👍
