### ISSUE TITLE
[feature] WebTransport support

### ISSUE THREAD

**Issue by adriancable** [centrifugal/centrifugo#509]
Hi - wasn't sure where to post this but thought it may be relevant. Was originally inspired by your blog post on WebTransport-over-QUIC in Go from a while back: https://centrifugal.github.io/centrifugo/blog/quic_web_transport/

Unfortunately the content of the post is now somewhat 'defunct' since WebTransport-over-QUIC has been deprecated in favour of WebTransport-over-HTTP/3.

So I thought I would put together a lightweight but fully-featured WebTransport-over-HTTP/3 server in Go, since I don't think there are any others out there, at least freely available. Here it is: https://github.com/adriancable/webtransport-go

Not sure if this is of direct use for Centrifugo but hopefully of some interest nonetheless.

**Comment by FZambia** [comment]
@adriancable hello, great news! I'll take a look after finishing current activity.

Couple of quick questions to help me dive into:

1. Do I understand right that it works fine with the latest Chrome 98.0?
2. Is it possible to have a single server which can serve both general HTTP and WebTransport handlers?

The main issue about Webtransport support in Centrifugo ecosystem is https://github.com/centrifugal/centrifuge/issues/212. I.e. in Centrifuge library for Go (which is a core of Centrifugo).  

We already successfully implemented MVP based on WebTransport pr to quic-go (just noticed your comments there, will read carefully soon). The proper support still requires several things to refactor as pointed in linked issue above but seems possible. Centrifuge protocol will work fully over bidirectional WebTransport stream - which means not really utilizing all power of Webtrabnsport, but makes sense in general anyway.

So the plan is to eventually have WebTransport support in Centrifugo but I think only after HTTP/3 and Webtransport will be standartized (or at least with explicit experimental signal till that moment). The short-term plan is to create an example in Centrifuge Go library.

@silischev fyi

**Comment by adriancable** [comment]
Hi @FZambia - thanks for the initial feedback/questions!

Regarding Chrome support, yes, in the latest release version of Chrome, WebTransport is shipping. That's what I have been using for testing.

Regarding a single server which serves both regular HTTP/3 and WebTransport, that's a very interesting question and, actually, it isn't clear from reading the WebTransport specs whether the intention is for this to be supported. You can of course run HTTP/3 and WebTransport servers on different ports on the same server, but presumably you are asking if they can be 'multiplexed' on the same port.

The problem I see with this is that WebTransport does things which are not allowed in 'bare' HTTP/3. One example (there may be others) - WebTransport, unlike HTTP/3, supports serverCertificateHashes to make talking to resources like https://localhost:4433 possible without the end user having to add/trust self-signed certificates. This happens during the TLS negotiation, i.e. long before we know that the client's 'intention' is for this request to be a WebTransport one (which is only communicated once the request headers and/or HTTP/3 SETTINGS frame is sent).

It may be possible to update my package to add the option - if the incoming HTTP/3 request is not WebTransport - to pass it back to quic-go's HTTP/3 mechanism to continue serving. I haven't looked at this yet but it may or may not be possible with quic-go 'out of the box' and so I think I would want to understand first if multiplexed WebTransport+HTTP/3 on the same port is a use case that is intended to be something that should generally be supported by a server. Thoughts on this are welcome.

**Comment by FZambia** [comment]
Renamed the issue to track WebTransport support in Centrifugo in this issue.

Current status: me and @silischev made MVP based on non-released WebTransport spec and Go libraries. It generally worked – but requires some additional changes and work in Centrifuge library (tracked by https://github.com/centrifugal/centrifuge/issues/212).

At this point I personally don't want to spend more time on it – as things are still WIP everywhere. But WebTransport is a very desired addition – so as soon as ecosystem will be in a better state we can continue with it.

Any help is appreciated :)

**Comment by FZambia** [comment]
Experimental support added to Centrifugo v4 🎉 

* [Announce](https://centrifugal.dev/blog/2022/07/19/centrifugo-v4-released#experimenting-with-webtransport)
* [Docs](https://centrifugal.dev/docs/transports/webtransport)

Let's see how it goes with time.
