### ISSUE TITLE
[question]  How don't loose messages on reconnecting 

### ISSUE THREAD

**Issue by sinistram** [centrifugal/centrifugo#510]
Hi! 
I faced an issue when users don't getting messages when js client updates sse connection.
May be you can tell how handle this case.

...
1. Client sends sse requests.
2. Clients subscribes to the channel XXX
3. Server sends message AAA to the channel XXX
4. Client receives message AAA  from the channel XXX
5. Client loses the SSE connection.
6. Server sends message BBB to the channel XXX
7. Client sends sse requests.
8. Clients subscribes to the channel XXX
9. Clients Does not receive BBB 

Please tell me how can I receive BBB message.
...

**Comment by FZambia** [comment]
Automatic message recovery in case of temporary connection loss is natively supported by our bidirectional transports. Bidirectional clients abstract away keeping subscription epoch and offset on the client-side and use those values upon reconnect/resubscribe. More info [in docs](https://centrifugal.dev/docs/server/history_and_recovery#automatic-message-recovery).

Achieving message recovery is also possible with unidirectional transports, but requires more work on the client-side – similar to bidirectional transports keep epoch/offset values for different channels and use them when reconnecting.

This is not well documented at the moment, and I don't have a ready example to share. But the idea is that in initial connect request we can provide stream position values last seen by client:

https://github.com/centrifugal/centrifugo/blob/v3.1.1/internal/unigrpc/unistream/unistream.proto#L15

This link is for unidirectional GRPC protocol definitions, but uni SSE works in similar way - information should be passed in initial connect request (i.e. JSON encoded url param for browsers as described [here](https://centrifugal.dev/docs/transports/uni_sse)). 

Passing `recover`, `epoch` and `offset` flags allows restoring missed messages in channels client was subscribed too. I understand that without working example this may be difficult to understand – feel free to reach me out in Centrifugo Telegram community and I can try to explain better and help with code.

**Comment by sinistram** [comment]
I have tried successfully. 

What I did:
- Added a namespace to tho config with recoverable flag;
- In subscribe I get from centrifugo epoch 1646226246 and also get offset for every published message;
- On reconnect I am passing the epoch and the offset of last message and getting all messages published in downtime.

Thank you for the support one more time!
