### ISSUE TITLE
[question]  Private messaging question

### ISSUE THREAD

**Issue by srivikraman** [centrifugal/centrifugo#511]
Using centrifugo now I am able to implement group message. Users who subscribed to that group will receive the message.

**Question:** I have a usecase where I need to implement private message between two users. Other users shouldn't have access to this conversation. Can someone guide me on how to implement this usecase ?

**Comment by FZambia** [comment]
Hello, @srivikraman !

FAQ [covers this](https://centrifugal.dev/docs/faq#how-to-create-a-secure-channel-for-two-users-only-private-chat-case). In addition to FAQ you can always use 2 separate personal channels for each user and send message to each individual user channel upon sending into chat.

Join our community channels and ask there if you need more details about approaches.
