### ISSUE TITLE
Prometheus Metris Endpoint Show Only One Node

### ISSUE THREAD

**Issue by ismkdc** [centrifugal/centrifugo#514]
Hello,
I have 4 nodes centrifugo setup and i enabled prometheus metric endpoint but when i run benchmark for 100k user metric endpoint provides only 1 node metric.

**Comment by FZambia** [comment]
Hello!

That's expected, this is how Prometheus instrumentation works. Metrics endpoint only report stats collected on the current node.

You can configure Prometheus to scrape all your nodes - and then visualize data using native Prometheus dashboard or Grafana with Prometheus datasource. Check out our Grafana dashboard for Prometheus datasource btw – https://grafana.com/grafana/dashboards/13039. Also, In Kubernetes our current Helm chart works with Prometheus out of the box.

**Comment by FZambia** [comment]
Closing, join our community in Telegram btw (link in docs)
