### ISSUE TITLE
[question] User limited channels uniqueness

### ISSUE THREAD

**Issue by matpuk** [centrifugal/centrifugo#529]
Hello!

Are two channels 'chat:private#45,46' and 'chat:private#48,49' are different channels or the same channel from Centrifugo point of view?
Do I need to invent unique channel name for every pair of users I want to have private communication or not?

**Comment by FZambia** [comment]
Yes, these two channels are different. Channel is just a string, if you have different channel strings then channels are separate.

Moreover, channels `chat:private#40,50` and `chat:private#50,40` are different too.

We have [FAQ section](https://centrifugal.dev/docs/faq#how-to-create-a-secure-channel-for-two-users-only-private-chat-case) about user-to-user communication - so there are several options actually.

**Comment by FZambia** [comment]
Fixed by https://github.com/centrifugal/centrifugal.dev/commit/396f2adbd7b86c3e4e3cccce9386fcbe8ac3e11a
