### ISSUE TITLE
[question] How enable ssl with docker image

### ISSUE THREAD

**Issue by devslimbr** [centrifugal/centrifugo#560]
I used a docker image and it worked without any problems. When I enabled ssl in the config.json file it does not respond. The IP points to the server.

I redid the process without using docker, installing manually on Ubuntu and it worked.

Is there any extra configuration to work?

**Comment by devslimbr** [comment]
Resolve using proxy reverse with aapanel

**Comment by FZambia** [comment]
The issue seems resolved and since there are no steps to reproduce – closing.
