### ISSUE TITLE
how to generate/get the grpc connection files for 4.0 ? 

### ISSUE THREAD

**Issue by garyng2000** [centrifugal/centrifugo#567]
I have inherited a go project that is coded for 2.x which is not compatible with 4.0(tried use_client_protocol_v1_by_default but still doesn't work). If I want to port that to 4.0, where/how do I get the protoc generated files.

The reason I want to make the change is it seems that the 3.x js client are more roboust than the 2.x version.

**Comment by FZambia** [comment]
Hello @garyng2000 

Links to actual Protobuf definitions can be found in docs of Centrifugo V4.

* [server API GRPC docs](https://centrifugal.dev/docs/server/server_api#grpc-api)
* [unidirectional GRPC client transport](https://centrifugal.dev/docs/transports/uni_grpc) docs

We have [example](https://github.com/centrifugal/examples/tree/master/v4/unidirectional/grpc) which uses both GRPC server API and  unidirectional GRPC transport of Centrifugo v4.

Is it helpful?

**Comment by FZambia** [comment]
Don't hesitate to reach out in the community rooms if you still have questions 🙏
