### ISSUE TITLE
[feature] NATS Engine idea: Map Security aspects of NATS JetStream to Centrifugo

### ISSUE THREAD

**Issue by gedw99** [centrifugal/centrifugo#569]
**Is your feature request related to a problem? Please describe.**

I use NATS alot and it would be nice if the Centrifugo channels for Pub / Sub and RFC respected the underlying ones in NATS.
The NSC tool for NATS is how you can configure account, users, etc.

The reason is because centrifugo is awesome at the Edge Transports like SSE; WS, GRPC and QUIC.
NATS Jetstream is awesome at the Back plane Mesh but has no interop for other transports.

**Describe the solution you'd like**.
> What would the feature look like? How would it work? How would it change the API?

The JWT of centrifugo can be matched up to the NATS one.
Then the centrifugo system would respect all pub sub / rfc message events being consumed from NATS, and visa versa respect all the message events from Centrifugo being published into NATS.

...

**Comment by FZambia** [comment]
Hello, I think the description here is not enough. What exactly should be done? I am totally confused. Is it about client connection tokens or tokens for server API? Please provide examples of what you mean with respect to the current Centrifugo approaches and how they should be modified/adopted to support this feature.

**Comment by gedw99** [comment]
Yeah its not easy to understand or explain...Its all about Security.

Centrifugo has Security. https://centrifugal.dev/blog/2022/07/19/centrifugo-v4-released#secure-by-default-channel-namespaces

NATS Jetstream is a mesh with Security overlaid on it. https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/jwt

https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/jwt#decentralized-authentication-and-authorization-configuration-and-nsc shos how the NCS tool and JWT interact.

So it would be great if a subscriber and publisher and the NATS security configured for it was used by Centrifugo.

https://github.com/ConnectEverything/nats-by-example/blob/main/examples/auth/nkeys-jwts/go/main.go shows the way that operators, accounts, and users are configured in the system.

Does this help ?

**Comment by FZambia** [comment]
No, it does not help – Centrifugo does not have accounts, users and operators.

Please provide examples of what you mean with respect to the current Centrifugo approaches and how they should be modified/adopted/improved to support this feature.

**Comment by gedw99** [comment]
OK. i am going to have to swing back to this later...

**Comment by gedw99** [comment]
If you want to have a chat about it on telegram let me know. Might be better if we talk to over.

**Comment by FZambia** [comment]
Thanks, let's discuss this in more detail and come to sth actionable with respect to Centrifugo state, closing for now.
