### ISSUE TITLE
Flat Buffers

### ISSUE THREAD

**Issue by mgesmundo** [centrifugal/centrifugo#579]
Hi,
how I can use FlatBuffers instead of Protobuf?
Thank you for your best project!
All the best

**Comment by FZambia** [comment]
Hello, @mgesmundo

It's not possible - the only 2 serialization formats Centrifugo supports at the moment are JSON and Protobuf. Flatbuffer support was never planned, and I think it may be an effort which is hard to justify for a project at this stage. It's rather huge addition in both server and client SDKs. I doubt many of Centrifugo users will benefit from this.

**Comment by FZambia** [comment]
It's worth noting that you can use Centrifugo with Protobuf protocol but have your application payloads encoded with Flatbuffers - for Centrifugo it's just raw bytes.
