### ISSUE TITLE
[question] Anonymous Access

### ISSUE THREAD

**Issue by Nearata** [centrifugal/centrifugo#591]
**Ask your question**. Please provide as many details as possible – you will get the answer much faster then!

Is there a way to disable `Anonymous Access` when authenticating to websocket?

**"Show us an example of what you mean!"**. An example can be useful, otherwise we're left guessing!

1. Guest on website
2. Frontend sends api request to backend to refresh token
3. Backend generates a jwt token with empty sub and returns it to Frontend
4. Centrifuge SDK loads the token and tries to connect to the Websocket Server with the provided jwt token from the backend
5. Centrifuge server denies the connection because the `sub` claim is empty, not allowed

I'd like a way to configure centrifuge to check this instead of doing it by myself with my backend, like

```json
{
  "anonymous_access": false,
  "namespaces": [...]
}
```

**Comment by FZambia** [comment]
Hello @Nearata - in general not a problem to add such an option. Possibly call it like `disallow_anonymous_connection_tokens: true`

Could you elaborate a bit more why you want this behaviour - do you already generate JWTs for anonymous users in your app and they use those JWTs to call backend API. But at the same time you want to avoid having Centrifugo connection? Just curious about exact reasoning here.

**Comment by Nearata** [comment]
Hello @FZambia ,

Lets' assume im building a plugin for a platform. This plugin allows to get realtime notification when new discussions are made. Now, the plugin has a toggle to allow/deny guests but it needs to check, in backend, if a visitor is a guest or not. my toughts were if this job can be left to centrifuge or if it is a overkill/not ideal in this use case. that means, im going to generate a jwt token no matter if the visitor is guest or not, so that i can get rid of this `Allow Guests` toggle in admin settings.

**Comment by FZambia** [comment]
Done in https://github.com/centrifugal/centrifugo/releases/tag/v4.1.1

**Comment by FZambia** [comment]
@Nearata Please avoid using v4.1.1, it contained a protocol bug. See [v4.1.2](https://github.com/centrifugal/centrifugo/releases/tag/v4.1.2) instead.

**Comment by Nearata** [comment]
Working as expected. Thank you !!
