### ISSUE TITLE
Simpler response.go

### ISSUE THREAD

**Issue by klauspost** [centrifugal/centrifugo#6]
Removes the need for a custom marshaller, and converting to a map[string]interface{}. Also doesn't initialize fields to zero value:

```Go
package libcentrifugo

import (
	"encoding/json"
)

// response represents an answer Centrifugo sends
// to client or API request commands
type response struct {
	Body   interface{} `json:"body"`
	Error  error       `json:"-"`
	ErrString  *string       `json:"error"`
	Method string      `json:"method"`
}

func newResponse(method string) *response {
	return &response{Method: method}
}

// multiResponse is a slice of responses in execution
// order - from first executed to last one
type multiResponse []*response

// toJson converts response into JSON
func (r *response) toJson() ([]byte, error) {
	if (r.Error != nil {
		s := r.Error.Error()
		r.ErrString = &s
	}
	return json.Marshal(r)
}

// toJson converts multiResponse into JSON
func (mr *multiResponse) toJson() ([]byte, error) {
	return json.Marshal(mr)
}
```

**Comment by FZambia** [comment]
Thanks!

**Comment by FZambia** [comment]
Added this implementation in a8bcf0218651e1e0c2b8c2f7bbd94417eba52469

**Comment by FZambia** [comment]
Hmm, I temporarily returned an old implementation in this commit  8b8e064108ba9a302c8513641b9989c88bfcd238 . I found a place (https://github.com/centrifugal/centrifugo/blob/master/libcentrifugo/handlers.go#L394) where I do not encode response using `toJson()` method but using `Encoder`. What do you think – should I always use `toJson` and use your implementation or go with custom marshalling?

**Comment by klauspost** [comment]
I would, if possible, avoid (and even remove) the toJson() function. However, it made the error conversion much simpler.  

I am in the process of moving my stuff to a new computer. In an hour I should have it set up, so I can compile stuff. I think we should be able to do this in a simply and easy to understand way, I just need to be able to test it :)

**Comment by klauspost** [comment]
(then I can also send pull-requests)

**Comment by FZambia** [comment]
Thanks a lot:)

**Comment by klauspost** [comment]
Continued in #7
