### ISSUE TITLE
why do you use Redis Pubsub

### ISSUE THREAD

**Issue by HoangNgo88** [centrifugal/centrifugo#606]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me  it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by FZambia** [comment]
Hello @HoangNgo88 

You can take a look at [this part of Scaling WebSocket in Go and beyond
](https://centrifugal.dev/blog/2020/11/12/scaling-websocket#performance-is-not-scalability) blog post which answers the question.

In general, the most important aspects here are ephemeral or persistent subscriptions, in-memory or on-disk storage. Theoretically both RabbitMQ and Kafka could be Centrifugo PUB/SUB brokers, but we aim towards super-fast brokers which can handle millions of ephemeral subscriptions from real-time connections. And for history we want broker which supports API to paginate over stream of events.
