### ISSUE TITLE
[question] Explicit in docs the "not allowed" proxy responses

### ISSUE THREAD

**Issue by GregOriol** [centrifugal/centrifugo#620]
In the Server docs page "Proxy events to the backend" (https://centrifugal.dev/docs/server/proxy), for each proxy, there is a line describing the expected response to allow the request. For example for the "Subscribe proxy", there is:
```
Expected response example if subscription is allowed:

{"result": {}}
```

But there is no clear indication on what the response should be when the proxy doesn't allow the request.

Could it be made more explicit?

**Comment by FZambia** [comment]
Hello, true - docs are not clear about this.

In general, application should not try to subscribe to channels for which access is not allowed (if possible). Regarding proxy response in this case – in most cases returning:

```json
{
  "error": {
    "code": 403,
    "message": "permission denied"
  }
}
```

– is sufficient enough. See [returning custom errors](https://centrifugal.dev/docs/server/proxy#return-custom-error). Error code may be not 403 actually, it's not HTTP - so it's up to Centrifugo user to decide. Just keep it in range  [400, 1999].

In this case on client side you will get `unsubscribed` event with error code. Subscription won't resubscribe automatically after that.

**Comment by FZambia** [comment]
Fixed in https://github.com/centrifugal/centrifugal.dev/commit/dbb68b78209876ce199ffd6fdd74781e9295848a, thanks for raising the question.

**Comment by GregOriol** [comment]
Awesome!
