### ISSUE TITLE
[question] How to configure namespaces for private and public channels

### ISSUE THREAD

**Issue by nikrovir** [centrifugal/centrifugo#634]
Hi everyone!
I am trying to configure the Centrifugo 4 in such a way that all channels in the private namespace have jwt auth and use the option "allow_user_limited_channels": true, and all channels in the public namespace do not require the mandatory presence of jwt (but if the user is authorized, he should also be able to subscribe).

Here is my current configuration:
```json
{
    "client_anonymous": true,
    "namespaces": [
        {
            "name": "private",
            "anonymous": false,
            "allow_user_limited_channels": true
        },
        {
            "name": "public",
            "anonymous": true,
            "allow_subscribe_for_anonymous": true,
        }
    ]
}

```

Judging by the documentation, everything should work with `"client_anonymous": true`, but when trying to connect using this example: 
```javascript
const centrifuge = new Centrifuge("ws://localhost:8010/connection/websocket");

    centrifuge.on('connecting', function (ctx) {
        console.log(`connecting: ${ctx.code}, ${ctx.reason}`);
    }).on('connected', function (ctx) {
        console.log(`connected over ${ctx.transport}`);
    }).on('disconnected', function (ctx) {
        console.log(`disconnected: ${ctx.code}, ${ctx.reason}`);
    }).connect();

    const sub = centrifuge.newSubscription("public:chat");

    sub.on('publication', function (ctx) {
        console.log(ctx.data);
    }).on('subscribing', function (ctx) {
        console.log(`subscribing: ${ctx.code}, ${ctx.reason}`);
    }).on('subscribed', function (ctx) {
        console.log('subscribed', ctx);
    }).on('unsubscribed', function (ctx) {
        console.log(`unsubscribed: ${ctx.code}, ${ctx.reason}`);
    }).subscribe();
```

I get an error in the logs of the Centrifugo:
```
{"level":"info","client":"36682f58-c4a2-44c4-a11a-f28a6c5b1a1d","user":"","time":"2023-04-02T15:55:25Z","message":"client credentials not found"}
2023-04-02T15:55:25.110833567Z {"level":"info","client":"36682f58-c4a2-44c4-a11a-f28a6c5b1a1d","command":"id:1  connect:{name:\"js\"}","reason":"bad request","user":"","time":"2023-04-02T15:55:25Z","message":"disconnect after handling command"}
```

Obviously, the error is related to the absence of jwt, but I want to make sure that it is not needed to connect to public channels. The option using `"client_insecure": true` is also not suitable, because I have a need for private channels, and trying to specify client_insecure for only one namespace does not lead to success

Please help!

**Comment by FZambia** [comment]
Hello,

From https://centrifugal.dev/docs/getting-started/migration_v4#other-configuration-option-changes:

> client_anonymous option renamed to allow_anonymous_connect_without_token – new name better describes the purpose of this option which was previously not clear. Converter above takes this into account.

Probably that's the reason?

**Comment by nikrovir** [comment]
> Probably that's the reason?

Thanks mate! I wasted two days of my life for that =)

**Comment by yl** [comment]
Here is my configuration:
```json
{
"allow_anonymous_connect_without_token": true,
  "namespaces": [
    {
      "name": "public",
      "anonymous": true,
      "allow_subscribe_for_anonymous": true
    }
  ]
}
```

I get error: `Code: 103, Message: "permission denied".`

**Comment by yl** [comment]
> Here is my configuration:
> 
> ```json
> {
> "allow_anonymous_connect_without_token": true,
>   "namespaces": [
>     {
>       "name": "public",
>       "anonymous": true,
>       "allow_subscribe_for_anonymous": true
>     }
>   ]
> }
> ```
> 
> I get error: `Code: 103, Message: "permission denied".`

Add `"allow_subscribe_for_client": true` to namespaces configuration to fix it.
