### ISSUE TITLE
[question] understand permisson channel system

### ISSUE THREAD

**Issue by Cyclone5** [centrifugal/centrifugo#635]
i am trying to channel with auth but i can't understand how i do that. i read doc. i tried jwt part 

my example jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNyIsImNoYW5uZWwiOiIkZ29zc2lwcyJ9.22nMmsR4Th5GkxI7GKQWIWmvQy-e9dbsmLtp8s-yMxk

docker logs:
{"level":"info","client":"e45a4216-b3b4-48c7-a8c2-4e683be4900e","error":"invalid token","time":"2023-04-06T18:34:56Z","message":"invalid connection token"}
{"level":"info","client":"e45a4216-b3b4-48c7-a8c2-4e683be4900e","command":"id:1  connect:{token:\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNyIsImNoYW5uZWwiOiIkZ29zc2lwcyJ9.22nMmsR4Th5GkxI7GKQWIWmvQy-e9dbsmLtp8s-yMxk\"  name:\"js\"}","reason":"invalid token","user":"","time":"2023-04-06T18:34:56Z","message":"disconnect after handling command"}

https://centrifugal.dev/docs/server/channel_token_auth#example is it wrong?

when i delete channel key on my jwt i get permisson denied ofc. can u help me about this permisson stuff

**Comment by FZambia** [comment]
Hello, connection token can't contain `channel` claim. This is a limitation to avoid using connection token as subscription token. Channel permission model described [here](https://centrifugal.dev/docs/server/channel_permissions) - you need to configure permissions in a way suitable for your use case.

Please try to ask help in our community groups - https://centrifugal.dev/docs/getting-started/community.
