### ISSUE TITLE
[bug] Centrifugo and Laravel valet

### ISSUE THREAD

**Issue by Oui-Dev** [centrifugal/centrifugo#636]
**Describe the bug**. A clear and concise description of what the bug is.

On my Laravel projects, I use Laravel Valet which allows me to use custom domain names instead of localhost:8000. However, centrifugo is giving me an error in this use case.
The error is: ```error proxying connect error="HTTP request error: Post \"http://example.test/centrifugo/connect/\": dial tcp: lookup example.test on 10.0.70.254:53: no such host" client=...```
It works when disabling valet, and use it with localhost:8000.

**Versions**

Centrifugo version is 4.1.2
Client library used is centrifuge-js of version 3.1.1
Operating system is macOs Ventura 13.3.1

**Steps to Reproduce** How can the bug be triggered?

Use centrifugo with connect proxy doesn't work when using Laravel valet

**Expected behavior** What output or behaviour were you expecting instead?

successful http request on valet dns

**Code Snippets** A minimum viable code snippet can be useful.

Centrifugo config
```
{
    "port": 8002,
    "admin": true,
    "admin_password": "...",
    "admin_secret": "...",
    "api_key": "...",
    "engine": "memory",
    "log_level": "debug",
    "allowed_origins": [
        "http://example.test"
    ],
    "proxy_connect_endpoint": "http://example.test/centrifugo/connect/",
    "proxy_http_headers": [
        "Cookie",
 	"Authorization"
    ],
    "namespaces": [
        ...
    ]
}
```

**Comment by FZambia** [comment]
Hello @Oui-Dev.

Centrifugo simply sends HTTP request to the configured endpoint. Could you please elaborate what exactly you think Centrifugo does wrong currently? I did not understand this from the description. If you pointed Centrifugo to the address which can not be resolved - then you are getting an error like you mentioned.

**Comment by Oui-Dev** [comment]
Sorry for the delay,
I manage to connect well to the endpoint with the proxy (valet), as can be seen on my Insomnia requests and I have defined my authorized domains. But despite that I still get this error when I use Laravel Valet.

localhost:8000
![image](https://user-images.githubusercontent.com/70695580/232086685-8b51407f-c8cf-4d5a-9b3b-c1282ae5375c.png)

example.test (laravel valet)
![image (1)](https://user-images.githubusercontent.com/70695580/232086734-8114200e-705b-46df-8488-14dec634128a.png)

**Comment by FZambia** [comment]
I don't see what Centrifugo can do differently from your report. Please describe why you think it's a bug in Centrifugo. I described in the above comment that all Centrifugo does currently is sending a request to the configured endpoint. If the address can't be resolved then you get the error. So make sure there is a network connectivity between Centrifugo and configured endpoint.

**Comment by FZambia** [comment]
Closing, I don't see what Centrifugo des wrong here.
