### ISSUE TITLE
json: error calling MarshalJSON for type *json.RawMessage

### ISSUE THREAD

**Issue by MadHamza** [centrifugal/centrifugo#64]
Hi,

I had this error message on my heroku logs and could'nt figure out what's about.

json: error calling MarshalJSON for type *json.RawMessage: invalid character '\'' looking for beginning of object key string

Thanks for getting a look on.

**Comment by banks** [comment]
Without checking code, I expect that means that some value passed to Centrifugo via rest API, redis API or WebSocket API was invalid JSON. 

Can you reproduce?

**Comment by MadHamza** [comment]
Thank you Paul for the hint.
Indeed, I've checked the info parameter I'm passing to the authEndpoint function and found out that's not a genuine json.

**Comment by FZambia** [comment]
@MadHamza do you have more questions? Can we close this?

**Comment by MadHamza** [comment]
@FZambia  No more questions. Thank you!! Sure you can close it.
