### ISSUE TITLE
[feature] Possibility to set separate configuration for subscription tokens

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifugo#640]
**Is your feature request related to a problem? Please describe.**

Currently the configuration for tokens shared for both connection and subscription tokens.

It seems to me that with introduction of JWKS users may require separate configuration for subscription tokens. Because auth may be fully managed by Keycloak, while subscription tokens may require management from the app backend side.

The idea is to give such possibility using sth like this:

```config
{
  "token_jwks_public_endpoint": "https://..."
  "subscription_token": {
    "hmac_secret_key": "XXX"
  }
}
```

So subscription token validation works using different configuration from the connection token configuration. I.e. in the example above connection tokens will be validated over JWKS endpoint, and subscription tokens using symmetric HMAC algorithm with secret key shared between Centrifugo and app backend.

But I am not sure whether it will be useful for someone in practice at this moment. So just logging this feature proposal here and waiting for feedback and real use case from Centrifugo users.

**Comment by steffenstolze** [comment]
Great suggestion. We faced the same issues with AWS Cognito JWKS.

**Comment by FZambia** [comment]
@steffenstolze hello, thanks for the feedback. I opened #669 - most probably will be part of Centrifugo v5

**Comment by FZambia** [comment]
Released as part of Centrifugo v5
