### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by mavvverick** [centrifugal/centrifugo#642]
Is it possible to maintain just one subscription per user across channels?

Our use case require user to allow subscribing one channel at a time. By default all channels are open for subscription from any user. 

It is similar to use case of one login session per user. The old connection is logout whenever user tries to login from another device/ browser window.

**Comment by FZambia** [comment]
Hello,

You can look at section [Maintain single user connection](https://centrifugal.dev/docs/server/server_subs#maintain-single-user-connection). Probably it will fit your use case.
