### ISSUE TITLE
[question]  Performance Tuning Socket Stream jitter

### ISSUE THREAD

**Issue by mavvverick** [centrifugal/centrifugo#646]
We have a use case where we need to push data in every 200ms and using same channel to send two categories of data size of avg 1kb and 8kb respectively. 

The socket stream is not continuous and jitters sometimes. It hangs for couple of second and dumps the data and goes back to continuously listening then after few seconds same behaviour. I have tried using separate channels but same issue.

**Comment by FZambia** [comment]
Hello, @mavvverick 

Since you are talking about performance please provide a working example which reproduces your setup, so it will be clear what you want to optimize.

**Comment by FZambia** [comment]
@mavvverick hello, any updates here?

**Comment by FZambia** [comment]
Closing since no response, if still actual - please reopen with proper reproducer, it's hard to help otherwise.
