### ISSUE TITLE
How to debug 401 unauthorized responses from the http api?

### ISSUE THREAD

**Issue by synw** [centrifugal/centrifugo#659]
Trying to post to the api with an api key I always get a 401 unauthorized response. The api works with api_insecure mode and responds with 200, but when using api_key I always get a 401. I am running Centrifugo v4.1.3 from a downloaded release. My config:

```json
{
    "token_hmac_secret_key": "8f70501b-7f03-40f4-b5b2-68c44e632795",
    "admin_password": "ea2ed9f4-5697-4910-967f-335a8422a878",
    "admin_secret": "dcb08f2d-bee6-4f3b-bc49-5f01e7238119",
    "api_key": "xxx",
    "allowed_origins": [
        "*"
    ],
    "port": "8427",
    "internal_port": "9000",
    "log_level": "debug"
}
```

I tried with the curl example:

```bash
curl --header "Authorization: apikey xxx" \
  --request POST \
  --data '{"method": "info", "params": {}}' \
  http://localhost:9000/api
```

With the python requests exemple:

```python
command = {
    "method": "publish",
    "params": {"channel": "public", "data": {"content": "1"}},
}
api_key = "xxx"
data = json.dumps(command)
print(data)
headers = {"Content-type": "application/json", "Authorization": f"apikey {api_key}"}
resp = requests.post("http://localhost:9000/api", data=data, headers=headers)
print(resp)
```

When I print the request debug info the header seems to be correctly sent:

```
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9000
send: b'POST /api HTTP/1.1\r\nHost: localhost:9000\r\nUser-Agent: python-requests/2.31.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nContent-type: application/json\r\nAuthorization: apikey xxx\r\nContent-Length: 80\r\n\r\n'
send: b'{"method": "publish", "params": {"channel": "public", "data": {"content": "1"}}}'
reply: 'HTTP/1.1 401 Unauthorized\r\n'
header: Date: Sat, 27 May 2023 12:36:54 GMT
header: Content-Length: 0
DEBUG:urllib3.connectionpool:http://localhost:9000 "POST /api HTTP/1.1" 401 0
```

Also tried with Cent, but I always get a 401:

```
[DBG] http request addr=127.0.0.1:57300 duration="8.171µs" method=POST path=/api status=401
```

What did I do wrong? Did I miss something? How to get more information about the reason of the unauthorized error?

**Comment by FZambia** [comment]
Hello @synw 

I tried running Centrifugo v4.1.3 with config.json you provided and using CURL from your comment above worked just fine. I used Centrifugo from binary release.

Please double-check

**Comment by synw** [comment]
Hi @FZambia , thanks for your help. After a lot of struggling I finally found out where the problem came from: I am running Centrifugo with the standard command `./centrifugo` and the info message says I am using config from the local `config.json`:

```
[INF] using config file path=/path/to/centrifugo/config.json
```

All is normal here. But the thing was that I had some env variables setup in my `.bashrc` from a previous project: `CENTRIFUGO_HMAC_KEY` and `CENTRIFUGO_API_KEY`and I forgot about them. It appears that Centrifugo uses these variables prior to config. This is okay but I would maybe suggest to add a debug message saying that the env variables are in use or something like that for the case where you have env vars + config mixup. It may help dumb people like me to have this debug message to figure out the situation about what is used for the running server config.

**Comment by FZambia** [comment]
Glad you found it! I suppose a way to somehow dump all the configuration could help. Not sure how to deal with secret values though.. Showing where the value came from I think not possible with Viper lib we are using for configuration - probably it should be improved for this. In general this reminds me about #656 - would be awesome to address all these configuration errors at some point.
