### ISSUE TITLE
[question] Using centrifuge for custom websocket behaviour

### ISSUE THREAD

**Issue by ysaakpr** [centrifugal/centrifugo#672]
I am planning to Centrifuge for an IOT case where the client device uses web socket to communicate with backend with a custom subprotocol, though the data transferred are in JSON formatted.

in my case the client is unaware of the channel within a connection. And there is not much control that i get with in the client side of the code. which is already deployed and works with a predfined protocol with JSON data format. The only thing that the client does is, open a connection on a websocket endpoint and start communicating with the backend server adhering to a protocol.

The client connects usually with predefined path, say `/websocket/v1/<uniqueid>`

We can consider the unique id as a user id or device id, and the client expect to subscribe to this channel and do biderectional communication with server.

Are there any direct way to use centrifuge in this kind of case. If i have to make changes, is it just the connection handler, like websocket client Handler that i have to modify, any other things do i have to take care to support this kind of use cases.

How do you think making this case a generic case to implement ?

**Comment by ysaakpr** [comment]
Thanks @FZambia  for response. I too felt to use something else. But the case for me is .. i do need the centrifugal for the remaining use case. 

I am trying to see if there is anyway to use a `custom handler or middleware/interceptors` to handle a custom client behaviour with `centrifugo` itself, so that i can avoid having multiple servers for almost similar functionality.

**Comment by FZambia** [comment]
> I am trying to see if there is anyway to use a custom handler or middleware/interceptors to handle a custom client behaviour with centrifugo itself, so that i can avoid having multiple servers for almost similar functionality.

No such option currently. Centrifugo is a standalone server and has its own bidirectional protocol which helps providing all the features. But as a standalone server it can't be easily extensible in a way you need. It would be very inconvenient to add support for custom protocols to Centrifugo, as I mentioned you better build your own server on top of WebSocket library, or probably find something close to your use case.

**Comment by FZambia** [comment]
Closing - think I answered the question. Overall - no way to use custom WebSocket protocols different from our own framing formats [described in docs](https://centrifugal.dev/docs/transports/overview) and no plans to add custom WebSocket protocols support in the observable perspective.
