### ISSUE TITLE
presence , not available

### ISSUE THREAD

**Issue by letian-tang** [centrifugal/centrifugo#694]
**Describe the bug**. A clear and concise description of what the bug is.

presence or presence_stat
response  code=108

**Versions**

Centrifugo version is 5.0.2

**Steps to Reproduce** How can the bug be triggered?

publish success
![image](https://github.com/centrifugal/centrifugo/assets/9101213/c631e7fe-55b7-460f-a121-7cdab3638060)

presence  error
![image](https://github.com/centrifugal/centrifugo/assets/9101213/7117dcc8-d8d9-4fcf-914c-5381e3e9719c)

**Comment by amzar96** [comment]
hi, I have the same issue but I do not understand how it works.

<img width="852" alt="image" src="https://github.com/centrifugal/centrifugo/assets/19677928/0a29b64e-eb9a-4dd2-90e4-0d5f4d4e729d">
/subscribe endpoint, response OK

<img width="684" alt="image" src="https://github.com/centrifugal/centrifugo/assets/19677928/9165d704-7b24-49ef-8256-98891de5f197">
/publish endpoint, response OK

however, no result and failed for /history 
<img width="828" alt="image" src="https://github.com/centrifugal/centrifugo/assets/19677928/5944d324-a6e0-4545-a888-fa847c902b32">
<img width="789" alt="image" src="https://github.com/centrifugal/centrifugo/assets/19677928/d183471b-ab89-4968-8f5c-c5853e0222a0">

<img width="1099" alt="image" src="https://github.com/centrifugal/centrifugo/assets/19677928/d31b4d37-99f2-4b9c-aa89-c0ac17dc3d4c">

zero channel

may I know the reason?
