### ISSUE TITLE
Ищу специалиста для подключения к centrifugo

### ISSUE THREAD

**Issue by multiton73** [centrifugal/centrifugo#703]
Для своего проекта использую устаревшие версию centrifugo v.2.2. Самостоятельно прикрутил ее к проекту, создав некий метод на js.  Есть потребность в переходе на новую версию, прочитав доки и встал в тупик. 
1. Вовсе не могу подключить клиента, создаю токен через PHP клиента, но в консоли вижу ошибку:  request Origin is not authorized.
Код подключения:
	var centrifuge = new Centrifuge(host, {
		token: token
	});
2. Мне нужно переписать своего клиента на подписку каналов под новую версию. На фрилансерах я не смог найти исполнителя. Жду предложений по договоренности. Спасибо.

**Comment by multiton73** [comment]
Токен получаю так: $token = $client->setSecret("Centrifugo secret key")->generateConnectionToken($userId);
в конфиге centrifugo параметр allowed_origins": ["*"]

**Comment by FZambia** [comment]
@multiton73 hello, please do not post issues like this in our Github organization. It's not suitable for looking for freelancers and job proposals.

Centrifugo v2 is not supported anymore, we have migration guides:

* v2 -> v3 https://centrifugal.dev/docs/3/getting-started/migration_v3
* v3 -> v4 https://centrifugal.dev/docs/4/getting-started/migration_v4
* v4 -> v5 https://centrifugal.dev/docs/getting-started/migration_v5

Probably ask for help in our community rooms, we did not have such cases before though.
