### ISSUE TITLE
[feature] gRPC compression

### ISSUE THREAD

**Issue by zs-dima** [centrifugal/centrifugo#704]
Might be nice to add gRPC compression options, as websocket is already available:

```json
"websocket_compression": true,
"websocket_compression_min_size": 2000,
"websocket_compression_level": 3,
```

**Comment by FZambia** [comment]
Hello @zs-dima

We have several GRPC interfaces now (server API, unidirectional client GRPC, GRPC proxy). Do you mean unidirectional GRPC transport? Do you have specific GRPC options in mind you need to be supported by Centrifugo?

**Comment by zs-dima** [comment]
@FZambia thanks a lot for answering.
I mean server API and unidirectional client GRPC.
https://centrifugal.dev/docs/server/server_api
https://centrifugal.dev/docs/transports/uni_grpc

It could be `config.json` settings for example:
```json
"grpc_compression": "gzip",
```

**Comment by FZambia** [comment]
Part of 5.1.0 - https://github.com/centrifugal/centrifugo/releases/tag/v5.1.0
