### ISSUE TITLE
[feature] JWKS should not be limited to RSA

### ISSUE THREAD

**Issue by shaunco** [centrifugal/centrifugo#719]
**Describe the bug**. A clear and concise description of what the bug is.
The current code limits JWKS support to RSA only:
https://github.com/centrifugal/centrifugo/blob/master/internal/jwtverify/token_verifier_jwt.go#L205

ECC keys are becoming more and more prevalent, and with since the auth server providing the JWKS picks the algorithm, Centrifugo should support both RSA and ECC.

I will get a PR submitted for this.

**Comment by shaunco** [comment]
@FZambia - Is there a strong affinity to https://github.com/cristalhq/jwt (seems relatively well supported but only handles JWT) and https://github.com/rakutentech/jwk-go rather than switching all JWT/JWK/JWKS handling to https://github.com/lestrrat-go/jwx/tree/develop/v2 ?

JWX implements:
- all of what is in https://github.com/centrifugal/centrifugo/tree/master/internal/jwks (with the added benefit of background auto-refresh of JWK sets)
- all of https://github.com/centrifugal/centrifugo/tree/master/internal/jwtutils
- almost all of https://github.com/centrifugal/centrifugo/blob/master/internal/jwtverify/token_verifier_jwt.go (missing Keycloak JWT-->JWKS URI injection, but easy to do this before calling JWX)

JWX is also very widely used, very well maintained, and MIT licensed.

**Comment by FZambia** [comment]
Hello @shaunco 

Not sure why it's a bug - it's a feature request. Please feel free to open PR.

Regarding JWT libraries - if current stack allows implementing the feature - let's stick with it for now.  `cristalhq/jwt` is clean and efficient, migrating to JWX should provide some value. This value may be:

* more performance
* or possibility to introduce some feature not possible with current libs - in this case we can sacrifice performance concern I suppose as we don't have choice.

> with the added benefit of background auto-refresh of JWK sets

I think we already handle JWK set refreshes (when key id is not presented in cache)

**Comment by shaunco** [comment]
@FZambia - Thanks for getting this in! If you have a moment, a v5.0.5 release would be much appreciated!
