### ISSUE TITLE
[bug] Grafana dashboard favicon image link returns 404

### ISSUE THREAD

**Issue by TissuePowder** [centrifugal/centrifugo#731]
Precisely, this isn't really a bug in that sense, but it isn't very nice visually. Centrifugo's grafana dashboard's favicon/logo link seems to have expired.

https://grafana.com/grafana/dashboards/13039-centrifugo

https://centrifugal.github.io/centrifugo/images/favicon.png 

![2023-10-30_12-39-14](https://github.com/centrifugal/centrifugo/assets/39616942/dfac0f2a-2d03-4c45-96f1-92602588a72f)

A fix would be appreciated.

**Comment by FZambia** [comment]
Hello @TissuePowder , thanks for reporting! It's from the old doc site closed recently.

While not fixed in dashboard.json - you can use:

* https://avatars.githubusercontent.com/u/6236442
* https://centrifugal.dev/img/favicon.png

**Comment by FZambia** [comment]
Uploaded new dashboard revision with fixed image link: https://grafana.com/grafana/dashboards/13039-centrifugo/?tab=revisions . With the following diff:

```diff
--- a/dashboard.json
+++ b/dashboard.json
@@ -78,7 +78,7 @@
       },
       "id": 38,
       "options": {
-        "content": "![image](https://centrifugal.github.io/centrifugo/images/favicon.png)",
+        "content": "![image](https://centrifugal.dev/img/favicon.png)",
         "mode": "markdown"
       },
       "pluginVersion": "8.1.5",
```

Please reopen in case of any issues.
