### ISSUE TITLE
[bug] Redis error: Lua redis lib command arguments must be strings or integers

### ISSUE THREAD

**Issue by VanderY** [centrifugal/centrifugo#732]
I'm constantly getting this error. This happens without any actions from me so I can't give steps to reproduce.

 **Message** 
Error calling history 
**Error**
```
Lua redis lib command arguments must be strings or integers script: c9735f3dd5ac99ee9c4e59d9f5ac297b036f9443, on @user_script:25.
```

**Versions**

Centrifugo version is 5.1
Redis version is 7.2

Running on docker

**Comment by FZambia** [comment]
Hello @VanderY ,

thanks - reproduced and prepared the fix in https://github.com/centrifugal/centrifuge/pull/328

**Comment by FZambia** [comment]
The fix is a part of [v5.1.1](https://github.com/centrifugal/centrifugo/releases/tag/v5.1.1)

**Comment by VanderY** [comment]
Hello again @FZambia,

Now it's the same error but in a different place

`Lua redis lib command arguments must be strings or integers script: 9f5e715bc195d5830e60915df951da8f4b6fe940, on @user_script:34.`

**Comment by FZambia** [comment]
Unfortunate.. 

The only reason I see now how this could happen is inconsistent state of meta key in Redis. This is generally not possible - but maybe I am missing sth. But unfortunately to precisely look at it we need to know the channel which is not now printed to the error log.

As first step I'll add channel logging for the next release.

Probably you can write to me in Telegram? Find me in our Telegram community - https://centrifugal.dev/docs/getting-started/community - and we can somehow speed up the investigation of this.

**Comment by FZambia** [comment]
Realized why this can happen - this is one more possible scenario, when meta key has only epoch field. Centrifugo v5.1.1 does not have this issue anymore for new installations or new Reds keys, but old keys result into this error.

**Comment by VanderY** [comment]
Actually, this is really what happened.
I just removed all redis data, and it seems to be working now.

Thank you so much for your support!

**Comment by FZambia** [comment]
Thanks! I also made some changes for next Centrifugo version to work correctly with both new and old keys

**Comment by FZambia** [comment]
Hope should be now fine for all cases with [v5.1.2](https://github.com/centrifugal/centrifugo/releases/tag/v5.1.2)
