### ISSUE TITLE
[feature] Add support for Ed25519 signature JWS

### ISSUE THREAD

**Issue by AlexeyAkulovich** [centrifugal/centrifugo#755]
Centrifugo supports for `EC` and `RSA` key types (`kty`) for JWKs tokens from [RFC 7517](https://datatracker.ietf.org/doc/html/rfc7517). But there are newer variants in [RFC 8037](https://www.rfc-editor.org/rfc/rfc8037.html) like
```
kty: OKP
crv: Ed25519
use: sig
```

As I see, Centrifugo already uses [a library](https://github.com/centrifugal/centrifugo/blob/master/internal/jwks/manager.go#L13), which has support for [OKP](https://github.com/rakutentech/jwk-go)

**Comment by FZambia** [comment]
Part of [v5.2.1](https://github.com/centrifugal/centrifugo/releases/tag/v5.2.1). @AlexeyAkulovich please check it out, closing for now.

**Comment by AlexeyAkulovich** [comment]
Thanks. We are still testing it
