### ISSUE TITLE
"Websocket Is Closed Before The Connection Is Established" - Web console error

### ISSUE THREAD

**Issue by begemotik** [centrifugal/centrifugo#789]
When establishing multiple websocket connections in a short period of time there are some errors observed in the Developer's console:

```
WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.
```

We run Centrifugo on a Kubernetes cluster behind an Nginx Ingress Controller and AWS Network Load Balancer. Our overall load on Centrifugo is very low.

At first, we thought that the issue might be related to the proxy configuration. However, there were no signs of any errors in the logs, only general entries indicating a successful WebSocket connection with a 101 code. We attempted to adjust the Nginx configuration, but this did not resolve the issue. Furthermore, switching the proxy to AWS ALB produced the same errors.

---

We suspect that this issue might be the root cause of some of our recent incidents.
Is the issue related to Centrifugo's configuration or is it just how the Centrifugo JS library works?

**Comment by FZambia** [comment]
Hello, this could mean that client side timeout was called. You could face ephemeral port problem - https://centrifugal.dev/docs/server/infra_tuning#ephemeral-port-exhaustion . But I can't say for sure.

If you don't observe the same behaviour in local environment – then it's sth infrastructural and most probably network stack related. If you can reproduce this with local Centrifugo – we can take a closer look.

> Is the issue related to Centrifugo's configuration or is it just how the Centrifugo JS library works?

In normal situation such errors may happen but should be relatively rare.

**Comment by begemotik** [comment]
Yes, indeed. I can confirm that the test has been performed from a single browser. Having the TCP dump I observe that some of TCP connections are reset on the client's side.

"I may have a better understanding of the situation now. In case the server's websocket connections reset, due to events such as Nginx reload config or rolling restart for Centrifugo containers, the client will attempt to establish new connections. However, it may encounter a limit on the number of concurrent connections allowed by the browser."

I can imagine that on the server's side, the action item is to try to minimize the situations when the connection is reset. What about the client-side? Are there any recommendations on how to handle it correctly?

**Comment by begemotik** [comment]
We were trying to reproduce an incident-related case, but as you highlighted we were doing it wrong.

I found a [k6 benchmarking test in the project](https://github.com/centrifugal/centrifugo/blob/master/misc/benchmarking/k6/benchmark.js). Would you recommend using it to test the number of clients/ws connections the installation can handle?

**Comment by FZambia** [comment]
> I found a [k6 benchmarking test in the project](https://github.com/centrifugal/centrifugo/blob/master/misc/benchmarking/k6/benchmark.js). Would you recommend using it to test the number of clients/ws connections the installation can handle?

You can, probably adapt it a bit for your needs. Note that you can still hit limitations of client when running benchmark using k6 - like local open file limits, local resource usage. BTW, ChatGPT writes k6 scripts pretty well - was using it to write this script when was testing sth.

**Comment by FZambia** [comment]
Closing, the main question was addressed.
