### ISSUE TITLE
[feature] Support for MessagePack Serialization

### ISSUE THREAD

**Issue by sky93** [centrifugal/centrifugo#790]
**Is your feature request related to a problem? Please describe.**

In our current use of Centrifugo for real-time communication, we heavily rely on efficient data transmission to ensure fast message delivery and reduce bandwidth consumption. We've found that while JSON is versatile and Protobuf offers efficiency improvements, there are scenarios where MessagePack would be the ideal format due to its balance of efficiency and ease of use across various programming languages. In particular, for applications requiring minimal overhead and schema-less data structures, MessagePack offers a compelling alternative. However, Centrifugo's lack of native support for MessagePack serialization forces us to encode MessagePack data in Base64 when wrapping it in JSON, leading to increased payload size and additional processing overhead for encoding and decoding.

**Describe the solution you'd like**.

I would like Centrifugo to add native support for MessagePack as a serialization format, alongside the existing JSON and Protobuf options. This would involve:

1. **Server-Side Support**: Allowing Centrifugo server configurations to specify MessagePack as the serialization format for incoming and outgoing messages. This would include parsing MessagePack data from clients and serializing messages to MessagePack format when broadcasting to clients.

2. **Client-Side Library Enhancements**: Updating Centrifugo's client libraries to support MessagePack serialization and deserialization, providing an API that is as simple and intuitive as the existing methods for JSON and Protobuf.

3. **Documentation and Examples**: Adding documentation to guide developers on how to use MessagePack with Centrifugo, including example use cases and performance benchmarks comparing JSON, Protobuf, and MessagePack in typical real-time messaging scenarios.

This feature would not only enhance the flexibility and efficiency of data transmission in Centrifugo but also align with the needs of developers looking for the most efficient real-time data handling solutions. Furthermore, by supporting a schema-less, binary format like MessagePack, Centrifugo could broaden its appeal to projects that prioritize speed and data efficiency without the need for predefined schemas.

**How would it change the API?**

- New configuration options to enable MessagePack serialization.
- Additional methods in client libraries to send and receive MessagePack encoded messages.
- No breaking changes to the existing API, ensuring that the introduction of MessagePack support is backward compatible.

By introducing MessagePack support, Centrifugo would significantly enhance its data transmission efficiency, making it even more suitable for high-performance, real-time applications across various domains.

**Comment by FZambia** [comment]
Hello @sky93 

Thanks for opening and detailed description. This involves big changes throughout Centrifugal ecosystem. What about using  Centrifugo Protobuf support for your use case?

In this case you get minimal protocol layer overhead, but the most important - you can encode your payloads using MessagePack when passing them over Centrifugo Protobuf protocol. It seems to solve your main concerns. Also, Protobuf serialization is increadibly efficient in Centrifugo.

**Comment by FZambia** [comment]
@sky93 hello, does it make sense for you? I think MessagePack won't appear in the observable future since Protobuf covers it and even more.
