### ISSUE TITLE
How to add multyple aud for a token in config file

### ISSUE THREAD

**Issue by josippavicic** [centrifugal/centrifugo#791]
the documentations says that the aud is a string:
{
  "token_audience": "centrifugo"
}
is there a delimiter for multiple auds,  if so what is it, if not why not? How to manage multiple auds?

**Comment by FZambia** [comment]
Hello @josippavicic 

Token may contain multiple audiences. Centrifugo checks that configured `token_audience` is among audiences in token. Is it not enough for your use case?
