### ISSUE TITLE
Redis Connections settings are not configurable via environment variables

### ISSUE THREAD

**Issue by oddurmagg** [centrifugal/centrifugo#81]
When deploying centrifugo as a docker container, it is preferable to be able to define which redis server  to connect to via an environment variable.

By binding the redis_host to an environment variable in main.go this would be possible. 

viper.BindEnv("redis_host")

**Comment by oddurmagg** [comment]
There seems to be a workaround in #21

**Comment by FZambia** [comment]
Hello @oddurmagg , does that workaround work fine for your case? If having environment variable is more convenient for you - I can add it in next release.

**Comment by oddurmagg** [comment]
It makes me have to jump through hoops in the dockerfile where I need to pass the environment variable to the command line

Reading it in like all the other environment variables is much cleaner and I would prefer that.

**Comment by FZambia** [comment]
Ok! Added in 9c3942b5f33b8ce8bc4656232c2aec8fd9fce341. I am planning to finish #73 and then make new release.

**Comment by oddurmagg** [comment]
Awesome ! Thanks

**Comment by FZambia** [comment]
@oddurmagg unfortunately still can not release new version, because I want to include 2 pull requests into new version: #83 and #84

**Comment by FZambia** [comment]
Finally released!
