### ISSUE TITLE
[bug] With protobuf binary, RPCRequest.Data is empty.

### ISSUE THREAD

**Issue by richelieu-yang** [centrifugal/centrifugo#810]
**Describe the bug**. A clear and concise description of what the bug is.

With protobuf binary, RPCRequest.Data is empty.
...

**Versions**

Centrifugo version is <5.3.2>
Client library used is centrifuge-<js> of version <"^5.1.1">
Operating system is <darwin arm64>

**Steps to Reproduce** How can the bug be triggered?

...

**Expected behavior** What output or behaviour were you expecting instead?

...

**Code Snippets** A minimum viable code snippet can be useful.
<img width="1728" alt="iShot_2024-05-09_16 27 27" src="https://github.com/centrifugal/centrifugo/assets/51251717/350a90fe-b76d-4a38-92b7-8a408703269f">
<img width="1713" alt="iShot_2024-05-09_16 29 57" src="https://github.com/centrifugal/centrifugo/assets/51251717/f2bb8270-9349-42b0-866d-a8d8a733476f">

**Comment by richelieu-yang** [comment]
Client library used is centrifuge-js of version <"^5.1.1">

**Comment by FZambia** [comment]
Hello @richelieu-yang ,

I suppose you have not encoded data properly on client side before passing it to `rpc` call: see [in centrifuge-js readme](https://github.com/centrifugal/centrifuge-js?tab=readme-ov-file#protobuf-support:~:text=When%20running%20with,to%20Uint8Array%20first%3A). Could you check?

**Comment by FZambia** [comment]
This look non-obvious though. Opened an issue to possibly improve current behaviour by throwing exceptions on client side: https://github.com/centrifugal/centrifuge-js/issues/283

We have this in Python SDK.
