### ISSUE TITLE
[question] jwt invalid token in subscriptions

### ISSUE THREAD

**Issue by sajjad-fatehi** [centrifugal/centrifugo#811]
hi . i'm using the v4.1.5 of centrifugo and trying to migrate from v3 .
after integrating everything i had a problem about `invalid token 3500`  error :
can you explain me what should i do ? where am i wrong ?

channel : ```$system:monitoring/report```
jwt : 
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYTU1YzNjZS1mNDZlLTQzMzctYjQ5ZS02ZDg1MTljZTVhYzQiLCJjaGFubmVsIjoiJHN5c3RlbTptb25pdG9yaW5nL3JlcG9ydCIsImlhdCI6MTcxNTQzNjkxOSwiZXhwIjoxMTE4MjcxNjkxOX0.mJJoA0pxcjQC_LvVPTNlAoRfQb8A2VJV2ee5gr6yVpY
```
payload of it :
```
{
  "sub": "da55c3ce-f46e-4337-b49e-6d8519ce5ac4",
  "channel": "$system:monitoring/report",
  "iat": 1715436919,
  "exp": 11182716919
}
```
error message :
```
{"context":{"code":3500,"reason":"invalid token"}}
```
centrifugo log :

```
{"level":"debug","client":"xxxx","reason":"invalid token","user":"yyyy","time":"2024-05-11T14:15:19Z","message":"closing client connection"}
```
thank you

**Comment by sajjad-fatehi** [comment]
- can it me because of time tolerance between my local machine and docker container ?

**Comment by FZambia** [comment]
Hello, token has sub `da55c3ce-f46e-4337-b49e-6d8519ce5ac4` while log contains `"user":"yyyy"` - `sub` in subscription token must be `"yyyy"` to work.

**Comment by sajjad-fatehi** [comment]
thanks a lot ! :pray: 
yeah it was mismatch about my connect token `sub` and subscribe token `sub` .
