### ISSUE TITLE
OSX version

### ISSUE THREAD

**Issue by nicktabolich** [centrifugal/centrifugo#82]
Hi there!
How can I use the Centrifugo on OSX?
Thank you

**Comment by banks** [comment]
Download the binary (https://github.com/centrifugal/centrifugo/releases/download/v1.4.1/centrifugo-1.4.1-darwin-amd64.zip) and run it!

There is getting started and config info in the documentation - should work just the same on OS X as anywhere else. 

See https://fzambia.gitbooks.io/centrifugal/content/

**Comment by nicktabolich** [comment]
Thank you!
