### ISSUE TITLE
[feature] Package for debian 12 bookworm

### ISSUE THREAD

**Issue by maheus** [centrifugal/centrifugo#825]
Hi,

Do you think to do a package for Debian 12 (bookworm) and upload it on https://packagecloud.io/FZambia/centrifugo, please ?

**Comment by FZambia** [comment]
Hello @maheus ,

Will try to make it for the next release. Hope it's just a new line [here](https://github.com/centrifugal/centrifugo/blob/426f027316669136f6e0609a8ec53fcade39e4cf/Makefile#L34)

**Comment by FZambia** [comment]
Release for Debian 12 was added in [v5.4.1](https://github.com/centrifugal/centrifugo/releases/tag/v5.4.1).

Please let me know in case of issues!

**Comment by maheus** [comment]
tests ok, thanks
