### ISSUE TITLE
[bug] http: TLS handshake error from 192.168.0.1:40532: EOF

### ISSUE THREAD

**Issue by hrustbb2** [centrifugal/centrifugo#834]
My config
`
{

    "token_hmac_secret_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",

    "admin_password": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",

    "admin_secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",

    "api_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",

    "allow_subscribe_for_client": true,

    "allow_publish_for_subscriber": true,

    "history_size": 500,

    "history_ttl": "300s",

    "allowed_origins": ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

    "admin": true,

    "tls": true,

    "tls_key": "/etc/letsencrypt/privkey3.pem",

    "tls_cert": "/etc/letsencrypt/cert3.pem",

    "api_error_mode": "transport"

}
`

I get an error when trying to connect to centrifugo:
`2024-06-23 20:54:46 [WRN] http: TLS handshake error from 192.168.0.1:40532: EOF`

The problem occurs in the Safari browser

**Comment by FZambia** [comment]
Hey @hrustbb2 , we have a [template for bug reports](https://github.com/centrifugal/centrifugo/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=%5Bbug%5D+), please properly fill the issue including all the necessary information.

**Comment by hrustbb2** [comment]
ok, I filed another bug report
