### ISSUE TITLE
[bug] http: TLS handshake error

### ISSUE THREAD

**Issue by hrustbb2** [centrifugal/centrifugo#836]
**Describe the bug**. A clear and concise description of what the bug is.

When trying to establish a connection from the telegram web app (essentially the safari browser), the error `2024-06-24 16:53:18 [WRN] http: TLS handshake error from 192.168.0.1:59596: EOF` occurs

**Versions**

Centrifugo version is <Centrifugo v5.4.1 (Go version: go1.22.4)>
Client library used is centrifuge-<https://www.npmjs.com/package/centrifuge> of version <5.2.1>
Operating system is <Linux alpine>

**Steps to Reproduce** How can the bug be triggered?

When trying to establish a connection

`import { Centrifuge } from 'centrifuge';

this.centrifuge = new Centrifuge("wss://domain.com/connection/websocket", {token: this.token});`

**Expected behavior** What output or behaviour were you expecting instead?

I think the connection should be established without errors

**Code Snippets** A minimum viable code snippet can be useful.

`
import { Centrifuge } from 'centrifuge';

this.centrifuge = new Centrifuge("wss://domain.com/connection/websocket", {token: this.token});
`

My centrifugo config

`
{

"token_hmac_secret_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",

"admin_password": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",

"admin_secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",

"api_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",

"allow_subscribe_for_client": true,

"allow_publish_for_subscriber": true,

"history_size": 500,

"history_ttl": "300s",

"allowed_origins": ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

"admin": true,

"tls": true,

"tls_key": "/etc/letsencrypt/privkey3.pem",

"tls_cert": "/etc/letsencrypt/cert3.pem",

"api_error_mode": "transport"
}
`

**Comment by FZambia** [comment]
Hello @hrustbb2 

So you are connecting to Centrifugo with TLS configured from Telegram web app.

My first suggestion - try moving TLS termination from Centrifugo to some proxy, like Nginx. This will allow to narrow down the problem, if it works with Nginx – then this is sth with Centrifugo TLS layer and we can try to dig deeper. If not – I guess it's an issue on different level (browser? device?), in that case we can't do a lot.

**Comment by FZambia** [comment]
Do I understand correctly that Telegram web app is sth described here - https://core.telegram.org/bots/webapps ? Or it's something different?

**Comment by hrustbb2** [comment]
yes, that's right https://core.telegram.org/bots/webapps

Essentially, this is a web page that opens in the browser built into telegram.

I use Letsencrypt certificates, this may be a problem for the Safari browser. Could this be?

If I configure centrifugo to work with http_stream I get the error Failed to load resource: Unacceptable TLS certificate in the Safari browser console

**Comment by hrustbb2** [comment]
Thank you, the issue is resolved.

I had to specify the path to fullchain.pem in the config

**Comment by FZambia** [comment]
Great! 🎉
