### ISSUE TITLE
[feature] RTT info in client SDK

### ISSUE THREAD

**Issue by boskiv** [centrifugal/centrifugo#842]
**Is your feature request related to a problem? Please describe.**

I want to have an ability to get a ping latency from server to display it in UI for every client

![Screenshot 2024-06-30 at 18 01 28](https://github.com/centrifugal/centrifugo/assets/1939783/7a7377e2-e88e-4270-a911-66e04daca434)

**Describe the solution you'd like**.
> Will be nice to have a Subscription on a client instance that I can use to get recent rtt value

```
this.client.rtt().then((rtt) => this.rtt$.next(rtt));
```

in Nats you can use
```
setInterval(() => {
  conn.rtt().then((rtt) => this.rtt$.next(rtt));
}, 1000);
```

in Socket.IO We did that
```
this.interval = setInterval(() => {
  const start = Date.now();
  this.socket.volatile.emit('rtt');
  this.socket.once('rtt', () => {
    const duration = Date.now() - start;
    this.rtt$.next(duration);
  });
}, 5000);But it require to someone respond in rtt channel
```

**Comment by FZambia** [comment]
Centrifugo [v5.4.2](https://github.com/centrifugal/centrifugo/releases/tag/v5.4.2) adds RPC ping extension which can be enabled and used to check RTT.
