### ISSUE TITLE
[question] PING and PONG frames of websocket protocol

### ISSUE THREAD

**Issue by 070hm** [centrifugal/centrifugo#844]
Hi Centrifugo team,

I have a small question about the ping and pong functionality.
Why does the server use the ping and pong from the [client protocol](https://github.com/centrifugal/protocol/blob/8024bc1bfadee2e614ec54b33f053b22fd4d6494/definitions/client.proto#L38C3-L38C15) instead of the `PING `and `PONG `frames of the `WebSocket `protocol?"

**Comment by FZambia** [comment]
There were several reasons:

* Desire to unify different transports and also have a way to expose protocol pings to the client code if needed. This is nice for unidirectional transports for example. 
* There were some researches/reports made in other repos that pings from server which result into browser's callback result into more stable connection when browser window is not in focus
* This allows optimizing the number of messages travelling around, see https://centrifugal.dev/blog/2022/07/19/centrifugo-v4-released#redesigned-ping-pong . For the browser there is no way to turn of client to server WS native PING frames, but for other platforms – it's technically possible.
* There is mode in Centrifugo where it can switch to native ping/pong - https://centrifugal.dev/docs/transports/websocket#debugging-with-postman-wscat-etc - mostly useful for websocket tools I believe

**Comment by 070hm** [comment]
Okay, bro, nice work. It's really helpful in this case. Your team thoroughly studies each situation, fantastic work!
