### ISSUE TITLE
[question] Is there a full configuration file available?

### ISSUE THREAD

**Issue by yl** [centrifugal/centrifugo#854]
I am a new user and am getting acquainted with all the features. Is there a complete configuration file available?

**Comment by FZambia** [comment]
Hello @yl ,

Unfortunately no, you can found most in one place in code - https://github.com/centrifugal/centrifugo/blob/776f5886a0f554d6189c6ee4a8bf6ef21b63ca82/main.go#L94, but there is no description so you should match with documentation.

Probably will create such file in the future
