### ISSUE TITLE
[question] What is the Maximum Size of Data to Push into the Channel?

### ISSUE THREAD

**Issue by 070hm** [centrifugal/centrifugo#859]
Hi everyone,

I have a small question about the size of data that can be pushed to a channel. Is there a limit to the size of data?

**Comment by FZambia** [comment]
Hello @070hm ,

There are limits on how much data can be read from client, for example:

https://centrifugal.dev/docs/transports/websocket#websocket_message_size_limit

Regarding the size of data to be pushed to client - the only limiting factor I know is a per-client message queue size: 

https://centrifugal.dev/docs/server/configuration#client_queue_max_size

– usually it's sufficient enough, but for large messages may become a limiting factor and client disconnections with `slow` reason. Note, that WebSocket is not meant to be used for transferring really large messages  – it works, but goes against best practices. Try keeping messages sufficiently small to achieve best results.
