### ISSUE TITLE
gRPC: Received message larger than max (32243844 vs. 4194304)

### ISSUE THREAD

**Issue by sajjad-fatehi** [centrifugal/centrifugo#865]
hi everybody.
currently im using `Batch` grpc api (grpc-js) in one of my services to batch concurrent requests to reduce my cpu and IO
and if  `Commands` array be larger than 4mb it will throw an error and publish messages will not sent to clients
`gRPC: Received message larger than max (32243844 vs. 4194304)`
in my client side i set this options 
```
      'grpc.max_receive_message_length': 1024 ** 3,
      'grpc.max_send_message_length': 1024 ** 3,
```
but not working anyway . i think i need to change my centrifugo server config to increase default 4mb value ! but there is no config option for this situation . am i right ?

> note : i also tested   'grpc.max_receive_message_length': 1 to ensure changes of my clients limit are working

do you have any advice or something else ?

**Comment by FZambia** [comment]
Hello @sajjad-fatehi 

I think there is no option to tweak max message sizes for GRPC at the moment. Seems it's time to add.

**Comment by sajjad-fatehi** [comment]
grate news :heart_eyes:  thank you. will we have it on next minor changes ?

**Comment by sajjad-fatehi** [comment]
also can we have an option in `batch` api to ignore response ? in my case i do not care about response and this will save lot of network bandwidth for me
for example:
```
curl --header "X-API-Key: <API_KEY>" \
  --request POST \
  --data '{"no_reply":true,"commands": [{"publish": {"channel": "test1", "data": {}}}, {"publish": {"channel": "x:test2", "data": {}}}]}' \
  http://localhost:8000/api/batch
  ``` 
  
  response :
  ```
  {}
```

**Comment by FZambia** [comment]
> will we have it on next minor changes ?

I think so

> also can we have an option in batch api to ignore response

I think the overhead should not be critical given you are getting empty publish responses. It's in Protobuf, and the amount of data should be much-much less than you are sending. Did you calculate the real overhead?

**Comment by sajjad-fatehi** [comment]
Im on it . After i get new details i will share it.

**Comment by FZambia** [comment]
Option to change GRPC API receive size was added in v5.4.3 - https://github.com/centrifugal/centrifugo/releases/tag/v5.4.3
