### ISSUE TITLE
[question] Issue when reconnecting and proxy connect to BE

### ISSUE THREAD

**Issue by duy-nguyen-ts** [centrifugal/centrifugo#870]
***Hi guys, I want to know exactly how Centrifugal handle this case and why it happen ?***

**Ask your question**. Please provide as many details as possible – you will get the answer much faster then!
- I have FE WebUI, Centrifugal and BE service
- User goes to Web UI -> FE init connection then chat -> the command init connection send to Centrifugal and it pass to my BE service by connect proxy (followed docs https://centrifugal.dev/docs/server/proxy#connect-proxy) -> This works fine -> Logs showed on BE service -> My BE attach metadata to the connection successfully.
- User chats ping/pong
- Then user was disconnected due to the internet broken.
--> If user reconnecting before 30s -> it still works fine, my BE receive connect event again and going on like above flow.
--> If user reconnecting after 30s -> my BE service can not receiver event connect -> can not attach metadata -> after that user chat and failed because we need metadata to processing user event

**"Show us an example of what you mean!"**. An example can be useful, otherwise we're left guessing!

...

**Comment by FZambia** [comment]
Hello @duy-nguyen-ts 

Centrifugo does not have any 30 sec timeout for reconnects by default, so I don't know what exactly is going on in your case. Our SDKs try to reconnect indefinitely. It can be 30 sec or one minute, or one hour - as soon as connection can be established the reconnect will happen and you should receive the connect event. You have not mentioned any SDK on FE, did not provide any reproducing steps and code - so I can't help you more at this point.

**Comment by duy-nguyen-ts** [comment]
Thanks @FZambia , I have investigated and found it was an issue of my integration flow of FE <-> Centrifugal <-> BE.
