### ISSUE TITLE
[question] Get client IP

### ISSUE THREAD

**Issue by itismoej** [centrifugal/centrifugo#877]
How to get users' or clients' IP based on a subscription or clientId?

For example, if I've got a UID from `presence` api, how can I see the IP related to that particular UID?

**Comment by FZambia** [comment]
Hello @itismoej 

Technically, you can extend presence information with `info` (connection-wide) and `chan_info` (channel specific) additional information. This information may be taken by Centrifugo from connect/subscription tokens or from responses of your connect/subscribe proxies.

Though including IP should be addressed from security perspective, probably in that case you may want to disable getting presence on client side and ask it through the backend and  pre-process presence data response by returning IP addresses which is a sensitive information. Or, you can keep information about IPs in storage like Redis and whether return it separately or enrich presence data.

**Comment by itismoej** [comment]
> Hello @itismoej
> 
> Technically, you can extend presence information with `info` (connection-wide) and `chan_info` (channel specific) additional information. This information may be taken by Centrifugo from connect/subscription tokens or from responses of your connect/subscribe proxies.
> 
> Though including IP should be addressed from security perspective, probably in that case you may want to disable getting presence on client side and ask it through the backend and pre-process presence data response by returning IP addresses which is a sensitive information.
> 
> Also, you can keep information about IPs in storage like Redis and whether return it separately or enrich Centrifugo presence data, but again don't forget to think about sensitive info exposing.

How can I enable `chan_info` and `conn_info` in the presence API?

**Comment by FZambia** [comment]
> How can I enable chan_info and conn_info in the presence API?

For connection wide `info`:

* in connection token [info](https://centrifugal.dev/docs/server/authentication#info) claim
* in connect proxy [result](https://centrifugal.dev/docs/server/proxy#connect-result-fields) `info` field

For channel-specific `chan_info`:

* in subscription token [info](https://centrifugal.dev/docs/server/channel_token_auth#info) claim
* in subscribe proxy [result](https://centrifugal.dev/docs/server/proxy#subscribe-result-fields) `info` field

**Comment by itismoej** [comment]
Got it. Thank you Alexander :)

**Comment by FZambia** [comment]
You are welcome, I'll try to improve docs a bit

**Comment by FZambia** [comment]
Did some in https://github.com/centrifugal/centrifugal.dev/commit/38e89164dc200f7575d16bd02b45d4fb48bfff09
