### ISSUE TITLE
[bug] Non parallel RPC calls over WS protocol

### ISSUE THREAD

**Issue by 8BitJonny** [centrifugal/centrifugo#879]
**Describe the bug**. A clear and concise description of what the bug is.

I just had the following realisation: In our current setup where centrifugo-js talks makes RPC calls over the ws protocol, the message IDs are always ordered when looking within the network tab.
Meaning I would see within the websocket
```
REQ {"id": 1, "rpc": {"method": "..."} }
REQ {"id": 2, "rpc": {"method": "..."} }
REQ {"id": 3, "rpc": {"method": "..."} }
RESP {"id": 1, "rpc": {...} }
RESP {"id": 2, "rpc": {...} }
RESP {"id": 3, "rpc": {...} }
```
which I thought at first was a coincidence that the RPC responses coming back from the backend were always coming back in order.
Then I added logging to our GoLang RPC proxy and the logs showed me that in fact the rpc request with id: 2 did not even reach the backend before the response of id 1 was sent.
So I added a sleep statement which then solidified my hunch.

![image](https://github.com/user-attachments/assets/83f5bfe2-e77d-4ea7-abcd-0dffbb65a21a)

The timestamp of the ws messages clearly shows the 10 second sleep while the backend logs (added print statement in the top most line in the rpc handler function) show that work on the second rpc call only started after the first one was done
```
method:  GET:/teams/c2907e26-4e79-4938-8aed-15e93b168fc9/projects
sleep donee
method:  GET:/projects/e5843ef3-ed2b-452b-aedf-71d0766a8f3d/routes
method:  GET:/projects/e5843ef3-ed2b-452b-aedf-71d0766a8f3d/routes/folders
```

**Versions**

Centrifugo version is centrifugo/centrifugo:v4
Client library used is centrifuge-js of version "centrifuge": "3.1.2"
Operating system is Mac

**Steps to Reproduce** How can the bug be triggered?

- create a centrifuge-js client with `transport: websocket`
- make three parallel `this.centrifuge.rpc(...)` calls
- modify the proxied rpc handler so that it sleeps on the first or second rpc call

**Expected behavior** What output or behaviour were you expecting instead?

If the centrifuge client launches 3 rpc calls parallel and the rpc call with id: 1 is the slowest of them, I would expect it not to matter since the backend also gets all 3rpc calls in parallel and then the frontend first gets the response to rpc call 2 and 3 before it gets the response to the first rpc call.

Or even if the rpc responses have reach the client in ascending order (which I don't see why when they seem to have id's for exactly that) than at least I would expect the backend to be able to work on all three 3rpc calls of the same client at the same time.

This works btw as I expect it to, when the centrifuge frontend client is using either the SSE transport protocol or the http_stream protocol.
Or is this a miss configuration on my end?

**Code Snippets** A minimum viable code snippet can be useful.

The golang rpc proxy
```go
func (p *ProxyController) RPC(ctx context.Context, request *proxyproto.RPCRequest) (*proxyproto.RPCResponse, error) {
	println("method: ", request.Method)
	if strings.HasPrefix(request.Method, "GET:/teams/") && strings.HasSuffix(request.Method, "/projects") {
		time.Sleep(10 * time.Second)
		println("sleep donee")
	}
```

centrifugo server config
```
{
  "allowed_origins": ["*"],
  "allow_subscribe_for_client": true,
  "proxy_rpc_timeout":  "60s",
  "log_level": "info",
  "api_disable": true,
  "grpc_api": true,
  "debug": false,
  "proxy_include_connection_meta": true,
  "http_stream": true,
  "sse": true,
  "namespaces": [
    {
      "name": "events",
      "allow_subscribe_for_client": true
    }
  ]
}
// WITH config ENVS
CENTRIFUGO_GRPC_API_KEY: $CENTRIFUGO_API_KEY
CENTRIFUGO_PROXY_RPC_ENDPOINT: "grpc://gateway:2999/"
CENTRIFUGO_TOKEN_JWKS_PUBLIC_ENDPOINT: "http://gateway:3001/auth/jwt/jwks.json"
```

**Comment by FZambia** [comment]
Hello @8BitJonny ,

Please check out `client_concurrency` option – https://centrifugal.dev/docs/server/configuration#client_concurrency - it should help to achieve the desired behaviour.

**Comment by FZambia** [comment]
BTW, it's worth mentioning that at some point during Centrifugo v5 life cycle there were some fixes in `centrifuge-js` and server regarding the correctness of client subscribe/unsubscribe behaviour when `client_concurrency` is used. So if you come across `already subscribed` errors in you app – this may be a signal that you hit the path which most probably is fixed in latest version of SDK and server.

**Comment by 8BitJonny** [comment]
Yeah, I feared that it was that easy but that I didn't see it ... Sorry for that and thank you 🙏🏼 

And thanks for the heads up. We are currently still on v4 but I'll look out for that bug and then know how to fix it, should it occur, many thanks🙏🏼
