### ISSUE TITLE
[feature] Centrifugo HTTP API JS client

### ISSUE THREAD

**Issue by sajjad-fatehi** [centrifugal/centrifugo#883]
**hi everyone**
i recently published npm package for nodejs users to communicate easily with v5 centrifugo api full typed and easy to use .

@FZambia you can add it in documents maybe

npm url : [Centri-Agent](https://www.npmjs.com/package/centri-agent)

**Comment by FZambia** [comment]
Hello @sajjad-fatehi 

Thank you for the contribution, I'll take a closer look myself very soon and will definitely add to docs.

**Comment by FZambia** [comment]
Added to the documentation: https://centrifugal.dev/docs/server/server_api#http-api-libraries - many thanks!
