### ISSUE TITLE
[question] Is There a Limit on the Number of Channels? Performance Impact of Large Numbers of Channels?

### ISSUE THREAD

**Issue by perfgao** [centrifugal/centrifugo#884]
Hello,

I am using Centrifugo as our real-time messaging server and I am very interested in its performance and scalability. I have a few questions regarding the number of channels:

Channel Limit: Does Centrifugo impose any limit on the number of channels? For example, is there a hard limit on the maximum number of channels?

Performance Impact: When the number of channels is very large (for instance, 10,000 or 100,000 channels), does it have a significant impact on server performance? If so, in what ways is the performance affected?

**Comment by FZambia** [comment]
Hello @perfgao 

> Channel Limit: Does Centrifugo impose any limit on the number of channels? For example, is there a hard limit on the maximum number of channels?

No, it does not have limit on global number of channels in the system. There are limits per [client](https://centrifugal.dev/docs/server/configuration#client_channel_limit) and per [user](https://centrifugal.dev/docs/server/configuration#client_user_connection_limit)  which may be configured.

> Performance Impact: When the number of channels is very large (for instance, 10,000 or 100,000 channels), does it have a significant impact on server performance? If so, in what ways is the performance affected?

Channels are lightweight. In the scenario where each client has one personal channel and one common channel it's proved to work easily with [millions of connections](https://centrifugal.dev/blog/2020/02/10/million-connections-with-centrifugo).

In the documentation we outline scalability concerns of some Centrifugo parts – check out:

* https://centrifugal.dev/docs/getting-started/design
* https://centrifugal.dev/docs/faq
