### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [centrifugal/centrifugo#887]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Centrifugo application as shown [here](https://elest.io/open-source/centrifugo). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

**Comment by FZambia** [comment]
Hello @kaiwalyakoparkar 

Appreciate the fact Elestio suggests the revenue program. At the same time, given the current state of things and the vision, we do not want to promote cloud hosting solutions and participate in the program.

**Comment by kaiwalyakoparkar** [comment]
Hey @FZambia, I understand. Thank you for your comment & letting me know :)
