### ISSUE TITLE
[question] Calculation of client SDK distribution

### ISSUE THREAD

**Issue by itismoej** [centrifugal/centrifugo#892]
I have reviewed both the Java and JavaScript SDKs and noticed they send a `name` payload when establishing a WebSocket connection. Could you confirm whether this `name` payload is stored on the Centrifugo server? Additionally, is there a way (excluding proxy or token claims) to track and analyze this information to determine the distribution of SDKs being used?

**Comment by FZambia** [comment]
Hello, `name` info is available in context of connect event on server side – Centrifugo OSS does not do anything with it, Centrifugo PRO uses it for [connection analytics](https://centrifugal.dev/docs/pro/analytics) with ClickHouse, so it's possible to build distributions, draw in Grafana, and admin UI shows widget with current distribution. Also, it's returned as part of [connections API](https://centrifugal.dev/docs/pro/connections) response.
