### ISSUE TITLE
[question] can I implement end-to-end encryption using centrifugo?



### ISSUE THREAD

**Issue by 0xMostafa** [centrifugal/centrifugo#902]
I'm evaluating centrifugo for a new project that requires end to end encryption of chats.

Is it possible to implement end to end encryption with centrifugo?

**Comment by FZambia** [comment]
Hello @0xMostafa 

Centrifugo does not provide end-to-end encryption out of the box, though it's totally possible to implement it on top of functionality Centrifugo provides. For Centrifugo payloads of messages are arbitrary bytes - utf-8 JSON bytes in case of JSON protocol or any binary in case of using Protobuf protocol. So you can add encryption on the application level.
