### ISSUE TITLE
[question] In gRPC proxy mode, does Centrifugo support customizing the gRPC service name (CentrifugoProxy)?

### ISSUE THREAD

**Issue by xuanskyer** [centrifugal/centrifugo#904]
**Ask your question**. 

In gRPC proxy mode, does Centrifugo support customizing the gRPC service name?

Specifically, can the `CentrifugoProxy` service name be dynamically set to a custom service name?

In most cases, the gRPC proxy implementation is usually integrated into the application’s gRPC service rather than deployed as a separate gRPC proxy server.

**Comment by FZambia** [comment]
Please feel free to comment further, closing - do not see what we can do here.
