### ISSUE TITLE
[feature] Support for Additional SASL Authentication Mechanisms

### ISSUE THREAD

**Issue by mohammadanaraki** [centrifugal/centrifugo#911]
Currently, Centrifugo's SASL mechanism only supports PLAIN authentication. While this works for basic scenarios, supporting additional mechanisms like `SCRAM-SHA-512` would enhance security options, especially for production environments.

## Current Behavior
- Only `PLAIN` authentication is supported in SASL

## Requested Feature
- Support for additional SASL mechanisms, specifically:
 - `SCRAM-SHA-512`
 - `SCRAM-SHA-256`

## Use Case
When implementing Centrifugo in environments with strict security requirements, having stronger authentication mechanisms would be beneficial.

**Comment by FZambia** [comment]
Release in v5.4.7
