### ISSUE TITLE
[question] Disconnect hooks

### ISSUE THREAD

**Issue by toannv1803** [centrifugal/centrifugo#924]
I read this faq: https://centrifugal.dev/docs/faq#why-centrifugo-does-not-have-disconnect-hooks
But this workaround can't resolve my use case.
My system allows users to chat in groups or direct messages. When a user is online, they do not receive push notifications.
When the user switches the app or kills the app, the user should receive a push notification when a new message is available.
But the workaround has some delay to known user disconnected, the system doesn't send a push notification, and the user will miss it
I use open source version
Mobile may call API to set status when the user switches the app or kills the app but I'm not sure it works well

**Comment by FZambia** [comment]
Closing, hope it helped. If you have ideas how Centrifugo may improve here – please post here, and we can reopen if find sth actionable.
