### ISSUE TITLE
event disconnect ???

### ISSUE THREAD

**Issue by alishademan** [centrifugal/centrifugo#926]
Is there an event or a method to determine if the user has disconnected ???

**Comment by FZambia** [comment]
Hello @alishademan 

Questions like this are better to ask in the community channels. Please [find the answer in docs](https://centrifugal.dev/docs/server/proxy#:~:text=Centrifugo%20does%20not%20emit%20unsubscribe%20and%20disconnect%20events%20at%20this%20point.%20For%20the%20reasoning%20and%20workarounds%20check%20out%20the%20answer%20in%20Centrifugo%20FAQ.).
