### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by lmj0011** [centrifugal/centrifugo#94]
Nothing has changed in my code since upgrading from v1.4.5 to  v1.5.0, however, I'm getting this syntax error when sending message between clients:

![chat1](https://cloud.githubusercontent.com/assets/9396189/16476969/defe21c4-3e52-11e6-9215-65014eb15fd0.png)

The JSON is being broken somehow:
```
{
	"method": "join",
	"body": {
		"channel": "testsite:575e286967c52:sim1",
		"data": {
			"default_info": {
				"user_data": {
					"id": 3,
					"username": "sim1",
					"rank": 100,
					"zip": "56894",
					"href": "http://www.testsite.com/users/sim1",
					"last_login_at": "1467261409"
				}
			},
			"user": "3",
			"client": "855cdfc3-5dd6-4af4-b005-fc12653f780  //here string is not terminated and missing '}'
```
This prevents my messages from being sent.
<hr>
for my app I'm using:
front-end: **centrifuge-js**
back-end: **centrifugo-1.5.0-linux-amd64**

**Comment by FZambia** [comment]
Hello! Do you use Memory or Redis engine? Is this reproduced all the time?

**Comment by lmj0011** [comment]
The default, Memory.
It's reproduced everytime.

**Comment by FZambia** [comment]
Hm.. Can't find what can cause this bug, and can not reproduce it. Could you post all websocket messages from chrome network console (Network -> WS)?

**Comment by FZambia** [comment]
I will also try that particular build as soon as I get to linux machine.

**Comment by FZambia** [comment]
Just tried to run on Centos 6 – works well... Could you also show the output of these 2 commands from machine where Centrifugo running?
```
uname -a
```
and
```
cat /proc/cpuinfo
```

**Comment by lmj0011** [comment]
```
forge@forge-virtual-machine:~/www/client1/BGateway$ uname -a
Linux forge-virtual-machine 3.19.0-49-generic #55-Ubuntu SMP Fri Jan 22 02:10:24 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux


forge@forge-virtual-machine:~/www/client1/BGateway$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 26
model name	: Intel(R) Xeon(R) CPU           W3565  @ 3.20GHz
stepping	: 5
microcode	: 0x19
cpu MHz		: 3200.000
cache size	: 8192 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf pni ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer hypervisor lahf_lm ida dtherm tsc_adjust
bugs		:
bogomips	: 6400.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 42 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 26
model name	: Intel(R) Xeon(R) CPU           W3565  @ 3.20GHz
stepping	: 5
microcode	: 0x19
cpu MHz		: 3200.000
cache size	: 8192 KB
physical id	: 2
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf pni ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer hypervisor lahf_lm ida dtherm tsc_adjust
bugs		:
bogomips	: 6400.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 42 bits physical, 48 bits virtual
power management:
```

**Comment by lmj0011** [comment]
>Hm.. Can't find what can cause this bug, and can not reproduce it. Could you post all websocket messages from chrome network console (Network -> WS)?

Nothing shows in the Network section of Chrome Web Console for this

**Comment by FZambia** [comment]
Can you write into [gitter chat](https://gitter.im/centrifugal/centrifugo) - more comfortable to chat when debugging

**Comment by lmj0011** [comment]
this is the data I'm sending on `new Centrifuge({})`

```
let data = '{"user_data":'+ JSON.stringify(this.app.whoiami) +'}';
```

**Comment by FZambia** [comment]
Could you post all the code? Including `new Centrifuge(...` etc? Because `join` messages use the info from connection parameters.

**Comment by FZambia** [comment]
@lmj0011 any news on this?

**Comment by lmj0011** [comment]
Give me until the end of the week to update this with more code. Sorry I've been quite busy

**Comment by FZambia** [comment]
@lmj0011 just reproduced this! will try to fix asap.

**Comment by lmj0011** [comment]
👍😀 that's great. Now I don't have to upload my confusing code

**Comment by FZambia** [comment]
@lmj0011 hope fixed this in [1.5.1](https://github.com/centrifugal/centrifugo/releases/tag/v1.5.1) – could you check it out?

**Comment by lmj0011** [comment]
On vacation at the moment, I will test it out, Monday.

**Comment by lmj0011** [comment]
Just tested it, was not able to reproduce the error.
:+1:

**Comment by FZambia** [comment]
Cool! Thanks for report!
