### ISSUE TITLE
A refreshData option for the refreshEndpoint url 

### ISSUE THREAD

**Issue by lmj0011** [centrifugal/centrifugo#98]
For connection check request there's only the option to send data as a query string.
Could we get an option to send it in the body of the request also? 
https://fzambia.gitbooks.io/centrifugal/content/clients/javascript.html#configuration-parameters

**Comment by FZambia** [comment]
I think yes, something like `refreshData` option in settings to Centrifuge object? At moment we send refresh POST request with empty body ([this line](https://github.com/centrifugal/centrifuge-js/blob/master/src/centrifuge.js#L596) - look at empty `{}` in `_ajax` call).

But could you first describe your use case? Which data you want to send and why you want it to be in body?

**Comment by lmj0011** [comment]
the use case is I want to send some data to the refresh endpoint that has some user info (username, id, etc) attached to it. I don't want this info in the url.

**Comment by FZambia** [comment]
Added code for this in [last commit](https://github.com/centrifugal/centrifuge-js/commit/796277f38ceadd9fcc0d222bdfeae13437f11320). Will release new version after finishing work on #99
